from __future__ import annotations

"""Authorial-identity deep polish for weather songs 0046-0050."""

GOLD_V5_46_50_SPEC_PATCHES: dict[str, dict[str, object]] = {
"0046": {
"authorial_intent":"Write a one-day weather watch where the child records what can be seen, felt, or measured from morning dew to night sky, separating observation from instrument reading.",
"lyric_identity":"A forecast notebook moves through time: morning surface clues, daytime cloud/wind changes, storm possibilities, evening cooling, then night sky.",
"image_motifs":("dew on railing","altocumulus rows","windsock turning","puddle after rain","night sky after clearing"),
"semantic_arc":("morning moisture","daytime cloud and wind","storm and precipitation clues","evening clearing and night record"),
"forbidden_generic_language":("today's forecast fun","weather words","look at the sky with me","everything changes"),
"rhyme_engine":"weather-watch-time-log-rhyme","chorus_rhyme_engine":"look-feel-record-hook","point_of_view":"a child keeping a supervised one-day weather notebook","chorus_function":"reset look-feel-measure-record","groove_meter":"light 4/4 notebook pulse with small forecast pauses","round1_grammar":"hand-written observational log; natural phenomena, clothing, and instruments keep distinct roles","round2_grammar":"observation cue -> recall beat -> target -> safe weather gesture",
"intro_lines":("Morning rail: tiny dew drops. Mid-sky: rows of cloud.","We write what we notice before we guess what comes next."),
"hook_lines":("Look, feel, record—A-B-C!","Weather watching starts with what is really there."),
"outro_lines":("The windsock settles and the page reaches night.","A to Z closes one weather day, not a promise about tomorrow."),
"round2_patterns":("Weather log {letter} ... {object}! {action}","Observe {letter} ... {object}! {action}","Seen, felt, or measured—{letter}? ... {object}! {action}","Notebook clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Altocumulus! Mid-level cloud patches can form rows or rounded clumps | our notebook starts above the morning rooftops."),
("B","B ... B ... Breeze! A light wind moves leaves and brushes skin | felt directly, even without an instrument."),
("C","C? Cloud! Tiny water droplets or ice crystals gather in air | shape and height become our first visual notes."),
("D","D is Dew. Water condenses onto cool surfaces | morning moisture written in beads, not falling rain."),
("E","E — Earmuffs! Clothing covers the ears in cold weather | gear belongs to the observer, not the forecast itself."),
("F","F ... F ... Fog! A cloud at ground level reduces visibility | record how far we can see instead of walking into poor visibility."),
("G","G? Gust! A brief stronger burst of wind interrupts the steadier air | one short change worth noting."),
("H","H is Hail. Balls or lumps of ice can fall from strong thunderstorms | we stay sheltered and observe safely."),
("I","I — Ice! Frozen water forms when conditions are cold enough | a surface clue that can make walking slippery."),
("J","J ... J ... Jet Stream! Fast narrow bands of wind high in the atmosphere help steer weather systems | invisible, inferred from meteorological data."),
("K","K? Kelvin Thermometer! A temperature instrument can display kelvins | measurement clue, not something the sky produces."),
("L","L is Lightning. A powerful electrical discharge flashes between cloud regions or cloud and ground | thunder may follow, so shelter matters."),
("M","M — Mist! Tiny droplets hang near the ground | usually lighter and less visibility-reducing than dense fog."),
("N","N ... N ... Night Sky! Darkness reveals stars where clouds and light pollution allow | final time-of-day frame, not a weather instrument."),
("O","O? Overcoat! Warm outer clothing helps in cold conditions | choose it from the weather, do not call it weather."),
("P","P is Puddle. Rainwater can collect in a shallow low spot | evidence that precipitation reached the ground."),
("Q","Q — Quiet Sky! Our project phrase for a calm-looking moment | observation language, not a scientific cloud type."),
("R","R ... R ... Raincoat! Water-resistant outerwear helps keep a person drier in rain | response to weather, not a forecast signal."),
("S","S? Snowflake! Ice crystals grow in clouds and may join into snowflakes | delicate structure changes on the way down."),
("T","T is Thermometer. Temperature instrument gives a reading | numbers belong in the notebook beside visual clues."),
("U","U — Updraft! Rising air carries heat and moisture upward | an invisible motion important inside many clouds and storms."),
("V","V ... V ... Vapor! Water vapor is invisible water in gas form | visible cloud droplets are a different phase."),
("W","W? Windsock! Its orientation shows wind direction and its extension gives a rough sense of wind strength | a station clue we can see."),
("X","At the classroom table, X is X-band Radar | short radio waves can help detect rain or moving weather."),
("Y","Y — Yellow Sun! The Sun can appear yellow from Earth because the atmosphere filters and scatters light | the star itself is not simply a yellow weather object."),
("Z","Z ... Z ... Zephyr! A gentle breeze | one soft wind word to close the daily log."),),
"style_blueprint":"Crisp diction. Open with dew and mid-level cloud at 86 BPM in light 4/4 with acoustic guitar, soft shaker, marimba and tiny notebook-click percussion. Keep melody narrow and mostly stepwise. Round 1 moves morning to night and clearly separates observation, clothing, and instruments. Chorus uses look-feel-record. Round 2 leaves one recall beat. Duck percussion at targets. Hail/lightning use shelter-safe wording; no thunder SFX over target names. End with sparse night texture and clean cadence."},
"0047": {
"authorial_intent":"Turn Cloud Parade into a slow sky gallery: cloud layer, coverage, optical effects, weather tools and clothing enter the frame one by one without pretending every mapping target is a cloud.",
"lyric_identity":"The child frames one part of the sky at a time—low, covered, clearing, rainbow, storm center, sun—while instruments sit at the observation station below.",
"image_motifs":("low cloud edge","overcast sheet","rainbow opening","storm eye on radar display","kite under clearing sky"),
"semantic_arc":("start with cloud shape","compare low/covered/clear sky","add storm and optical clues","finish at ground instruments under changing sky"),
"forbidden_generic_language":("cloud parade fun","every cloud has a shape","sky friends","drifting clues"),
"rhyme_engine":"cloud-gallery-frame-reveal-rhyme","chorus_rhyme_engine":"frame-layer-open-hook","point_of_view":"a child slowly framing sky scenes from an observation spot","chorus_function":"reset frame-layer-open","groove_meter":"airy 6/8 gallery sway","round1_grammar":"hand-written sky framing; gear and instruments are ground-station context","round2_grammar":"frame cue -> recall beat -> target -> safe point/shape gesture",
"intro_lines":("One low cloud covers the hill; one bright gap opens beside it.","We frame the sky slowly enough to notice what changes."),
"hook_lines":("Frame, layer, open—A-B-C!","Clouds cover some of the sky, never all of the story."),
"outro_lines":("The last cloud frame drifts past the windsock.","A to Z leaves one open patch of sky."),
"round2_patterns":("Sky frame {letter} ... {object}! {action}","Layer clue {letter} ... {object}! {action}","Cloud, tool, or gear—{letter}? ... {object}! {action}","Open-sky clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Anemometer! Cups or propeller turn with wind | a ground instrument below our cloud gallery."),
("B","B ... B ... Boots! Weather boots protect feet from wet, cold, or rough conditions | observer gear stays below the sky."),
("C","C? Cloud! Droplets or ice crystals make visible shapes in air | the central frame of the gallery."),
("D","D is Dew. Condensed water beads on a cool surface | a ground-level moisture clue under the clouds."),
("E","E — Eye of Storm! Some strong tropical cyclones develop a relatively calm center | a storm structure seen in data and imagery, not a cloud shape to chase."),
("F","F ... F ... Frost! Ice crystals can form on surfaces when they become cold enough | a close ground texture beneath the sky."),
("G","G? Gauge! A gauge displays a measured quantity | station context that needs a label telling us what it measures."),
("H","H is Hail. Ice lumps from strong thunderstorm clouds can reach the ground | shelter first, observation second."),
("I","I — Icicle! Frozen drip water forms a hanging point | we look without touching or standing beneath unstable ice."),
("J","J ... J ... Jacket! Outer clothing responds to conditions | not a cloud category."),
("K","K? Kite! Wind can lift a kite in safe open conditions | never during thunderstorms or near power lines."),
("L","L is Low Cloud. Cloud base sits relatively near the ground | a lower sky layer that can hide hills."),
("M","M — Mittens! Hand coverings help in cold weather | small gear in the foreground of our sky frame."),
("N","N ... N ... Night Sky! Cloud cover can hide stars or leave gaps | the gallery changes after sunset."),
("O","O? Overcast Sky! Clouds cover nearly all or all of the visible sky | broad sheet instead of separate puffs."),
("P","P is Pressure Gauge. Pressure instrument provides a reading | meteorologists care about pressure trends, not just one decorative dial."),
("Q","Q — Quiet Sky! A project phrase for calm-looking conditions | not a formal meteorological class."),
("R","R ... R ... Rainbow! Sunlight refracts, reflects, and disperses inside water droplets | colored arc appears opposite the Sun direction."),
("S","S? Snowflake! Ice-crystal structure grows in cloud | tiny geometry emerging from a huge sky layer."),
("T","T is Thermometer. Temperature reading gives one part of the weather picture | instrument stays at the station."),
("U","U — Umbrella! Portable rain protection | keep it closed in dangerous high wind or lightning conditions."),
("V","V ... V ... Vane! A weather vane points with wind direction | simple arrow below the moving clouds."),
("W","W? Windsock! Fabric tube aligns with wind and fills more as wind strengthens | visible ground clue under the gallery."),
("X","X is X-band Radar. Weather radar using X-band microwaves can detect precipitation structure | a technical observation tool, not a cloud itself."),
("Y","Y — Yellow Sun! Atmospheric scattering can make the Sun look yellowish | a bright visual anchor between cloud layers."),
("Z","Z ... Z ... Zephyr! Gentle breeze moves the cloud frame slowly | a soft finish rather than a storm climax."),),
"style_blueprint":"Crisp diction. Open with low cloud and bright gap in 84 BPM airy 6/8, nylon guitar, soft piano, marimba droplets and light shaker. Melody stays narrow. Round 1 acts like a sky gallery, alternating cloud states with ground tools/gear. Chorus is frame-layer-open. Round 2 uses hand-framing gestures and one recall beat. Eye of Storm, hail, icicle and kite include safety boundaries. Duck all target onsets. End with instruments thinning as a gap of sky opens."},
"0048": {
"authorial_intent":"Make Dress for Weather a decision song: first identify the condition, then choose a sensible layer or protection; instruments explain why, and non-gear targets never get forced into clothing language.",
"lyric_identity":"A child asks condition first, clothing second—cold, wet, windy, warm—while radar and meters stay in the information column.",
"image_motifs":("boots beside puddle","coat under low cloud","earmuffs in cold mist","umbrella after drizzle","zipper jacket at doorway"),
"semantic_arc":("observe sky","choose warm/wet gear","check instruments and hazards","finish by adjusting layers rather than dressing for one permanent forecast"),
"forbidden_generic_language":("zip pull button","dress for weather fun","wear everything","weather letter helps us choose"),
"rhyme_engine":"condition-choice-response-rhyme","chorus_rhyme_engine":"check-choose-adjust-hook","point_of_view":"a child making simple weather clothing decisions with adult guidance","chorus_function":"repeat check-choose-adjust","groove_meter":"bouncy 4/4 with decision pauses","round1_grammar":"hand-written condition-response pairs; gear, instruments, hazards and sky terms remain distinct","round2_grammar":"condition cue -> recall beat -> target -> safe gear/point gesture",
"intro_lines":("Before the zipper moves, we check the sky and temperature.","Weather gear works best when it matches the condition."),
"hook_lines":("Check, choose, adjust—A-B-C!","Wear what helps now; change it when the weather changes."),
"outro_lines":("Umbrella down, jacket unzipped—the condition changed again.","A to Z ends with one more look outside."),
"round2_patterns":("Decision clue {letter} ... {object}! {action}","Condition or gear {letter} ... {object}! {action}","What helps now—{letter}? ... {object}! {action}","Adjust clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Altocumulus! Mid-level patches tell us about the sky | cloud name first, clothing choice later."),
("B","B ... B ... Boots! Protective footwear can help with wet, cold, or muddy ground | choose the pair for the condition."),
("C","C? Coat! Outer layer adds warmth or weather protection | useful when conditions call for it, not automatically."),
("D","D is Drizzle. Very light rain falls in fine drops | a wet-condition clue before rain gear."),
("E","E — Earmuffs! Ear coverings reduce cold exposure | one small layer for chilly conditions."),
("F","F ... F ... Fog! Ground-level cloud lowers visibility | clothing cannot fix visibility, so route safety matters too."),
("G","G? Gust! Brief stronger wind can change how cold it feels and how gear behaves | hats and umbrellas need care."),
("H","H is Humidity Meter. A hygrometer measures air moisture | information tool, not something to wear."),
("I","I — Icicle! Frozen drip water signals cold surfaces | look, do not stand under unstable hanging ice."),
("J","J ... J ... Jacket! Flexible outer layer can add warmth or weather protection | easy to put on or remove as conditions change."),
("K","K? Kelvin Thermometer! Temperature instrument displaying kelvins | a reading helps describe temperature, not pick clothes by itself."),
("L","L is Low Cloud. Low cloud can reduce visibility and bring damp conditions | sky clue rather than wardrobe item."),
("M","M — Mist! Fine droplets near ground can feel damp | light moisture may change what outer layer feels comfortable."),
("N","N ... N ... Nimbus Cloud! A rain-cloud label in everyday use | precipitation possibility belongs in the condition column."),
("O","O? Overcast Sky! Broad cloud cover blocks much direct sunlight | cloudiness alone does not tell us exact temperature."),
("P","P is Puddle. Standing rainwater shows the ground is wet | boots may help more than extra warm layers."),
("Q","Q — Quilt! Warm bedding belongs indoors or at rest | not outdoor weather clothing."),
("R","R ... R ... Rainbow! Optical effect from sunlight and water droplets | beautiful clue, no special clothing required."),
("S","S? Snowflake! Falling ice crystals indicate snowy conditions | warmth and traction matter more than copying the shape."),
("T","T is Thunder. Sound caused by rapid heating and expansion around lightning | go indoors; clothing is not lightning protection."),
("U","U — Umbrella! Rain cover can help in ordinary rain | avoid using it as a solution in lightning or dangerous wind."),
("V","V ... V ... Vane! Wind-direction instrument points into or with wind orientation depending on design | station clue, not gear."),
("W","W? Wind! Moving air changes comfort and can increase heat loss | one reason layers may need adjustment."),
("X","X is X-band Radar. Weather radar can show precipitation patterns | information comes before a clothing decision."),
("Y","Y — Yellow Rain Boots! Bright waterproof boots keep feet drier in puddles and rain | color is fun; function is the real clue."),
("Z","Z ... Z ... Zipper Jacket! Zipper closes an outer layer quickly | final reminder that layers can be adjusted, not fixed all day."),),
"style_blueprint":"Crisp diction. Open with check-the-sky before dressing at 92 BPM in light 4/4 with acoustic guitar, snaps, soft bass and marimba. Melody narrow and speech-natural. Round 1 follows condition -> information -> gear decisions. Chorus says check-choose-adjust. Round 2 leaves one beat before target. Thunder, fog, icicle, wind and umbrella lines keep safety clear. Quilt is indoor context; radar/meters are information tools. Duck percussion at targets. End by unzipping one layer as conditions change."},
"0049": {
"authorial_intent":"Organize the song by three physical textures—wind movement, liquid rain, frozen precipitation—while instruments and clothing become responses or observers rather than being shoved into one rhythm family.",
"lyric_identity":"Whoosh, tap, hush are compositional colors, not fake sound effects for every target; transitions explain whether a target is wind, water, ice, gear, or measurement.",
"image_motifs":("windsock filling","drizzle tapping coat","frost edge","sun after storm","radar screen showing bands"),
"semantic_arc":("wind texture","rain and liquid water","ice and snow texture","clearing sun and measurement recap"),
"forbidden_generic_language":("three weather rhythms","whoosh tap hush for everything","weather beat","come sing"),
"rhyme_engine":"wind-rain-snow-texture-rhyme","chorus_rhyme_engine":"whoosh-tap-hush-hook","point_of_view":"a child sorting weather phenomena by physical texture and response","chorus_function":"reset the three texture families while allowing nonmembers to stay context","groove_meter":"4/4 with three restrained timbral pockets","round1_grammar":"hand-written physical-category lines; instruments and clothing are context","round2_grammar":"texture cue -> recall beat -> target -> safe abstract gesture",
"intro_lines":("Wind moves air. Drizzle moves drops. Frost holds still on a cold edge.","Three textures can share one day without becoming the same thing."),
"hook_lines":("Whoosh, tap, hush—A-B-C!","Wind, liquid, ice: sort the texture before the word."),
"outro_lines":("The Sun returns; puddles remain; the windsock still turns.","A to Z ends with three textures kept distinct."),
"round2_patterns":("Texture clue {letter} ... {object}! {action}","Wind-rain-ice {letter} ... {object}! {action}","Which family, {letter}? ... {object}! {action}","Weather texture {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Anemometer! Wind turns the sensor | instrument belongs to the whoosh family only as a measurement tool."),
("B","B ... B ... Boots! Footwear responds to wet or cold ground | gear, not precipitation."),
("C","C? Coat! Outer layer changes comfort | response object outside our three physical textures."),
("D","D is Drizzle. Fine liquid drops fall lightly | tap texture begins with actual water."),
("E","E — Eye of Storm! Some tropical cyclones have a calmer center | storm structure, not a rhythm effect."),
("F","F ... F ... Frost! Ice crystals form on cold surfaces | hush texture stays still rather than falling."),
("G","G? Gust! Brief increase in wind speed | one sharper whoosh inside moving air."),
("H","H is Humidity Meter. Hygrometer measures moisture in air | data clue connecting vapor and cloud formation."),
("I","I — Ice! Solid frozen water | same substance as rainwater, different phase and texture."),
("J","J ... J ... Jet Stream! Strong high-altitude wind band | huge-scale whoosh we cannot feel directly from the ground."),
("K","K? Kelvin Thermometer! Temperature in kelvins | measurement helps explain phase changes without becoming weather itself."),
("L","L is Lightning. Electrical discharge flashes during storms | thunder may follow; shelter beats rhythm play."),
("M","M — Mittens! Hand coverings respond to cold | gear in the hush section, not frozen water."),
("N","N ... N ... Nimbus Cloud! Rain-bearing cloud idea | source region for liquid or frozen precipitation depending conditions."),
("O","O? Overcoat! Warm outer layer | human response to cold or wet conditions."),
("P","P is Puddle. Liquid water collects after rain | tap texture becomes a still ground clue."),
("Q","Q — Quilt! Indoor warmth layer | not field gear and not weather."),
("R","R ... R ... Raincoat! Water-resistant outerwear | response to liquid precipitation."),
("S","S? Sun! Solar energy drives atmospheric heating | clearing does not belong to wind, rain, or snow texture itself."),
("T","T is Thunder. Sound follows lightning because air heats and expands rapidly | safety cue, not percussion for children outdoors."),
("U","U — Umbrella! Ordinary rain cover | useful in some liquid-rain conditions, unsafe as a lightning solution."),
("V","V ... V ... Vapor! Invisible water gas | water can change phase before cloud droplets become visible."),
("W","W? Windsock! Fabric tube aligns with wind | visible measurement-like clue for the whoosh family."),
("X","X is X-band Radar. Radar can reveal precipitation structure | screen clue connecting rain or snow bands to observation."),
("Y","Y — Yellow Sun! Atmospheric appearance clue | a warm visual ending after the precipitation sections."),
("Z","Z ... Z ... Zephyr! Gentle breeze | softest whoosh closes the sorting game."),),
"style_blueprint":"Crisp diction. Open by naming physical differences at 90 BPM in 4/4 with acoustic guitar, soft hand drum, shaker, muted claves and airy pad. Wind gets light continuous motion, rain gets sparse taps, ice/snow gets held quiet tones; gear/instruments use neutral texture. Chorus is whoosh-tap-hush but never overlays target words. Round 2 leaves one recall beat. Lightning/thunder/umbrella safety stays explicit. Duck percussion at target onsets. End with sun warmth and one gentle zephyr phrase."},
"0050": {
"authorial_intent":"Build a real little weather station workflow: sense wind, temperature, pressure, humidity/cloud state, compare readings, then write observations; ordinary gear appears only as nearby human context.",
"lyric_identity":"A child moves instrument to instrument—anemometer, gauge, thermometer, vane—then matches numbers with visible sky clues without claiming one device predicts everything.",
"image_motifs":("anemometer spinning","gauge needle","thermometer reading","vane arrow","notebook under overcast sky"),
"semantic_arc":("start wind instruments","add temperature and pressure","compare cloud/moisture observations","finish by logging rather than overpredicting"),
"forbidden_generic_language":("little station fun","one instrument tells the weather","click spin learn","weather machine"),
"rhyme_engine":"weather-station-measure-compare-rhyme","chorus_rhyme_engine":"measure-compare-log-hook","point_of_view":"a child using simple station instruments with adult guidance","chorus_function":"repeat measure-compare-log","groove_meter":"precise 4/4 with clean instrument-response gaps","round1_grammar":"hand-written measurement workflow; non-instruments are conditions or human context","round2_grammar":"station cue -> recall beat -> target -> safe instrument/point gesture",
"intro_lines":("Anemometer turns. Thermometer holds a number. Vane points a direction.","A weather station works by combining clues, not by trusting one dial."),
"hook_lines":("Measure, compare, log—A-B-C!","One reading joins another before we describe the sky."),
"outro_lines":("Numbers written, clouds sketched, instruments left in place.","A to Z closes the station log without pretending certainty."),
"round2_patterns":("Station clue {letter} ... {object}! {action}","Measure or observe {letter} ... {object}! {action}","Tool or condition—{letter}? ... {object}! {action}","Log entry {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Anemometer! Rotating cups or propeller respond to wind | station begins with wind speed."),
("B","B ... B ... Breeze! Light wind is the thing being sensed | phenomenon stays separate from the sensor."),
("C","C? Coat! Human outerwear beside the station | not a measuring device and not part of the weather data."),
("D","D is Drizzle. Fine liquid rain reaches the ground | visible observation that instruments can accompany."),
("E","E — Earmuffs! Cold-weather gear for the observer | useful context, zero measurement role."),
("F","F ... F ... Fog! Ground-level cloud lowers visibility | station log can record visibility along with numbers."),
("G","G? Gauge! A gauge displays a quantity | always name what a particular gauge measures before interpreting it."),
("H","H is Hail. Solid ice precipitation from strong thunderstorms | safety observation, not something to catch or collect."),
("I","I — Ice! Frozen water on surfaces can signal low temperatures | direct condition clue beside the thermometer."),
("J","J ... J ... Jet Stream! High-altitude strong wind band is tracked with broader meteorological data | our little station cannot measure it directly overhead."),
("K","K? Kelvin Thermometer! Temperature instrument can show kelvins | kelvin values are written without a degree symbol."),
("L","L is Low Cloud. Cloud base sits relatively low | visual sky observation beyond the instrument panel."),
("M","M — Mittens! Warm hand coverings for the observer | station context only."),
("N","N ... N ... Nimbus Cloud! Rain-cloud term in the mapping | cloud observation belongs beside precipitation notes."),
("O","O? Overcast Sky! Nearly complete cloud cover | broad visual category rather than one sensor reading."),
("P","P is Pressure Gauge. Pressure instrument adds another number | trends can matter more than decoration on the dial."),
("Q","Q — Quilt! Indoor warm layer | not station equipment, so it stays clearly outside the panel."),
("R","R ... R ... Rainbow! Optical effect from sunlight and droplets | observation clue no station dial needs to manufacture."),
("S","S? Sun! Solar heating drives daily temperature changes | source of energy, not an instrument reading."),
("T","T is Thermometer. Measures temperature | one of the station's clearest numeric tools."),
("U","U — Updraft! Rising air inside convection | important weather motion our simple ground station infers only indirectly."),
("V","V ... V ... Vane! Weather vane indicates wind direction | different job from anemometer speed."),
("W","W? Wind! Moving air is the phenomenon | compare vane direction and anemometer speed to describe it."),
("X","At the station shelf, X is X-band Radar | short radio waves help show rain or moving weather."),
("Y","Y — Yellow Sun! Apparent yellowish color can come from atmospheric scattering | visual note, not a sensor output."),
("Z","Z ... Z ... Zephyr! Gentle breeze | final wind observation returns us to the anemometer and vane."),),
"style_blueprint":"Crisp diction. Open with three distinct instrument functions at 88 BPM in precise 4/4 with acoustic guitar, marimba, soft woodblock ticks, bass and light shaker. Melody narrow and repeated-note friendly for technical words. Round 1 follows measure -> compare -> log. Chorus uses measure-compare-log. Round 2 leaves one clean recall beat. Anemometer=speed, vane=direction, thermometer=temperature, pressure gauge=pressure; never blur roles. Hail and low-visibility fog stay safety-aware. X-band Radar is the station's precipitation-observation tool. Duck target onsets and end with notebook-closing cadence."}
}
