from __future__ import annotations

"""Authorial-identity deep polish for mountain songs 0041-0045."""

GOLD_V5_41_45_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0041": {
        "authorial_intent": "Use real mountain echo as the memory device: hard rock returns sound, open valleys soften it, and each target either belongs to the landscape or is framed honestly as a helper object.",
        "lyric_identity": "A child calls once and listens to what comes back; the song alternates close rock, far ridge, bird flight, water and fading echo rather than shouting every line twice.",
        "image_motifs": ("voice returning from cliff", "hawk crossing a ridge", "glacier below dark rock", "waterfall carrying sound", "zigzag trail disappearing uphill"),
        "semantic_arc": ("first echo locates the cliff", "living and nonliving mountain clues answer differently", "water and altitude widen the sound field", "echo fades into the final switchback"),
        "forbidden_generic_language": ("highland words come back to me", "mountain fun", "everything echoes", "come sing with me"),
        "rhyme_engine": "mountain-echo-distance-answer-rhyme",
        "chorus_rhyme_engine": "call-return-fade-hook",
        "point_of_view": "a child making one careful call from a safe viewpoint and listening to how distance changes sound",
        "chorus_function": "turn call-return-fade into a memory reset without echoing over the target word",
        "groove_meter": "measured 4/4 with one-beat echo pockets and long valley tails",
        "round1_grammar": "hand-written distance-and-sound scenes; silent targets are visual anchors and unsafe cliff/ledge/summit cues remain viewpoint-only",
        "round2_grammar": "call or sight cue -> recall gap -> target -> safe point/listen gesture",
        "intro_lines": ("Hello, mountain—one call, then wait.", "The cliff sends part of our voice back across the air."),
        "hook_lines": ("Call, return, fade—A-B-C!", "Rock gives back a sound, then the valley lets it go."),
        "outro_lines": ("The last echo thins beside the waterfall.", "A to Z disappears around one quiet zigzag turn."),
        "interlude_lines": ("No new call for one breath—what mountain words return by memory alone?",),
        "round2_patterns": ("Echo clue {letter} ... {object}! {action}", "Near-or-far {letter} ... {object}! {action}", "Listen or look, {letter}? ... {object}! {action}", "Mountain reply {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Aspen! Pale trunks rise where mountain soil and moisture allow | leaves can tremble in a breeze while our echo stays in the rock."),
            ("B", "B ... B ... Bighorn Sheep! Split hooves grip steep terrain | heavy curved horns belong to adults, not to the cliff itself."),
            ("C", "C? Cliff! A steep rock face catches our first call | sound returns only after the target name is clear."),
            ("D", "D is Douglas Fir. Tall evergreen, hanging cones | a quiet vertical landmark beside louder stone."),
            ("E", "E — Eagle! Broad wings cross open air | the bird gives no echo, but its shape travels ridge to ridge."),
            ("F", "F ... F ... Fir! Evergreen needles hold through cold seasons | branches frame the view without making a sound cue."),
            ("G", "G? Glacier! Thick ice moves slowly downhill under its own weight | a long mountain motion, almost silent on our song's timescale."),
            ("H", "H is Hawk. Keen-eyed raptor rides moving air | one small silhouette above the echo line."),
            ("I", "I — Ibex! Sure hooves handle steep rocky ground | curved horns rise above a body built for mountain travel."),
            ("J", "J ... J ... Juniper! Evergreen shrub or tree with scale- or needle-like foliage | a low green anchor near stone."),
            ("K", "K? Kettle Lake! A depression left when buried glacier ice melted can fill with water | an old ice story held in a quiet basin."),
            ("L", "L is Ledge. Narrow shelf of rock | we name it from a safe viewpoint and never step toward an exposed edge."),
            ("M", "M — Mountain! Slopes rise into ridges and summit | the broad landform carrying every smaller clue."),
            ("N", "N ... N ... Nest! Twigs or other materials make a place for eggs and young | we look without disturbing it."),
            ("O", "O? Owl! Broad wings and forward-facing eyes | night flight belongs to the bird, not to a daytime echo trick."),
            ("P", "P is Pine. Needle bundles and woody cones | evergreen shape holds steady while sound fades."),
            ("Q", "Q — Quail! Ground bird with quick steps and short rounded body | a low moving clue beneath high rock."),
            ("R", "R ... R ... Ridge! Long narrow high ground | one skyline line can separate near slope from far valley."),
            ("S", "S? Summit! Highest point of a hill or mountain | a destination we can identify without pretending every route is safe."),
            ("T", "T is Trail. A route people follow through outdoor terrain | good paths guide feet while cliffs guide our eyes."),
            ("U", "U — Urial! Wild sheep with sure hooves | dry mountain slopes fit a different animal than the ibex but demand the same respect."),
            ("V", "V ... V ... Vulture! Broad wings soar on rising air | scavenging helps recycle nutrients through the ecosystem."),
            ("W", "W? Waterfall! Water drops over rock | continuous rush can mask a tiny echo, so the arrangement leaves the target dry."),
            ("X", "At the shelter, X is Xenolith. A rock fragment held inside another rock makes a visible mountain clue."),
            ("Y", "Y — Yarrow! Flat clusters of tiny flowers grow on a leafy stem in open mountain meadows."),
            ("Z", "Z ... Z ... Zigzag Trail! Switchbacks bend across a slope | back-and-forth routing can reduce steepness on the climb."),
        ),
        "style_blueprint": "Crisp diction. Open with one dry spoken-sung mountain call, then leave a real beat before a soft instrumental echo. Keep melody narrow and mostly stepwise at 88 BPM in 4/4 with acoustic guitar, low hand drum, sparse glockenspiel and soft flute. Round 1 alternates close rock, distant ridge, wildlife, ice and water; do not echo every line. Chorus lifts only slightly on call-return-fade. Round 2 uses a clean response gap. Duck percussion and backing voices at each target onset. Ledge, cliff and summit remain safe-viewpoint language. Xenolith is shown as a rock fragment inside another rock. Arrangement widens toward waterfall, then ends with the echo shrinking to silence and a clean cadence.",
    },
    "0042": {
        "authorial_intent": "Make peaks and valleys a true contour song: every phrase rises, falls, crosses, or rests according to landform, while animals and plants occupy honest positions instead of all being 'high mountain' objects.",
        "lyric_identity": "A child reads a side-profile of terrain from valley floor to slope to crest and back down; vertical contour is the recurring compositional logic.",
        "image_motifs": ("valley floor under a cliff", "goat on broken slope", "icefall dropping through glacier", "waterfall descending", "switchback easing a steep grade"),
        "semantic_arc": ("begin low in valley", "climb through slope animals and rock", "reach summit and open meadow", "descend by waterfall and zigzag trail"),
        "forbidden_generic_language": ("valleys low come sing with me", "peaks up high", "up and down all day", "mountain words"),
        "rhyme_engine": "peak-valley-contour-chain",
        "chorus_rhyme_engine": "low-rise-crest-return-hook",
        "point_of_view": "a child tracing terrain shape with eyes and hands from valley to crest and down again",
        "chorus_function": "re-establish low-rise-crest-return as the route memory",
        "groove_meter": "6/8 contour sway with rising and descending melodic arcs",
        "round1_grammar": "hand-written contour placement; living targets use habitat contrast and tools remain human-use context",
        "round2_grammar": "contour cue -> recall beat -> target -> low/mid/high or shape gesture",
        "intro_lines": ("Start low where two slopes lean toward the valley.", "Now trace one line upward until the sky meets rock."),
        "hook_lines": ("Low, rise, crest—A-B-C!", "Every slope has another way back down."),
        "outro_lines": ("Water falls while the trail folds gently across the slope.", "A to Z returns to the valley floor."),
        "round2_patterns": ("Contour clue {letter} ... {object}! {action}", "Low-mid-high {letter} ... {object}! {action}", "Where on the slope, {letter}? ... {object}! {action}", "Rise or return {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Alpine Goat! Sure hooves take broken ground | body stays close to the slope while our melody starts to rise."),
            ("B", "B ... B ... Boulder! One huge rock sits still | a contour marker that does not need to be a summit."),
            ("C", "C? Cliff! Steep exposed rock lifts almost straight | a sharper rise than a walkable trail."),
            ("D", "D is Douglas Fir. Tall evergreen follows the slope line | hanging cones point down while the tree rises up."),
            ("E", "E — Edelweiss! Small starry flower of high mountain habitats | a low plant beneath a large sky."),
            ("F", "F ... F ... Falcon! Strong wings cross from one contour line to another | air ignores the route our feet must follow."),
            ("G", "G? Goat! Hooves step where footing allows | one living clue on the incline, not a cartoon climber on every cliff."),
            ("H", "H is Hawk. Broad circles ride rising air | height comes from flight, not from standing at the crest."),
            ("I", "I — Icefall! A steep broken section of glacier flows downhill faster than flatter ice | cracked blue-white contour in motion."),
            ("J", "J ... J ... Jay! Perch, hop, fly | a bird crossing trees and openings along the slope."),
            ("K", "K? Kestrel! Small falcon can hover or perch | one precise sky marker over lower ground."),
            ("L", "L is Lynx. Furry wild cat moves quietly over land | broad paws and long legs belong to terrain, not vertical rock faces."),
            ("M", "M — Marmot! Stocky mountain mammal lives around burrows and rocky places | a low round body beneath high peaks."),
            ("N", "N ... N ... Nest! A protected place for eggs or young | height varies by species, so we do not force one layer."),
            ("O", "O? Outcrop! Bedrock appears at the surface | a hard edge where the landform shows what it is made of."),
            ("P", "P is Pika. Small round-eared mammal lives among rocks | quick movement stays close to talus and crevices."),
            ("Q", "Q — Quail! Ground bird steps through lower cover | one valley-side contrast to falcon and hawk."),
            ("R", "R ... R ... Rope! Strong flexible climbing equipment | children identify it as adult-guided gear, never a cue to climb."),
            ("S", "S? Summit! Highest point closes the upward contour | our voice reaches the crest before the route turns down."),
            ("T", "T is Trail. A path bends with terrain | good routes avoid pretending the shortest line is always safest."),
            ("U", "U — Upland Meadow! Open grassy or flower-rich ground at elevation | a broad pause after steep rock."),
            ("V", "V ... V ... Valley! Low land between higher slopes | the place our contour has been measuring against all along."),
            ("W", "W? Waterfall! Water takes the steepest visible direction—down | one clear descending phrase."),
            ("X", "X is Xenolith. A rock fragment trapped inside another rock | a small inner shape in the mountain contour."),
            ("Y", "Y — Yarrow! Flat clusters of tiny flowers rise on a leafy stem | a meadow plant in the mountain scene."),
            ("Z", "Z ... Z ... Zigzag Trail! Switchbacks spread one steep climb across many gentler turns | contour becomes route design."),
        ),
        "style_blueprint": "Crisp diction. Open low in register, then let the melody rise and fall with terrain. 84 BPM, gentle 6/8 with nylon guitar, marimba, shaker and soft bass. Keep targets on stable repeated or stepwise notes; long terms like Upland Meadow get extra space. Round 1 uses real contour logic: valley low, cliff steep, summit high, waterfall down, zigzag across. Chorus states low-rise-crest and then descends. Round 2 leaves one recall beat and uses low/mid/high hand levels. Rope is identify-only adult-guided gear. Duck percussion at target words. End by descending back to the opening register with a clean cadence.",
    },
    "0043": {
        "authorial_intent": "Make the alpine meadow song about small life inside a huge landscape: grass, flowers, seed-carrying birds, rocks, shelter and weather scale are contrasted without calling every mapping target meadow flora.",
        "lyric_identity": "A child kneels visually into meadow scale, then looks back to glacier and mountain scale; the writing alternates tiny details and vast background.",
        "image_motifs": ("grass bent by wind", "nutcracker carrying seed", "quartz in thin soil", "glacier beyond flowers", "tent at meadow edge"),
        "semantic_arc": ("start with tiny meadow movement", "notice birds, plants and ground textures", "pull focus outward to ice and mountain", "return to a careful camp-edge view"),
        "forbidden_generic_language": ("mountain nature blooms with me", "everything blooms", "meadow friends", "pretty flowers everywhere"),
        "rhyme_engine": "alpine-meadow-scale-shift-rhyme",
        "chorus_rhyme_engine": "small-wide-near-far-hook",
        "point_of_view": "a child shifting focus from close meadow details to huge alpine background",
        "chorus_function": "reset near-small versus far-wide visual scale",
        "groove_meter": "airy 6/8 with close-detail pizzicato and wide held phrases",
        "round1_grammar": "hand-written scale shifts; human gear and garden-mapping helpers are framed honestly",
        "round2_grammar": "near/far cue -> recall beat -> target -> point/shape gesture",
        "intro_lines": ("One blade of grass bends while a glacier fills the far horizon.", "The alpine meadow is small detail inside a very large place."),
        "hook_lines": ("Near, far, small, wide—A-B-C!", "Meadow detail, mountain distance—hold them both in view."),
        "outro_lines": ("Tent zipped, boots still, meadow left untouched.", "A to Z closes on one flower-size detail beneath a mountain-size sky."),
        "round2_patterns": ("Near clue {letter} ... {object}! {action}", "Far-view {letter} ... {object}! {action}", "Small or wide, {letter}? ... {object}! {action}", "Meadow frame {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Aspen! Leaves flutter above the meadow edge | one tree-scale frame around smaller grass."),
            ("B", "B ... B ... Boulder! Large rock sits among much smaller stems | scale changes before the alphabet does."),
            ("C", "C? Cabin! Human shelter belongs near the landscape | it is context, not alpine wildlife or meadow growth."),
            ("D", "D is Deer. Hooves carry a large herbivore over land | one moving body beyond our close flower view."),
            ("E", "E — Eagle! Broad wings cross the far sky | tiny from here, large in reality."),
            ("F", "F ... F ... Fir! Evergreen needles hold on branches | taller plant structure beyond low meadow leaves."),
            ("G", "G? Glacier! Thick moving ice fills a distant valley | huge background to fragile foreground plants."),
            ("H", "H is Hiking Boot. Sturdy human footwear protects feet on rough trails | keep boots on the route, not on meadow flowers."),
            ("I", "I — Icefall! Broken steep glacier ice flows downhill | jagged far texture behind soft grass."),
            ("J", "J ... J ... Jay! Feathered bird hops, perches, then flies | quick motion between near and far."),
            ("K", "K? Kettle Lake! A basin linked to old buried glacier ice can hold water | an ice-age shape now reflecting the sky."),
            ("L", "L is Lynx. Quiet wild cat moves over land | a distant wildlife clue that we never follow through the meadow."),
            ("M", "M — Mountain! Massive slopes hold the whole scene | widest scale in the song."),
            ("N", "N ... N ... Nutcracker! Mountain bird uses a strong bill to handle and cache seeds | small actions can shape future plant growth."),
            ("O", "O? Outcrop! Solid rock exposed at ground surface | hard texture emerging through thin soil."),
            ("P", "P is Pine. Needles and woody cones | tree-scale green beyond the meadow layer."),
            ("Q", "Q — Quartz! Hard mineral can flash glassy light | tiny bright detail inside a boulder-sized world."),
            ("R", "R ... R ... Rope! Strong flexible equipment used by people | identify it safely; the song never invites climbing practice."),
            ("S", "S? Summit! Highest point on the mountain | far above our low meadow viewpoint."),
            ("T", "T is Tent. Portable fabric shelter for people | set on suitable ground, not on fragile plants."),
            ("U", "U — Upland Meadow! Open grassy or flower-rich area at elevation | the central habitat frame of the song."),
            ("V", "V ... V ... Valley! Low land between higher slopes | broad distance cue beyond close grass."),
            ("W", "W? Wolf! Wild canid travels over land | observe from distance and never turn a meadow walk into tracking wildlife."),
            ("X", "X is Xenolith. A rock fragment trapped inside another rock | a different stone story within the mountain wall."),
            ("Y", "Y — Yak! Large long-haired bovine of high Asian regions | one high-country animal, not a universal alpine species."),
            ("Z", "Z ... Z ... Zigzag Trail! Switchbacks bend across the slope | a route that makes a steep climb gentler."),
        ),
        "style_blueprint": "Crisp diction. Open with near grass and far glacier in one image. 86 BPM airy 6/8 with acoustic guitar, pizzicato strings, soft shaker and very sparse bell. Keep melody narrow around target names. Arrange near details with dry pizzicato and far landscapes with longer held tones. Round 1 alternates small/large scale instead of catalog facts. Chorus says near-far-small-wide. Round 2 leaves one recall beat and uses framing gestures. Hiking Boot, Rope, Cabin and Tent stay human context; Zigzag Trail is a real switchback route across the slope. Duck percussion on target onset. End sparse, as if leaving the meadow untouched.",
    },
    "0044": {
        "authorial_intent": "Turn Mountain Trail Scout into evidence-based route reading: trail surface, landmark, weather residue, safe equipment and distant wildlife become field notes, while the song repeatedly rewards leaving things where they are.",
        "lyric_identity": "A child scout records rather than collects; recurring verbs are notice, sketch, mark, compare, leave, check and turn back.",
        "image_motifs": ("boot tread beside trail marker", "quartz left in place", "snow patch in shade", "ridge used as orientation", "waterfall heard before seen"),
        "semantic_arc": ("begin with route evidence", "add geology and wildlife clues", "check gear and changing conditions", "finish by leaving every natural clue undisturbed"),
        "forbidden_generic_language": ("find the mountain clues with me", "trail scout fun", "collect the clues", "explorer eyes"),
        "rhyme_engine": "mountain-fieldnote-evidence-rhyme",
        "chorus_rhyme_engine": "notice-mark-leave-hook",
        "point_of_view": "a supervised child scout documenting mountain clues without collecting natural objects or approaching wildlife",
        "chorus_function": "repeat notice-mark-leave as the ethical memory rule",
        "groove_meter": "steady 4/4 hiking pulse with field-note pauses",
        "round1_grammar": "hand-written field evidence; gear gets use context, hazards get turn-back language, wildlife stays distant",
        "round2_grammar": "field-note cue -> recall beat -> target -> sketch/point gesture",
        "intro_lines": ("Boot tread, trail mark, one patch of old snow.", "We can learn a lot without picking up a single thing."),
        "hook_lines": ("Notice, mark, leave—A-B-C!", "Good scouts learn the clue and leave the mountain free."),
        "outro_lines": ("Notebook closed; quartz, flower, nest, and snow stay where they were.", "A to Z walks home with observations, not souvenirs."),
        "round2_patterns": ("Field note {letter} ... {object}! {action}", "Route evidence {letter} ... {object}! {action}", "Check, don't collect—{letter}? ... {object}! {action}", "Leave-it clue {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "Field note A — Alpine Goat. Sure hooves on steep ground | wildlife evidence belongs at distance, not at the end of our path."),
            ("B", "B ... B ... Boulder! Shape, grain, shadow | sketch the large rock and leave it exactly where it sits."),
            ("C", "C? Cabin! Human-built shelter becomes a route landmark | useful context, not a natural clue to collect."),
            ("D", "D is Deer. Hoofed mammal can leave tracks | identify signs without following the animal."),
            ("E", "E — Edelweiss! Small pale flower of mountain habitats | observe or photograph, never pluck for the notebook."),
            ("F", "F ... F ... Falcon! Fast raptor crosses open sky | one distant motion mark on the field page."),
            ("G", "G? Glacier! Thick flowing ice marks a much larger process | route planning respects crevasses and unstable ice."),
            ("H", "H is Hiking Boot. Sturdy sole supports feet on rough trail | equipment clue stays on the hiker, not in the ecosystem."),
            ("I", "I — Ibex! Wild goat relative on steep rock | note body shape and distance, then keep the route."),
            ("J", "J ... J ... Juniper! Evergreen woody plant | leaf and cone shapes are enough—no cutting needed."),
            ("K", "K? Kettle Lake! Basin created after buried glacier ice melted | water becomes a landmark and a geology clue together."),
            ("L", "L is Ledge. Narrow rock shelf | if a route reaches exposure, the field note can simply say turn back."),
            ("M", "M — Marmot! Stocky mountain mammal around burrows and rocks | watch from afar and keep food packed away."),
            ("N", "N ... N ... Nutcracker! Mountain bird with strong bill | seed-caching behavior is a clue we observe, not interrupt."),
            ("O", "O? Owl! Night-active bird with broad wings and keen senses | a possible sound or sight note, never a nest-search mission."),
            ("P", "P is Pine. Needle bundles and woody cones | tree identity comes from features, not souvenirs."),
            ("Q", "Q — Quartz! Hard mineral with glassy luster | point, sketch, leave—the rock stays on the mountain."),
            ("R", "R ... R ... Ridge! Long high line guides orientation | skyline becomes a natural map edge."),
            ("S", "S? Snow! Ice crystals can linger in shaded mountain patches | condition clue that can change footing and route choice."),
            ("T", "T is Tent. Portable human shelter | camping belongs only where rules and suitable sites allow."),
            ("U", "U — Upland Meadow! Open elevated grassland | footsteps stay on durable routes when plants are fragile."),
            ("V", "V ... V ... Vulture! Soaring scavenger uses rising air | record the silhouette and let it keep its distance."),
            ("W", "W? Waterfall! Sound may arrive before the view | route clue heard around a bend, not a reason to scramble off-trail."),
            ("X", "X is Xenolith. Rock fragment inside another rock | compare the inner shape without breaking the stone."),
            ("Y", "Y — Yarrow! Tiny flowers gather in flat clusters | a leafy meadow plant in the mountain mapping."),
            ("Z", "Z ... Z ... Zigzag Trail! Switchbacks turn repeatedly across a slope | route design becomes the final field-note pattern."),
        ),
        "style_blueprint": "Crisp diction. Open with boot tread, marker and snow patch. 92 BPM steady 4/4 hiking folk with acoustic guitar, woodblock, light hand clap, recorder accents and warm bass. Keep melody narrow and speech-natural. Round 1 functions like field notes: notice, sketch, compare, leave. Chorus lifts on notice-mark-leave, not generic exploration. Round 2 leaves one recall beat and uses air-sketch/point gestures only. Glacier, ledge, snow and wildlife all carry explicit safety or distance framing. Duck percussion on every target onset. End with notebook-closing dry cadence and no triumphant conquest feel.",
    },
    "0045": {
        "authorial_intent": "Use glacier time as the song's signature: animal steps happen in seconds, snow changes by season, valleys and kettle lakes preserve old ice stories, and glacier flow happens far more slowly than a walking beat.",
        "lyric_identity": "A child compares fast, slow, seasonal and geological change along one glacier-adjacent trail.",
        "image_motifs": ("fresh hoofprint beside old moraine-like rock", "ice moving too slowly to see", "kettle lake holding glacial history", "snow patch melting", "zigzag trail crossing valley wall"),
        "semantic_arc": ("begin with fast living steps", "slow down toward ice processes", "read old glacier-shaped landforms", "return to present trail and seasonal snow"),
        "forbidden_generic_language": ("glacier steps", "walk on with me", "sparkle ice", "everything moves slowly"),
        "rhyme_engine": "glacier-timescale-contrast-rhyme",
        "chorus_rhyme_engine": "fast-slow-old-now-hook",
        "point_of_view": "a child comparing timescales beside a glacier without stepping onto dangerous ice",
        "chorus_function": "restate fast-slow-old-now as the learning framework",
        "groove_meter": "measured 4/4 with fast pickups against long sustained ice phrases",
        "round1_grammar": "hand-written timescale contrast; glacier and landform facts are distinct from animal motion and human gear",
        "round2_grammar": "fast/slow/old/now cue -> recall beat -> target -> safe timing gesture",
        "intro_lines": ("A hoofprint can appear in one moment; a glacier valley takes far longer to shape.", "Today we walk beside different clocks."),
        "hook_lines": ("Fast, slow, old, now—A-B-C!", "Mountain time is more than one walking beat."),
        "outro_lines": ("Fresh tracks fade; the valley keeps a much older shape.", "A to Z leaves us beside ice we only observe from safe ground."),
        "round2_patterns": ("Time clue {letter} ... {object}! {action}", "Fast-or-slow {letter} ... {object}! {action}", "Old or now, {letter}? ... {object}! {action}", "Glacier-side {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Alpine Goat! One hoofstep happens now | sure-footed movement makes the first fast clock."),
            ("B", "B ... B ... Bighorn Sheep! Walking, pausing, climbing | living motion measured in seconds and minutes."),
            ("C", "C? Cabin! Human shelter can be built within a lifetime | a much shorter clock than a mountain valley."),
            ("D", "D is Deer. Hooves cross land in present time | fresh movement against old rock."),
            ("E", "E — Eagle! Wingbeats happen quickly, soaring can last longer | still tiny compared with moving ice."),
            ("F", "F ... F ... Fir! Evergreen growth adds rings and branches over years | plant time sits between footsteps and glaciers."),
            ("G", "G? Goat! Step, pause, step | a fast living rhythm on a slow landscape."),
            ("H", "H is Hawk. A turn in the air takes seconds | shadow passes long before the valley changes."),
            ("I", "I — Ibex! Sure hooves cross steep ground | another now-time clue above very old rock."),
            ("J", "J ... J ... Juniper! Woody growth records seasons | slow enough to miss in a single walk."),
            ("K", "K? Kettle Lake! A hollow linked to melting buried glacier ice can remain as a lake | old ice process visible in today's water."),
            ("L", "L is Lynx. Quiet mammal crosses land in moments | tracks may fade far sooner than the landform."),
            ("M", "M — Marmot! Quick movement, long seasonal rest patterns | animal time changes with the year."),
            ("N", "N ... N ... Nutcracker! Seed carrying can happen in seconds | cached seeds connect one season to another."),
            ("O", "O? Outcrop! Bedrock exposed at the surface | geological material older than our whole trail day."),
            ("P", "P is Pika. Small mountain mammal moves quickly among rocks | a fast clock tucked inside slow terrain."),
            ("Q", "Q — Quartz! Hard mineral formed by geological processes | stone time stretches far beyond a song."),
            ("R", "R ... R ... Rope! Human-made gear can be packed away tonight | context on the shortest practical clock."),
            ("S", "S? Snow! Falls in weather, melts with conditions, may linger seasonally | cold landscape changes on more than one timescale."),
            ("T", "T is Trail. A path can shift through use, weather and maintenance | human-scale change written over older terrain."),
            ("U", "U — Urial! Wild sheep steps belong to the present | another living pulse over long-lived slopes."),
            ("V", "V ... V ... Valley! Low land between slopes may preserve the shape of ancient erosion or glaciation | old geometry beneath today's walk."),
            ("W", "W? Wolf! Wild canid crosses large distances in living time | we observe from afar and never follow."),
            ("X", "At the visitor shelter, X is Xenolith | one rock fragment held inside another tells a small geology story."),
            ("Y", "Y — Yarrow! A flower can open and fade within a season | short plant time against old valley rock."),
            ("Z", "Z ... Z ... Zigzag Trail! Switchbacks can be built or repaired by people | present-day route laid across a much older slope."),
        ),
        "style_blueprint": "Crisp diction. Open by contrasting one hoofstep with glacier-scale change. 85 BPM measured 4/4 with acoustic guitar, muted drum, soft shaker, low strings and sparse glockenspiel. Use short pickups for animals, medium held phrases for plants/seasons, and long sustained notes for glacier/valley/geology. Round 1 must make timescale contrast explicit without claiming exact ages. Chorus is fast-slow-old-now. Round 2 leaves one recall beat and uses finger-tap versus long hand-glide timing gestures. No walking onto glacier or icefall. Xenolith is a shelter-side geology observation, not a living thing. Duck percussion at targets and finish on a long valley note with a clean cadence.",
    },
}
