from __future__ import annotations

"""Authorial-identity deep polish for pet-care songs 0071-0075."""

GOLD_V5_71_75_SPEC_PATCHES: dict[str, dict[str, object]] = {
"0071": {
"authorial_intent":"Make Pet Care ABC a daily-needs routine: species-appropriate habitat, fresh water, food, exercise, grooming, identification and veterinary care come before toys, with each animal's needs kept distinct.",
"lyric_identity":"Morning-to-evening care checklist asks what the animal needs rather than what looks cute.",
"image_motifs":("fresh water bowl","hamster wheel sized safely","iguana UVB basking area","cat scratching post","carrier ready for vet"),
"semantic_arc":("habitat and water","food and exercise","grooming/ID","vet travel and rest"),
"forbidden_generic_language":("pet words padding","pets are toys","one care fits all","cute pet fun"),
"rhyme_engine":"pet-daily-needs-checklist-rhyme","chorus_rhyme_engine":"water-food-shelter-hook","point_of_view":"a child helping with pet care under adult responsibility","chorus_function":"reset water-food-shelter-health","groove_meter":"calm 4/4 routine pulse","round1_grammar":"hand-written species-specific care; medical/grooming tools adult-guided","round2_grammar":"care cue -> recall beat -> target -> safe point/pretend gesture",
"intro_lines":("Fresh water first. Habitat check second. Play comes after the animal's needs are met.","Pet care is a routine, not a pile of toys."),
"hook_lines":("Water, food, shelter—A-B-C!","Care fits the species, every day."),
"outro_lines":("Carrier ready, bowls clean, lights timed, resting place quiet.","A to Z ends when the pet can settle safely."),
"round2_patterns":("Care need {letter} ... {object}! {action}","Routine {letter} ... {object}! {action}","Need or tool—{letter}? ... {object}! {action}","Care check {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Angelfish! Tropical freshwater fish needs suitable tank volume, stable water quality, heat, and compatible tankmates | bowl-sized living is not enough."),
("B","B ... B ... Bowl! Food or water dish must suit the animal and stay clean | one bowl cannot replace a proper fish aquarium."),
("C","C? Cat! Needs food, fresh water, litter care, scratching outlets, play, rest, and veterinary care | independence is not no-care."),
("D","D is Doghouse. Outdoor shelter can provide shade and weather protection | it never replaces exercise, companionship, water, and safe indoor care where appropriate."),
("E","E — Exercise Wheel! Hamster wheel should be solid-surfaced and large enough for a natural running posture | tiny bent-back wheels are not enrichment."),
("F","F ... F ... Fish! Different species need different tank size, temperature, filtration, water chemistry, and social setup."),
("G","G? Grooming Brush! Coat-appropriate brushing can remove loose hair and detect tangles | gentle technique depends on species and coat type."),
("H","H is Hamster. Needs secure spacious habitat, deep bedding, hiding places, suitable wheel, food and water | many hamsters are solitary by nature."),
("I","I — Iguana! Reptile needs species-appropriate heat gradient, diet, humidity, space, and UVB exposure | care is specialized."),
("J","J ... J ... Jingle Ball! Toy may enrich play if size and construction are safe | inspect for loose parts and swallowing hazards."),
("K","K? Kibble! Dry prepared food can be part of a balanced diet when formulated for the species and life stage | portion still matters."),
("L","L is Leash. Properly fitted leash and collar or harness help manage a dog outdoors | training and supervision matter too."),
("M","M — Meal Bowl! Portion goes in the dish; nutritional balance comes from the food plan | a full bowl is not automatically the right amount."),
("N","N ... N ... Nail Clipper! Nail trimming needs correct tool and knowledge of the quick | adult or veterinary/grooming guidance prevents injury."),
("O","O? Octopus Toy! Shape is playful, but safety depends on material, size, seams, and the pet using it | inspect toys regularly."),
("P","P is Puppy. Young dog needs socialization, training, sleep, vaccines and veterinary care, suitable food, and safe exercise | play is only one part."),
("Q","Q — Quilt Bed! Soft resting place can add comfort | bedding must be washable and safe from chewing or loose threads for that animal."),
("R","R ... R ... Rabbit! Needs unlimited grass hay as a major diet component, leafy greens, water, space, hiding, and safe chewing opportunities."),
("S","S? Scratching Post! Gives cats an appropriate surface to scratch, stretch, and mark | stable height and placement improve use."),
("T","T is Turtle. Care varies by species; aquatic turtles need appropriate water, basking, filtration, heat, diet, and UVB."),
("U","U — UV Lamp! Reptile care often requires a suitable UVB source, correctly placed and replaced on schedule | not every lamp labeled UV is appropriate."),
("V","V ... V ... Vest Harness! Harness must fit the species and body securely without rubbing or restricting breathing or movement."),
("W","W? Water Bowl! Fresh clean water needs regular replacement | some species also need other hydration or aquatic-habitat systems."),
("X","X is Xylophone Toy, our picture clue | sound toys should be pet-safe and never forced on animals that find noise stressful."),
("Y","Y — Yellow Canary! Small songbird needs spacious flight-oriented cage, perches, balanced diet, bathing opportunity, light-dark routine, and social/environmental enrichment."),
("Z","Z ... Z ... Zip Carrier! Secure ventilated carrier makes transport safer | introduce it calmly before emergency or vet travel."),),
"style_blueprint":"Crisp diction. Open with needs-before-toys at 86 BPM in calm 4/4 with acoustic guitar, soft bass, shaker and marimba. Melody narrow and speech-clear. Round 1 follows habitat -> water/food -> enrichment -> grooming/health -> transport. Chorus water-food-shelter. Round 2 uses pretend care gestures only; no real nail clipping, ear cleaning, feeding, or animal restraint. Duck target onsets. End with quiet resting-place cadence."},
"0072": {
"authorial_intent":"Make Pets at Home A-Z a home-environment zoning song: aquarium, litter area, resting area, perch, kennel, grooming kit and carrier each belong to different species and functions instead of one generic pet room.",
"lyric_identity":"A child maps clean, quiet, active, feeding and health zones around a responsible home.",
"image_motifs":("filtered aquarium","litter box away from food","canary perch","guinea pig hide","vet carrier by door"),
"semantic_arc":("habitat zones","feeding/toileting separation","grooming and health","safe travel/rest"),
"forbidden_generic_language":("one caring picture","every pet at home same","pet room","alphabet grow"),
"rhyme_engine":"pet-home-zone-rhyme","chorus_rhyme_engine":"place-clean-quiet-hook","point_of_view":"a child mapping species-specific home care zones","chorus_function":"reset place-clean-quiet","groove_meter":"gentle 6/8 room-to-room sway","round1_grammar":"hand-written placement/function; medical tools adult/vet context","round2_grammar":"zone cue -> recall beat -> target -> point-to-place gesture",
"intro_lines":("Aquarium water belongs in one zone; litter belongs far from the food bowl; a quiet bed belongs somewhere else.","A good pet home is arranged around the animal, not the alphabet."),
"hook_lines":("Place, clean, quiet—A-B-C!","Right care item, right species, right part of home."),
"outro_lines":("Litter cleaned, water refreshed, carrier stored open and familiar.","A to Z leaves the home organized around real needs."),
"round2_patterns":("Home zone {letter} ... {object}! {action}","Place {letter} ... {object}! {action}","Which zone {letter}? ... {object}! {action}","Home-care {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Aquarium! Fish habitat needs adequate size, filtration, temperature and water quality | decoration comes after biology."),
("B","B ... B ... Bunny! Domestic rabbit needs large exercise space, hay, hiding and litter options | not a tiny cage corner."),
("C","C? Cat! Home needs clean litter area, scratch surfaces, vertical/rest spaces, play and resources distributed to reduce stress."),
("D","D is Doghouse. Outdoor shelter can be one weather-protected rest spot | family contact and broader care still happen beyond it."),
("E","E — Ear Cleaner! Only pet-safe product used when appropriate and directed by a veterinarian | never pour random household liquid into ears."),
("F","F ... F ... Feather Toy! Cat toy can mimic prey movement | supervised play prevents swallowing strings or detached feathers."),
("G","G? Guinea Pig! Needs roomy enclosure, hay, vitamin-C-appropriate nutrition, hiding places, companionship with compatible guinea pigs, and floor time."),
("H","H is Hamster. Deep bedding and hiding zones support burrowing | nocturnal rest needs a quiet daytime location."),
("I","I — ID Tag! Identification information helps return lost pets | tag complements, not replaces, secure management and microchip where appropriate."),
("J","J ... J ... Jumping Toy! Enrichment item must fit species and avoid unsafe heights, entrapment, or loose pieces."),
("K","K? Kitten! Growing cat needs kitten-appropriate nutrition, litter setup, socialization, play, sleep, vaccination and veterinary care."),
("L","L is Litter Box. Toilet area for cats should be accessible, regularly scooped, and generally kept away from food and water."),
("M","M — Mouse! Pet mice need secure ventilated enclosure, bedding, hides, nesting material, food and enrichment | social needs depend on sex and individual management."),
("N","N ... N ... Nail Clipper! Grooming tool belongs in adult-guided care | knowing nail anatomy matters more than speed."),
("O","O? Outdoor Kennel! Secure outdoor area can provide temporary exercise or shelter | not a substitute for social contact, climate safety, and indoor care."),
("P","P is Perch. Bird perches should vary in diameter and texture and allow clean foot placement | cage layout must preserve flight/movement space."),
("Q","Q — Quilt Bed! Washable soft rest zone can comfort some pets | choose material that cannot be dangerously shredded or swallowed."),
("R","R ... R ... Rope Toy! Tug or climbing toy must match species, supervision, fiber condition, and chewing behavior."),
("S","S? Scratching Post! Place where cat naturally wakes, travels, or marks | sturdy positioning turns furniture conflict into a better option."),
("T","T is Turtle. Habitat can require water zone, basking zone, heat, filtration and UVB depending species | setup is a system, not a bowl."),
("U","U — Undercoat Brush! Coat-specific grooming tool removes loose undercoat | overbrushing or wrong tools can irritate skin."),
("V","V ... V ... Vet Kit! At-home kit should support basic safe transport/records and veterinarian-recommended supplies | it does not replace diagnosis or treatment."),
("W","W? Water Bowl! Fresh water station stays clean and accessible | placement should reduce contamination."),
("X","X is X-ray Vet Image. Diagnostic image made by veterinary equipment | interpretation belongs to trained veterinary professionals."),
("Y","Y — Yellow Canary! Bird home needs horizontal flight room, safe perches, balanced nutrition and predictable rest | cage is habitat, not decoration."),
("Z","Z ... Z ... Zip Carrier! Ventilated secure transport zone | familiar bedding or calm training can reduce travel stress."),),
"style_blueprint":"Crisp diction. Open with three separate home zones at 84 BPM in gentle 6/8 with nylon guitar, pizzicato, soft shaker and bass. Melody narrow. Round 1 moves room-to-room by function, never mixing litter/food/rest. Chorus place-clean-quiet. Round 2 uses pointing-to-imaginary-zone gestures. Ear cleaner, nail clipper, vet kit and X-ray stay adult/veterinary context. Duck target onsets. End with a calm organized-home cadence."},
"0073": {
"authorial_intent":"Make Pet Playtime Beat an enrichment design song: play should fit species, age, body and safety, and the lyric repeatedly separates enrichment from food, housing, medical care and identification.",
"lyric_identity":"A child tests 'safe, sized, supervised, optional' before calling an object a toy.",
"image_motifs":("cat scratch/play split","hamster wheel","rope toy inspection","dog collar ID","X-ray image no-play boundary"),
"semantic_arc":("movement enrichment","chew/scratch/play","food/rest boundaries","medical/non-toy boundary"),
"forbidden_generic_language":("bounce roll stop","everything is a toy","pet play beat","play all day"),
"rhyme_engine":"pet-enrichment-safe-choice-rhyme","chorus_rhyme_engine":"safe-sized-supervised-hook","point_of_view":"a child choosing enrichment with adult supervision","chorus_function":"repeat safe-sized-supervised","groove_meter":"playful 4/4 stop-check-go pulse","round1_grammar":"hand-written play suitability; non-toys explicit","round2_grammar":"play-or-not cue -> recall beat -> target -> pretend-only gesture",
"intro_lines":("Before play starts: safe size, strong seams, no loose piece to swallow.","A care item is not automatically a toy."),
"hook_lines":("Safe, sized, supervised—A-B-C!","Play works when the animal can choose and the object fits."),
"outro_lines":("Toy box checked, food put away, X-ray image stays with the vet.","A to Z ends when play can stop calmly."),
"round2_patterns":("Play check {letter} ... {object}! {action}","Toy or care {letter} ... {object}! {action}","Safe play {letter}? ... {object}! {action}","Enrichment {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Angelfish! Fish enrichment comes from suitable habitat complexity, compatible social setup, and room to swim | tapping glass is not play."),
("B","B ... B ... Bunny! Rabbits benefit from tunnels, digging, chewing and foraging | lifting or chasing is not enrichment."),
("C","C? Collar! Identification/control equipment, not a toy | fit should allow comfort and safe attachment."),
("D","D is Dog. Play may include sniffing, tug, retrieve, training games, and social interaction | individual preference and health matter."),
("E","E — Exercise Wheel! Appropriate for hamsters and some small rodents when solid, stable, and correctly sized | not universal pet equipment."),
("F","F ... F ... Fish! Habitat enrichment should not obstruct swimming or damage fins | species behavior guides design."),
("G","G? Grooming Brush! Care tool can feel pleasant for some pets, but brushing is not play and must stop if the animal is stressed."),
("H","H is Hutch. Housing/shelter structure, not enrichment by itself | rabbits still need far more usable space and activity."),
("I","I — ID Tag! Safety/identification object | keep it readable and securely attached, never use as a jingle toy."),
("J","J ... J ... Jumping Toy! Only useful if designed for the species with safe landing height and no entrapment risk."),
("K","K? Kibble! Food can become enrichment through puzzles or training portions | count it within the daily diet."),
("L","L is Litter Box. Toilet resource, not toy | clean placement supports normal behavior."),
("M","M — Meal Bowl! Feeding tool; puzzle feeding may add enrichment, but mealtime nutrition remains the priority."),
("N","N ... N ... Nest! Bird or small-animal nesting area/material supports rest or reproduction | do not turn an occupied nest into play."),
("O","O? Outdoor Kennel! Containment/shelter area, not a complete play plan | exercise and interaction require more."),
("P","P is Puppy. Young dogs need short age-appropriate play, training, sleep and safe socialization | overtired puppies need rest too."),
("Q","Q — Quail! Ground bird enrichment can include cover, dust-bathing and foraging | handling is not the default game."),
("R","R ... R ... Rope Toy! Tug toy needs strong intact fibers and supervision | retire it when strands become swallowable."),
("S","S? Scratching Post! Cat enrichment supports scratching and stretching | stable structure lets the cat choose the behavior."),
("T","T is Treat. Small reward can support training or foraging | extra calories mean treats are limited, not an unlimited game."),
("U","U — Undercoat Brush! Grooming tool, not toy | use only on appropriate coat with gentle pressure."),
("V","V ... V ... Vet Kit! Health-care context stays out of play | veterinary tools are not pretend pet toys during actual care."),
("W","W? Wheel! Exercise device belongs only to species and size for which it is safe | correct diameter and solid surface matter."),
("X","X is X-ray Vet Image. Diagnostic image, never a play object | it helps a veterinarian see internal structures."),
("Y","Y — Yarn Ball! Loose yarn can be swallowed or entangle a cat | use safer designed toys and supervise string-like play."),
("Z","Z ... Z ... Zebra Finch! Small social bird benefits from flight space, perches, bathing and foraging | forced handling is not enrichment."),),
"style_blueprint":"Crisp diction. Open with safety inspection at 94 BPM in stop-check-go 4/4 with acoustic guitar, snaps, bass and marimba. Melody narrow. Round 1 repeatedly labels toy versus care/housing/medical. Chorus safe-sized-supervised. Round 2 uses pretend hand gestures only; Yarn/Rope hazards and X-ray/vet boundary stay explicit. Duck targets. End by slowing play into calm rest."},
"0074": {
"authorial_intent":"Make Small Animal Friends a needs-are-not-size song: fish, rabbits, dogs, mice, iguanas, quail and canaries may all be 'small' in a picture set yet require radically different space, diet, temperature, social and veterinary care.",
"lyric_identity":"A child compares one care dimension at a time and rejects the idea that small body means simple care.",
"image_motifs":("aquarium system","rabbit hay pile","mouse nesting material","iguana basking","canary flight cage"),
"semantic_arc":("space needs","diet needs","temperature/light/social needs","handling/health/transport"),
"forbidden_generic_language":("little home awake","small pet simple","one cage fits all","pet-picture clue"),
"rhyme_engine":"small-animal-needs-contrast-rhyme","chorus_rhyme_engine":"small-body-big-needs-hook","point_of_view":"a child comparing care complexity across species","chorus_function":"repeat small-body-big-needs","groove_meter":"measured 4/4 comparison pulse","round1_grammar":"hand-written contrast; equipment belongs only to matching species","round2_grammar":"need-dimension cue -> recall beat -> target -> compare gesture",
"intro_lines":("A mouse is small; an iguana may grow large; both need more than a box and a bowl.","Body size does not tell us how simple care will be."),
"hook_lines":("Small body, big needs—A-B-C!","Space, diet, light, health: check the species."),
"outro_lines":("No one cage, food bag, or toy solves every animal.","A to Z ends with care matched one species at a time."),
"round2_patterns":("Need check {letter} ... {object}! {action}","Compare {letter} ... {object}! {action}","Space, food, or health—{letter}? ... {object}! {action}","Species care {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Aquarium! Aquatic habitat is a water-quality system with volume, filtration, heat/light as species require | not decorative container."),
("B","B ... B ... Bunny! Rabbit needs large floor space, hay, water, litter options, chew items and social/veterinary care."),
("C","C? Collar! Fits some companion animals, not every small animal | correct fit and purpose matter."),
("D","D is Dog. Even a small dog needs exercise, training, social contact, veterinary care and species-appropriate diet."),
("E","E — Ear Cleaner! Veterinary-approved ear product is species/condition specific | adult guidance only."),
("F","F ... F ... Feather Toy! Cat enrichment item can be fun under supervision | dangerous if loose parts are swallowed."),
("G","G? Grooming Brush! Coat-specific tool | useful to a furry pet, irrelevant to fish and potentially wrong for other species."),
("H","H is Hutch. Traditional rabbit housing word | a hutch alone is usually too small to provide the exercise area a rabbit needs."),
("I","I — Iguana! Reptile with demanding enclosure size, heat, humidity, diet and UVB needs | 'small animal' label quickly becomes misleading."),
("J","J ... J ... Jingle Ball! Noise toy may suit some pets but stress others | enrichment requires choice."),
("K","K? Kibble! Formulated dry food applies to some mammals, not a universal diet for rabbits, birds, reptiles or fish."),
("L","L is Leash. Dog walking/control tool; some other species may use specialized harnesses, but leash is never universal small-animal gear."),
("M","M — Mouse! Secure ventilated enclosure needs bedding, hides, nesting material, food and enrichment | tiny body still needs complexity."),
("N","N ... N ... Nest! Nesting structure/material suits certain birds and rodents | not every pet needs or should receive the same material."),
("O","O? Octopus Toy! Novelty toy must be judged by material and species behavior | shape alone tells us nothing about suitability."),
("P","P is Puppy. Young dog needs structured care and rest | small age does not mean small responsibility."),
("Q","Q — Quail! Ground-dwelling bird needs horizontal floor area, cover, suitable substrate, social setup and species-appropriate nutrition."),
("R","R ... R ... Rabbit! Hay-centered diet and large movement space distinguish rabbit care from rodent stereotypes."),
("S","S? Seed Mix! Seeds can be part of some bird/rodent diets, but seed-only feeding is often nutritionally incomplete | species formulation matters."),
("T","T is Treat. Optional extra, not core nutrition | amount and ingredients depend on species."),
("U","U — Undercoat Brush! Designed for certain fur coats | do not apply the 'groom every pet' rule across scales, feathers or skin."),
("V","V ... V ... Vest Harness! Fit-sensitive equipment for selected species/individuals | supervision and comfort first."),
("W","W? Water Bowl! Common hydration tool for many mammals/birds | aquatic pets and some species require different water systems too."),
("X","X is X-ray Vet Image. Veterinary diagnostic evidence applies across many species | interpretation and restraint belong to professionals."),
("Y","Y — Yellow Canary! Small bird still needs flight room, balanced diet, perches, bathing, rest schedule and enrichment."),
("Z","Z ... Z ... Zip Carrier! Transport container must fit body, ventilation, temperature and stress needs | correct carrier differs by species."),),
"style_blueprint":"Crisp diction. Open with mouse-versus-iguana care contrast at 86 BPM in measured 4/4 with nylon guitar, soft bass, woodblock and marimba. Melody narrow. Round 1 compares space, diet, light, social and health dimensions. Chorus small-body-big-needs. Round 2 uses compare gestures only. Medical/grooming tools remain adult/pro context. Duck targets. End with five care dimensions named softly."},
"0075": {
"authorial_intent":"Turn Pet Shop Picture Song into a responsible decision sequence: learn the species, calculate long-term habitat/cost/time, prepare the home, choose ethical source/adoption route, then commit—supplies are not permission for impulse buying.",
"lyric_identity":"A child and adult walk past picture cards and supply shelves asking whether the household can meet lifelong needs before any animal comes home.",
"image_motifs":("care sheet beside aquarium","empty prepared habitat","carrier before travel","vet plan card","canary perch diagram"),
"semantic_arc":("learn species","prepare habitat/supplies","health and cost planning","commit or walk away responsibly"),
"forbidden_generic_language":("picture window opens","buy the pet","pet shop day fun","take one home"),
"rhyme_engine":"pet-decision-readiness-rhyme","chorus_rhyme_engine":"learn-prepare-commit-hook","point_of_view":"a child participating in an adult-led responsible pet decision","chorus_function":"repeat learn-prepare-commit","groove_meter":"thoughtful 4/4 shop-walk pulse","round1_grammar":"hand-written readiness criteria; supplies do not imply purchase","round2_grammar":"readiness cue -> recall beat -> target -> checklist/point gesture",
"intro_lines":("Before choosing an animal, read the care sheet and prepare the habitat at home.","A picture can start interest; responsibility decides what happens next."),
"hook_lines":("Learn, prepare, commit—A-B-C!","If the lifelong needs do not fit, walking away is good care too."),
"outro_lines":("List checked; no impulse purchase; every animal stays more important than the display.","A to Z ends with readiness, whether or not a pet comes home."),
"round2_patterns":("Readiness {letter} ... {object}! {action}","Plan {letter} ... {object}! {action}","Need or supply—{letter}? ... {object}! {action}","Decision check {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Aquarium! Prepare and cycle an appropriate aquatic system before fish arrive | empty setup first, animal later."),
("B","B ... B ... Bowl! Basic supply, but owning bowls proves nothing about readiness for a species."),
("C","C? Collar! Dog/cat identification or control item may be useful | correct fit comes after species and individual choice."),
("D","D is Dog. Long-term commitment includes training, exercise, health care, housing and time | individual needs vary."),
("E","E — Exercise Wheel! Species-specific enrichment, not a generic sign that any small pet belongs in the same cage."),
("F","F ... F ... Fish! Research adult size, schooling/territorial behavior, water parameters and lifespan before choosing a species."),
("G","G? Guinea Pig! Social herbivore with hay-centered diet, vitamin C needs and large floor space | plan compatible companionship and vet access."),
("H","H is Hamster. Nocturnal burrower needs deep bedding, space and correct wheel | tiny starter cages can be inadequate."),
("I","I — Iguana! Specialized reptile with large adult size and demanding heat/UVB/diet needs | a serious long-term commitment."),
("J","J ... J ... Jingle Ball! Optional toy comes after habitat, nutrition, health and safety planning."),
("K","K? Kibble! Food supply must be appropriate to species and life stage | price and storage belong in the ongoing budget."),
("L","L is Litter Box. Cat supply needs ongoing cleaning, litter cost and suitable placement | readiness includes routine chores."),
("M","M — Mouse! Research enclosure, social grouping, lifespan, enrichment and veterinary access before adoption."),
("N","N ... N ... Nest! Habitat feature may be needed for certain birds/rodents | never collect wild nests or assume every species needs one."),
("O","O? Outdoor Kennel! Shelter cannot replace family contact, exercise, climate safety or secure fencing."),
("P","P is Perch. Bird setup requires multiple safe perch sizes and flight space | one perch does not make a cage adequate."),
("Q","Q — Quail! Ground bird needs floor space, cover, social planning and appropriate housing | research local rules and welfare before keeping."),
("R","R ... R ... Rope Toy! Optional enrichment needs inspection and replacement | budget for wear."),
("S","S? Seed Mix! Package on a shelf is not automatically a complete diet | species-specific nutrition research comes first."),
("T","T is Turtle. Many turtles live for decades and need large, specialized aquatic/terrestrial setup with heat and UVB | plan adult needs, not hatchling size."),
("U","U — UV Lamp! For reptiles requiring UVB, choose correct UVB output, placement and replacement schedule | equipment is a recurring responsibility."),
("V","V ... V ... Vet Kit! Plan access to a species-experienced veterinarian and budget for preventive or emergency care."),
("W","W? Wheel! Correct exercise wheel is one component of a whole habitat | size and surface matter."),
("X","X is Xylophone Toy, our supply-picture clue | optional noise toy never outranks species welfare or calm choice."),
("Y","Y — Yellow Canary! Research lifespan, flight space, diet, light cycle and avian-vet access before bringing one home."),
("Z","Z ... Z ... Zip Carrier! Buy or prepare secure transport before the first trip | carrier is part of emergency and veterinary planning."),),
"style_blueprint":"Crisp diction. Open with care-sheet-before-animal at 84 BPM in thoughtful 4/4 with acoustic guitar, soft bass, brush and marimba. Melody narrow. Round 1 moves learn -> habitat -> budget/health -> optional supplies -> commit/walk-away. Chorus learn-prepare-commit. Round 2 uses checklist gestures only; never sings a purchase command. Duck target onsets. End with a calm no-impulse-decision cadence."}
}
