from __future__ import annotations

"""Authorial-identity deep polish for desert songs 0031-0035."""

GOLD_V5_31_35_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0031": {
        "authorial_intent": "Make the desert readable through traces: pawprints, hoof marks, tail lines, bird steps, wind-shaped sand and stationary plant or rock landmarks tell a story without claiming every target leaves a track.",
        "lyric_identity": "A child reads signs left on open ground; recurring language uses print, trace, line, mark, crossing, fade, still marker and wind-erased.",
        "image_motifs": ("hoofprints across hard sand", "roadrunner steps", "scorpion track line", "quartz marker", "wind erasing the trail"),
        "semantic_arc": ("first fresh track appears", "different bodies leave different signs", "plants and rocks become fixed landmarks", "wind softens every trace by evening"),
        "forbidden_generic_language": ("desert friends walk on with me", "follow every track", "fun in the sand", "everything leaves footprints"),
        "rhyme_engine": "desert-track-trace-linked-rhyme",
        "chorus_rhyme_engine": "print-line-fade-hook",
        "point_of_view": "a child reading desert signs from a safe distance and distinguishing moving traces from stationary landmarks",
        "chorus_function": "return to print-trace-landmark and the idea that wind eventually erases signs",
        "groove_meter": "dry 4/4 walking pulse with footprint rests",
        "round1_grammar": "hand-written trace observations; animal tracks, plant forms and rock markers are clearly different kinds of clues",
        "round2_grammar": "track or landmark cue -> recall beat -> target -> safe point/trace gesture",
        "intro_lines": ("Two small marks cross the sand, then disappear at a stone.", "The desert keeps clues—but the wind never keeps them forever."),
        "hook_lines": ("Print, trace, fade—A-B-C!", "Read the sand, then let the wind erase the trail."),
        "outro_lines": ("Even our own footsteps blur at the edges.", "A to Z returns to open sand and wind."),
        "interlude_lines": ("No new steps for one beat—what tracks and landmarks can we remember?",),
        "round2_patterns": ("Track-or-landmark {letter} ... {object}! {action}", "Desert clue {letter} ... {object}! {action}", "What sign, {letter}? ... {object}! {action}", "Trace or point, {letter} ... {object}! {action}"),
        "round2_overrides": (("N", "Desert clue N ... Nopales! Point to the flat cactus pads; no touching spines."), ("P", "Trace or point, P ... Prickly Pear! Point to the cactus pads and fruit from a safe distance.")),
        "round1_overrides": (
            ("A", "A — Agave! Thick pointed leaves form a rosette | a rooted landmark that stays while animal tracks pass by."),
            ("B", "B ... B ... Bighorn Sheep! Split hooves mark rocky or sandy ground | curved horns ride above a sure-footed body."),
            ("C", "C? Cactus! Spines guard thick water-storing tissues in many desert cacti | a still marker beside moving tracks."),
            ("D", "D is Desert Tortoise. Round shell, sturdy feet | low tracks lead toward shade or a burrow during safer hours."),
            ("E", "E — Eagle! Wide wings leave no footprints in the air | its moving shadow can cross the sand below."),
            ("F", "F ... F ... Fox! Light paws print a narrow trail | pointed ears and bushy tail move on ahead."),
            ("G", "G? Gila Monster! Heavy-bodied lizard with bead-like scales | short legs carry a patterned body across warm ground."),
            ("H", "H is Hawk. Strong wings and grasping feet | a sky clue above the track map rather than on it."),
            ("I", "I — Ibex! Sure hooves grip rock | a mountain-and-desert goat leaving hard-to-follow marks on stony slopes."),
            ("J", "J ... J ... Joshua Tree! Branching trunk and stiff pointed leaves | a landmark tall enough to guide the eye."),
            ("K", "K? Kestrel! Small falcon, quick wingbeats | hovering or perching above ground signs we can actually follow."),
            ("L", "L is Lizard. Tiny feet and a long tail can draw different lines | scales stay close to the desert surface."),
            ("M", "M — Mesquite! Deep-rooted woody plant with fine leaves | shade and branch shape make a fixed point in the open."),
            ("N", "N ... N ... Nopales! Flat green prickly-pear pads | plant food and cactus tissue, not footprints in the sand."),
            ("O", "O? Oryx! Long straight horns over a strong hoofed body | a broad desert trail crossing open ground."),
            ("P", "P is Prickly Pear. Flat pads, spines, colorful fruit | one cactus landmark holding still through the wind."),
            ("Q", "Q — Quartz! Hard mineral with a glassy sparkle | a bright stone marker that outlasts soft tracks."),
            ("R", "R ... R ... Roadrunner! Long legs make quick bird steps | the trail can zig, stop, then race on."),
            ("S", "S? Scorpion! Small legs and curved stinging tail | observe any desert scorpion only from a safe distance."),
            ("T", "T is Tortoise. Hard shell rides low above sturdy feet | slow marks cross the ground without any branch-climbing story."),
            ("U", "U — Umbrella Thorn! Spreading thorny crown makes shade | a rooted landmark where the track map changes texture."),
            ("V", "V ... V ... Viper! Venomous snake can leave a winding body trace | we learn that sign without approaching the animal."),
            ("W", "W? Wren! Tiny bird steps may gather near cover | then wings erase the need for a ground trail."),
            ("X", "X is Xerus. African ground squirrel of open dry country | quick feet write a small trail between shelter and food."),
            ("Y", "Y — Yellow Scorpion! Pale scorpion against warm sand | a safety clue we identify only from far away."),
            ("Z", "Z ... Z ... Ziziphus Shrub! Hardy thorny branches can carry small fruits | one last rooted landmark before the wind clears the page."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Dry, close adult lead at 90 BPM in walking 4/4 with muted acoustic guitar, hand drum, soft shaker, woodblock footstep and warm bass. Use short rests as empty patches between tracks. Round 1 must separate actual traces from fixed landmarks and sky clues; never claim Eagle or Cactus leaves a footprint. Chorus is print-trace-fade with percussion thinning on 'fade'. Round 2 uses trace-in-air and pointing gestures only; venomous animals remain distance-observation. Duck percussion on target onset. End by gradually removing the footprint pulse as if wind smooths the sand.",
    },
    "0032": {
        "authorial_intent": "Teach desert life through the daily negotiation between heat, shade and scarce water: bodies, burrows, ears, thick tissues and timing matter more than a cartoon cactus bounce.",
        "lyric_identity": "A child notices hot/cool contrast and water-saving adaptations; recurring language uses sun, shade, store, wait, burrow, evening, cool ground and one precious drop.",
        "image_motifs": ("cactus shadow", "fennec ears", "oasis blue", "kangaroo-rat night steps", "xerophyte holding through drought"),
        "semantic_arc": ("morning heat rises", "animals seek shade or safer timing", "oasis and plants show where water matters", "evening cool releases movement again"),
        "forbidden_generic_language": ("cactus bounce", "dunes and desert look with me", "desert is always hot", "everything stores water"),
        "rhyme_engine": "heat-shade-water-response-rhyme",
        "chorus_rhyme_engine": "sun-shade-drop-hook",
        "point_of_view": "a child comparing how desert plants, animals, rocks and water sources respond differently to heat and dryness",
        "chorus_function": "contrast sun, shade and water without making one adaptation fit every target",
        "groove_meter": "gentle 6/8 heat-shimmer sway with cool half-time pockets",
        "round1_grammar": "hand-written adaptation scenes; heat and water language is specific and never universalized",
        "round2_grammar": "sun/shade/water cue -> recall beat -> target -> safe cooling/shape gesture",
        "intro_lines": ("Sun climbs; the shadow of one cactus gets shorter.", "Desert life is not one trick—it is many ways to handle heat and little water."),
        "hook_lines": ("Sun, shade, one drop—A-B-C!", "Desert life makes every cool place count."),
        "outro_lines": ("The ground cools; small evening movement begins again.", "A to Z waits out the heat and keeps going."),
        "round2_patterns": ("Heat-or-shade {letter} ... {object}! {action}", "Desert strategy {letter} ... {object}! {action}", "Sun, shade, or water—{letter}? ... {object}! {action}", "Cool-down clue {letter} ... {object}! {action}"),
        "round2_overrides": (("N", "Desert strategy N ... Nopales! Point to the flat cactus pads; keep hands away from spines."),),
        "round1_overrides": (
            ("A", "A — Armadillo! Mammal with bony armor plates | low body searches dry ground when conditions are safer."),
            ("B", "B ... B ... Beetle! Six legs cross sand or stone | small bodies often use timing and shelter to avoid the fiercest heat."),
            ("C", "C? Cactus! Thick tissues can store water | spines replace broad leaves on many desert species."),
            ("D", "D is Desert Tortoise. Hard shell above, burrow below | underground shelter helps escape extreme heat."),
            ("E", "E — Euphorbia! Some desert euphorbias have thick succulent stems | another plant strategy for dry places."),
            ("F", "F ... F ... Fennec! Very large ears help release heat and catch faint sounds | small fox built for desert nights."),
            ("G", "G? Gecko! Small lizard grips rock or wall | shade and cooler hours matter more than standing in open noon."),
            ("H", "H is Hawk. Wings ride rising air above hot ground | a bird using the sky while shadows shrink below."),
            ("I", "I — Iguana! Scaled body and long tail | a lizard seeks the right place and time rather than one magical heat-proof trick."),
            ("J", "J ... J ... Jackrabbit! Huge ears can release body heat | long hind legs cross open ground quickly."),
            ("K", "K? Kangaroo Rat! Powerful hind legs, small night-active body | desert life often waits for cooler darkness."),
            ("L", "L is Limestone. Pale rock holds no water-saving behavior | it simply changes how heat, shade and ground feel around it."),
            ("M", "M — Meerkat! Small mammal stands to scan, then returns to group or shelter | open sun is only part of its day."),
            ("N", "N ... N ... Nopales! Flat prickly-pear pads are succulent cactus tissue | thick green surfaces hold moisture."),
            ("O", "O? Oasis! Water and shade gather in one dry landscape | green becomes possible where moisture reaches roots."),
            ("P", "P is Palm. Leaf crown lifts over a trunk or stems | oasis shade can spread beneath broad fronds."),
            ("Q", "Q — Quartz! Hard glassy mineral catches sun | a heat-and-light clue, not a living adaptation."),
            ("R", "R ... R ... Rattlesnake! Rattle at the tail, scaled body | venomous wildlife is observed only from a safe distance."),
            ("S", "S? Scorpion! Pincers, many walking legs, curved stinging tail | another animal we never touch or approach."),
            ("T", "T is Tortoise. Low shell and sturdy feet | slow travel makes shade and timing especially important."),
            ("U", "U — Urial! Wild sheep with sure hooves | shade, terrain and access to water shape life in dry country."),
            ("V", "V ... V ... Vulture! Broad wings soar efficiently | height and moving air can reduce the need for constant flapping."),
            ("W", "W? Wren! Small bird uses cover, shade and brief movement | not every desert strategy is about storing water inside a body."),
            ("X", "X is Xerophyte. A plant adapted to dry conditions | the word itself points to surviving where water is scarce."),
            ("Y", "Y — Yellow Scorpion! Pale desert scorpion | keep distance and let shade belong to wildlife too."),
            ("Z", "Z ... Z ... Ziziphus Shrub! Hardy thorny shrub can bear small fruits | woody shade holds on through dry conditions."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Warm adult lead in 6/8 at 84 BPM with nylon guitar, soft marimba, brushed shaker, low bass and sparse hand drum. Arrange heat as thin bright upper notes and shade as lower half-time pockets; never use harsh sizzling effects. Round 1 centers adaptation and contrast, correcting Armadillo as a mammal. Chorus is sun-shade-one-drop, memorable but not preachy. Round 2 uses shade/fan/shape gestures and a clear recall beat; Rattlesnake and Scorpion remain observe-only. Long words like Xerophyte sit on repeated notes. End with warmer low-register evening texture.",
    },
    "0033": {
        "authorial_intent": "Set hard desert geology beside brief living change: rock, dune and wadi may hold still for long stretches while flowers, birds and animals appear, move, bloom or vanish on much shorter clocks.",
        "lyric_identity": "A child compares still/moving, hard/soft, old/new and dry/bloom; recurring language uses stone, edge, grain, open, pass, wait and after rain.",
        "image_motifs": ("limestone face", "agave rosette against rock", "prickly-pear bloom", "wadi after rain", "nighthawk at dusk"),
        "semantic_arc": ("begin with stone and plant contrast", "animals cross the still landscape", "water and bloom interrupt dryness", "evening returns the scene to long quiet"),
        "forbidden_generic_language": ("desert plants are fun to see", "rock and bloom for me", "everything is dry", "shining bright"),
        "rhyme_engine": "stone-bloom-contrast-assonance",
        "chorus_rhyme_engine": "still-open-pass-hook",
        "point_of_view": "a quiet observer comparing geological stillness with short-lived movement, bloom and water",
        "chorus_function": "hold the contrast between what stays and what briefly changes",
        "groove_meter": "open 4/4 with long stone holds and short living pickups",
        "round1_grammar": "hand-written contrast images; geology lines can be sparse while living lines move more quickly",
        "round2_grammar": "still/moving cue -> recall beat -> target -> safe contrast gesture",
        "intro_lines": ("Stone keeps its shape while one flower opens beside it.", "The desert carries two clocks: very slow, and suddenly alive."),
        "hook_lines": ("Stone stays, petals open—A-B-C!", "Some desert moments last; some only pass."),
        "outro_lines": ("Dusk closes the bloom; limestone keeps the last light.", "A to Z leaves the slow desert waiting again."),
        "round2_patterns": ("Still-or-moving {letter} ... {object}! {action}", "Change clue {letter} ... {object}! {action}", "Rock or life, {letter}? ... {object}! {action}", "Desert contrast {letter} ... {object}! {action}"),
        "round2_overrides": (("P", "Desert contrast P ... Prickly Pear! Point to the flat pads and bloom; leave the spines untouched."),),
        "round1_overrides": (
            ("A", "A — Agave! Thick pointed leaves radiate from one center | living geometry set against hard ground."),
            ("B", "B ... B ... Beetle! Six legs cross a stone edge | tiny movement on a surface that hardly moves at all."),
            ("C", "C? Camel! Broad feet carry a large mammal over dry ground | one slow traveler crossing a much older landscape."),
            ("D", "D is Dune. Wind-built hill of sand | shape changes grain by grain even when the desert looks still."),
            ("E", "E — Eagle! Broad wings pass over rock | a moving shadow skims a surface that stays."),
            ("F", "F ... F ... Fox! Quiet paws move through scrub | soft fur against thorn, stone, and dust."),
            ("G", "G? Gila Monster! Bead-like scales pattern a heavy lizard body | living texture beside mineral texture."),
            ("H", "H is Horned Lizard. Broad flat body and pointed scales | its outline almost repeats the rough ground around it."),
            ("I", "I — Iguana! Long tail, back spines | a moving reptile shape cutting across still rock."),
            ("J", "J ... J ... Jackrabbit! Long ears rise, hind legs launch | sudden speed over a patient landscape."),
            ("K", "K? Kestrel! Small falcon holds or darts in the air | one quick shape above unmoving stone."),
            ("L", "L is Limestone. Pale sedimentary rock | layer on layer, a slow record compared with one day's animal tracks."),
            ("M", "M — Mesquite! Woody branches and fine leaves | living shade rooted beside hard mineral ground."),
            ("N", "N ... N ... Nighthawk! Dusk-flying bird catches insects in the air | evening movement begins as heat releases."),
            ("O", "O? Oasis! Water interrupts dry color | reflection and plant growth gather where the landscape changes."),
            ("P", "P is Prickly Pear. Flat pads can hold flowers and fruit | soft bloom rising from a spine-guarded cactus."),
            ("Q", "Q — Quail! Small ground bird crosses gravel and scrub | quick feet between stones."),
            ("R", "R ... R ... Rattlesnake! Scaled body, tail rattle | venomous wildlife remains a far-away observation."),
            ("S", "S? Scorpion! Pincers and curved stinging tail | small life beside stone, always viewed from distance."),
            ("T", "T is Tumbleweed. A dried plant can break free and roll with wind | living tissue becomes a moving desert shape after drying."),
            ("U", "U — Urial! Wild sheep moves over dry slopes | hooves crossing rock that outlasts every track."),
            ("V", "V ... V ... Vulture! Large wings circle above open country | slow-looking flight over slower stone."),
            ("W", "W? Wadi! Dry channel can suddenly carry water after rain | one of the desert's sharpest still-to-moving changes."),
            ("X", "X is Xerophyte. Dry-adapted plant | living form shaped by scarcity beside rock that needs no water at all."),
            ("Y", "Y — Yucca! Stiff leaves rise from a living base | pale flowers may lift above the sharp green form."),
            ("Z", "Z ... Z ... Zebra Finch! Small finch, short beak, quick bird movement | a final living flicker over the long-still ground."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Intimate adult lead at 80 BPM, spacious 4/4 with nylon guitar, low cello pizzicato, sparse marimba, brushed drum and occasional airy flute. Stone targets get longer held notes and less percussion; animal/bird targets get brief rhythmic pickups; water/bloom moments widen harmony. Round 1 should feel poetic but factual. Tumbleweed must be described as a dried plant that can detach and roll, not a generic growing vine. Chorus contrasts stone-stays with petals-open. Round 2 uses still/move gestures and one recall beat. Dangerous wildlife remains distant. End on a long low guitar/cello decay.",
    },
    "0034": {
        "authorial_intent": "Turn a dune walk into spatial navigation: crest, slope, lee side, horizon, shadow and wind direction make the alphabet feel like crossing landforms rather than repeating animal facts.",
        "lyric_identity": "A child climbs and descends dunes with map-like language; recurring words are crest, slope, lee, horizon, upwind, downwind, shadow and next rise.",
        "image_motifs": ("dune crest line", "wind ripples", "long fennec shadow", "Joshua tree horizon mark", "roadrunner crossing a slope"),
        "semantic_arc": ("approach first dune", "cross alternating crests and sheltered sides", "use plants/animals as orientation marks", "reach final horizon as wind redraws slopes"),
        "forbidden_generic_language": ("across the dunes come look with me", "one dune two dunes", "explorer eyes", "up and down all day"),
        "rhyme_engine": "dune-crest-slope-spatial-rhyme",
        "chorus_rhyme_engine": "crest-slope-horizon-hook",
        "point_of_view": "a child navigating desert topography by shape, shadow and distant landmarks",
        "chorus_function": "reorient the listener to crest-slope-horizon before the next route section",
        "groove_meter": "walking 4/4 with rising crest phrases and descending lee-side phrases",
        "round1_grammar": "hand-written spatial route; object facts serve navigation and habitat rather than a generic explorer template",
        "round2_grammar": "route-position cue -> recall beat -> target -> up/down/point gesture",
        "intro_lines": ("The first dune hides everything beyond its crest.", "Climb the shape, read the horizon, then choose the next gentle route."),
        "hook_lines": ("Crest, slope, horizon—A-B-C!", "Wind redraws the route, but landmarks help us see."),
        "outro_lines": ("Behind us, the first crest already looks different.", "A to Z reaches the horizon without owning the sand."),
        "interlude_lines": ("Stop below the crest for one beat—what route markers can we call back?",),
        "round2_patterns": ("Route mark {letter} ... {object}! {action}", "Crest-or-slope {letter} ... {object}! {action}", "Where on the route, {letter}? ... {object}! {action}", "Horizon clue {letter} ... {object}! {action}"),
        "round2_overrides": (("P", "Horizon clue P ... Prickly Pear! Point to the cactus shape; do not reach toward the spines."),),
        "round1_overrides": (
            ("A", "A — Armadillo! Low armored mammal crosses firm ground | a moving marker before the first sand rise."),
            ("B", "B ... B ... Beetle! Tiny legs trace a short path across rippled sand | scale changes when we look down from a dune."),
            ("C", "C? Camel! Broad feet travel over sand | tall body becomes a clear shape against the horizon."),
            ("D", "D is Dune. Wind-shaped ridge of sand | crest above, slope below, and a sheltered side out of direct wind."),
            ("E", "E — Euphorbia! Dry-adapted plant shape breaks the open slope | a rooted route marker that does not move with us."),
            ("F", "F ... F ... Fennec! Huge ears, small fox body | long shadow stretches when the sun sits low."),
            ("G", "G? Gila Monster! Heavy patterned lizard stays close to ground | a low clue we never approach."),
            ("H", "H is Horned Lizard. Flat body and pointed scales | shape blends with rough ground below the crest."),
            ("I", "I — Ibex! Sure hooves belong on rocky slopes | a reminder that desert routes are not only loose sand."),
            ("J", "J ... J ... Joshua Tree! Branching silhouette stands high enough to guide the horizon | one fixed point beyond shifting ripples."),
            ("K", "K? Kestrel! Small falcon holds above the slope | sky position changes while the dune stays beneath."),
            ("L", "L is Lizard. Long body, scales, tail | quick low motion crosses from sun into a small shadow."),
            ("M", "M — Meerkat! Upright lookout shape rises above low scrub | one small vertical marker in wide space."),
            ("N", "N ... N ... Nighthawk! Dusk bird enters when the horizon cools | route time changes as well as route shape."),
            ("O", "O? Oryx! Long horns and strong hoofed body | a large distant silhouette beyond the next rise."),
            ("P", "P is Prickly Pear. Flat cactus pads make a rooted landmark | easy to see, never a reason to leave the safe route."),
            ("Q", "Q — Quail! Small ground bird moves along low cover | a quick crossing on the lee side."),
            ("R", "R ... R ... Roadrunner! Long legs race across flatter ground | fast motion between two slow dune shapes."),
            ("S", "S? Sand! Millions of tiny grains build the slope | wind rearranges the route one ripple at a time."),
            ("T", "T is Tumbleweed. Dried plant can roll with wind after breaking free | a moving landmark that refuses to stay a landmark."),
            ("U", "U — Urial! Wild sheep uses firm dry slopes and rocky country | sure hooves on terrain beyond loose sand."),
            ("V", "V ... V ... Viper! Venomous snake may use warm ground and cover | any sighting means more distance, not closer exploration."),
            ("W", "W? Wren! Small bird uses scrub and low shelter | a tiny route clue where vegetation gathers."),
            ("X", "X is Xerophyte. Dry-adapted plant holds its place through heat | one botanical marker on the open route."),
            ("Y", "Y — Yellow Scorpion! Pale scorpion on desert ground | safety turns this clue into a stop-and-back-away marker."),
            ("Z", "Z ... Z ... Ziziphus Shrub! Thorny hardy shrub with small fruits | last fixed shape before the final horizon."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Clear adult lead at 88 BPM in walking 4/4 with acoustic guitar, muted tom, shaker, warm bass and sparse whistle-like flute. Melodic contour follows landform: rise toward crest, descend on slope, hold long tones at horizon. Round 1 is spatial navigation, not generic animal definitions. Chorus clearly articulates crest-slope-horizon. Round 2 uses up/down/point gestures and a real recall beat. Venomous targets turn into stop-and-distance cues. Keep Dune, Sand and Xerophyte speech-clear. End with a sustained horizon chord while percussion fades like wind-smoothed footprints.",
    },
    "0035": {
        "authorial_intent": "Make an oasis meaningful as a concentration of water, shade and visitors within a dry landscape: approach through heat, arrive at blue/green relief, notice who uses nearby habitat, then follow the water story into a wadi.",
        "lyric_identity": "A child approaches and rests near water; recurring language uses dry road, blue patch, shade, drink, bank, visit, leave space and water-after-rain.",
        "image_motifs": ("first blue glimpse", "palm shade", "animal tracks near water but not crowded", "wadi channel", "thorn shrub at dry edge"),
        "semantic_arc": ("dry approach", "water and shade reveal the oasis", "wildlife visits surrounding habitat", "water story expands into wadi and dry edge"),
        "forbidden_generic_language": ("oasis friends sing with me", "desert wildlife party", "everyone comes to drink", "blue water fun"),
        "rhyme_engine": "oasis-arrival-gather-release-rhyme",
        "chorus_rhyme_engine": "dry-blue-shade-hook",
        "point_of_view": "a child resting at a respectful oasis viewpoint and noticing how water changes nearby habitat",
        "chorus_function": "mark the transition from dry approach to water-and-shade center",
        "groove_meter": "gentle 3/4 arrival sway with cooler chorus voicing",
        "round1_grammar": "hand-written oasis-centered scenes; animals may live nearby or visit, but are never forced into one drinking-party narrative",
        "round2_grammar": "dry/shade/water cue -> recall beat -> target -> safe point/cup/shape gesture",
        "intro_lines": ("At first it is only a blue line under palms.", "Then shade, water, tracks, and green tell us why this place matters."),
        "hook_lines": ("Dry road, blue shade—A-B-C!", "Water changes what can gather nearby."),
        "outro_lines": ("Beyond the palms, the ground opens dry again.", "A to Z carries the water story into the wadi."),
        "round2_patterns": ("Oasis-map clue {letter} ... {object}! {action}", "Shade-or-open {letter} ... {object}! {action}", "Water or dry edge—{letter}? ... {object}! {action}", "Next oasis clue {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Armadillo! Armored mammal travels dry ground nearby | not every oasis visitor stands at the water's edge."),
            ("B", "B ... B ... Bighorn Sheep! Curved horns and split hooves | rocky dry country can lead animals toward scattered water sources."),
            ("C", "C? Camel! Broad feet and large body cross dry land | a classic traveler through landscapes where water is spaced far apart."),
            ("D", "D is Dune. Wind-shaped sand still surrounds the blue-green center | oasis does not erase the desert around it."),
            ("E", "E — Eagle! High wings cross over palms and open ground | a sky visitor above the water story."),
            ("F", "F ... F ... Fox! Quiet paws move along dry cover | shade and water influence where life can pass."),
            ("G", "G? Gecko! Small lizard holds to rock, wall, or trunk | a close-up animal in the cooler edge habitat."),
            ("H", "H is Hawk. Keen eyes scan from above | water, trees, and open ground make different hunting spaces below."),
            ("I", "I — Ibex! Sure hooves handle rocky slopes | access to water matters even when the animal is far from the pool."),
            ("J", "J ... J ... Joshua Tree! Stiff leaves on branching trunks | a dry-land landmark beyond the greener oasis core."),
            ("K", "K? Kestrel! Small falcon perches or hovers | one light sky clue above palms and scrub."),
            ("L", "L is Limestone. Pale rock holds heat beside shade | hard ground frames the softer water reflection."),
            ("M", "M — Meerkat! Small social mammal scans open country | dry habitat continues beyond the palm shade."),
            ("N", "N ... N ... Nighthawk! Dusk flight begins as the oasis edge cools | insects and evening air change the scene."),
            ("O", "O? Oasis! Water and vegetation gather inside dry country | the central idea of the whole route."),
            ("P", "P is Palm. Crown of broad leaves throws shade | green reflection trembles where fronds meet water."),
            ("Q", "Q — Quail! Small ground bird uses cover near the greener edge | quick feet stay low beneath taller shapes."),
            ("R", "R ... R ... Rattlesnake! Tail rattle and scaled body | venomous wildlife keeps its space, and we keep ours."),
            ("S", "S? Sand! Tiny grains continue right to the oasis edge | dry texture beside cool reflection."),
            ("T", "T is Tortoise. Hard shell and sturdy feet | slow desert life may use shade and suitable water without becoming an oasis-only animal."),
            ("U", "U — Umbrella Thorn! Spreading thorny crown makes a patch of shade | dry-edge green beyond the palms."),
            ("V", "V ... V ... Vulture! Broad wings soar over open country | a distant scavenger linked to the wider ecosystem, not the water alone."),
            ("W", "W? Wadi! Usually dry channel can carry water after rain | the oasis story widens into water that appears and disappears."),
            ("X", "X is Xerus. African ground squirrel of dry open country | quick movement at the drier edge of our oasis map."),
            ("Y", "Y — Yellow Scorpion! Pale desert scorpion | one more reason to look carefully and never reach into rocks or shade holes."),
            ("Z", "Z ... Z ... Ziziphus Shrub! Thorny hardy shrub can carry small fruits | green persists where roots find enough moisture."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Warm calm lead at 82 BPM in 3/4 with nylon guitar, soft upright bass, brushed shaker, marimba droplets and airy flute. Verses begin dry and sparse; chorus cools harmonically and adds gentle sustained tones to mark water/shade. Round 1 keeps the oasis as ecological center without claiming every animal drinks there. Use arrival/departure imagery and soft internal rhyme. Round 2 uses shade/water/dry-edge cues with one recall beat. Rattlesnake and scorpion remain distance-only. End by removing the watery instruments and returning to dry acoustic texture beyond the palms.",
    },
}
