from __future__ import annotations

"""V5 authorial-identity deep polish for classroom songs 0101-0105."""

from abc_creative_gold_v5_101_200_support import craft_from, make_spec, register_craft

FACTS = {
    "Art Paper": "Drawing/craft paper; thickness and surface vary by medium.",
    "Backpack": "School bag; two fitted shoulder straps help spread a sensible load.",
    "Crayon": "Colored wax-based drawing stick makes broad marks without liquid ink; classroom versions should be age-appropriate and non-toxic.",
    "Dictionary": "Word reference gives spelling, meaning, pronunciation, and usage.",
    "Eraser": "Rubber-like material lifts many graphite marks from paper; it does not erase every kind of ink or damage-free mark.",
    "Folder": "Folded cover keeps loose papers together and separates subjects or projects.",
    "Globe": "Spherical Earth model reduces many shape distortions of flat maps, while remaining tiny-scale.",
    "Highlighter": "Translucent marker emphasizes selected text while leaving words visible; highlighting everything defeats its purpose.",
    "Ink": "Colored liquid or paste carries pigment or dye to a surface and can stain, so lids and careful handling matter.",
    "Jigsaw Map": "Map puzzle breaks a geographic picture into interlocking pieces; matching shape and location rebuilds the whole.",
    "Knowledge Card": "Project card holds a fact, clue, or concept; it is not one standardized product.",
    "Lunchbox": "Food container; safe temperature control depends on contents and storage.",
    "Map": "Place model uses symbols, direction, scale, and selected features.",
    "Number Chart": "Ordered grid or line displays numerals so learners can notice sequence, place, and numerical patterns.",
    "Organizer": "Compartments or labeled sections keep supplies separated so items can be found and returned efficiently.",
    "Pencil": "Writing tool usually contains a graphite-and-clay core, not metallic lead; pressure changes line darkness.",
    "Question Card": "Prompt asks for recall, explanation, comparison, or discussion; it is not the answer.",
    "Ruler": "Straight tool marks units such as centimeters or inches; measure from zero.",
    "Scissors": "Two pivoting blades cut material by shearing; preschool use requires suitable blunt-tip tools and adult supervision.",
    "Tape": "Flexible strip carries adhesive on one or both sides to join or hold materials temporarily or permanently.",
    "USB Drive": "Flash-memory device stores files; supervised computer use prevents loss or mishandling.",
    "Violin Case": "Protective container supports and shields a violin and bow during storage or transport; the case itself makes no musical pitch.",
    "Whiteboard": "Smooth reusable writing surface accepts dry-erase markers and can be wiped for the next idea.",
    "Xylophone": "Tuned-bar percussion instrument; shorter matching bars generally sound higher.",
    "Yellow Pencil": "A pencil with a yellow-painted body still writes through its graphite core; body color does not change the writing mechanism.",
    "Zero Card": "Card shows 0: no counted items in some contexts and a place-holding digit in others.",
    "Alphabet Chart": "Chart displays letter forms and sequence; it can support recognition without replacing sound, writing, or word practice.",
    "Book": "Pages can carry stories, facts, images, or instructions; contents tell the purpose.",
    "Envelope": "Folded paper container protects and carries a letter or small flat item; flap closes the opening.",
    "Flashcard": "Study card pairs a prompt with an answer; recall before peeking.",
    "Glue": "Adhesive joins materials after it spreads and sets; classroom glue should be non-toxic and used only as directed, never tasted.",
    "Index Card": "Small stiff card gives limited writing space for one note, label, example, or study prompt.",
    "Journal": "Record collects thoughts, observations, or events over time.",
    "Keyboard": "Here it is a computer input device for letters, numbers, and commands?not a musical keyboard.",
    "Library Book": "Shared book is borrowed for a period and returned so another reader can use the same copy.",
    "Marker": "Fiber- or felt-tip writing tool feeds ink to a broad or fine point; cap care helps keep many markers from drying out.",
    "Origami Paper": "Light square folding paper; classic origami builds forms mainly with creases.",
    "Paintbrush": "Bristles or synthetic fibers carry paint and release it with strokes; brush shape changes the kind of mark.",
    "Reading Book": "Book selected for reading practice or enjoyment; text difficulty and purpose matter more than the cover.",
    "Uniform": "Standardized clothing identifies a school or group; it is part of school routine, not a learning tool by itself.",
    "Vocabulary Card": "Card links a word to meaning, example, picture, or pronunciation.",
    "X-axis Graph": "Horizontal Cartesian axis usually carries x-values paired with vertical y-values.",
    "Calculator": "Electronic or mechanical tool performs entered calculations; correct keys still depend on choosing the right mathematical operation.",
    "Desk": "Work surface supports books, writing, and materials; clear space helps separate active work from stored supplies.",
    "Hole Punch": "Lever tool cuts small holes through paper; moving metal parts can pinch, so preschool handling belongs with an adult or teacher.",
    "Notebook": "Bound pages keep related notes or drawings in order and make earlier work easy to revisit.",
    "Quiz Card": "Prompt checks recall or understanding; a miss shows what to practice next.",
    "Textbook": "Instructional book organizes a subject into explanations, examples, images, and often practice material.",
    "Workbook": "Practice book leaves spaces for learners to write, draw, solve, or respond directly on the page.",
    "Yarn": "Long twisted strand of fibers can be woven, knitted, or used in supervised crafts; loose lengths can tangle around fingers or objects.",
    "Zipper Pouch": "Small fabric or plastic pouch closes with interlocking zipper teeth and keeps loose supplies together.",
    "Stapler": "Tool bends metal staples through stacked sheets; staple points and the closing mechanism require adult or teacher management for preschoolers.",
}

ACTIONS = {
    "Scissors": "Point only; trace two blade shapes in the air while the real tool stays with an adult.",
    "Stapler": "Point only; show a paper stack with flat palms while the real stapler stays with an adult.",
    "Hole Punch": "Point only; make one small circle in the air, not a squeezing gesture on a real tool.",
    "Glue": "Point to the glue picture; mime placing a tiny dot with an empty fingertip.",
    "Ink": "Point to the closed ink picture; do not mime pouring.",
    "USB Drive": "Point to the USB picture; mime plugging into an imaginary port only.",
    "Yarn": "Trace one loose curve in the air; keep real yarn off the body.",
    "Xylophone": "Tap two fingers gently on the opposite palm like two bars; no hard striking.",
}

OBJECT_CRAFT_101_105 = craft_from(FACTS, ACTIONS)

OBJECTS = {
    "0101": ("Art Paper","Backpack","Crayon","Dictionary","Eraser","Folder","Globe","Highlighter","Ink","Jigsaw Map","Knowledge Card","Lunchbox","Map","Number Chart","Organizer","Pencil","Question Card","Ruler","Scissors","Tape","USB Drive","Violin Case","Whiteboard","Xylophone","Yellow Pencil","Zero Card"),
    "0102": ("Alphabet Chart","Book","Crayon","Dictionary","Envelope","Flashcard","Glue","Highlighter","Index Card","Journal","Keyboard","Library Book","Marker","Number Chart","Origami Paper","Paintbrush","Question Card","Reading Book","Scissors","Tape","Uniform","Vocabulary Card","Whiteboard","X-axis Graph","Yellow Pencil","Zero Card"),
    "0103": ("Art Paper","Book","Calculator","Desk","Eraser","Folder","Globe","Hole Punch","Index Card","Journal","Knowledge Card","Library Book","Map","Notebook","Origami Paper","Pencil","Quiz Card","Reading Book","Scissors","Textbook","Uniform","Vocabulary Card","Workbook","X-axis Graph","Yarn","Zipper Pouch"),
    "0104": ("Alphabet Chart","Book","Calculator","Desk","Envelope","Flashcard","Globe","Hole Punch","Ink","Jigsaw Map","Knowledge Card","Lunchbox","Marker","Notebook","Organizer","Pencil","Quiz Card","Ruler","Stapler","Textbook","Uniform","Violin Case","Whiteboard","X-axis Graph","Yellow Pencil","Zero Card"),
    "0105": ("Alphabet Chart","Backpack","Calculator","Desk","Eraser","Folder","Glue","Highlighter","Ink","Jigsaw Map","Knowledge Card","Library Book","Marker","Notebook","Origami Paper","Paintbrush","Quiz Card","Reading Book","Stapler","Tape","USB Drive","Vocabulary Card","Workbook","Xylophone","Yellow Pencil","Zero Card"),
}

register_craft(OBJECTS, FACTS, ACTIONS)

GOLD_V5_101_105_SPEC_PATCHES = {
"0101": make_spec(objects=OBJECTS["0101"], facts=FACTS, actions=ACTIONS,
 authorial_intent="Turn Classroom Picture Parade into an organization walk: supplies move from carry-in to work surface, reference area, storage, and return-home positions, so objects have jobs instead of merely marching past.",
 lyric_identity="A child follows where classroom objects belong and why; organization becomes the narrative spine, with tools that can cut, stain, or store data given explicit boundaries.",
 image_motifs=("backpack arrival","paper-and-pencil work zone","globe and map reference shelf","organizer compartments","zip-up return routine"),
 semantic_arc=("arrive and unpack","work and reference","organize and retrieve","return and reset"),
 forbidden_generic_language=("classroom parade","school things march","put it in the parade","everything is a learning tool"),
 rhyme_engine="classroom-place-purpose-chain", chorus_rhyme_engine="place-use-return-hook",
 point_of_view="a child mapping where classroom supplies belong", chorus_function="reset place-use-return", groove_meter="steady 4/4 tidy-room walk",
 round1_grammar="object -> real function -> storage/use distinction", round2_grammar="neutral recall -> exact target -> safe point/shape action",
 intro_lines=("Backpack by the hook, paper at the work table, globe on the reference shelf.","A classroom gets easier to use when every object has a place and a purpose."),
 hook_lines=("Place, use, return—A-B-C!","Find the tool, then put the idea back where it belongs."),
 outro_lines=("Whiteboard cleared, pencil stored, backpack ready for the door.","A to Z leaves the classroom organized for the next learner."),
 style_blueprint="Crisp preschool classroom-pop at 88 BPM, restrained piano, marimba, soft bass, woodblock, dry lead. Begin sparse at the backpack hook, widen at map/globe reference, tighten rhythm around organizers, then resolve into a quiet reset. Protect every target onset. No school-bell masking, no chant wall, no tool sound effects over Scissors or Stapler.", signature_color="place-purpose" , cue_prefix="Place check"),
"0102": make_spec(objects=OBJECTS["0102"], facts=FACTS, actions=ACTIONS,
 authorial_intent="Make Learning Tools Tap about cognitive function: look up, record, retrieve, calculate, draw, revise, and communicate are different learning operations, and non-tools such as Uniform are labeled honestly.",
 lyric_identity="Each object answers the question 'what kind of thinking can this support?' rather than being praised just for appearing in school.",
 image_motifs=("dictionary lookup","flashcard recall gap","journal record","whiteboard revision","x-axis coordinate pair"),
 semantic_arc=("find information","record information","practice and retrieve","represent and revise"),
 forbidden_generic_language=("tap the tools","our learning tool today","every object teaches","tool bounce"),
 rhyme_engine="learning-operation-linked-rhyme", chorus_rhyme_engine="find-record-recall-hook",
 point_of_view="a child comparing learning operations", chorus_function="reset find-record-recall-revise", groove_meter="86 BPM tap-rest thinking pulse",
 round1_grammar="tool -> learning operation -> limitation", round2_grammar="operation cue -> recall gap -> target -> low-risk gesture",
 intro_lines=("A dictionary helps us look up; a journal helps us record; a flashcard asks us to remember before we peek.","Learning tools do different jobs for the mind."),
 hook_lines=("Find, record, recall—A-B-C!","Choose the tool that fits the thinking job."),
 outro_lines=("The answer side stays hidden for one last recall beat.","A to Z ends with the learner choosing the tool, not the tool choosing the learner."),
 style_blueprint="Clear educational pop at 86 BPM with piano, muted marimba, pizzicato, soft kick and intentional one-beat retrieval gaps. Differentiate lookup, writing, recall and graphing with tiny motifs; no repeated tap on every target. Keep X-axis Graph spoken cleanly. No dense claps, no computer beeps over words.", signature_color="thinking-operation", cue_prefix="Operation check"),
"0103": make_spec(objects=OBJECTS["0103"], facts=FACTS, actions=ACTIONS,
 authorial_intent="Turn School Day Steps into a real day arc: arrive, settle, learn, make, read, practice, pack, and leave; objects appear where they make temporal sense instead of on one endless walk.",
 lyric_identity="A child moves through a school day with changing energy and task type; the same room feels different during reading, making, practice, and pack-up.",
 image_motifs=("desk at morning settle","library-book quiet block","art-paper making block","workbook practice","zipper-pouch pack-up"),
 semantic_arc=("arrival and setup","learning blocks","quiet/practice blocks","pack-up and departure"),
 forbidden_generic_language=("school-day walk","step through school","meets during our walk","all day is one activity"),
 rhyme_engine="schoolday-timecourse-rhyme", chorus_rhyme_engine="arrive-learn-pack-hook",
 point_of_view="a child narrating one school day in time", chorus_function="mark transitions in the day", groove_meter="92 BPM morning-to-afternoon contour",
 round1_grammar="object fact anchored to plausible day phase", round2_grammar="time-neutral recall so no target gets a false schedule claim",
 intro_lines=("Desk first, library later, art after that, then the zipper pouch closes near the end.","A school day changes jobs as the hours move."),
 hook_lines=("Arrive, learn, pack—A-B-C!","Different parts of the day ask for different tools."),
 outro_lines=("Workbook closed, yarn put away, zipper pouch zipped.","A to Z walks out with the day complete, not with every task still running."),
 style_blueprint="Narrative classroom-folk pop at 90 BPM: morning piano and soft shaker, lighter guitar in reading, tactile marimba in making, thinner texture in practice, descending cadence at pack-up. Never imply unsafe use of Hole Punch or Scissors. Protect target nouns with dry vocals and no transition effects on onset.", signature_color="day-arc", cue_prefix="Day recall"),
"0104": make_spec(objects=OBJECTS["0104"], facts=FACTS, actions=ACTIONS,
 authorial_intent="Make Learn and Look A-Z an evidence habit: observe a clue, ask a question, consult a source or tool, and check the answer; cards and charts are prompts, not magic containers of knowledge.",
 lyric_identity="The child practices uncertainty and verification—seeing starts an idea, but books, measurements, maps, and questions help test it.",
 image_motifs=("alphabet chart observation","question card pause","ruler check","map versus globe comparison","zero on number card"),
 semantic_arc=("notice","ask","check with source/tool","revise or confirm"),
 forbidden_generic_language=("learn and look","our learning clue","look means know","card gives the truth"),
 rhyme_engine="observe-question-check-rhyme", chorus_rhyme_engine="notice-ask-check-hook",
 point_of_view="a curious child verifying classroom claims", chorus_function="repeat notice-ask-check", groove_meter="84 BPM spacious inquiry pulse",
 round1_grammar="concrete object fact plus what it can and cannot establish", round2_grammar="question-safe recall -> target -> verification gesture",
 intro_lines=("A picture can start a guess; a ruler, map, dictionary, or question can help us check it.","Looking is the beginning of learning, not the end."),
 hook_lines=("Notice, ask, check—A-B-C!","A good answer can survive another look."),
 outro_lines=("The last Zero Card is checked, not merely guessed.","A to Z leaves one habit behind: ask what evidence supports the answer."),
 style_blueprint="Curious chamber-pop for preschool at 84 BPM with warm piano, soft guitar harmonics, marimba and sparse brush. Use short silence after question-shaped lines, then a settled confirmation cadence. Keep quiz/question language calm, never test-anxiety music. Stapler/Hole Punch remain point-only. Target diction stays dry and centered.", signature_color="inquiry-check", cue_prefix="Evidence check"),
"0105": make_spec(objects=OBJECTS["0105"], facts=FACTS, actions=ACTIONS,
 authorial_intent="Make Classroom Action ABC about activity cycles: choose materials, do an age-appropriate task, stop, clean, store, and reset; action never means grabbing every tool.",
 lyric_identity="A child learns that making and studying include setup and cleanup, while powered, staining, pinching, sharp, or digital objects get specific safe roles.",
 image_motifs=("materials chosen before activity","small glue dot","paintbrush rinse","stapler teacher station","clean workbook-and-pencil reset"),
 semantic_arc=("choose","work","pause/check","clean and store"),
 forbidden_generic_language=("classroom action","brings to today's activity","do everything yourself","grab the tool"),
 rhyme_engine="activity-reset-cadence-rhyme", chorus_rhyme_engine="choose-do-clean-hook",
 point_of_view="a child participating in supervised classroom activities", chorus_function="reset choose-do-clean", groove_meter="94 BPM stop-start-clean pulse",
 round1_grammar="material/tool function plus safe activity boundary", round2_grammar="retrieval -> exact target -> empty-hand or point gesture",
 intro_lines=("Choose what the task needs, use only the safe materials, then clean and return them.","Classroom action includes stopping and resetting."),
 hook_lines=("Choose, do, clean—A-B-C!","The activity is not finished until the tools are safe and stored."),
 outro_lines=("Glue capped, marker capped, workbook stacked, teacher tools untouched.","A to Z ends with the table ready for what comes next."),
 style_blueprint="Stop-start classroom groove at 92 BPM with piano, ukulele, soft bass, muted woodblock and marimba. Setup is light, task sections slightly fuller, every cleanup chorus strips back. No stapler clicks, scissor snips, USB beeps or ink splashes over target words. Clear lead, compact phrases, final quiet table-reset cadence.", signature_color="activity-reset", cue_prefix="Activity recall"),
}
