from __future__ import annotations

"""Authorial-identity deep polish for bug songs 0061-0065."""

GOLD_V5_61_65_SPEC_PATCHES: dict[str, dict[str, object]] = {
"0061": {
"authorial_intent":"Make Tiny Bug Bounce a mechanics-at-small-scale song: piercing, chewing, jumping, clinging, glowing, rolling and flying are distinct body solutions, with dangerous species kept observe-only.",
"lyric_identity":"A child watches tiny movement and feeding mechanics instead of making every bug bounce; body parts drive the verbs.",
"image_motifs":("aphid stylet at leaf","beetle elytra opening","dung beetle rolling","firefly lantern abdomen","stick insect still on twig"),
"semantic_arc":("feeding mouthparts","walking rolling jumping","metamorphosis and light","camouflage wings and safety"),
"forbidden_generic_language":("tiny bug bounce","little wings and feet","all bugs hop","bug friends"),
"rhyme_engine":"tiny-body-mechanics-rhyme","chorus_rhyme_engine":"cling-crawl-fly-hook","point_of_view":"a child comparing tiny body mechanics from a safe close view","chorus_function":"reset cling-crawl-fly","groove_meter":"light 4/4 with varied motion pockets","round1_grammar":"hand-written body-mechanics facts; safety species observe-only","round2_grammar":"mechanic cue -> recall beat -> target -> safe finger gesture",
"intro_lines":("One insect pierces a leaf; one rolls dung; one flashes light after dark.","Tiny bodies solve different jobs in different ways."),
"hook_lines":("Cling, crawl, fly—A-B-C!","Small does not mean simple when the body parts change."),
"outro_lines":("The last butterfly closes its wings; the stick insect stays still.","A to Z ends with twenty-six different tiny-body clues."),
"round2_patterns":("Body clue {letter} ... {object}! {action}","Tiny mechanic {letter} ... {object}! {action}","How works {letter}? ... {object}! {action}","Close-view {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Aphid! Slender mouthparts tap plant sap | tiny feeder anchored to a leaf."),
("B","B ... B ... Beetle! Hardened forewings called elytra protect the flight wings beneath | armor opens before many beetles fly."),
("C","C? Caterpillar! Butterfly or moth larva chews and grows | later metamorphosis rebuilds the body for adulthood."),
("D","D is Dung Beetle. Many species feed on dung and some roll or bury it | legs turn waste into food and nursery resources."),
("E","E — Earwig! Forceps-like cerci curve at the abdomen tip | useful for defense, handling, and species-specific behavior."),
("F","F ... F ... Firefly! Light organs produce bioluminescence in many species | flashes can carry courtship signals."),
("G","G? Gnat! Tiny fly with one pair of true wings | small flight does not mean every gnat bites."),
("H","H is Honeybee. Hairy body carries pollen; a proboscis reaches nectar | worker bees also use a stinger defensively."),
("I","I — Inchworm! Caterpillar of a geometer moth loops because it has fewer middle prolegs than many caterpillars."),
("J","J ... J ... Jewel Beetle! Metallic-looking elytra can reflect brilliant color | hard wing covers hide softer flight wings."),
("K","K? Kissing Bug! Blood-feeding triatomine insect | observe only; some species can transmit Trypanosoma cruzi."),
("L","L is Ladybug. Lady beetle with hardened elytra | many species eat aphids and other small prey."),
("M","M — Mosquito! Female mosquitoes of many species take blood meals; both sexes use plant sugars | some species transmit disease."),
("N","N ... N ... Nymph! Immature stage of insects with incomplete metamorphosis | resembles the adult more than a caterpillar does."),
("O","O? Orange Butterfly! Scaled wings carry orange color patterns | butterfly flight comes after a larval caterpillar stage."),
("P","P is Praying Mantis. Grasping forelegs seize prey | predator observed with hands away."),
("Q","Q — Queen Butterfly! Orange-brown milkweed butterfly | scaled wings and gradual wingbeats, unrelated to a queen bee caste."),
("R","R ... R ... Roach! Cockroach has long antennae and flattened body | fast legs fit narrow shelters."),
("S","S? Stick Insect! Long body and legs can resemble twigs | camouflage works best when the insect barely moves."),
("T","T is Termite. Social insect colony includes specialized castes | termites are closer relatives of cockroaches than of ants."),
("U","U — Ulysses Butterfly! Large blue swallowtail from Australasia | dark wings flash vivid blue in motion."),
("V","V ... V ... Viceroy Butterfly! Orange-and-black North American butterfly | wing pattern resembles monarch-type warning coloration."),
("W","W? Wasp! Narrow-waisted hymenopteran group with many lifestyles | some sting defensively, so observe without handling."),
("X","X is Xylophone Beetle, our project X mapping | treat it as a named picture clue rather than inventing anatomy the label does not guarantee."),
("Y","Y — Yellow Butterfly! Yellow wing color can occur in many butterfly groups | color alone is not a species identification."),
("Z","Z ... Z ... Zebra Longwing! Long narrow black wings striped yellow | tropical butterfly with unusually long adult lifespan for a butterfly."),),
"style_blueprint":"Crisp diction. Open with three different tiny-body mechanisms at 92 BPM in light 4/4 with muted guitar, pizzicato, shaker and marimba. Melody narrow and stepwise around targets. Give crawl, roll, flash, cling and fly distinct rhythmic pockets; never make all bugs bounce. Round 1 protects nymph versus caterpillar and safety species. Chorus cling-crawl-fly. Round 2 leaves a recall beat and uses finger-only gestures. Duck target onsets. End quietly with folded wings and still camouflage."},
"0062": {
"authorial_intent":"Turn Butterfly Beetle Beat into a classification close-up: six-legged insects are compared with an eight-legged orb-weaver and a many-legged terrestrial crustacean, so 'tiny creature' never collapses into 'insect'.",
"lyric_identity":"A magnified field guide checks legs, wings, antennae and life stage before naming the group.",
"image_motifs":("six insect legs","orb-weaver eight legs","pill bug plates","rhinoceros beetle horn","butterfly scales"),
"semantic_arc":("define insect body plan","compare insect orders","contrast arachnid/crustacean","finish with wing and metamorphosis diversity"),
"forbidden_generic_language":("magnifying glass down","all are insects","tiny world fun","one close-up clue"),
"rhyme_engine":"closeup-classification-contrast-rhyme","chorus_rhyme_engine":"count-check-classify-hook","point_of_view":"a child classifying tiny animals by visible anatomy","chorus_function":"repeat count-check-classify","groove_meter":"precise 4/4 close-up pulse","round1_grammar":"hand-written classification facts with non-insect exceptions explicit","round2_grammar":"classification cue -> recall beat -> target -> count/point gesture",
"intro_lines":("Six legs under the lens—then eight legs appear in the next frame.","Count before you call every tiny creature an insect."),
"hook_lines":("Count, check, classify—A-B-C!","Legs, wings, antennae tell us which group we see."),
"outro_lines":("Lens up: insect, spider, crustacean stay in different boxes.","A to Z closes the field guide without flattening the tiny world."),
"round2_patterns":("Classify {letter} ... {object}! {action}","Count clue {letter} ... {object}! {action}","Which group {letter}? ... {object}! {action}","Close-up {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Ant! Six-legged social insect; workers in many species are wingless | antennae bend from the head."),
("B","B ... B ... Bee! Six-legged insect with two pairs of wings in adults | many species carry pollen while visiting flowers."),
("C","C? Caterpillar! Larval butterfly or moth | six true legs plus fleshy prolegs, so visible 'legs' need careful counting."),
("D","D is Dung Beetle. Beetle means hardened elytra over flight wings | dung use is ecology, beetle anatomy is classification."),
("E","E — Emperor Moth! Large moth with scaled wings | adult is insect; caterpillar was its larval stage."),
("F","F ... F ... Flea! Wingless insect compressed side-to-side with powerful jumping legs | still six-legged despite no wings."),
("G","G? Grasshopper! Insect with enlarged hind legs for jumping | nymphs resemble smaller wingless adults."),
("H","H is Honeybee. Insect with six legs, antennae and two pairs of wings | colony role does not change insect anatomy."),
("I","I — Insect! Adult body plan has head, thorax, abdomen and six legs | wings may be present or absent."),
("J","J ... J ... June Bug! Scarab beetle | hardened elytra identify the beetle branch."),
("K","K? Katydid! Long-antennaed orthopteran related to crickets | powerful hind legs and leaflike camouflage are common."),
("L","L is Leafhopper. Small sap-feeding hemipteran | piercing mouthparts and jumping legs fit its insect group."),
("M","M — Mantis! Predatory insect with grasping forelegs | six legs total, even when two are specialized as traps."),
("N","N ... N ... Nymph! Immature stage in incomplete metamorphosis | same broad insect body plan develops without a pupal stage."),
("O","O? Orb Weaver! Spider that builds wheel-shaped webs | arachnid with eight legs, not an insect."),
("P","P is Pill Bug. Terrestrial isopod crustacean with many jointed legs and armored segments | not an insect despite living under garden debris."),
("Q","Q — Queen Butterfly! Butterfly insect with scaled wings | the word queen is part of the species common name, not a colony caste."),
("R","R ... R ... Rhinoceros Beetle! Scarab beetle; males of many species bear large horns | horn grows from the exoskeleton."),
("S","S? Stick Insect! Six-legged insect shaped like a twig | camouflage can hide the leg count at first glance."),
("T","T is Termite. Social insect in the cockroach lineage | workers, soldiers, and reproductives share insect ancestry."),
("U","U — Underwing Moth! Moth with cryptic forewings and often bright hindwings | two wing layers reveal different patterns."),
("V","V ... V ... Vinegar Fly! Small drosophilid fly | one pair of functional wings identifies the fly order."),
("W","W? Wasp! Six-legged hymenopteran with two pairs of wings in many adults | many species are parasitoids or predators."),
("X","X is Xylocopa Bee. Xylocopa is the carpenter-bee genus | robust bees often nest by tunneling into wood."),
("Y","Y — Yellow Butterfly! Butterfly color clue | scaled wings identify the order more reliably than yellow alone."),
("Z","Z ... Z ... Zebra Longwing! Butterfly with long striped wings | six legs place it firmly inside insects."),),
"style_blueprint":"Crisp diction. Open with six legs versus eight at 88 BPM in precise 4/4 with pizzicato strings, acoustic guitar, soft woodblock and bass. Melody narrow; count gestures get clean pauses. Round 1 distinguishes insect, arachnid and terrestrial crustacean. Chorus count-check-classify. Round 2 uses finger counting only, no handling animals. Duck target onsets. End with three classification boxes and a clean cadence."},
"0063": {
"authorial_intent":"Make Garden Bug Hunt an ecological-role map: pollinator, plant feeder, predator, decomposer, aquatic-juvenile visitor, nuisance and disease-vector risks all occupy different relationships in one garden.",
"lyric_identity":"A child asks what each tiny creature is doing in the garden rather than whether it is 'good' or 'bad'.",
"image_motifs":("bee on flower","aphid colony","dragonfly above pond","mantis ambush","weevil on leaf"),
"semantic_arc":("plant feeders and pollinators","predators and aquatic links","decomposers/nuisance species","safety and coexistence"),
"forbidden_generic_language":("catch the tiny name","good bugs bad bugs","garden bug party","flutter tap wiggle"),
"rhyme_engine":"garden-ecological-role-rhyme","chorus_rhyme_engine":"feed-pollinate-hunt-hook","point_of_view":"a child mapping ecological roles without moralizing animals","chorus_function":"reset feed-pollinate-hunt-decompose","groove_meter":"walking 4/4 garden observation pulse","round1_grammar":"hand-written ecological role and safety; spiders explicit non-insect","round2_grammar":"role cue -> recall beat -> target -> observe/point gesture",
"intro_lines":("One creature drinks plant sap, one carries pollen, one hunts another insect.","A garden is a web of jobs, not a list of heroes and villains."),
"hook_lines":("Feed, pollinate, hunt—A-B-C!","Ask what it does before you decide what it means."),
"outro_lines":("Leaves stay, web stays, insects keep their distance from our hands.","A to Z leaves the garden working after we go."),
"round2_patterns":("Garden role {letter} ... {object}! {action}","What job {letter} ... {object}! {action}","Feed, hunt, or visit—{letter}? ... {object}! {action}","Garden clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Aphid! Sap-feeding insect can form colonies on stems and leaves | prey for lady beetles and other predators."),
("B","B ... B ... Bee! Many bees move pollen while collecting nectar or pollen | pollination is a plant-insect relationship, not a favor done on purpose."),
("C","C? Cricket! Omnivorous or plant-feeding roles vary by species | many males produce chirps by rubbing wing structures."),
("D","D is Dragonfly. Adult aerial predator hunts small insects | aquatic nymph lives underwater, linking pond and garden."),
("E","E — Earwig! Omnivore that may eat plant material, fungi, or small animals | role changes with species and food available."),
("F","F ... F ... Firefly! Beetle whose larvae often prey on small soft-bodied animals | adults of many species signal with light."),
("G","G? Gnat! Tiny fly; roles range from decomposer larvae to plant feeder or nuisance | 'gnat' covers many groups."),
("H","H is Hercules Beetle. Huge rhinoceros beetle; larvae develop in decaying wood | decomposition habitat matters to its life cycle."),
("I","I — Insect! Six-legged animal group filling many garden roles | one label cannot predict its job."),
("J","J ... J ... June Bug! Scarab beetle; larvae often feed underground on roots or organic matter | adults may feed on leaves."),
("K","K? Kissing Bug! Blood-feeding triatomine | not a garden handling target; some species can transmit Chagas disease parasites."),
("L","L is Leafhopper. Sap-feeding hemipteran can move between plants | some species transmit plant pathogens."),
("M","M — Mosquito! Aquatic larvae grow in standing water; adults feed on plant sugars, and females of many species also take blood | some transmit disease."),
("N","N ... N ... Net-winged Beetle! Adults often show ridged, netlike elytra | larvae of many species live in decaying wood or soil."),
("O","O? Orb Weaver! Eight-legged spider catches insects in an orb web | garden predator, not an insect."),
("P","P is Praying Mantis. Ambush predator grabs insects and other small prey | useful ecological role does not make it safe to handle."),
("Q","Q — Queen Bee! Reproductive female in a social bee colony | colony role differs from worker tasks such as foraging."),
("R","R ... R ... Rhinoceros Beetle! Scarab larvae often develop in decaying plant material | adults carry large horns in many species."),
("S","S? Stick Insect! Plant eater camouflaged as twigs or leaves | feeding role differs from mantis predation."),
("T","T is Tiger Moth. Moth group with often hairy caterpillars | caterpillars feed on plants while adults occupy a different life stage."),
("U","U — Underwing Moth! Moth hides bright hindwings beneath cryptic forewings | caterpillars feed on host plants."),
("V","V ... V ... Vinegar Fly! Small fly attracted to fermenting fruit and microbes | larvae help process yeasty decaying material."),
("W","W? Weevil! Beetle with elongated snout | many species feed on particular plants or seeds."),
("X","X is Xylocopa Bee. Carpenter bee often nests in tunnels it excavates in wood | adults also visit flowers."),
("Y","Y — Yellowjacket! Social wasp that can sting defensively | observe food-seeking workers from distance and never disturb a nest."),
("Z","Z ... Z ... Zebra Butterfly! Zebra-patterned butterfly mapping clue | flower visits and host plants connect adult and larval stages."),),
"style_blueprint":"Crisp diction. Open with three contrasting garden roles at 90 BPM in walking 4/4 with acoustic guitar, soft bass, shaker and marimba. Melody narrow and conversational. Round 1 groups feeding, pollination, predation, decomposition and safety without 'good/bad bug' framing. Chorus feed-pollinate-hunt. Round 2 uses pointing gestures and one recall beat; kissing bug, mosquito, yellowjacket and mantis are observe-only. Duck target onsets. End with living garden ambience, no swarm SFX."},
"0064": {
"authorial_intent":"Make Little Creature Crawl a life-cycle song: egg/larva/pupa/adult concepts are contrasted with incomplete-metamorphosis nymphs, using the mapped caterpillar-like Inchworm and many adult insects to show that young stages can look very different.",
"lyric_identity":"A child tracks 'same animal, different stage' rather than a morning wake-up parade.",
"image_motifs":("inchworm larva","moth adult","grasshopper-like nymph idea","beetle adult elytra","butterfly adult wings"),
"semantic_arc":("larval body","adult insect diversity","complete vs incomplete metamorphosis","stage labels and safety"),
"forbidden_generic_language":("morning bugs waking","dew bright","everyone crawls","tiny creature crawl"),
"rhyme_engine":"life-stage-transformation-rhyme","chorus_rhyme_engine":"young-change-adult-hook","point_of_view":"a child following life stages across different insect groups","chorus_function":"reset young-change-adult","groove_meter":"gentle 6/8 transformation sway","round1_grammar":"hand-written stage-aware lines; adult mapped object does not imply its juvenile looks same","round2_grammar":"stage cue -> recall beat -> target -> safe transform gesture",
"intro_lines":("A moth begins as a caterpillar; a grasshopper begins as a nymph that already looks grasshopper-like.","Young insects do not all grow by the same route."),
"hook_lines":("Young, change, adult—A-B-C!","Larva or nymph? The life-cycle path tells us."),
"outro_lines":("One adult folds its wings; another nymph still has growing left to do.","A to Z ends with life stages kept distinct."),
"round2_patterns":("Life-stage {letter} ... {object}! {action}","Young/adult {letter} ... {object}! {action}","Which stage path—{letter}? ... {object}! {action}","Change clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Ant! Complete metamorphosis: egg, larva, pupa, adult | worker adult looks nothing like the grub-like larva."),
("B","B ... B ... Bee! Complete metamorphosis also reshapes bee larvae into winged adults | colony care shelters the young."),
("C","C? Cricket! Incomplete metamorphosis: egg to nymph to adult | nymph resembles a small wingless cricket."),
("D","D is Dragonfly. Aquatic nymph transforms directly into winged adult without a pupal stage | water-to-air life-cycle shift."),
("E","E — Emperor Moth! Adult moth came through caterpillar and pupa stages | complete metamorphosis changes the body dramatically."),
("F","F ... F ... Flea! Complete metamorphosis: wormlike larva becomes pupa, then jumping adult."),
("G","G? Gnat! Fly life cycles use larva and pupa before the winged adult | many larvae live in moist habitats."),
("H","H is Hercules Beetle. Huge adult beetle begins as a large grub-like larva in decaying wood | complete metamorphosis."),
("I","I — Inchworm! Geometer-moth caterpillar | larval stage, not a tiny adult worm."),
("J","J ... J ... Jewel Beetle! Adult metallic beetle develops from a larva that often tunnels in plant tissue or wood."),
("K","K? Kissing Bug! True bug with incomplete metamorphosis | nymph resembles a smaller wingless adult and can also blood-feed."),
("L","L is Ladybug. Beetle larva looks elongated and spiky, then pupates into the rounded adult beetle."),
("M","M — Mantis! Incomplete metamorphosis | mantis nymph resembles a miniature adult without full wings."),
("N","N ... N ... Net-winged Beetle! Complete metamorphosis separates larval body from net-ridged adult elytra."),
("O","O? Orange Butterfly! Adult butterfly follows caterpillar and chrysalis stages | scaled wings appear only after metamorphosis."),
("P","P is Praying Mantis. Same incomplete-metamorphosis path as other mantises | nymph grows through molts rather than a pupa."),
("Q","Q — Queen Bee! Queen is an adult reproductive caste | she also began as larva, with diet influencing caste development in honeybees."),
("R","R ... R ... Roach! Cockroach nymph resembles a smaller adult | incomplete metamorphosis, no pupa."),
("S","S? Stag Beetle! Beetle larvae can spend years developing in decaying wood before pupation | adult life is the final stage."),
("T","T is Tiger Moth. Caterpillar-to-pupa-to-moth is complete metamorphosis | fuzzy larva and winged adult can look unrelated."),
("U","U — Underwing Moth! Another complete-metamorphosis example | cryptic adult wings come after caterpillar growth."),
("V","V ... V ... Viceroy Butterfly! Caterpillar and chrysalis precede the orange-and-black adult butterfly."),
("W","W? Wasp! Complete metamorphosis | larva develops before pupating into a winged or wingless adult caste depending species."),
("X","X is Xylocopa Bee. Carpenter bee uses complete metamorphosis inside nest cells | larva, pupa, then adult."),
("Y","Y — Yellow Butterfly! Adult wing color arrives after caterpillar and pupa stages | color does not identify the larva."),
("Z","Z ... Z ... Zebra Longwing! Adult butterfly comes from a caterpillar specialized on host plants | same individual, radically different stage."),),
"style_blueprint":"Crisp diction. Open with larva versus nymph contrast at 84 BPM in gentle 6/8 with acoustic guitar, pizzicato, soft shaker and warm pad. Use short repeating motifs that transform orchestration from larva to adult. Round 1 names complete versus incomplete metamorphosis accurately. Chorus young-change-adult. Round 2 leaves one recall beat and uses curl/open hand transformations. Kissing bug/wasp remain observe-only. Duck target onsets. End with wings folding and an unfinished nymph motif."},
"0065": {
"authorial_intent":"Make Insect Explorer a field-identification protocol: first observe body shape, leg count, antennae, wings and behavior, then identify cautiously; uncertain project mapping terms stay labeled rather than overclaimed.",
"lyric_identity":"A child builds a field-note ID from multiple traits instead of marching or guessing from color.",
"image_motifs":("antennae sketch","elytra line","dragonfly wing pair","weevil snout","yellow butterfly color warning against over-ID"),
"semantic_arc":("body basics","wing and antenna traits","behavior and ecology","uncertainty/safety and final identification"),
"forbidden_generic_language":("parade line ready","march hop crawl flutter","guess the bug","color tells the species"),
"rhyme_engine":"field-id-multi-trait-rhyme","chorus_rhyme_engine":"look-note-check-hook","point_of_view":"a child building cautious field identifications from several traits","chorus_function":"repeat look-note-check","groove_meter":"steady 4/4 field-guide pulse","round1_grammar":"hand-written field marks with uncertainty and safety","round2_grammar":"field-mark cue -> recall beat -> target -> sketch/point gesture",
"intro_lines":("Do not name it from color alone: count legs, check wings, notice antennae.","A field guide works best when several clues agree."),
"hook_lines":("Look, note, check—A-B-C!","One trait starts the guess; several traits build the name."),
"outro_lines":("Notebook shut; uncertain labels stay uncertain instead of forced.","A to Z ends with careful identification, not a bug parade."),
"round2_patterns":("Field mark {letter} ... {object}! {action}","ID clue {letter} ... {object}! {action}","Which traits {letter}? ... {object}! {action}","Check {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Ant! Elbowed antennae, narrow waist, six legs | social behavior can add another ID clue."),
("B","B ... B ... Beetle! Elytra are the strongest field mark | hard forewings meet in a line down the back."),
("C","C? Cricket! Very long antennae and enlarged jumping hind legs | sound can support ID, but body marks come first."),
("D","D is Dragonfly. Huge compound eyes and two pairs of long open wings | adult often patrols near water."),
("E","E — Earwig! Paired forceps at abdomen tip | one unmistakable shape clue."),
("F","F ... F ... Firefly! Soft-bodied beetle; many adults have light organs | glow is useful only in species and life stages that actually produce it."),
("G","G? Grasshopper! Shorter antennae than katydids, enlarged hind legs | jumping body plan is a strong field mark."),
("H","H is Honeybee. Hairy body, pollen-carrying structures, elbowed antennae | flower behavior supports the ID."),
("I","I — Inchworm! Looping geometer-moth caterpillar | fewer middle prolegs create its measuring gait."),
("J","J ... J ... Jewel Beetle! Streamlined beetle with often metallic elytra | shape plus wing covers beats color alone."),
("K","K? Kissing Bug! Elongate head and piercing mouthparts in triatomines | potentially hazardous; identify from image or expert source, never handling."),
("L","L is Leafhopper. Wedge-shaped small insect with jumping hind legs | sap-feeding beak tucked under the head."),
("M","M — Mantis! Triangular head and raptorial forelegs | predatory posture is a strong clue."),
("N","N ... N ... Net-winged Beetle! Raised ridges form a netlike pattern on elytra | texture becomes the field mark."),
("O","O? Orb Weaver! Spider with eight legs and orb web | non-insect exception catches careless leg counting."),
("P","P is Pill Bug. Many-legged terrestrial isopod with overlapping plates | crustacean, not insect."),
("Q","Q — Queen Bee! A reproductive colony role, not a species field mark | identifying a queen depends on colony and body context."),
("R","R ... R ... Rhinoceros Beetle! Large scarab with horn structures in many males | elytra still identify it as beetle."),
("S","S? Stag Beetle! Large mandibles in many males resemble antlers | scarab-like beetle body plus jaw shape narrows ID."),
("T","T is Termite. Straight-looking antennae and broad waist contrast with ants | reproductive adults may have equal-length wings."),
("U","U — Ulysses Butterfly! Brilliant blue upper wings with dark margins | range and wing shape must join color for reliable ID."),
("V","V ... V ... Vinegar Fly! Tiny drosophilid with one wing pair and attraction to fermenting material | behavior plus fly anatomy."),
("W","W? Weevil! Elongated snout and elbowed antennae | specialized beetle profile."),
("X","X is Xylophone Beetle, our project X label | keep the field note tied to the provided picture until a more precise taxon is supplied."),
("Y","Y — Yellow Butterfly! Yellow is only a color clue | wing shape, markings, range, and host plants are needed for species ID."),
("Z","Z ... Z ... Zebra Longwing! Long narrow black wings with yellow stripes | distinctive shape-plus-pattern combination."),),
"style_blueprint":"Crisp diction. Open with count-legs/check-wings at 88 BPM in steady 4/4 with acoustic guitar, muted woodblock, bass and light marimba. Melody narrow and speech-clear. Round 1 follows field-mark protocol and explicitly catches Orb Weaver/Pill Bug non-insect exceptions. Chorus look-note-check. Round 2 uses air-sketch/point gestures and one recall beat. Hazardous insects remain image-only. Duck target onsets. End with an uncertain label intentionally left open."}
}
