from __future__ import annotations

# Deep-polish layer for songs 0001-0010.
#
# The V4 gold module remains the source for locked mappings, object facts/actions,
# section forms, and the broad creative fingerprints.  This layer owns the
# hand-written Round-1 lyric and rhyme architecture requested for the final
# catalog polish.  Keeping it separate makes it obvious which lines are truly
# song-specific rather than shared object templates.

GOLD_V5_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0001": {
        "authorial_intent": "Make the catalog opener feel like one musical ripple, not a nature encyclopedia: it starts tiny, crosses reef and shore, dips through deeper water, rises for breath and light, then carries the final letter back toward the first ripple. Facts should be memorable because the phrasing moves, surprises, and sings.",
        "lyric_identity": "Ripple-motion is the signature. Short sound-words and child-repeatable verbs - plip, bob, flick, swish, glide, dip, rise, drift - alternate with a few vivid wow-facts. Information weight deliberately breathes: some letters are quick musical hits, others open into a larger image.",
        "image_motifs": ("one silver ripple", "reef-light", "shore meeting water", "surface breath", "tiny current-riders"),
        "semantic_arc": ("one ripple opens and finds reef life", "shore structures and seafloor movement widen the scene", "deep water rises repeatedly toward light and air", "current carries Y and Z back toward the opening ripple"),
        "forbidden_generic_language": ("fun to see", "shining bright", "come sing with me", "ocean friend"),
        "opening_type": "single-ripple scene drop",
        "target_entry_families": ("direct", "repeated-letter", "is-for", "question-answer", "narrative"),
        "line_length_contour": ("short", "medium", "short", "long"),
        "rhyme_engine": "ripple-cluster-rhyme-with-open-release",
        "chorus_rhyme_engine": "paired-me-z",
        "point_of_view": "child-sized observer riding one ripple through changing ocean layers",
        "chorus_function": "ultra-repeatable movement hook with a clean me/Z rhyme and no explanatory prose",
        "groove_meter": "rolling 4/4 acoustic-pop with a light triplet undertow",
        "round1_grammar": "song-first ocean snapshots: target early, one concrete image or fact, strong internal sound where natural, and deliberate short lines between richer teaching moments",
        "round2_grammar": "brief clue -> one real beat -> target -> tiny semantic gesture; child response stays much shorter than Round 1 and rotates shape, motion, habitat, and function clues",
        "section_contrast": "A-H close and buoyant; I-P slightly wider; Q-X more spacious for rare words and wow-facts; Y-Z drift outward; interlude nearly empties; Round 2 is voice-first stop-start recall; final chorus blooms once before a tide-like strip-down",
        "signature_color": "two-note marimba ripple answers after targets, never on their first syllable",
        "intro_lines": ("Plip\u2014one silver ripple starts small.", "Follow it past reef and shore; watch the blue grow wide."),
        "hook_lines": ("Splash-splash! Ride the ripple with me,", "Ocean letters, A to Z!"),
        "outro_lines": ("One last silver ripple touches the shore.", "A to Z grows quiet; the water moves once more."),
        "interlude_lines": ("The ripple turns. I call the letter; you bring the ocean word back.",),
        "chorus_after_round1": (2, 4, 6),
        "chorus_after_round2": (2, 4, 7),
        "round1_overrides": (
            ("A", "A - Angelfish! Tall fins fan; flat body turns | slipping through coral branches where reef light gleams."),
            ("B", "B ... B ... Buoy! Bob, bob, bright on blue | anchored in place, a floating marker for boats."),
            ("C", "C is for Coral. Tiny animals, side by side | hard skeletons can build reefs where little swimmers hide."),
            ("D", "D? Dock! Shore meets boat | boats tie up, load up, rocking with the tide."),
            ("E", "Here comes E with Eel. Long fish, no legs | bend through a rocky gap, wave after wave."),
            ("F", "F - Fish! Fin flick, tail swish | gills take oxygen from water as it swims."),
            ("G", "G ... G ... Grouper! Stout in reef shade | broad mouth waiting by a ledge."),
            ("H", "H is for Harbor. Waves grow mild behind shelter | boats find calmer water to rest in."),
            ("I", "I? Island! Land in a ring of blue | one still shape with moving water all around."),
            ("J", "J - Jetty! Built out from shore | rock, concrete, or timber reaches into the water."),
            ("K", "Kayak - that's K. Narrow boat, double-bladed paddle | left stroke, right stroke, glide and turn."),
            ("L", "L ... L ... Lobster! Step-step on the seafloor | long antennae feel the way ahead."),
            ("M", "M is for Mussel. Shell shuts tight | silky threads hold fast when the tide pulls by."),
            ("N", "N? Narwhal! Cold Arctic blue | that spiral tusk is really one very long tooth."),
            ("O", "O - Octopus! Eight arms feel and grip | soft body squeezes through a narrow gap."),
            ("P", "P - Pelican! Skim, dip, scoop | throat pouch catches fish, then lets the water drain."),
            ("Q", "Q ... Q ... Quahog! Say KOH-hog | hard-shell clam tucked in coastal sand or mud."),
            ("R", "R is for Ray. Wide fins ripple like wings | gliding low like a shadow over sand."),
            ("S", "S? Seahorse! Upright, tiny fin flutter | curled tail grips seagrass when the current pulls."),
            ("T", "T - Turtle! In the sea, broad flippers sweep | steady strokes through open water."),
            ("U", "U - Undersea Cave! Rock opens under waves | a dark saltwater hollow below the light."),
            ("V", "V ... V ... Violet Sea Snail! Tiny purple-blue | hanging from a bubble raft at the surface."),
            ("W", "W is for Whale. Deep below, then up for air | one huge breath at the surface, then down again."),
            ("X", "X? X-ray Tetra! Freshwater visitor, not sea | translucent body lets some bones partly show."),
            ("Y", "Y - Yellowfin Tuna! Yellow finlets flash | streamlined body slices through open blue."),
            ("Z", "Z ... Z ... Zooplankton! Tiny drifters ride the flow | current carries our last letter where the first ripple goes."),
        ),
        "round2_overrides": (
            ("A", "A ... Angelfish! Tall fins\u2014fan and glide."),
            ("B", "B - what bobs? ... Buoy! Bob one hand up and down."),
            ("C", "C - reef builder? ... Coral! Open fingers like branches."),
            ("D", "D at the shore ... Dock! One flat arm makes the platform."),
            ("E", "E - long and bendy ... Eel! Wave one hand side to side."),
            ("F", "F - fin flick, tail swish ... Fish! Swish one hand once."),
            ("G", "G in reef shade ... Grouper! Make one slow glide."),
            ("H", "H - calmer water ... Harbor! Curve both hands into a bay."),
            ("I", "Water all around - I? ... Island! Circle one still fist."),
            ("J", "J reaches out ... Jetty! Slide one flat hand outward."),
            ("K", "K - double paddle ... Kayak! Paddle left, then right."),
            ("L", "L - seafloor walker ... Lobster! Walk two fingers."),
            ("M", "M - shell shuts tight ... Mussel! Close two palms."),
            ("N", "N - spiral tooth ... Narwhal! Trace one spiral."),
            ("O", "Eight arms - O? ... Octopus! Wiggle both hands."),
            ("P", "P - bill and pouch ... Pelican! Scoop, then lift."),
            ("Q", "Q ... Quahog! KOH-hog\u2014close two palms like a clam."),
            ("R", "R - wide fins over sand ... Ray! Glide hands wide."),
            ("S", "S - upright, curled tail ... Seahorse! Curl one finger."),
            ("T", "T - shell and flippers ... Turtle! Make a shell, then sweep."),
            ("U", "U - dark hollow under waves ... Undersea Cave! Arch both hands."),
            ("V", "V - bubble raft ... Violet Sea Snail! Spiral, then float."),
            ("W", "Who rises for air? W ... Whale! Lift, breathe, glide down."),
            ("X", "X - freshwater visitor ... X-ray Tetra! Small fish glide\u2014freshwater is home."),
            ("Y", "Y - yellow finlets ... Yellowfin Tuna! Sweep fast and smooth."),
            ("Z", "Z - tiny drifters ... Zooplankton! Let fingertips ride the flow."),
        ),
        "style_blueprint": 'Bright polished acoustic ocean-pop for preschool, 88 BPM, rolling 4/4 with gentle triplet feel. Warm clear adult female lead, close and dry, crisp en-US diction, minimal vibrato. Narrow mostly stepwise major-key melody; conversational verses, slightly higher choruses. Light ukulele/acoustic guitar, rounded bass, soft shaker, brushed percussion, two-note marimba ripple motif. Sparse intro, then widen like water moving from reef to open sea. Round 1 alternates short rhythmic hits and longer teaching lines; let phrase-break rhymes breathe, with Q, V and X near speech rhythm. Chorus: simple catchy singalong, strong pulse, light child-group echo after lead. Round 2: cue, one beat silence, target answer, tiny action; thin accompaniment before answers, keep target onset dry, marimba reply after. Stable harmony and low density around vocabulary. Final chorus fullest; strip back to marimba ripple and end cleanly.',
    },

    "0002": {
        "authorial_intent": "Make the alphabet feel like beachcombing at low tide: the sea pulls back, leaves clues, and the child gathers each discovery as a small shoreline treasure.",
        "lyric_identity": "Discovery verbs and tide-made images lead: washed up, tucked, traced, bobbed, left behind, found. Sand, tide lines, shallow blue, shells, and shore marks recur while the narrator sounds like a child collector rather than a lecturer.",
        "image_motifs": ("low-tide line", "sand marks", "washed-up clues", "shallow blue", "shoreline treasures"),
        "semantic_arc": ("tide pulls back", "small clues appear", "larger coast-and-sea discoveries widen the view", "tide returns while the found words remain"),
        "forbidden_generic_language": ("fun to see", "today", "come with me", "nice and neat"),
        "intro_lines": ("Low tide pulls a silver line away.", "What little letter-clues did the shoreline save?"),
        "hook_lines": ("Tide rolls out—look what we found!", "Letter treasures all around!"),
        "outro_lines": ("Tide rolls in and smooths the sand.", "Our letter treasures stay in hand."),
        "rhyme_engine": "alternating-quatrain-near-rhyme",
        "round1_grammar": "hand-written shoreline quatrains using ABAB or near-ABAB rhyme across neighboring letter lines, with occasional internal echoes",
        "round1_overrides": (
            ("A", "Anchor — that's A. Low tide shows the sand | heavy metal drops to hold a boat close at hand."),
            ("B", "Spot B: Boat! A floating little carrier rocking on the blue."),
            ("C", "C brings Coral. Branches lace | little reef rooms make a living space."),
            ("D", "What does D bring? Dock! The shoreline reaches out | a long platform where boats come close."),
            ("E", "E — Estuary. River meets the tide | fresh and salty waters mix side by side."),
            ("F", "Flipper — that's F. A broad swimming limb sweeps water back to help an animal through."),
            ("G", "Spot G: Gull! White wings lean into coastal wind and circle wide."),
            ("H", "H brings Harbor—a calmer pocket where the boats can rest in blue."),
            ("I", "What does I bring? Isopod! Under shoreline cover, a hard segmented body carries many little legs underneath."),
            ("J", "J — Jellyfish. Soft bell drifting, trailing tentacles behind."),
            ("K", "Kelp — that's K. Below the tide | long brown-green ribbons sway side to side."),
            ("L", "Spot L: Lagoon! Shallow water set apart from open sea—a quiet place to find."),
            ("M", "M brings Manatee. Slow with ease | paddle flippers sweep warm rivers and seas."),
            ("N", "What does N bring? Narwhal! Arctic whale; one spiral tusk can point ahead as it goes."),
            ("O", "O — Oyster. Shell shuts well | rough two-part home where tidal waters swell."),
            ("P", "Pufferfish — that's P. It can make its body rounder when a danger shows."),
            ("Q", "Spot Q: Quahog! Under sand | hard clam shell tucked close at hand."),
            ("R", "R brings Reef—a rocky or coral home with cracks where little animals hide."),
            ("S", "What does S bring? Seahorse! Hold a strand | curled tail grips the plant like a hand."),
            ("T", "T — Turtle. Hard shell on its back; steady strokes carry it through the tide."),
            ("U", "Urchin — that's U. Round on the ground | stiff sea spines point all around."),
            ("V", "Spot V: Vessel! Beyond the beach line, a boat or ship travels over open water."),
            ("W", "W brings Whale. Up, then down | giant mammal breathes at the surface, then turns around."),
            ("X", "What does X bring? X-ray Fish! Partly see-through body shows where some tiny bones are."),
            ("Y", "Y — Yellowfin Tuna. Fins flash into view | yellow-tinted swimmer racing through blue."),
            ("Z", "Zooplankton — that's Z. Too tiny to choose a path | moving water carries the drifters along."),
        ),
        "style_blueprint": "Clear warm adult lead, crisp consonants and stable vowels. Gentle 6/8 acoustic surf sway at 90 BPM with clean guitar upstrokes, soft shaker, glockenspiel and rounded bass; narrow singable melody. Open with a shoreline question and answer it musically, not with a generic invitation. Round 1 is shaped as beachcombing quatrains: neighboring A-B-C-D style groups use alternating ABAB or near-ABAB end sounds, with occasional internal echoes, so a rhyme can wait one line before answering. Do not over-accent the rhyme word; preserve natural English stress and allow a longer semantic line to breathe across two bars. Chorus brightens into the name-the-coast refrain. Round 2 uses search-and-find call-and-response with a predictable one-beat response gap. Duck guitar and percussion at target-word onset; glockenspiel answers afterward. Keep the arrangement airy and vocals forward. End with a gentle surf cadence and the final A-to-Z hook.",
    },
    "0003": {
        "authorial_intent": "Turn A to Z into one small working voyage where every new word joins the boat crew; the child should feel departure, teamwork, lookout calls, and a satisfying return to harbor.",
        "lyric_identity": "Compact deck calls, lookout language, rowing pulse, and delayed answer-rhymes. Verbs such as row, call, spot, haul, turn, rise, and home give the lyric a cooperative work-song identity without military or shouted language.",
        "image_motifs": ("oars", "deck rail", "lookout calls", "wake behind the boat", "harbor return"),
        "semantic_arc": ("crew casts off", "lookouts call sea clues", "mid-voyage work and wildlife", "final watch turns back toward harbor"),
        "forbidden_generic_language": ("fun to see", "come sing with me", "on our tour", "hooray"),
        "intro_lines": ("Oars in—one, two. Deck crew, ready?", "First letter off the bow!"),
        "hook_lines": ("Pull together—row and say!", "Every letter joins the crew today!"),
        "outro_lines": ("Last call, crew—the harbor's near.", "A to Z comes home loud and clear."),
        "rhyme_engine": "crew-delayed-payoff-rhyme",
        "round1_grammar": "hand-written deck-call work-song lines; a rhyme or sound planted early in a four-line crew block may resolve only on the third or fourth line",
        "round1_overrides": (
            ("A", "A ... A ... Angelfish! Fins flare bright | reef-blue swimmer catching light."),
            ("B", "B — Boat! Our deck rides on its hull, carrying crew and gear over water."),
            ("C", "From the deck, C finds Crab—sideways feet stitch little tracks across wet sand."),
            ("D", "D is for Dolphin—lookout calls; surface, breathe, arc, then disappear behind the boat."),
            ("E", "Crew calls E? Eel! Long body bends | slipping through reef cracks as currents go."),
            ("F", "F ... F ... Fish! Fins steer while gills draw oxygen from the water."),
            ("G", "G — Grouper! Stout reef fish, wide mouth waiting near rocky shade."),
            ("H", "From the deck, H finds Hermit Crab—soft body sheltered in a borrowed shell wherever it goes."),
            ("I", "I is for Isopod. Plate after plate | many little legs hurry in a row."),
            ("J", "Crew calls J? Jellyfish! Soft bell pulses while trailing tentacles drift behind."),
            ("K", "K ... K ... Kayak! Two paddle blades flash left-right as the narrow boat turns across our course."),
            ("L", "L — Lagoon! Shallow water rests apart from open sea, calm and low."),
            ("M", "From the deck, M finds Mussel. Two dark halves | closed shell holds tight on stone."),
            ("N", "N is for Nautilus—coil after coil, its chambered shell travels as it swims."),
            ("O", "Crew calls O? Oyster! Rough two-part shell closes around the soft animal inside."),
            ("P", "P ... P ... Pelican! Bill down, pouch scoop, wings up—the lookout crosses over our wake."),
            ("Q", "Q — Queen Angelfish! Yellow and blue glow | bright reef colors turning slow."),
            ("R", "From the deck, R finds Reef—a rocky or coral home full of cracks and hiding places."),
            ("S", "S is for Seahorse—upright swimmer, curled tail holding tight to a plant."),
            ("T", "Crew calls T? Tidepool! A rocky hollow keeps seawater when the tide goes low."),
            ("U", "U ... U ... Urchin! Round on the ground | stiff sea spines point all around."),
            ("V", "V — Vessel! Boat or ship—the watercraft our crew can ride from harbor to harbor."),
            ("W", "From the deck, W finds Wave—our bow rises, a crest passes, then water falls away behind."),
            ("X", "X is for X-ray Fish. Partly see-through body | some tiny bones can be found."),
            ("Y", "Crew calls Y? Yellow Tang! Yellow in view | flat oval reef fish gliding through blue."),
            ("Z", "Z ... Z ... Zebra Shark! Young sharks wear dark zebra-like bands; a long tail trails behind."),
        ),
        "style_blueprint": "Friendly clear adult lead with a small group response, crisp diction and no shouted delivery. Light 2/4 nautical preschool stomp at 92 BPM: brushed snare, ukulele, soft accordion breaths, hand claps and bass. Open with a rhythmic rowing pickup before the hook. Round 1 behaves like a gentle work-song: each four-letter deck-call block can plant a rhyme, vowel color, or rhythmic phrase in line one and delay its payoff until line three or four; middle lines may stay open and factual. Keep the crew pulse stable so delayed rhyme still feels intentional. Use internal phrase rhymes only where they add image or motion, never as filler. Chorus lands strongly on beat one as a crew-response refrain. Round 2 is stripped to soft stomp plus voice, with one clean beat of silence between letter cue and target confirmation. Keep backing voices out of target-word attacks; accordion may answer after. Stable simple harmony. End with the rowing pulse slowing into a short final cadence.",
    },
    "0004": {
        "authorial_intent": "Write the alphabet as one continuous sailing tale in which each image hands a word, sound, or place into the next; the child should feel that A to Z is a journey rather than 26 separate cards.",
        "lyric_identity": "Linked-image language is the signature: the end of one scene becomes the doorway into the next. Water, shore, glow, breath, surface, and distance recur as connective tissue while the narrator stays gentle and observant.",
        "image_motifs": ("morning water-road", "shore-to-sea transitions", "glow and reflection", "surface breath", "evening gold"),
        "semantic_arc": ("morning departure", "shore and reef pass by", "the voyage reaches wider/deeper water", "last light closes the linked chain"),
        "forbidden_generic_language": ("fun to see", "come look with me", "today", "nice and neat"),
        "intro_lines": ("Morning lays a bright road on the water.", "One clue will lead us into the next."),
        "hook_lines": ("One clue opens into two;", "Sail A to Z across the blue."),
        "outro_lines": ("Evening turns the blue to gold.", "A to Z—one linked tale told."),
        "rhyme_engine": "linked-end-to-internal-rhyme",
        "round1_grammar": "hand-written sailing narrative where the end image or sound of one target line is echoed naturally inside the next line; inspired by linked poetic rhyme, not a fixed syllable-count imitation",
        "round1_overrides": (
            ("A", "On our way, A meets Anchor. Down through water | heavy metal helps the boat stay still."),
            ("B", "Small waves spill around B — Boat | a floating carrier moving over blue."),
            ("C", "From blue shallows, C is Crab | sideways feet stitch tracks across sand."),
            ("D", "Beyond the strand, D — Dolphin | rises for air, then curves back through the sea."),
            ("E", "E is for Estuary. Sea meets river | fresh and salty waters join and flow."),
            ("F", "In that flow, F meets Flipper | a broad limb sweeps water back to make a swimmer go."),
            ("G", "Where swimmers go, G is Grouper | stout reef body, wide mouth waiting in shade."),
            ("H", "In reef shade, H — Hermit Crab | soft body carries a borrowed shell."),
            ("I", "I — Island. Water all around | land rises inside a blue ring."),
            ("J", "Along that ring, J is Jetty | reaching from the shore out over water."),
            ("K", "Over water, K meets Kayak | narrow boat, double paddle forward and back."),
            ("L", "Looking back, L — Lobster | claws ahead, walking on the seafloor."),
            ("M", "By afternoon, what waits at M? Manatee! Warm-water swimmer | paddle-like flippers moving slow and free."),
            ("N", "Moving free, N — Nautilus | coiled shell divided into chambers as it swims."),
            ("O", "Where it swims, O is Octopus | eight arms, soft body, squeezing through tight spaces under the sea."),
            ("P", "Above the sea, P meets Pelican | long bill and throat pouch scoop fish from the water."),
            ("Q", "Across that water, late light finds Q — Queen Angelfish. Yellow and blue glow | reef colors bright below."),
            ("R", "In that glow, R is Ray | wide fins glide through water like wings."),
            ("S", "Under gliding wings, S — Seal | flippers sweep, then the seal rests on rock or shore."),
            ("T", "At the shore, T is Tidepool | rocky hollow keeps seawater when the tide goes out."),
            ("U", "When tide goes out, U meets Urchin | round sea animal covered in stiff spines."),
            ("V", "Past the spines, V — Violet Sea Snail | tiny purple-blue snail floating near the surface."),
            ("W", "At the evening surface, W is Whale | giant marine mammal rising to breathe."),
            ("X", "After that breath, X — X-ray Fish | translucent little body lets us partly see through."),
            ("Y", "Through the last light, Y is Yellowfin Tuna | yellow-tinted fins flash fast through blue."),
            ("Z", "Under that fading blue, Z meets Zooplankton | tiny drifters ride wherever moving water flows."),
        ),
        "style_blueprint": "Warm intimate adult lead with clear consonants, minimal vibrato and calm breath. Floating 6/8 preschool travel-pop at 86 BPM with kalimba, soft marimba, brushed percussion, ukulele and light bass; narrow lyrical contour and stable major center. Open by dropping directly into a morning-on-the-water scene. Round 1 uses linked poetic rhyme: when natural, the final image or sound of one letter line is echoed inside the next line before that next line travels onward to a new image. This borrows the linking principle found in chain verse and lục-bát-like rhyme connection, but do not force English into six/eight-syllable counts or repeat words unnaturally. Let long lines breathe across two bars and keep the target word clear near the front. Chorus opens the arrangement into a wide but simple sailing hook. Round 2 removes pads and becomes a spacious cue-gap-answer pattern with roughly two quiet beats for recall. Keep target words dry and exposed; no backing vocal or percussion attack on their first syllable. End by returning to the sailing hook over a soft two-chord cadence.",
    },
    "0005": {
        "authorial_intent": "Make every letter feel like field evidence in a young explorer's notebook: notice one telling shape, motion, texture, sound, or function and let that clue earn the line.",
        "lyric_identity": "Clipped observation language, sensory evidence, and notebook-like clue phrases. Internal rhyme/alliteration should sound like quick pencil marks—drop/stop, slip/slide, wing/wind—not ornamental nursery filler.",
        "image_motifs": ("open notebook", "tracks and marks", "shape clues", "motion clues", "binocular-distance clues"),
        "semantic_arc": ("open the field notebook", "collect motion and shoreline evidence", "compare shapes/shelters/functions", "close the notebook with a coast full of remembered clues"),
        "forbidden_generic_language": ("fun to see", "shining bright", "on our trail", "without fail"),
        "intro_lines": ("Notebook open. Eyes up. Listen close.", "Every letter leaves a different kind of clue."),
        "hook_lines": ("Look twice, listen once—what do you know?", "Find the clue, then let the letter show!"),
        "outro_lines": ("Notebook shut; one last gull crosses through.", "A to Z—our coast is full of clues."),
        "rhyme_engine": "internal-rhyme-alliterative-clue-cadence",
        "round1_grammar": "hand-written field-guide observations driven by internal rhyme, alliteration, consonance, and occasional delayed end-rhyme rather than regular couplets",
        "round1_overrides": (
            ("A", "First notebook mark—A: Anchor! Drop, stop | heavy hold helps the boat stay in place."),
            ("B", "B — Buoy. Bobbing marker on the water, helping boats recognize a place."),
            ("C", "What clue starts at C? Crab! Side-step, sand-scratch | little tracks stitch the shore."),
            ("D", "Along the coast, D finds Dolphin—breath at the surface, silver arc, splash, and gone."),
            ("E", "E ... E ... Eel! Slip, slide | winding body threads between reef rocks."),
            ("F", "Spot F: Fish! Fin flick, gill pull | it steers and breathes beneath the water."),
            ("G", "G — Gull. Wing tilt, wind lift | it rides the air above the shore."),
            ("H", "Sound clue H: Harbor! Surf grows soft; sheltered water lets the boats rest."),
            ("I", "Along the coast, I finds Island. Ring of sea | land sits with water all around."),
            ("J", "J ... J ... Jetty! Jetty juts from shore, a straight path reaching over water."),
            ("K", "Spot K: Kayak! Paddle pair, narrow hull | left-right strokes send it on."),
            ("L", "L — Lagoon. Shallow and sheltered, its water lies apart from the open sea."),
            ("M", "What clue starts at M? Manatee! Slow roll | paddle-like flippers move through warm water."),
            ("N", "Spiral clue N: Nautilus. Coil after coil, chambers hide inside its shell."),
            ("O", "O ... O ... Oyster! Rough shell, soft center | two hard halves close around the animal."),
            ("P", "Shape clue P: Pufferfish! Under threat its body can look rounder—a sudden change in shape."),
            ("Q", "Q — Queen Angelfish. Yellow-blue blaze | bright reef colors turn through the water."),
            ("R", "What clue starts at R? Reef! Crack, crevice, coral cover—many small hiding places."),
            ("S", "Along the coast, S finds Seal. Flipper sweep | it swims, then rests on rock or shore."),
            ("T", "T ... T ... Turtle! Shell steady on its back; measured strokes carry it through the sea."),
            ("U", "Spot U: Undersea Cave! Dark under wave | rocky hollow below the ocean surface."),
            ("V", "Travel clue V: Vessel. A boat or ship built to carry people or things over water."),
            ("W", "What clue starts at W? Wave! Rise, roll, fall | surface water lifts and settles again."),
            ("X", "Light-through clue X: X-ray Tetra. Its translucent body lets us partly see through."),
            ("Y", "Y ... Y ... Yellowfin Tuna! Flash and pass | yellow-tinted fins cut quickly through blue."),
            ("Z", "Spot Z: Zooplankton! Tiny drifters travel wherever the moving current carries them."),
        ),
        "style_blueprint": "Curious clear adult lead, crisp diction, lightly animated but never breathless. Bouncy 4/4 preschool explorer-pop at 94 BPM with acoustic guitar, claves, marimba, soft bass and hand claps; compact stepwise melody. Open with a movement-based field-guide pickup, not a spoken welcome. Round 1 should sound like an observant explorer taking quick notes: use internal rhyme, alliteration, consonance, repeated action sounds, and occasional delayed end-rhyme, but do not make every line close as a couplet. Let phrases such as drop/stop, slip/slide, wing/wind, crack/crevice work rhythmically inside the line while the semantic image remains primary. Alternate punchy clue lines with longer natural-history snapshots. Chorus becomes a clap-ready explorer badge hook. Round 2 uses a short one-beat recall gap, then object-specific gestures; muted guitar and sparse marimba leave target words uncovered. No dense choir, fast patter or vocal runs. End with two clave ticks, one final hook, then a clean stop.",
    },
    "0006": {
        "authorial_intent": "Use one small ripple as the memory metaphor for the whole alphabet: it opens, travels, widens, meets living things and river shapes, then softens without really stopping.",
        "lyric_identity": "Flow-language and recurring circular motion bind the lyric: ring, ripple, bend, drift, bank, current, settle. Rhyme comes in short current-clusters and then releases into plain observation like water leaving a pool.",
        "image_motifs": ("one widening ripple", "damp bank", "current bends", "floating reflections", "soft settling rings"),
        "semantic_arc": ("first ring opens", "current carries the song outward", "banks and living things interrupt/redirect it", "last ring softens and the water continues"),
        "forbidden_generic_language": ("fun to see", "by the riverside", "come sing with me", "all day"),
        "intro_lines": ("Plip—one ring opens on the pond.", "Follow that ripple; each letter moves it on."),
        "hook_lines": ("One little ripple—circle and flow.", "Letter by letter, follow where it goes."),
        "outro_lines": ("The last ring softens by the shore.", "The river keeps the words, then moves once more."),
        "rhyme_engine": "three-line-current-clusters",
        "round1_grammar": "hand-written river-folk verses where two or three neighboring targets can share one rhyme or vowel current before a plain factual line releases the pattern",
        "round1_overrides": (
            ("A", "First ring reaches A — Alder. By the flow | roots hold damp banks as branches grow."),
            ("B", "B is for Boat. Row, then float | carrying people or things along the river."),
            ("C", "Catfish — remember C. Down below | whisker-like barbels wave around its mouth as it goes."),
            ("D", "What drifts in with D? Dam! A wall holds water back and changes how the current moves."),
            ("E", "The ripple slips toward E — Eel. Easy glide | winding body bends from side to side."),
            ("F", "F — Frog. Bankside hop | strong back legs kick for swimming, then stop."),
            ("G", "G is for Green Algae. Green sheen | soft patches spread in water and over wet surfaces."),
            ("H", "Heron — remember H. Long legs pause in shallow water; stillness comes before a step."),
            ("I", "Farther along, what drifts in with I? Iris! Wet-ground bright | flower opens into morning light."),
            ("J", "By the water, J meets June Bug. Warm-evening flight | shiny beetle circles into sight."),
            ("K", "K — Kingfisher. Flash in sight | dives for a fish, then climbs back to height."),
            ("L", "L is for Lily Pad. Flat green leaf floats like a plate on quiet water."),
            ("M", "At the next bank, M is Muskrat. Body low | paddles beside wet grass where the current goes."),
            ("N", "What drifts in with N? Nest! Twigs held tight | a bird-built place for eggs or chicks inside."),
            ("O", "By the water, O meets Otter. Side to side | float, turn, tumble, dive, then glide."),
            ("P", "P — Pond. A small body of still water gives plants and animals a place to live."),
            ("Q", "Q is for Quillwort. Quillwort low | spiky-looking leaves in wet places grow."),
            ("R", "Reed — remember R. Tall stems show | straight at the water's edge, swaying slow."),
            ("S", "What drifts in with S? Salamander! Long and low | four small legs help the moist-skinned body go."),
            ("T", "By the water, T meets Trout. Cool-water fish flicks its tail against the current."),
            ("U", "U — Underwater Plant. Sway this way | submerged leaves bend with moving water all day."),
            ("V", "V is for Vallisneria. Long ribbon-like leaves grow underwater in freshwater."),
            ("W", "Then the current drops at W — Waterfall. Rush and spray | water falls from higher rock and breaks into mist."),
            ("X", "What drifts in with X? X-ray Tetra! Small translucent fish with a partly see-through body."),
            ("Y", "By the water, Y meets Yellow Water Lily. Yellow in light | broad leaves float, flower bright."),
            ("Z", "Z — Zooplankton. Tiny and light | little drifters ride the current day and night."),
        ),
        "style_blueprint": "Clear gentle adult lead with close dry diction and stable vowels. Relaxed 6/8 river-folk at 84 BPM with acoustic guitar, pizzicato strings, soft woodblock, glockenspiel and light bass; narrow rising-and-falling contour. Open with quiet ripple onomatopoeia over two sparse bars. Round 1 should feel as if rhyme itself is carried by the current: allow two or three neighboring target lines to share one end-sound or vowel family, then release the pattern with a plain vivid factual line before beginning a new current. This is intentionally not a sequence of 13 couplets. Use internal phrase breaks where a natural mini-rhyme helps the flow, and keep difficult plant names almost speech-like. Chorus adds a small glockenspiel shimmer and an easy flowing refrain. Round 2 drops to woodblock pulse plus voice, leaving about two supportive beats after each letter cue before confirmation. Thin every instrument at target-word onset, then answer with pizzicato. End by letting the ripple motif settle into one soft final chord.",
    },
    "0007": {
        "authorial_intent": "Turn the alphabet into a paddle route where every bend creates anticipation: pause, look, name what appears, then move on. The recurring pleasure is discovery around the next turn.",
        "lyric_identity": "Route language—bend, reach, bank, channel, paddle, pause, again—plus compact answer-rhymes that behave like instrumental replies. The narrator is a calm guide in a moving boat, not a static picture-book host.",
        "image_motifs": ("paddle strokes", "river bends", "quiet reaches", "bank-side pauses", "new view around a turn"),
        "semantic_arc": ("launch from the first bank", "move through bends and shallow reaches", "cross varied waterway habitats", "paddles rest after the final turn"),
        "forbidden_generic_language": ("fun to see", "come sing with me", "along the way", "say it true"),
        "intro_lines": ("Paddle left. Pause. What's round the bend?", "A new letter waits where the water turns."),
        "hook_lines": ("Paddle, pause—what's round the bend?", "Say the word, then paddle again."),
        "outro_lines": ("Paddles rest; the shoreline stays.", "A to Z rode all the waterways."),
        "rhyme_engine": "bluegrass-answer-rhyme-irregular",
        "round1_grammar": "hand-written paddle-song clues using short internal answer-rhymes, slant rhyme, and irregular open lines; rare names deliberately remain unrhymed",
        "round1_overrides": (
            ("A", "Launch at A: Alligator! Bank-side rest | then a quiet glide comes next."),
            ("B", "B ... B ... Beaver! Branch by branch, flat tail paddling as sharp teeth cut wood."),
            ("C", "Catfish — that's C. Whisker-like barbels feel around its mouth as it swims."),
            ("D", "D — Dam. A wall holds water back and changes the current's path."),
            ("E", "First bend—what's waiting at E? Egret! Stand and scan | long legs pause in shallow water."),
            ("F", "At the bank, F: Fishing Rod! Long pole, fishing line, and reel—three parts easy to spot."),
            ("G", "G ... G ... Goose! Glide wide | paddles on water, then walks grassy banks."),
            ("H", "Heron — that's H. Hold still | then one long-legged step through the shallows."),
            ("I", "I — Insect. Six in line | six legs, three main body parts in the design."),
            ("J", "What's waiting at J? Jetty! A structure reaches from the shore out over water."),
            ("K", "Next reach, K: Kayak! On the track | double paddle forward and back."),
            ("L", "L ... L ... Lake! A large body of water held inside surrounding land."),
            ("M", "Minnow — that's M. Quick little flick | small fish darts through shallow water."),
            ("N", "N — Nest. Rest in the nest | bird-built place for eggs and chicks."),
            ("O", "What's waiting at O? Oar! Row as we go | long blade pulls water to move a boat."),
            ("P", "Paddle to P: Pike! Long freshwater fish waiting still among water plants."),
            ("Q", "Q ... Q ... Quillwort! Spiky little leaves make this wet-place plant easy to spot."),
            ("R", "Around another bend, R is River. Bend after bend | water runs downhill through a channel."),
            ("S", "S — Salamander. Long body, moist skin, four legs, and a tail behind."),
            ("T", "What's waiting at T? Trout! Tail flick | cool-water fish pushes against the current."),
            ("U", "Paddle to U: Umbrella Sedge! Green rays spread | leaf-like spokes above the stem."),
            ("V", "V ... V ... Valley! Low between hills, often giving running water a way through."),
            ("W", "Waterfall — that's W. High to low | rushing water drops from rock below."),
            ("X", "X — Xiphophorus. A group of small freshwater fish including swordtails and platies."),
            ("Y", "Near the last turn, what's waiting at Y? Yellow Water Lily! Yellow in light | broad leaves float, flower bright."),
            ("Z", "Paddle to Z: Zooplankton! Tiny drifters move wherever the water carries them."),
        ),
        "style_blueprint": "Friendly adult lead with clean en-US diction and a tiny group echo only in the hook. Light 4/4 acoustic bluegrass-lite hop at 90 BPM: restrained banjo plucks, upright bass, hand claps, soft woodblock and brief whistle answers; no virtuoso picking or exaggerated twang. Open with two paddle motions as rhythmic pickup. Round 1 uses irregular bluegrass answer-rhyme: some lines contain a short semantic rhyme after the phrase break, some neighboring lines share a slant rhyme, and some facts deliberately land without rhyme. Do not regularize this into couplets. Let punchy phrases such as rest/next, whisker/swish, shore/more, track/back or light/bright act like little banjo answers. Xiphophorus and other difficult names stay near speech rhythm with no rhyme pressure. Chorus becomes a paddle-and-answer refrain. Round 2 leaves one clear beat of silence after each cue; hard words slow to near speech rhythm. Keep whistle and claps away from target-word attacks. End with the paddle pulse stopping under a final sung hook.",
    },
    "0008": {
        "authorial_intent": "Compose A to Z as a freshwater movement score: each plant, animal, or object contributes a visible motion, and the child learns by feeling a sequence of sway, paddle, hop, flash, float, and glide.",
        "lyric_identity": "Motion verbs are the melody's vocabulary. Lines should show how different bodies move through the same water world, using clusters of related action-sounds rather than generic location description.",
        "image_motifs": ("swaying stems", "paddle strokes", "tail flicks", "quick flashes", "floating leaves"),
        "semantic_arc": ("water begins to move", "creatures answer with different motions", "motion grows more varied across bank and channel", "one last tail flick and leaf sway settle the song"),
        "forbidden_generic_language": ("fun to see", "in our freshwater world", "come swim with me", "today"),
        "intro_lines": ("Sway—paddle—hop—glide.", "Watch the water teach each body how to move."),
        "hook_lines": ("Sway, paddle, hop, then glide!", "Freshwater letters move side by side."),
        "outro_lines": ("One last tail flick, one leaf sway.", "A to Z has moved all day."),
        "rhyme_engine": "motion-cluster-rhyme",
        "round1_grammar": "hand-written freshwater snapshots where rhyme clusters are organized around motion families such as sway, glide, hop, paddle, flow, and flash",
        "round1_overrides": (
            ("A", "A finds Alder. Bank-side sway | roots stay damp while branches move with the day."),
            ("B", "B — Beaver! Flat tail paddles; branches travel away."),
            ("C", "What moves with C? Canoe! Paddle left, paddle right; narrow hull slides on its way."),
            ("D", "Look at D: Duck. Webbed feet paddle while the broad bill dips through spray."),
            ("E", "E is for Eel. Easy glide | long winding body bends from side to side."),
            ("F", "F finds Frog. Waterside hop | strong back legs kick to swim, then stop."),
            ("G", "G — Green Algae! Soft green patches spread and shift where water moves over wet surfaces."),
            ("H", "What moves with H? Hydrilla! Leafy stems sway underwater with the current."),
            ("I", "Look at I: Insect. Six-leg line | three main body parts make the design."),
            ("J", "J is for Jetty. Shore, then water | a straight structure reaches farther out."),
            ("K", "K finds Kingfisher. Flash and splash | perch, quick dive, then back in a dash."),
            ("L", "L — Lake. Wide water holds every little ripple inside a boundary of land."),
            ("M", "What moves with M? Muskrat! Body low | paddles beside wet banks where waters flow."),
            ("N", "Look at N: Newt. Four legs walk low | long tail follows as the little amphibian goes."),
            ("O", "O is for Oar. Row, row | long blade pulls water and helps the boat go."),
            ("P", "P finds Pond. Small and still, it holds a whole home where freshwater plants and animals can move."),
            ("Q", "Q — Quail! Quick ground steps | small bird walks and pecks."),
            ("R", "What moves with R? River! Flow as we go | water follows a downhill channel."),
            ("S", "Look at S: Salamander. Long and low | four legs and a tail help the moist-skinned body go."),
            ("T", "T is for Tadpole. Wiggle, little tail | water-stage youngster grows legs later on."),
            ("U", "U finds Umbrella Sedge. Green rays fan and spread | leaf-like spokes above the stem."),
            ("V", "V — Valley. Low where waters flow | land dips between hills or mountains."),
            ("W", "What moves with W? Water Lily! Round leaves float | one flower lifts above the water."),
            ("X", "Look at X: Xiphophorus. Small freshwater fish group including swordtails and platies."),
            ("Y", "Y is for Yellow Perch. Bars in rows | yellow sides flash and off it goes."),
            ("Z", "Z finds Zebra Danio. Stripes in a row | small freshwater fish darts to and fro."),
        ),
        "style_blueprint": "Bright clear adult female lead, friendly nature-host delivery, crisp consonants and no baby voice. Acoustic 4/4 preschool bounce at 91 BPM with marimba, ukulele, finger snaps, soft kick and bass; narrow stepwise melody. Open with a quick montage of visible motions rather than saying the theme name generically. Round 1 organizes rhyme by movement: three or four neighboring targets may share a motion-sound family such as sway/away/way/spray, glide/side, hop/stop, low/flow/go, or rows/go/fro. These clusters should feel like bodies and water moving together, not like arbitrary end-word matching. Break the rhyme whenever a rare plant or taxonomic word needs clean speech. Chorus lifts into a swim-hop-glide participation hook. Round 2 is cue-gap-confirm-action; drop the soft kick at every target-word onset and let finger taps answer afterward. Hydrilla remains visual recognition only. End with the motion hook once and a clean marimba button.",
    },
    "0009": {
        "authorial_intent": "Create a quiet wetland listening poem where stillness matters as much as motion: each letter briefly disturbs reflection, reed, water, or air, then the scene settles again.",
        "lyric_identity": "Hushed sensory language, reflected light, tiny sounds, and sparse verbs. Flash, dip, ring, lean, drift, and stillness recur; rhyme is occasional so silence and image can carry the song.",
        "image_motifs": ("reed shadows", "water reflections", "single ripples", "brief wing flashes", "returning stillness"),
        "semantic_arc": ("hushed surface and first movement", "small flashes disturb the calm", "growth/change becomes noticeable", "motion thins until the wetland rests again"),
        "forbidden_generic_language": ("fun to see", "bright and clear", "come sing with me", "today"),
        "intro_lines": ("Hush. One drop. A wing crosses the reeds.", "Morning opens slowly, one letter at a time."),
        "hook_lines": ("Hush and listen—water, wing.", "Wetland letters softly sing."),
        "outro_lines": ("Light goes low; the reeds grow still.", "One last ripple, then the wetland sleeps."),
        "rhyme_engine": "sparse-assonance-delayed-closure",
        "round1_grammar": "hand-written wetland dawn verse with spacious sensory images, sparse internal rhyme, assonance/consonance, and occasional delayed closure; silence is part of the prosody",
        "round1_overrides": (
            ("A", "Alligator — our A. Still by the bank, then one quiet glide through brown-green water."),
            ("B", "Near the reeds, B meets Beaver. Flat tail cuts a small V through the reflected sky."),
            ("C", "C — Canoe. One paddle dips; silver rings widen behind the blade, then fade."),
            ("D", "What belongs to D? Duck! Dip, then drip | broad bill lowers while webbed feet paddle."),
            ("E", "E ... E ... Egret. Long legs hold still; the whole shallow world keeps moving around them."),
            ("F", "Fishing Rod — our F. Long pole, line, and reel make a quiet silhouette beside the water."),
            ("G", "In reflected water, G meets Green Algae. Green sheen | soft patches tint water and wet surfaces."),
            ("H", "H — Hydrilla. Leafy stems stay below the surface and move with the current."),
            ("I", "What belongs to I? Iris! Morning light | bright flower opens near wet ground."),
            ("J", "J ... J ... June Bug. A shiny beetle lifts into the warm evening air."),
            ("K", "Kingfisher — our K. One flash breaks the reflection | quick dive for a fish, then stillness on a perch."),
            ("L", "On the quiet surface, L meets Lily Pad. Flat green leaf rests on the water like a plate."),
            ("M", "M — Minnow. Quick flick | small fish darts through the shallow edge."),
            ("N", "What belongs to N? Newt! Four legs, long tail, small amphibian moving between damp land and water."),
            ("O", "O ... O ... Otter. Float, turn, dive; the smooth body writes a line on the surface, then erases it."),
            ("P", "Pond — our P. Still water holds reflections, plants, insects, and animal life."),
            ("Q", "Under low cover, Q meets Quail. Peck, step | small ground bird moving through the wetland edge."),
            ("R", "R — Reed. Tall stem leans, straightens, then leans again; its reflection follows below."),
            ("S", "What belongs to S? Swan! Long neck curves while the body glides over calm water."),
            ("T", "T ... T ... Tadpole. Tail first, legs later—the little swimmer is changing as it grows."),
            ("U", "Umbrella Sedge — our U. Green rays spread from the top of the stem like a small open umbrella."),
            ("V", "Below the surface, V meets Vallisneria. Long ribbon-like leaves grow underwater in freshwater."),
            ("W", "W — Waterfall. White fall | water drops past dark rock and breaks into spray."),
            ("X", "What belongs to X? Xiphophorus! A freshwater fish group that includes swordtails and platies."),
            ("Y", "Y ... Y ... Yellow Water Lily! Yellow in light | broad leaves float, flower bright."),
            ("Z", "Zooplankton — our Z. Tiny drifters move with the water, almost too small to notice one by one."),
        ),
        "style_blueprint": "Calm close adult lead with crisp diction, natural breath and minimal vibrato. Slow 3/4 preschool nature sway at 82 BPM with kalimba, soft shaker, airy pad used sparingly and gentle bass; narrow mostly stepwise melody. Open with a tiny wetland sound-image—drip, hush, distant wing motion—then enter the first clue. Round 1 should feel closer to free verse than to a nursery rhyme: use silence, sensory images, assonance, consonance, and only occasional internal rhyme or delayed closure. A line may answer a sound two or three lines later; many lines should not rhyme at all. Do not add filler merely to close a rhyme. Rare names such as Vallisneria and Xiphophorus are intentionally plain and speech-clear. Chorus stays calm and memorable instead of becoming hyperactive. Round 2 becomes nearly percussion-free with about two beats of recall space before each answer. Keep all target words dry and forward, with no harmony on their attack. End by thinning to solo kalimba and one soft final refrain line.",
    },
    "0010": {
        "authorial_intent": "Make the alphabet a real riverbank walk: each letter is something the child notices by taking another step, and the repeated bend-by-bend motion turns observation into memory.",
        "lyric_identity": "Walking verbs and trail geography lead—step, bend, bank, pass, pause, follow, cross, look back. Ballad rhyme appears mainly as a walking cadence, while concrete observations keep the narrator grounded in the path.",
        "image_motifs": ("footsteps", "river bends", "bank-side flowers", "small moving creatures", "path beside the stream"),
        "semantic_arc": ("first steps beside the stream", "near-bank discoveries", "longer look across water and valley", "steps slow and the walk becomes a remembered A-to-Z trail"),
        "forbidden_generic_language": ("fun to see", "tell the tale", "come with me", "nice and neat"),
        "intro_lines": ("Step, step—the path keeps close to the stream.", "Every bend leaves one small thing to notice."),
        "hook_lines": ("Step by step, bend by bend.", "Find a word, then walk again."),
        "outro_lines": ("Steps slow down beside the stream.", "Every letter lives in something we have seen."),
        "rhyme_engine": "walking-ballad-abcb-flexible",
        "round1_grammar": "hand-written riverbank ballad quatrains; second and fourth lines usually answer in rhyme or near-rhyme while first and third lines carry free narrative, with form broken whenever fact or pronunciation needs room",
        "round1_overrides": (
            ("A", "First step finds A ... A ... Alligator! Resting by the bank, then gliding quietly into water."),
            ("B", "Step to B: Boat. Boat afloat | carrying people or things down the stream."),
            ("C", "C — Canoe. Narrow hull moves with a paddle dipped left, then right."),
            ("D", "Duck — that's D. Webbed feet paddle while the broad bill dips where water gleams."),
            ("E", "What did E find? Eel! Long winding body slips through water in muscular curves."),
            ("F", "At a muddy turn, F ... F ... Frog! From log to bog | strong back legs hop and swim at waterside."),
            ("G", "Step to G: Goose. It paddles on water and walks the grassy bank."),
            ("H", "H — Heron. Long legs hold still, then take one careful stride."),
            ("I", "Iris — that's I. Bright flower opens near wet ground when morning warms the bank."),
            ("J", "Later on the path, what did J find? June Bug! Evening light | shiny beetle lifts into flight."),
            ("K", "K ... K ... Kingfisher! Perched near water, then one quick dive after a fish."),
            ("L", "Step to L: Lake. Wide water lies within surrounding land, open in sight."),
            ("M", "M — Minnow. Flick, quick | small fish darts through shallow water."),
            ("N", "Newt — that's N. Four legs in view | one long tail follows behind it, too."),
            ("O", "What did O find? Oar! Long blade pulls through water to help move a boat."),
            ("P", "P ... P ... Pike! Long freshwater fish waits among water plants before it moves into view."),
            ("Q", "Step to Q: Quail. Small ground bird walks, pauses, and pecks along the bank."),
            ("R", "R — River. Our path follows as water descends | winding downhill through its channel and around the bend."),
            ("S", "Swan — that's S. Long curved neck rises above a body gliding over water."),
            ("T", "What did T find? Trout! Cool-water fish flicks its tail, holding against the current around the bend."),
            ("U", "U ... U ... Underwater Plant! Leaves grow below the surface and bend with moving water."),
            ("V", "Step to V: Valley. Low below | land lies between hills where waters flow."),
            ("W", "W — Water Lily. Round leaves float while the flower stands above the surface."),
            ("X", "X-ray Tetra — that's X. Partly see-through body lets some tiny bones show."),
            ("Y", "Near the last bend, what did Y find? Yellow Water Lily! Yellow in light | broad leaves float, flower bright."),
            ("Z", "Z ... Z ... Zooplankton! Tiny drifters ride the moving water by day and night."),
        ),
        "style_blueprint": "Bright clear adult lead with friendly walking-story delivery and crisp dry diction. Easy 4/4 campfire-folk preschool pulse at 89 BPM with acoustic guitar, light footstep stomps, shaker, glockenspiel and soft bass; narrow melody with ballad-like cadences. Open with two audible walking steps and a stream-side discovery line. Round 1 uses a flexible ABCB walking-ballad idea: in many four-letter groups the second and fourth lines rhyme or near-rhyme while the first and third remain free narrative, but never force the scheme when a scientific fact or rare word needs cleaner language. Let stream/gleam, side/stride, light/sight, low/show and bright/night provide natural closures; elsewhere accept slant rhyme or no rhyme. Chorus uses the stream/seen rhyme as a compact step-and-name hook. Round 2 strips to soft stomps and bass, leaves one real beat after the letter cue, then confirms the object and one congruent gesture. Mute stomps and backing vocals on target-word attacks; glockenspiel answers afterward. End by slowing the steps and resolving on the final hook without extra spoken praise.",
    },
}
