from __future__ import annotations

"""Authorial-identity deep polish for songs 0016-0020.

V4 remains the source of locked mappings and object/action craft. This layer
turns the five garden songs into distinct authored worlds with hand-written
Round-1 lyrics, separate rhyme behaviors, narrative arcs and performance plans.
"""


GOLD_V5_16_20_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0016": {
        "authorial_intent": "Let the child see a garden as a living architecture: hidden roots and soil lead upward into stems, leaves, blooms, fruit and finally a whole layered bed.",
        "lyric_identity": "A close observer keeps moving the eye down, through, around and upward; root/shoot/leaf/bloom language links the alphabet without pretending every mapped object itself grows.",
        "image_motifs": ("dark soil below", "root and shoot", "climbing stems", "opening leaves and flowers", "water returning to the bed"),
        "semantic_arc": ("begin below the soil line", "rise through stems and climbing growth", "open into flower and food shapes", "step back and see the whole garden fed by water and soil"),
        "forbidden_generic_language": ("garden words sprout up with me", "everything grows", "fun to see", "come sing with me"),
        "rhyme_engine": "root-to-shoot-linked-chain",
        "chorus_rhyme_engine": "below-grow-linked-rhyme",
        "point_of_view": "a child tracing the hidden-to-visible structure of a garden from soil and roots up into leaves, flowers and fruit",
        "chorus_function": "return the ear to the below-to-above growth path before the next garden layer",
        "groove_meter": "gentle 4/4 growth pulse with rising two-bar phrases",
        "round1_grammar": "hand-written vertical garden imagery; use below/above, root/shoot, curl/climb/open and water/soil links, while tools and helpers keep their real non-growing functions",
        "round2_grammar": "growth-position cue -> recall beat -> target -> safe shape, grow, open, pour or point gesture",
        "intro_lines": (
            "Under the soil, a root reaches where we cannot see.",
            "Above it, one green shape begins the garden map.",
        ),
        "hook_lines": (
            "Down below, up we grow—A-B-C!",
            "Root to leaf, the garden opens for me!",
        ),
        "outro_lines": (
            "Water sinks; evening leaves fold slow.",
            "A to Z mapped the garden from below to bloom.",
        ),
        "interlude_lines": ("Roots stay hidden for one quiet beat—can the garden words rise back up?",),
        "round1_patterns": (),
        "round2_patterns": (
            "Garden map {letter} ... {object}! {action}",
            "Trace to {letter} ... {object}! {action}",
            "Which layer, {letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "A — Apple Tree! Roots hold below | woody branches lift leaves, blossoms, and fruit into the light."),
            ("B", "B ... B ... Bean! Seed wakes low, stem climbs high | pods later line up beans inside."),
            ("C", "C is for Carrot. Green above, orange below | the thick root stores food under the soil."),
            ("D", "D? Dirt! Crumb, grain, dark mix | garden soil gives roots room to spread and take in water."),
            ("E", "Up through E — Eggplant. Broad leaves spread | glossy fruit hangs beneath the green."),
            ("F", "F is Flower. Bud to bloom | petals open around the flower's center."),
            ("G", "G ... G ... Garden Gate! It does not grow; it swings | one clear doorway into the beds."),
            ("H", "H? Hoe! Adult hands may loosen or shape soil with it | children learn the tool from a safe distance."),
            ("I", "I is Ivy. Curl and climb | trailing stems hold leaves as they reach along a support."),
            ("J", "J ... J ... Jug! Handle steady, narrow mouth | a pour can carry water where roots need it."),
            ("K", "K? Kneeling Pad! Soft under knees | a cushion for low garden work, not part of the plant."),
            ("L", "L — Ladybug! Tiny beetle on a leaf | six legs crawl beneath spotted wing covers."),
            ("M", "M is Mulch. Layer on soil | it helps moisture stay and makes weed growth harder."),
            ("N", "N ... N ... Nasturtium! Round leaves spread low | bright flowers lift above them."),
            ("O", "O? Onion! Green leaves rise while layer wraps layer | the bulb thickens underground."),
            ("P", "P — Pea! Tendril, stem, pod | round peas wait in a row inside."),
            ("Q", "At the bed edge, Q is Quince. Firm yellow fruit grows on a shrub or small tree."),
            ("R", "R ... R ... Rose! Woody stem, prickles, folded petals | the bloom opens layer by layer."),
            ("S", "S? Sunflower! Root down, stem tall | a broad flower head rises toward the light."),
            ("T", "T is Tomato. Branching green stems | round fruit gathers weight beneath the leaves."),
            ("U", "U ... U ... Umbrella Plant! Leaf clusters fan overhead | little green umbrellas above the pot."),
            ("V", "V? Vegetable Bed! Soil held ready in one patch | roots, stems, leaves, and food plants share the space."),
            ("W", "W — Watering Can! Spout tips low | a gentle shower returns water to the soil below."),
            ("X", "By the path, X is Xylem—tiny plant tubes carry water upward through the stem."),
            ("Y", "Y ... Y ... Yarrow! Flat clusters gather many tiny flowers | light heads above divided leaves."),
            ("Z", "Z? Zinnia! Layered petals ring the center | one last bloom opens at the top of our garden map."),
        ),
        "style_blueprint": "Clear warm adult lead, dry diction and natural child-friendly phrasing. Light garden-pop in 4/4 at 87 BPM with ukulele, soft marimba, brushed shaker and tiny plucked-string answers. The arranging idea is vertical growth: begin low and sparse, let phrases gently rise through roots, stems and leaves, then open harmonically around flowers and fruit. Honor the hand-written | phraselets and the below/above imagery; do not force equal line lengths or end-rhyme on every target. Round 1 should sound observational, not like a science list. Tools, gate and pad stay clearly non-growing helpers/objects, while Xylem is the plant-water pathway inside a stem. Chorus rises from low register toward a modest open top, then settles. Round 2 uses position/growth cues, one clear recall beat, target, and one safe gesture. Duck percussion on target onsets. No magical claim that every object sprouts, no rapid patter, no dense backing vocals. End by sinking arrangement energy back toward soil level.",
    },
    "0017": {
        "authorial_intent": "Turn the garden into a small pollinator journey: wing, scent, color and petal shape guide the ear from one close-up to the next.",
        "lyric_identity": "A child follows a bee-sized path through flowers and leafy corners; flutter verbs, color words, scent images and brief hovering pauses replace generic flower praise.",
        "image_motifs": ("bee wing blur", "petal landing pads", "purple and gold color patches", "scent drifting between blooms", "small life under leaves"),
        "semantic_arc": ("a first wing enters the garden", "the route moves through soil and leafy shelter", "color and scent become denser among flowers", "the final blooms settle after the small wings pass"),
        "forbidden_generic_language": ("buzz and bloom come sing with me", "flowers are pretty", "fun to see", "shining bright"),
        "rhyme_engine": "wing-petal-delayed-cross-rhyme",
        "chorus_rhyme_engine": "wing-sing-near-rhyme",
        "point_of_view": "a child tracking a tiny pollinator-scale route through petals, leaves, scent and soil",
        "chorus_function": "lift into a short fluttering refrain that reconnects wing movement with flower color",
        "groove_meter": "lilting 6/8 flutter with hover-and-land pauses",
        "round1_grammar": "hand-written pollinator-scale close-ups; alternate color, scent, texture, crawling and flying motion, allowing non-flower objects to remain practical scene anchors",
        "round2_grammar": "flutter/flower cue -> recall beat -> target -> one compact object-specific motion",
        "intro_lines": (
            "Bzz—one wing skims a petal, then hangs in the air.",
            "Follow the tiny flight; every color changes the path.",
        ),
        "hook_lines": (
            "Wing to bloom—A-B-C!",
            "Color follows where the little wings lead!",
        ),
        "outro_lines": (
            "The last small wing slips past the garden wall.",
            "A to Z leaves the garden colors resting after all.",
        ),
        "round1_patterns": (),
        "round2_patterns": (
            "Flutter to {letter} ... {object}! {action}",
            "Garden stop {letter} ... {object}! {action}",
            "Hover—{letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "A — Ant! Six tiny legs follow a scent trail between soil and flowers."),
            ("B", "B ... B ... Bee! Wing blur, flower pause | it visits blooms for nectar or pollen and can carry pollen onward."),
            ("C", "C? Carrot! Feathery leaves above | orange root stays hidden below the flight."),
            ("D", "D is Dirt. Dark crumbs under every color | soil holds the roots beneath our flight path."),
            ("E", "Low below, E — Earthworm. Bend and burrow | soft body tunnels through moist soil."),
            ("F", "F ... F ... Fern! Fronds uncurl in green spirals | a leafy roof close to the ground."),
            ("G", "G? Garden Hose! Long green curve across the path | water travels through it toward thirsty plants."),
            ("H", "H is Hoe. Long handle, flat working end | an adult soil tool we notice from a safe distance."),
            ("I", "Now color opens at I — Iris. Blade-like leaves below | showy petals lift into the flight line."),
            ("J", "J ... J ... Jasmine! Small pale flowers release a noticeable scent | a soft clue carried on the air."),
            ("K", "K? Kale! Crinkle, curl | broad leafy greens make a textured patch below the flight."),
            ("L", "L is Lavender. Purple spikes, narrow leaves | scent and color gather along each stem."),
            ("M", "M — Marigold! Gold-orange head | many petals pack color close together."),
            ("N", "N ... N ... Nasturtium! Round leaves like little plates | bright blooms sit between them."),
            ("O", "O? Orchid! Petals make a curious shape | one special lip sits near the flower's center."),
            ("P", "P is Pot. Soil held in a small round home | roots stay contained while flowers rise above."),
            ("Q", "At ground level, Q — Queen Butterfly. Orange-brown wings with dark veins pass between flowers."),
            ("R", "R ... R ... Radish! Leaves above, crisp root below | another color hiding under soil."),
            ("S", "S? Sunflower! Broad head high | yellow rays ring a center packed with many tiny flowers."),
            ("T", "T is Tomato. Green stems branch | round fruit hangs below small yellow blossoms."),
            ("U", "Rain comes; U — Umbrella! Wide canopy opens | drops slide away while the garden keeps its color."),
            ("V", "V ... V ... Violet! Small and low | purple, blue, white, or yellow blooms near the ground."),
            ("W", "W? Watering Can! Gentle pour, silver arc | the flight pauses while water darkens the soil."),
            ("X", "X is Xeranthemum. Papery flower heads | dry-looking petals keep a crisp texture."),
            ("Y", "Y ... Y ... Yarrow! Many tiny flowers gather in flat clusters | a whole landing field in miniature."),
            ("Z", "Z? Zinnia! Layer after layer of petals | the final bright stop before the small wings leave."),
        ),
        "style_blueprint": "Smiling but precise adult lead in a light 6/8 garden swing at 91 BPM. Use pizzicato strings, soft marimba, tiny shaker and occasional airy flute-like answers; musical gestures should flutter, hover and land without becoming busy. Open with one restrained bee-like vocal/instrumental buzz, then immediately move into clear singing—never loop realistic insect noise. Round 1 follows a pollinator-scale camera: soil close-ups, leaf shelter, scent, color, petal shape and short flight transitions. Use delayed cross-rhyme, assonance and repeated consonants across neighboring lines, but let botanical names stay speech-natural. Chorus should feel like a brief wing lift, not a generic sing-along. Round 2 uses a flutter or petal cue, one clean recall beat, target, gesture, then a tiny instrumental landing. No dense claps over words, no caricature buzzing through target syllables. End with instruments thinning as the imagined wing exits the garden.",
    },
    "0018": {
        "authorial_intent": "Make garden care feel like a sequence of small purposeful actions: prepare, feed, protect, water, wait and notice what the work makes possible.",
        "lyric_identity": "A child watches safe garden work from close range; tap, pat, scrape, spread, pour and pause form a restrained work rhythm while plants show the result of care.",
        "image_motifs": ("crumbly compost", "hands near soil", "kneeling pad", "trowel and safe tool distance", "water soaking in"),
        "semantic_arc": ("prepare the growing space", "notice plants and materials already there", "care for soil and roots", "finish by watering, waiting and seeing what the bed can support"),
        "forbidden_generic_language": ("tools and plants look carefully", "tap tap garden A-B-C", "every tool is for children", "fun to see"),
        "rhyme_engine": "work-rhythm-internal-percussion",
        "chorus_rhyme_engine": "tap-pat-open-cadence",
        "point_of_view": "a child observing and helping only with safe garden-care motions while adults handle tools that require distance",
        "chorus_function": "reset the care sequence—touch the rhythm, then leave space for growth rather than celebrating tools themselves",
        "groove_meter": "stop-go 4/4 care rhythm with muted tap-rest figures",
        "round1_grammar": "hand-written care sequence; practical verbs describe compost, mulch, containers, watering and safe tools, while flowers/food show the living result rather than being treated as equipment",
        "round2_grammar": "care cue -> recall beat -> target -> safe mime/point/shape action; adult-only tools remain observation-only",
        "intro_lines": (
            "Pat the soil flat; stop and listen to the little garden sounds.",
            "Pat, pour, wait—the garden asks for little things, one at a time.",
        ),
        "hook_lines": (
            "Pat, pour, pause—A-B-C!",
            "Care for the bed, then let the garden be.",
        ),
        "outro_lines": (
            "Last drop sinks; the tools and hands grow still.",
            "A to Z leaves a cared-for bed behind.",
        ),
        "interlude_lines": ("Hands off the tools for one beat—what garden-care words can we call back?",),
        "round1_patterns": (),
        "round2_patterns": (
            "Care clue {letter} ... {object}! {action}",
            "Pause at {letter} ... {object}! {action}",
            "Safe check, {letter}? ... {object}! {action}",
            "Show {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "A — Apple Tree! Trunk steady, branches spread | a living garden anchor that needs soil, water, and time."),
            ("B", "B ... B ... Bee! Small visitor at the flowers | wingbeats pass while garden work stays gentle."),
            ("C", "C? Compost! Crumble and mix | broken-down plant and food material can enrich garden soil."),
            ("D", "D is Daisy. Round center, petal ring | one simple bloom showing what a cared-for bed can hold."),
            ("E", "E — Eggplant! Broad leaves shade glossy fruit | a living crop beside the tools and paths."),
            ("F", "F ... F ... Flower! Bud opens into bloom | color arriving after soil, water, and time."),
            ("G", "G? Garden Gate! Swing, stop | a simple entrance that keeps the bed boundary clear."),
            ("H", "H is Herb. Pinch-shaped leaves, strong scent | a useful plant growing close to the kitchen path."),
            ("I", "I — Iris! Long blade-like leaves | showy petals rise from the cared-for soil."),
            ("J", "J ... J ... Jasmine! Small fragrant flowers | scent drifts while hands move to the next job."),
            ("K", "K? Kneeling Pad! Soft square under knees | cushioning low work near the bed."),
            ("L", "L is Lavender. Narrow leaves, purple spikes | a scented plant we leave rooted while we care around it."),
            ("M", "M — Mulch! Spread, rest | a cover over soil that helps hold moisture and reduce weeds."),
            ("N", "N ... N ... Nest! Twigs cup eggs or chicks | garden care also means leaving wildlife homes undisturbed."),
            ("O", "O? Orchid! Distinct flower shape | a delicate living thing to notice rather than handle roughly."),
            ("P", "P is Pea. Tendrils climb, pods fill | care gives the vine support, water, and time."),
            ("Q", "Q — Quince! Firm yellow fruit | a shrub or small tree can carry it after a season of growth."),
            ("R", "R ... R ... Radish! Leaves up, root down | loosened soil leaves room for the crisp root below."),
            ("S", "S? Sunflower! Tall stem holds a broad head | care below supports height above."),
            ("T", "T is Trowel. Small hand tool for moving soil | use it only with appropriate adult guidance."),
            ("U", "Rain check, U — Umbrella! Wide canopy keeps drops off a person | waiting beside the bed when showers come."),
            ("V", "V ... V ... Violet! Low bloom, soft color | a small plant tucked close to the soil."),
            ("W", "W? Worm! Wiggle, tunnel | the long soft body moves through moist soil under our work."),
            ("X", "X is Xeranthemum. Dry, papery-looking flower heads | a texture clue among softer petals."),
            ("Y", "Y — Yam! Thick tuber stores food underground | careful soil work happens above what we cannot see."),
            ("Z", "Z ... Z ... Zucchini! Broad leaves, yellow blossoms, long green squash | the bed answers care with a crop."),
        ),
        "style_blueprint": "Friendly clear adult lead at 94 BPM in a restrained stop-go acoustic 4/4. Use muted guitar, soft woodblock, claves, light bass and tiny shaker; percussion represents small care motions, never dangerous tool impact. Open with pat-rest-pour gestures rather than scrape-heavy sound effects. Round 1 should move through prepare, enrich, protect, support, water and wait, while clearly distinguishing plants from equipment. Internal percussion-rhyme can live inside phrases—pat/pause, spread/rest, wiggle/tunnel—but facts and safety beat rhyme. Adult-use tools such as Trowel are speech-clear and observation/supervision framed. Chorus drops into a simple pat-pour-pause motif. Round 2 leaves one beat of silence after each care cue and uses safe mimes or pointing; mute woodblock at target onset. No rapid DIY patter, no implication that children independently use sharp tools. End with one last water-drop gesture and a dry acoustic stop.",
    },
    "0019": {
        "authorial_intent": "Reveal the garden as a cycle rather than a straight list: old plant matter feeds soil, hidden life moves through it, seeds and roots become leaves, flowers and food, and the cycle can begin again.",
        "lyric_identity": "A curious child keeps asking where garden food and growth come from; circular language—down, up, back, again—connects soil life, seed, root, flower and harvest.",
        "image_motifs": ("compost returning to soil", "worm tunnels", "seed coat opening", "roots and pods underground/above", "food and flowers returning to the bed"),
        "semantic_arc": ("begin with what protects and feeds the soil", "follow hidden life and climbing growth", "reach roots, pods, fruit and seed", "return water and plant matter so another cycle can begin"),
        "forbidden_generic_language": ("garden foods grow happily", "tiny seed big A-B-C", "everything becomes a snack", "fun to see"),
        "rhyme_engine": "garden-cycle-return-rhyme",
        "chorus_rhyme_engine": "down-sun-run-chain",
        "point_of_view": "a child tracing how soil, tiny life, seed, water and plants connect in a repeating garden cycle",
        "chorus_function": "remind the listener that the story loops from below the soil up to light and back again",
        "groove_meter": "walking 4/4 circular folk groove with returning melodic tail",
        "round1_grammar": "hand-written cycle language; use down/up/back/again selectively, distinguish edible crops from flowers/tools/helpers, and connect each fact to soil, water, seed, root, leaf or return when truthful",
        "round2_grammar": "cycle cue -> recall beat -> target -> safe grow/trace/pour/pick/point gesture",
        "intro_lines": (
            "Yesterday's leaves sink into soil; tomorrow's green begins there.",
            "Down, up, around again—the garden keeps a quiet circle.",
        ),
        "hook_lines": (
            "Down in soil, up to sun—A-B-C!",
            "Round and round, the garden cycle runs.",
        ),
        "outro_lines": (
            "One seed waits where the last dry petals fall.",
            "A to Z turns back toward the soil again.",
        ),
        "round1_patterns": (),
        "round2_patterns": (
            "Cycle back to {letter} ... {object}! {action}",
            "Round to {letter} ... {object}! {action}",
            "What returns at {letter}? ... {object}! {action}",
            "Show {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "A — Apron! Before soil and water splash | cloth protects the front of our work clothes."),
            ("B", "B ... B ... Bee! Flower to flower | a small visitor can carry pollen as it feeds."),
            ("C", "C? Compost! Old plant and food material breaks down | nutrients return to the soil instead of ending the story."),
            ("D", "D is Daisy. Petals ring a center | flower today, seeds later in the plant's life cycle."),
            ("E", "Down below, E — Earthworm. Tunnel and turn | moist soil shifts around its long soft body."),
            ("F", "F ... F ... Fern! Curled young fronds unfurl | green returns from a tight spiral."),
            ("G", "G? Garden Gate! Open, close | a still boundary around a garden that keeps changing."),
            ("H", "H is Herb. Leaf becomes scent and flavor | some herbs are gathered from the garden for use."),
            ("I", "I — Ivy! Stem reaches, leaf follows | climbing growth keeps searching for light."),
            ("J", "J ... J ... Jug! Tip and pour | water leaves the container and returns to the soil."),
            ("K", "K? Kneeling Pad! Soft under knees | a helper while we look closely at what happens near the ground."),
            ("L", "L is Ladybug. Six little legs cross a leaf | a beetle moving through the living garden web."),
            ("M", "M — Marigold! Bud opens gold | flowers mark one bright stage before seeds and fading petals."),
            ("N", "N ... N ... Nest! Twigs hold new bird life | another cycle sharing the garden space."),
            ("O", "O? Onion! Layers build below | green leaves above feed a bulb thickening underground."),
            ("P", "P is Pea. Flower gives way to pod | round peas line up inside for the next part of the story."),
            ("Q", "Q — Quince! Firm yellow fruit | a shrub or small tree carries it after flower and growth."),
            ("R", "R ... R ... Rose! Petals open, petals fall | the woody plant keeps living after the bloom."),
            ("S", "S? Seed! Coat outside, tiny plant within | a small beginning waiting for the right conditions."),
            ("T", "T is Trowel. Soil-moving hand tool | use it only with appropriate adult guidance."),
            ("U", "U — Umbrella! Rain stays on the outside | while garden water keeps moving through its own cycle."),
            ("V", "V ... V ... Vegetable Bed! Many food plants share prepared soil | roots below, leaves above, harvest in between."),
            ("W", "W? Watering Can! Spout pours a gentle arc | water sinks down, then plants pull it up."),
            ("X", "X is Xeranthemum. Papery flower heads can dry and hold their shape | one bloom stage lingering after fresh petals."),
            ("Y", "Y — Yarrow! Flat clusters gather many tiny blooms | flowering now before the plant moves on."),
            ("Z", "Z ... Z ... Zinnia! Layered petals close our alphabet | another flower can make seeds and send the circle on."),
        ),
        "style_blueprint": "Warm conversational adult lead over a circular acoustic 4/4 at 89 BPM with ukulele, soft bass, marimba and shaker. Build a recurring melodic tail that gently returns to its starting note, making the garden-cycle idea audible without sounding repetitive. Round 1 moves conceptually through return-to-soil, hidden soil life, upward growth, flowers/food and back toward seed/water; the alphabet stays ordered but the imagery should feel cyclic. Use linked rhyme or repeated sound families across 2–3 lines, then release them. Do not imply every mapped item is edible, and keep tools/helpers outside the biological cycle when necessary. Chorus uses down/up motion in melody. Round 2 gives one supportive recall beat after a cycle cue, then target and safe gesture. Target onsets stay dry and unmasked. No sugary 'everything grows happily' tone; favor curiosity and cause-and-effect. End by resolving the recurring melodic tail back to its low starting note.",
    },
    "0020": {
        "authorial_intent": "Make an ordinary backyard feel enormous at child scale: one step outside reveals tiny worlds under leaves, beside pots, along a fence and close to the soil.",
        "lyric_identity": "A child narrator moves physically through a familiar backyard using near/beside/under/around language and close-up discoveries; wonder comes from proximity, not fantasy.",
        "image_motifs": ("back step", "fence edge", "pots and beds", "under-leaf close-ups", "late light near the back door"),
        "semantic_arc": ("step through the back door", "move from path and hose into beds and pots", "kneel closer for tiny flowers, seed and worm", "stand up and return to the door seeing the same yard differently"),
        "forbidden_generic_language": ("look and point along with me", "backyard green A-B-C", "magic garden", "fun to see"),
        "rhyme_engine": "backyard-closeup-free-rhyme",
        "chorus_rhyme_engine": "wide-outside-paired-rhyme",
        "point_of_view": "a child taking one slow loop from the back door around a small backyard garden and back again",
        "chorus_function": "zoom out briefly from close-up discoveries and remind the listener that the whole adventure is just outside",
        "groove_meter": "easygoing 4/4 backyard walk with occasional half-time close-ups",
        "round1_grammar": "hand-written spatial walk; use under/beside/near/behind/along and child-height viewpoints, with varied line lengths and sparse rhyme so the backyard feels observed rather than catalogued",
        "round2_grammar": "location cue -> two-beat recall space -> target -> small look/trace/shape gesture",
        "intro_lines": (
            "Back door clicks; one warm step lands beside the garden bed.",
            "Nothing is far away when you kneel down close.",
        ),
        "hook_lines": (
            "Backyard small, backyard wide—A-B-C!",
            "A whole little world is waiting just outside.",
        ),
        "outro_lines": (
            "Back at the step, soil dust rests on our shoes.",
            "A to Z made one small backyard feel wide.",
        ),
        "interlude_lines": ("Kneel down close for one quiet beat—what backyard clues come back?",),
        "round1_patterns": (),
        "round2_patterns": (
            "Backyard clue {letter} ... {object}! {action}",
            "Look close, {letter} ... {object}! {action}",
            "Close-up {letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "At the back step, A — Apron! Cloth front ready | a small shield for water and soil splashes."),
            ("B", "Beside the trellis, B ... B ... Bean! Tendrils reach | pods hide among the leaves."),
            ("C", "Close to the bed, C is Compost. Dark, crumbly material | broken-down scraps help enrich the soil."),
            ("D", "D? Daisy! Round center, simple petal ring | a small white bloom above the grass."),
            ("E", "Around the corner, E — Eggplant. Broad leaves make shade | glossy fruit hangs low beneath them."),
            ("F", "F ... F ... Flower! Get eye-level with the bloom | petals frame the flower's center."),
            ("G", "Along the path, G is Garden Hose. Long flexible curve | water travels through it from tap to plants."),
            ("H", "H? Hoe! Leaning where adults keep garden tools | a long handle we identify from a safe distance."),
            ("I", "At the fence, I — Ivy. Climb and cling | green leaves trail along the vertical edge."),
            ("J", "J ... J ... Jug! On the little table, handle and narrow mouth | ready for a careful pour."),
            ("K", "K? Kneeling Pad! Down at child height | soft cushion between knees and hard ground."),
            ("L", "Beside the path, L is Lavender. Purple spikes brush the air | narrow leaves carry a familiar scent."),
            ("M", "M — Marigold! Orange-gold bloom close to the border | color packed into a round flower head."),
            ("N", "Look higher for N ... N ... Nest! Twigs make a cup | a bird home we watch without disturbing."),
            ("O", "O? Orchid! In a pot near the shade | a distinctive bloom opens around one special central lip."),
            ("P", "P is Pot. Round wall, soil inside | a small container giving roots one bounded place."),
            ("Q", "At the sunny side, Q — Quince. Firm yellow fruit | growing on a shrub or small tree."),
            ("R", "R ... R ... Radish! Pull the view underground | crisp root below, leaves above."),
            ("S", "Close-up S? Seed! Tiny coat in our fingertips | a plant beginning small enough to miss."),
            ("T", "T is Tomato. Green branch, round fruit | a backyard snack growing above the soil."),
            ("U", "Under the eaves, U — Umbrella Plant. Leaf clusters spread | little green canopies above the pot."),
            ("V", "V ... V ... Violet! Low by the edge | a small bloom in purple, blue, white, or yellow."),
            ("W", "Kneel closer for W — Worm. Wiggle through moist soil | soft body tunneling under our feet."),
            ("X", "Back by the step, X is Xylem—tiny tubes carry water upward inside a garden stem."),
            ("Y", "Y ... Y ... Yarrow! Many tiny flowers gather flat | a cluster larger than each bloom alone."),
            ("Z", "Last close-up, Z? Zinnia! Layered petals ring the center | bright beside the path home."),
        ),
        "style_blueprint": "Friendly close adult lead at 86 BPM in easygoing acoustic 4/4 with guitar, soft glockenspiel, finger snaps, light kick and occasional plucked-string details. The production camera should feel child-height: start at the back step, move beside fence/path, drop into half-time close-ups near pots and soil, then widen briefly in the chorus. Round 1 uses spatial words and tactile observations more than rhyme; allow short close-up fragments beside two-bar descriptive lines. Avoid magical-garden language—the wonder comes from real proximity. Round 2 uses near/under/around cues, two short beats of recall space, clear target, then one safe gesture. Adult garden tools stay observation-only; Xylem is the plant-water pathway inside the garden, not a separate plant species. Keep backing vocals light and never cover target onsets. End with the same back-step acoustic texture as the opening so the loop feels complete.",
    },
}
