from __future__ import annotations

# Deep-polish layer for songs 0001-0010.
#
# The V4 gold module remains the source for locked mappings, object facts/actions,
# section forms, and the broad creative fingerprints.  This layer owns the
# hand-written Round-1 lyric and rhyme architecture requested for the final
# catalog polish.  Keeping it separate makes it obvious which lines are truly
# song-specific rather than shared object templates.

GOLD_V5_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0001": {
        "rhyme_engine": "wave-chain-linked-rhyme",
        "round1_grammar": "hand-written ocean image lines; rhyme may travel across three or four neighboring targets before changing family",
        "round1_overrides": (
            ("A", "A — Angelfish! Tall fins open wide | gliding through reef water side to side."),
            ("B", "B ... B ... Buoy! Bobbing bright, it marks a place where boats can ride."),
            ("C", "C is for Coral. Reef rooms grow below | branching shelter, row by row."),
            ("D", "D? Dock! A long arm from the shore where boats can pause beside the tide."),
            ("E", "Here comes E with Eel. Slip through blue | winding body disappears from view."),
            ("F", "F — Fish! Fins steer; gills breathe as water passes through."),
            ("G", "G ... G ... Grouper! Round and low | wide mouth waits where reef shadows grow."),
            ("H", "H is for Harbor—sheltered water quiets waves and lets the boats rest too."),
            ("I", "I? Island! Ringed by sand | water wraps around the land."),
            ("J", "Here comes J with Jetty—a walkway starting on shore and reaching out over the water."),
            ("K", "K — Kayak! Paddle the track | forward, turn, and paddle back."),
            ("L", "L ... L ... Lobster! Claws out front, it walks the seafloor forward and back."),
            ("M", "M is for Mussel. Shell shuts well | two dark halves hold fast below."),
            ("N", "N? Narwhal! Arctic whale | one long spiral tusk may grow."),
            ("O", "Here comes O with Octopus. Eight arms flow | soft body squeezes through a narrow place."),
            ("P", "P — Pelican! Bill dips low | throat pouch scoops a fish with grace."),
            ("Q", "Q ... Q ... Quahog! Hard-shell clam | tucked under coastal sand."),
            ("R", "R is for Ray—wide fins wave | gliding low above that sand."),
            ("S", "S? Seahorse! Upright swimmer | curled tail holds fast around a plant."),
            ("T", "Here comes T with Turtle. Shell rides light | steady strokes beneath it all."),
            ("U", "U — Undersea Cave! Under the wave | a deep rocky hollow where dark water stays."),
            ("V", "V ... V ... Violet Sea Snail! Purple-blue and tiny, it floats near the surface on the swell."),
            ("W", "W is for Whale. Rise for a breath | giant mammal diving down to depth."),
            ("X", "X? X-ray Tetra! Small and translucent; through its body we can partly see."),
            ("Y", "Here comes Y with Yellowfin Tuna. Yellow fins in view | fast body cutting through the blue."),
            ("Z", "Z — Zooplankton! Tiny drifters ride wherever moving water carries them too."),
        ),
        "style_blueprint": "Warm clear adult female lead with crisp dry diction. Playful 4/4 island-acoustic preschool groove at 88 BPM, narrow stepwise major-key melody. Open with a two-bar splash-and-marimba sound-image and the title hook, no generic spoken invitation. Round 1 is a hand-written wave-chain poem: several neighboring letter lines may share one rhyme or vowel family before the sound changes, so rhyme can travel across three or four lines instead of resetting as a couplet every target. Allow internal rhyme and short phrase-break echoes where written, but never force equal bar lengths; short targets land quickly and long image lines may breathe over two bars. Chorus lifts into a simple two-line singalong with a light group echo. Round 2 becomes stop-start call-and-response with one real beat of silence after each letter cue. Thin percussion and backing vocals at every target-word onset, then let marimba answer after the word. Ukulele, marimba, soft shaker and warm bass; stable harmony, no melisma or rapid patter. End with one final hook and a short clean cadence.",
    },
    "0002": {
        "rhyme_engine": "alternating-quatrain-near-rhyme",
        "round1_grammar": "hand-written shoreline quatrains using ABAB or near-ABAB rhyme across neighboring letter lines, with occasional internal echoes",
        "round1_overrides": (
            ("A", "Anchor — that's A. Down to the sand | heavy hold keeps a boat close at hand."),
            ("B", "Spot B: Boat! A floating little carrier rocking on the blue."),
            ("C", "C brings Coral. Branches lace | little reef rooms make a living space."),
            ("D", "What does D bring? Dock! From shore it reaches out where boats come into view."),
            ("E", "E — Estuary. River meets the tide | fresh and salty waters mix side by side."),
            ("F", "Flipper — that's F. A broad swimming limb sweeps water back to help an animal through."),
            ("G", "Spot G: Gull! White wings lean into coastal wind and circle wide."),
            ("H", "H brings Harbor—a calmer pocket where the boats can rest in blue."),
            ("I", "What does I bring? Isopod! Hard segmented body, with many little legs underneath."),
            ("J", "J — Jellyfish. Soft bell drifting, trailing tentacles behind."),
            ("K", "Kelp — that's K. Below the tide | long brown-green ribbons sway side to side."),
            ("L", "Spot L: Lagoon! Shallow water set apart from open sea—a quiet place to find."),
            ("M", "M brings Manatee. Slow with ease | paddle flippers sweep warm rivers and seas."),
            ("N", "What does N bring? Narwhal! Arctic whale; one spiral tusk can point ahead as it goes."),
            ("O", "O — Oyster. Shell shuts well | rough two-part home where tidal waters swell."),
            ("P", "Pufferfish — that's P. It can make its body rounder when a danger shows."),
            ("Q", "Spot Q: Quahog! Under sand | hard clam shell tucked close at hand."),
            ("R", "R brings Reef—a rocky or coral home with cracks where little animals hide."),
            ("S", "What does S bring? Seahorse! Hold a strand | curled tail grips the plant like a hand."),
            ("T", "T — Turtle. Hard shell on its back; steady strokes carry it through the tide."),
            ("U", "Urchin — that's U. Round on the ground | stiff sea spines point all around."),
            ("V", "Spot V: Vessel! A boat or ship made to travel over water far."),
            ("W", "W brings Whale. Up, then down | giant mammal breathes at the surface, then turns around."),
            ("X", "What does X bring? X-ray Fish! Partly see-through body shows where some tiny bones are."),
            ("Y", "Y — Yellowfin Tuna. Fins flash into view | yellow-tinted swimmer racing through blue."),
            ("Z", "Zooplankton — that's Z. Tiny drifters travel where the moving water carries them too."),
        ),
        "style_blueprint": "Clear warm adult lead, crisp consonants and stable vowels. Gentle 6/8 acoustic surf sway at 90 BPM with clean guitar upstrokes, soft shaker, glockenspiel and rounded bass; narrow singable melody. Open with a shoreline question and answer it musically, not with a generic invitation. Round 1 is shaped as beachcombing quatrains: neighboring A-B-C-D style groups use alternating ABAB or near-ABAB end sounds, with occasional internal echoes, so a rhyme can wait one line before answering. Do not over-accent the rhyme word; preserve natural English stress and allow a longer semantic line to breathe across two bars. Chorus brightens into the name-the-coast refrain. Round 2 uses search-and-find call-and-response with a predictable one-beat response gap. Duck guitar and percussion at target-word onset; glockenspiel answers afterward. Keep the arrangement airy and vocals forward. End with a gentle surf cadence and the final A-to-Z hook.",
    },
    "0003": {
        "rhyme_engine": "crew-delayed-payoff-rhyme",
        "round1_grammar": "hand-written deck-call work-song lines; a rhyme or sound planted early in a four-line crew block may resolve only on the third or fourth line",
        "round1_overrides": (
            ("A", "A ... A ... Angelfish! Fins flare bright | reef-blue swimmer catching light."),
            ("B", "B — Boat! Hull floats steady, carrying people and gear."),
            ("C", "From the deck, C finds Crab—sideways feet stitch little tracks across wet sand."),
            ("D", "D is for Dolphin—surface, breathe, then arc and dive back out of sight."),
            ("E", "Crew calls E? Eel! Long body bends | slipping through reef cracks as currents go."),
            ("F", "F ... F ... Fish! Fins steer while gills draw oxygen from the water."),
            ("G", "G — Grouper! Stout reef fish, wide mouth waiting near rocky shade."),
            ("H", "From the deck, H finds Hermit Crab—soft body sheltered in a borrowed shell wherever it goes."),
            ("I", "I is for Isopod. Plate after plate | many little legs hurry in a row."),
            ("J", "Crew calls J? Jellyfish! Soft bell pulses while trailing tentacles drift behind."),
            ("K", "K ... K ... Kayak! A double paddle turns the narrow boat through water."),
            ("L", "L — Lagoon! Shallow water rests apart from open sea, calm and low."),
            ("M", "From the deck, M finds Mussel. Two dark halves | closed shell holds tight on stone."),
            ("N", "N is for Nautilus—coil after coil, its chambered shell travels as it swims."),
            ("O", "Crew calls O? Oyster! Rough two-part shell closes around the soft animal inside."),
            ("P", "P ... P ... Pelican! Long bill dips; throat pouch scoops a fish, then wings carry it home."),
            ("Q", "Q — Queen Angelfish! Yellow and blue glow | bright reef colors turning slow."),
            ("R", "From the deck, R finds Reef—a rocky or coral home full of cracks and hiding places."),
            ("S", "S is for Seahorse—upright swimmer, curled tail holding tight to a plant."),
            ("T", "Crew calls T? Tidepool! A rocky hollow keeps seawater when the tide goes low."),
            ("U", "U ... U ... Urchin! Round on the ground | stiff sea spines point all around."),
            ("V", "V — Vessel! A boat or ship built to travel on water."),
            ("W", "From the deck, W finds Wave—surface water rising, cresting, falling on its way."),
            ("X", "X is for X-ray Fish. Partly see-through body | some tiny bones can be found."),
            ("Y", "Crew calls Y? Yellow Tang! Yellow in view | flat oval reef fish gliding through blue."),
            ("Z", "Z ... Z ... Zebra Shark! Young sharks wear dark zebra-like bands; a long tail trails behind."),
        ),
        "style_blueprint": "Friendly clear adult lead with a small group response, crisp diction and no shouted delivery. Light 2/4 nautical preschool stomp at 92 BPM: brushed snare, ukulele, soft accordion breaths, hand claps and bass. Open with a rhythmic rowing pickup before the hook. Round 1 behaves like a gentle work-song: each four-letter deck-call block can plant a rhyme, vowel color, or rhythmic phrase in line one and delay its payoff until line three or four; middle lines may stay open and factual. Keep the crew pulse stable so delayed rhyme still feels intentional. Use internal phrase rhymes only where they add image or motion, never as filler. Chorus lands strongly on beat one as a crew-response refrain. Round 2 is stripped to soft stomp plus voice, with one clean beat of silence between letter cue and target confirmation. Keep backing voices out of target-word attacks; accordion may answer after. Stable simple harmony. End with the rowing pulse slowing into a short final cadence.",
    },
    "0004": {
        "rhyme_engine": "linked-end-to-internal-rhyme",
        "round1_grammar": "hand-written sailing narrative where the end image or sound of one target line is echoed naturally inside the next line; inspired by linked poetic rhyme, not a fixed syllable-count imitation",
        "round1_overrides": (
            ("A", "On our way, A meets Anchor. Down through water | heavy metal helps the boat stay still."),
            ("B", "Small waves spill around B — Boat | a floating carrier moving over blue."),
            ("C", "From blue shallows, C is Crab | sideways feet stitch tracks across sand."),
            ("D", "Beyond the strand, D — Dolphin | rises for air, then curves back through the sea."),
            ("E", "E is for Estuary. Sea meets river | fresh and salty waters join and flow."),
            ("F", "In that flow, F meets Flipper | a broad limb sweeps water back to make a swimmer go."),
            ("G", "Where swimmers go, G is Grouper | stout reef body, wide mouth waiting in shade."),
            ("H", "In reef shade, H — Hermit Crab | soft body carries a borrowed shell."),
            ("I", "I — Island. Water all around | land rises inside a blue ring."),
            ("J", "Along that ring, J is Jetty | reaching from the shore out over water."),
            ("K", "Over water, K meets Kayak | narrow boat, double paddle forward and back."),
            ("L", "Looking back, L — Lobster | claws ahead, walking on the seafloor."),
            ("M", "What waits at M? Manatee! Warm-water swimmer | paddle-like flippers moving slow and free."),
            ("N", "Moving free, N — Nautilus | coiled shell divided into chambers as it swims."),
            ("O", "Where it swims, O is Octopus | eight arms, soft body, squeezing through tight spaces under the sea."),
            ("P", "Above the sea, P meets Pelican | long bill and throat pouch scoop fish from the water."),
            ("Q", "Queen Angelfish — that's our Q. Yellow and blue glow | reef colors bright below."),
            ("R", "In that glow, R is Ray | wide fins glide through water like wings."),
            ("S", "Under gliding wings, S — Seal | flippers sweep, then the seal rests on rock or shore."),
            ("T", "At the shore, T is Tidepool | rocky hollow keeps seawater when the tide goes out."),
            ("U", "When tide goes out, U meets Urchin | round sea animal covered in stiff spines."),
            ("V", "Past the spines, V — Violet Sea Snail | tiny purple-blue snail floating near the surface."),
            ("W", "At the surface, W is Whale | giant marine mammal rising to breathe."),
            ("X", "After that breath, X — X-ray Fish | translucent little body lets us partly see through."),
            ("Y", "Through the water, Y is Yellowfin Tuna | yellow-tinted fins flash fast through blue."),
            ("Z", "Through the blue, Z meets Zooplankton | tiny drifters ride wherever moving water flows."),
        ),
        "style_blueprint": "Warm intimate adult lead with clear consonants, minimal vibrato and calm breath. Floating 6/8 preschool travel-pop at 86 BPM with kalimba, soft marimba, brushed percussion, ukulele and light bass; narrow lyrical contour and stable major center. Open by dropping directly into a morning-on-the-water scene. Round 1 uses linked poetic rhyme: when natural, the final image or sound of one letter line is echoed inside the next line before that next line travels onward to a new image. This borrows the linking principle found in chain verse and lục-bát-like rhyme connection, but do not force English into six/eight-syllable counts or repeat words unnaturally. Let long lines breathe across two bars and keep the target word clear near the front. Chorus opens the arrangement into a wide but simple sailing hook. Round 2 removes pads and becomes a spacious cue-gap-answer pattern with roughly two quiet beats for recall. Keep target words dry and exposed; no backing vocal or percussion attack on their first syllable. End by returning to the sailing hook over a soft two-chord cadence.",
    },
    "0005": {
        "rhyme_engine": "internal-rhyme-alliterative-clue-cadence",
        "round1_grammar": "hand-written field-guide observations driven by internal rhyme, alliteration, consonance, and occasional delayed end-rhyme rather than regular couplets",
        "round1_overrides": (
            ("A", "Spot A: Anchor! Drop, stop | heavy hold helps the boat stay in place."),
            ("B", "B — Buoy. Bobbing marker on the water, helping boats recognize a place."),
            ("C", "What clue starts at C? Crab! Side-step, sand-scratch | little tracks stitch the shore."),
            ("D", "Along the coast, D finds Dolphin—breath at the surface, silver arc, splash, and gone."),
            ("E", "E ... E ... Eel! Slip, slide | winding body threads between reef rocks."),
            ("F", "Spot F: Fish! Fin flick, gill pull | it steers and breathes beneath the water."),
            ("G", "G — Gull. Wing tilt, wind lift | it rides the air above the shore."),
            ("H", "What clue starts at H? Harbor! Surf grows soft; sheltered water lets the boats rest."),
            ("I", "Along the coast, I finds Island. Ring of sea | land sits with water all around."),
            ("J", "J ... J ... Jetty! Jetty juts from shore, a straight path reaching over water."),
            ("K", "Spot K: Kayak! Paddle pair, narrow hull | left-right strokes send it on."),
            ("L", "L — Lagoon. Shallow and sheltered, its water lies apart from the open sea."),
            ("M", "What clue starts at M? Manatee! Slow roll | paddle-like flippers move through warm water."),
            ("N", "Along the coast, N finds Nautilus. Coil after coil, chambers hide inside its shell."),
            ("O", "O ... O ... Oyster! Rough shell, soft center | two hard halves close around the animal."),
            ("P", "Spot P: Pufferfish! Under threat its body can look rounder, a sudden change in shape."),
            ("Q", "Q — Queen Angelfish. Yellow-blue blaze | bright reef colors turn through the water."),
            ("R", "What clue starts at R? Reef! Crack, crevice, coral cover—many small hiding places."),
            ("S", "Along the coast, S finds Seal. Flipper sweep | it swims, then rests on rock or shore."),
            ("T", "T ... T ... Turtle! Shell steady on its back; measured strokes carry it through the sea."),
            ("U", "Spot U: Undersea Cave! Dark under wave | rocky hollow below the ocean surface."),
            ("V", "V — Vessel. A boat or ship built to travel over water."),
            ("W", "What clue starts at W? Wave! Rise, roll, fall | surface water lifts and settles again."),
            ("X", "Along the coast, X finds X-ray Tetra. Translucent body lets us partly see through."),
            ("Y", "Y ... Y ... Yellowfin Tuna! Flash and pass | yellow-tinted fins cut quickly through blue."),
            ("Z", "Spot Z: Zooplankton! Tiny drifters travel wherever the moving current carries them."),
        ),
        "style_blueprint": "Curious clear adult lead, crisp diction, lightly animated but never breathless. Bouncy 4/4 preschool explorer-pop at 94 BPM with acoustic guitar, claves, marimba, soft bass and hand claps; compact stepwise melody. Open with a movement-based field-guide pickup, not a spoken welcome. Round 1 should sound like an observant explorer taking quick notes: use internal rhyme, alliteration, consonance, repeated action sounds, and occasional delayed end-rhyme, but do not make every line close as a couplet. Let phrases such as drop/stop, slip/slide, wing/wind, crack/crevice work rhythmically inside the line while the semantic image remains primary. Alternate punchy clue lines with longer natural-history snapshots. Chorus becomes a clap-ready explorer badge hook. Round 2 uses a short one-beat recall gap, then object-specific gestures; muted guitar and sparse marimba leave target words uncovered. No dense choir, fast patter or vocal runs. End with two clave ticks, one final hook, then a clean stop.",
    },
    "0006": {
        "rhyme_engine": "three-line-current-clusters",
        "round1_grammar": "hand-written river-folk verses where two or three neighboring targets can share one rhyme or vowel current before a plain factual line releases the pattern",
        "round1_overrides": (
            ("A", "A — Alder. By the flow | roots hold damp banks as branches grow."),
            ("B", "B is for Boat. Row, then float | carrying people or things along the river."),
            ("C", "Catfish — remember C. Down below | whisker-like barbels wave around its mouth as it goes."),
            ("D", "What drifts in with D? Dam! A wall holds water back and changes how the current moves."),
            ("E", "By the water, E meets Eel. Easy glide | winding body bends from side to side."),
            ("F", "F — Frog. Bankside hop | strong back legs kick for swimming, then stop."),
            ("G", "G is for Green Algae. Green sheen | soft patches spread in water and over wet surfaces."),
            ("H", "Heron — remember H. Long legs pause in shallow water; stillness comes before a step."),
            ("I", "What drifts in with I? Iris! Wet-ground bright | flower opens into morning light."),
            ("J", "By the water, J meets June Bug. Warm-evening flight | shiny beetle circles into sight."),
            ("K", "K — Kingfisher. Flash in sight | dives for a fish, then climbs back to height."),
            ("L", "L is for Lily Pad. Flat green leaf floats like a plate on quiet water."),
            ("M", "Muskrat — remember M. Body low | paddles beside the wet bank where grasses grow."),
            ("N", "What drifts in with N? Nest! Twigs held tight | a bird-built place for eggs or chicks inside."),
            ("O", "By the water, O meets Otter. Side to side | float, turn, tumble, dive, then glide."),
            ("P", "P — Pond. A small body of still water gives plants and animals a place to live."),
            ("Q", "Q is for Quillwort. Quillwort low | spiky-looking leaves in wet places grow."),
            ("R", "Reed — remember R. Tall stems show | straight at the water's edge, swaying slow."),
            ("S", "What drifts in with S? Salamander! Long and low | four small legs help the moist-skinned body go."),
            ("T", "By the water, T meets Trout. Cool-water fish flicks its tail against the current."),
            ("U", "U — Underwater Plant. Sway this way | submerged leaves bend with moving water all day."),
            ("V", "V is for Vallisneria. Long ribbon-like leaves grow underwater in freshwater."),
            ("W", "Waterfall — remember W. Rush and spray | water drops from higher rock and breaks into mist on the way."),
            ("X", "What drifts in with X? X-ray Tetra! Small translucent fish with a partly see-through body."),
            ("Y", "By the water, Y meets Yellow Water Lily. Yellow in light | broad leaves float, flower bright."),
            ("Z", "Z — Zooplankton. Tiny and light | little drifters ride the current day and night."),
        ),
        "style_blueprint": "Clear gentle adult lead with close dry diction and stable vowels. Relaxed 6/8 river-folk at 84 BPM with acoustic guitar, pizzicato strings, soft woodblock, glockenspiel and light bass; narrow rising-and-falling contour. Open with quiet ripple onomatopoeia over two sparse bars. Round 1 should feel as if rhyme itself is carried by the current: allow two or three neighboring target lines to share one end-sound or vowel family, then release the pattern with a plain vivid factual line before beginning a new current. This is intentionally not a sequence of 13 couplets. Use internal phrase breaks where a natural mini-rhyme helps the flow, and keep difficult plant names almost speech-like. Chorus adds a small glockenspiel shimmer and an easy flowing refrain. Round 2 drops to woodblock pulse plus voice, leaving about two supportive beats after each letter cue before confirmation. Thin every instrument at target-word onset, then answer with pizzicato. End by letting the ripple motif settle into one soft final chord.",
    },
    "0007": {
        "rhyme_engine": "bluegrass-answer-rhyme-irregular",
        "round1_grammar": "hand-written paddle-song clues using short internal answer-rhymes, slant rhyme, and irregular open lines; rare names deliberately remain unrhymed",
        "round1_overrides": (
            ("A", "Paddle to A: Alligator! Bank-side rest | then a quiet glide comes next."),
            ("B", "B ... B ... Beaver! Branch by branch, flat tail paddling as sharp teeth cut wood."),
            ("C", "Catfish — that's C. Whisker-like barbels feel around its mouth as it swims."),
            ("D", "D — Dam. A wall holds water back and changes the current's path."),
            ("E", "What's waiting at E? Egret! Stand and scan | long legs pause in shallow water."),
            ("F", "Paddle to F: Fishing Rod! Long pole, fishing line, and reel make the picture clue."),
            ("G", "G ... G ... Goose! Glide wide | paddles on water, then walks grassy banks."),
            ("H", "Heron — that's H. Hold still | then one long-legged step through the shallows."),
            ("I", "I — Insect. Six in line | six legs, three main body parts in the design."),
            ("J", "What's waiting at J? Jetty! A structure reaches from the shore out over water."),
            ("K", "Paddle to K: Kayak! On the track | double paddle forward and back."),
            ("L", "L ... L ... Lake! A large body of water held inside surrounding land."),
            ("M", "Minnow — that's M. Quick little flick | small fish darts through shallow water."),
            ("N", "N — Nest. Rest in the nest | bird-built place for eggs and chicks."),
            ("O", "What's waiting at O? Oar! Row as we go | long blade pulls water to move a boat."),
            ("P", "Paddle to P: Pike! Long freshwater fish waiting still among water plants."),
            ("Q", "Q ... Q ... Quillwort! Spiky little leaves make this wet-place plant easy to spot."),
            ("R", "River — that's R. Bend after bend | water runs downhill through a channel."),
            ("S", "S — Salamander. Long body, moist skin, four legs, and a tail behind."),
            ("T", "What's waiting at T? Trout! Tail flick | cool-water fish pushes against the current."),
            ("U", "Paddle to U: Umbrella Sedge! Green rays spread | leaf-like spokes above the stem."),
            ("V", "V ... V ... Valley! Low between hills, often giving running water a way through."),
            ("W", "Waterfall — that's W. High to low | rushing water drops from rock below."),
            ("X", "X — Xiphophorus. A group of small freshwater fish including swordtails and platies."),
            ("Y", "What's waiting at Y? Yellow Water Lily! Yellow in light | broad leaves float, flower bright."),
            ("Z", "Paddle to Z: Zooplankton! Tiny drifters move wherever the water carries them."),
        ),
        "style_blueprint": "Friendly adult lead with clean en-US diction and a tiny group echo only in the hook. Light 4/4 acoustic bluegrass-lite hop at 90 BPM: restrained banjo plucks, upright bass, hand claps, soft woodblock and brief whistle answers; no virtuoso picking or exaggerated twang. Open with two paddle motions as rhythmic pickup. Round 1 uses irregular bluegrass answer-rhyme: some lines contain a short semantic rhyme after the phrase break, some neighboring lines share a slant rhyme, and some facts deliberately land without rhyme. Do not regularize this into couplets. Let punchy phrases such as rest/next, whisker/swish, shore/more, track/back or light/bright act like little banjo answers. Xiphophorus and other difficult names stay near speech rhythm with no rhyme pressure. Chorus becomes a paddle-and-answer refrain. Round 2 leaves one clear beat of silence after each cue; hard words slow to near speech rhythm. Keep whistle and claps away from target-word attacks. End with the paddle pulse stopping under a final sung hook.",
    },
    "0008": {
        "rhyme_engine": "motion-cluster-rhyme",
        "round1_grammar": "hand-written freshwater snapshots where rhyme clusters are organized around motion families such as sway, glide, hop, paddle, flow, and flash",
        "round1_overrides": (
            ("A", "A finds Alder. Bank-side sway | roots stay damp while branches move with the day."),
            ("B", "B — Beaver! Flat tail paddles; branches travel away."),
            ("C", "What moves with C? Canoe! Paddle left, paddle right; narrow hull slides on its way."),
            ("D", "Look at D: Duck. Webbed feet paddle while the broad bill dips through spray."),
            ("E", "E is for Eel. Easy glide | long winding body bends from side to side."),
            ("F", "F finds Frog. Waterside hop | strong back legs kick to swim, then stop."),
            ("G", "G — Green Algae! Soft green patches spread in water and over wet surfaces."),
            ("H", "What moves with H? Hydrilla! Leafy stems sway underwater with the current."),
            ("I", "Look at I: Insect. Six-leg line | three main body parts make the design."),
            ("J", "J is for Jetty. Shore to more | a straight structure reaches out over water."),
            ("K", "K finds Kingfisher. Flash and splash | perch, quick dive, then back in a dash."),
            ("L", "L — Lake. Wide water rests inside a boundary of land."),
            ("M", "What moves with M? Muskrat! Body low | paddles beside wet banks where waters flow."),
            ("N", "Look at N: Newt. Four legs walk low | long tail follows as the little amphibian goes."),
            ("O", "O is for Oar. Row, row | long blade pulls water and helps the boat go."),
            ("P", "P finds Pond. Small and still, it gives freshwater plants and animals a home."),
            ("Q", "Q — Quail! Quick ground steps | small bird walks and pecks."),
            ("R", "What moves with R? River! Flow as we go | water follows a downhill channel."),
            ("S", "Look at S: Salamander. Long and low | four legs and a tail help the moist-skinned body go."),
            ("T", "T is for Tadpole. Wiggle, little tail | water-stage youngster grows legs later on."),
            ("U", "U finds Umbrella Sedge. Green rays spread | leaf-like spokes above the stem."),
            ("V", "V — Valley. Low where waters flow | land dips between hills or mountains."),
            ("W", "What moves with W? Water Lily! Round leaves float | flower rises above the water."),
            ("X", "Look at X: Xiphophorus. Small freshwater fish group including swordtails and platies."),
            ("Y", "Y is for Yellow Perch. Bars in rows | yellow sides flash and off it goes."),
            ("Z", "Z finds Zebra Danio. Stripes in a row | small freshwater fish darts to and fro."),
        ),
        "style_blueprint": "Bright clear adult female lead, friendly nature-host delivery, crisp consonants and no baby voice. Acoustic 4/4 preschool bounce at 91 BPM with marimba, ukulele, finger snaps, soft kick and bass; narrow stepwise melody. Open with a quick montage of visible motions rather than saying the theme name generically. Round 1 organizes rhyme by movement: three or four neighboring targets may share a motion-sound family such as sway/away/way/spray, glide/side, hop/stop, low/flow/go, or rows/go/fro. These clusters should feel like bodies and water moving together, not like arbitrary end-word matching. Break the rhyme whenever a rare plant or taxonomic word needs clean speech. Chorus lifts into a swim-hop-glide participation hook. Round 2 is cue-gap-confirm-action; drop the soft kick at every target-word onset and let finger taps answer afterward. Hydrilla remains visual recognition only. End with the motion hook once and a clean marimba button.",
    },
    "0009": {
        "rhyme_engine": "sparse-assonance-delayed-closure",
        "round1_grammar": "hand-written wetland dawn verse with spacious sensory images, sparse internal rhyme, assonance/consonance, and occasional delayed closure; silence is part of the prosody",
        "round1_overrides": (
            ("A", "Alligator — our A. Still by the bank, then one quiet glide through brown-green water."),
            ("B", "At wetland dawn, B meets Beaver. Flat tail cuts a small V through the reflected sky."),
            ("C", "C — Canoe. Paddle dips softly; rings widen behind the blade."),
            ("D", "What belongs to D? Duck! Dip, then drip | broad bill lowers while webbed feet paddle."),
            ("E", "E ... E ... Egret. Long legs hold still in the shallows while the water moves around them."),
            ("F", "Fishing Rod — our F. Long pole, line, and reel make a quiet silhouette beside the water."),
            ("G", "At wetland dawn, G meets Green Algae. Green sheen | soft patches tint water and wet surfaces."),
            ("H", "H — Hydrilla. Leafy stems stay below the surface and move with the current."),
            ("I", "What belongs to I? Iris! Morning light | bright flower opens near wet ground."),
            ("J", "J ... J ... June Bug. A shiny beetle lifts into the warm evening air."),
            ("K", "Kingfisher — our K. Flash and splash | quick dive for a fish, then stillness on a perch."),
            ("L", "At wetland dawn, L meets Lily Pad. Flat green leaf rests on the water like a plate."),
            ("M", "M — Minnow. Quick flick | small fish darts through the shallow edge."),
            ("N", "What belongs to N? Newt! Four legs, long tail, small amphibian moving between damp land and water."),
            ("O", "O ... O ... Otter. Float, turn, dive; the smooth body redraws the surface."),
            ("P", "Pond — our P. Still water holds reflections, plants, insects, and animal life."),
            ("Q", "At wetland dawn, Q meets Quail. Peck, step | small ground bird moving through low cover."),
            ("R", "R — Reed. Tall stem leans, straightens, then leans again at the water's edge."),
            ("S", "What belongs to S? Swan! Long neck curves while the body glides over calm water."),
            ("T", "T ... T ... Tadpole. Tail first, legs later—the little swimmer is changing as it grows."),
            ("U", "Umbrella Sedge — our U. Green rays spread from the top of the stem like a small open umbrella."),
            ("V", "At wetland dawn, V meets Vallisneria. Long ribbon-like leaves grow underwater in freshwater."),
            ("W", "W — Waterfall. White fall | water drops past dark rock and breaks into spray."),
            ("X", "What belongs to X? Xiphophorus! A freshwater fish group that includes swordtails and platies."),
            ("Y", "Y ... Y ... Yellow Water Lily! Yellow in light | broad leaves float, flower bright."),
            ("Z", "Zooplankton — our Z. Tiny drifters move with the water, almost too small to notice one by one."),
        ),
        "style_blueprint": "Calm close adult lead with crisp diction, natural breath and minimal vibrato. Slow 3/4 preschool nature sway at 82 BPM with kalimba, soft shaker, airy pad used sparingly and gentle bass; narrow mostly stepwise melody. Open with a tiny wetland sound-image—drip, hush, distant wing motion—then enter the first clue. Round 1 should feel closer to free verse than to a nursery rhyme: use silence, sensory images, assonance, consonance, and only occasional internal rhyme or delayed closure. A line may answer a sound two or three lines later; many lines should not rhyme at all. Do not add filler merely to close a rhyme. Rare names such as Vallisneria and Xiphophorus are intentionally plain and speech-clear. Chorus stays calm and memorable instead of becoming hyperactive. Round 2 becomes nearly percussion-free with about two beats of recall space before each answer. Keep all target words dry and forward, with no harmony on their attack. End by thinning to solo kalimba and one soft final refrain line.",
    },
    "0010": {
        "rhyme_engine": "walking-ballad-abcb-flexible",
        "round1_grammar": "hand-written riverbank ballad quatrains; second and fourth lines usually answer in rhyme or near-rhyme while first and third lines carry free narrative, with form broken whenever fact or pronunciation needs room",
        "round1_overrides": (
            ("A", "A ... A ... Alligator! Resting by the bank, then gliding quietly into water."),
            ("B", "Step to B: Boat. Boat afloat | carrying people or things down the stream."),
            ("C", "C — Canoe. Narrow hull moves with a paddle dipped left, then right."),
            ("D", "Duck — that's D. Webbed feet paddle while the broad bill dips where water gleams."),
            ("E", "What did E find? Eel! Long winding body slips through water in muscular curves."),
            ("F", "F ... F ... Frog! From log to bog | strong back legs hop and swim at waterside."),
            ("G", "Step to G: Goose. It paddles on water and walks the grassy bank."),
            ("H", "H — Heron. Long legs hold still, then take one careful stride."),
            ("I", "Iris — that's I. Bright flower opens near wet ground when morning warms the bank."),
            ("J", "What did J find? June Bug! Evening light | shiny beetle lifts into flight."),
            ("K", "K ... K ... Kingfisher! Perched near water, then one quick dive after a fish."),
            ("L", "Step to L: Lake. Wide water lies within surrounding land, open in sight."),
            ("M", "M — Minnow. Flick, quick | small fish darts through shallow water."),
            ("N", "Newt — that's N. Four legs in view | one long tail follows behind it, too."),
            ("O", "What did O find? Oar! Long blade pulls through water to help move a boat."),
            ("P", "P ... P ... Pike! Long freshwater fish waits among water plants before it moves into view."),
            ("Q", "Step to Q: Quail. Small ground bird walks, pauses, and pecks along the bank."),
            ("R", "R — River. Water descends | winding downhill through its channel and around the bend."),
            ("S", "Swan — that's S. Long curved neck rises above a body gliding over water."),
            ("T", "What did T find? Trout! Cool-water fish flicks its tail, holding against the current around the bend."),
            ("U", "U ... U ... Underwater Plant! Leaves grow below the surface and bend with moving water."),
            ("V", "Step to V: Valley. Low below | land lies between hills where waters flow."),
            ("W", "W — Water Lily. Round leaves float while the flower stands above the surface."),
            ("X", "X-ray Tetra — that's X. Partly see-through body lets some tiny bones show."),
            ("Y", "What did Y find? Yellow Water Lily! Yellow in light | broad leaves float, flower bright."),
            ("Z", "Z ... Z ... Zooplankton! Tiny drifters ride the moving water by day and night."),
        ),
        "style_blueprint": "Bright clear adult lead with friendly walking-story delivery and crisp dry diction. Easy 4/4 campfire-folk preschool pulse at 89 BPM with acoustic guitar, light footstep stomps, shaker, glockenspiel and soft bass; narrow melody with ballad-like cadences. Open with two audible walking steps and a stream-side discovery line. Round 1 uses a flexible ABCB walking-ballad idea: in many four-letter groups the second and fourth lines rhyme or near-rhyme while the first and third remain free narrative, but never force the scheme when a scientific fact or rare word needs cleaner language. Let stream/gleam, side/stride, light/sight, low/show and bright/night provide natural closures; elsewhere accept slant rhyme or no rhyme. Chorus uses the stream/seen rhyme as a compact step-and-name hook. Round 2 strips to soft stomps and bass, leaves one real beat after the letter cue, then confirms the object and one congruent gesture. Mute stomps and backing vocals on target-word attacks; glockenspiel answers afterward. End by slowing the steps and resolving on the final hook without extra spoken praise.",
    },
}
