from __future__ import annotations

"""Authorial-identity deep polish for zoo/wildlife songs 0076-0080."""

GOLD_V5_76_80_SPEC_PATCHES: dict[str, dict[str, object]] = {
"0076":{
"authorial_intent":"Make Zoo Friends ABC a behavior-observation walk: feeding, resting, social grouping, climbing, swimming and thermoregulation are observed through habitat design without treating wild animals as pet-like friends.",
"lyric_identity":"A child reads exhibit signs, watches behavior at distance, and accepts that a resting or hidden animal does not owe a performance.",
"image_motifs":("gorilla foraging","hippo underwater","flamingo flock","tiger resting shade","seal swimming"),
"semantic_arc":("observe body/behavior","social and feeding patterns","water/land contrasts","rest/privacy and welfare"),
"forbidden_generic_language":("picture gates swing","zoo friends","animal show","make it move"),
"rhyme_engine":"zoo-behavior-welfare-rhyme","chorus_rhyme_engine":"watch-read-respect-hook","point_of_view":"a child observing zoo animals respectfully","chorus_function":"repeat watch-read-respect","groove_meter":"calm 4/4 exhibit-walk pulse","round1_grammar":"hand-written behavior/habitat; no petting/feeding/chasing","round2_grammar":"observation cue -> recall beat -> target -> point/shape gesture",
"intro_lines":("The gorilla may forage; the tiger may sleep; the animal can choose what to do.","A good zoo visit watches without demanding a show."),
"hook_lines":("Watch, read, respect—A-B-C!","Wild animals stay wild, even behind a viewing window."),
"outro_lines":("No glass tapped, no food tossed, no resting animal called closer.","A to Z leaves the habitats quiet after our walk."),
"round2_patterns":("Observe {letter} ... {object}! {action}","Behavior {letter} ... {object}! {action}","Land, water, or rest—{letter}? ... {object}! {action}","Sign clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Ape! Broad primate category without a tail | grasping hands and flexible shoulders support varied climbing and ground movement."),
("B","B ... B ... Bison! Massive grazing bovine with shoulder hump and curved horns | herd space and grazing behavior matter more than a close photo."),
("C","C? Cheetah! Slender cat specialized for short high-speed pursuit | resting occupies far more time than sprinting."),
("D","D is Dhole. Social Asian wild dog often hunts and communicates in groups | not a domestic dog for petting."),
("E","E — Elephant! Trunk handles food, water, touch and smell | complex social life needs space, choice, and stimulation."),
("F","F ... F ... Flamingo! Long-legged filter feeder often lives socially in flocks | shallow water supports feeding and bathing."),
("G","G? Gorilla! Great ape mainly eats plant material | foraging, resting, climbing and social behavior all matter."),
("H","H is Hippo. Semi-aquatic mammal spends much daytime in water | extremely dangerous in the wild, always distance-only."),
("I","I — Ibex! Wild goat with sure hooves and curved horns | rocky climbing habitat supports natural movement."),
("J","J ... J ... Jackal! Wild canid of Africa/Eurasia depending species | scavenging and hunting roles vary."),
("K","K? Koala! Australian tree-dwelling marsupial specialized on eucalyptus leaves | long rest helps conserve energy."),
("L","L is Lion. Social big cat living in prides in the wild | resting is normal behavior, not laziness for visitors."),
("M","M — Meerkat! Social mongoose scans, digs, forages and uses burrows | upright lookout is only one behavior."),
("N","N ... N ... Nile Crocodile! Large African crocodilian ambush predator | stillness is part of its biology, not an invitation to approach."),
("O","O? Okapi! Central African forest relative of giraffe | striped legs and long tongue fit a browsing life."),
("P","P is Panda. Giant panda specializes heavily on bamboo | feeding and resting dominate much of its day."),
("Q","Q — Quail! Small ground bird | cover and ground-foraging space matter more than flight display."),
("R","R ... R ... Rhino! Large herbivore with keratin horn | viewing distance protects both animal and visitor."),
("S","S? Seal! Marine mammal swims with flippers and hauls out to rest | water and dry resting space serve different needs."),
("T","T is Tiger. Solitary big cat in the wild | scent, cover, climbing/resting options and privacy support behavior."),
("U","U — Uakari! Amazonian monkey with short tail and bare face | canopy movement needs complex climbing space."),
("V","V ... V ... Vicuna! South American camelid of high Andes | light body and fine coat suit cold dry elevations."),
("W","W? Wolf! Social wild canid with large territories in nature | pack behavior cannot be reduced to howling on cue."),
("X","X is Xerus. African ground squirrel | digging and alert posture fit open dry habitats."),
("Y","Y — Yellow Mongoose! Southern African mongoose | small predator forages on ground and uses burrows."),
("Z","Z ... Z ... Zebu! Domestic cattle type with shoulder hump | human-managed animal, distinct from the wild species around it."),),
"style_blueprint":"Crisp diction. Open with forage/rest/choice at 86 BPM calm 4/4 with acoustic guitar, soft bass, shaker and marimba. Melody narrow. Round 1 changes texture by observed behavior, never forcing action. Chorus watch-read-respect. Round 2 uses pointing/shape gestures only. No feeding, glass tapping, roaring SFX, or petting cues. Duck target onsets. End with quiet habitats."},
"0077":{
"authorial_intent":"Repair Safari Letter Ride as a global wildlife route: Africa, Asia, Australia, Americas, marine coasts and freshwater cards appear sequentially, with geography stated instead of putting every animal on one dusty savanna.",
"lyric_identity":"A child moves a world map marker between regions; each animal gets a location/habitat clue before its body clue.",
"image_motifs":("African antelope grassland","Australian emu/kangaroo","Asian red panda forest","seal coast","Xenopus freshwater"),
"semantic_arc":("Africa/open habitats","Asia forests and canids","Australia marsupials/birds","Americas/marine/freshwater world finish"),
"forbidden_generic_language":("follow the tracks safari","dust trail for all","safari wildlife words","every animal Africa"),
"rhyme_engine":"global-wildlife-map-rhyme","chorus_rhyme_engine":"region-habitat-animal-hook","point_of_view":"a child moving across a world wildlife map","chorus_function":"reset region-habitat-animal","groove_meter":"4/4 map-travel pulse with region pauses","round1_grammar":"hand-written geography/habitat; safari premise corrected","round2_grammar":"map cue -> recall beat -> target -> point-to-region gesture",
"intro_lines":("Antelope in Africa—then Emu moves the map to Australia, and Red Panda pulls it toward Asia.","This is a world wildlife ride, not one safari road."),
"hook_lines":("Region, habitat, animal—A-B-C!","Move the map before you move the rhyme."),
"outro_lines":("Freshwater frog, coastal seal, desert cattle—the map stays wide.","A to Z ends with every animal left in its real part of the world."),
"round2_patterns":("Map {letter} ... {object}! {action}","Region clue {letter} ... {object}! {action}","Where belongs {letter}? ... {object}! {action}","World route {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Antelope! Many hoofed species live across Africa and Eurasia | grassland, scrub, forest, and desert habitats vary by species."),
("B","B ... B ... Baboon! African/Arabian monkeys spend much time on ground | strong limbs and social troops fit varied open habitats."),
("C","C? Cheetah! Mostly African with a tiny Iranian remnant population | open habitat supports high-speed hunting."),
("D","D is Dhole. Asian wild dog of forests and grasslands | geography shifts the map east."),
("E","E — Emu! Large flightless Australian bird | long legs cross open woodland and grassland."),
("F","F ... F ... Fox! Fox species occur across many continents and habitats | one word needs species context."),
("G","G? Giraffe! African browser with long neck and legs | savanna/woodland frame belongs here."),
("H","H is Hippo. Sub-Saharan African semi-aquatic mammal | river/lake habitat interrupts the dry-road cliché."),
("I","I — Iguana! Iguanas are primarily tropical American lizards | branch, ground, and island habitats vary."),
("J","J ... J ... Jaguar! Large spotted cat of the Americas | tropical forest and wetland map, not African safari."),
("K","K? Kangaroo! Australian marsupial | hopping movement moves the route firmly to Australia."),
("L","L is Lemur. Primate native to Madagascar | island geography is essential to the clue."),
("M","M — Monkey! Broad primate term across tropical Americas, Africa and Asia | exact species decides the map point."),
("N","N ... N ... Nile Crocodile! African crocodilian of rivers, lakes and wetlands | water habitat, not dusty track."),
("O","O? Ostrich! African flightless bird of open dry habitats | long running legs fit the continental card."),
("P","P is Puma. American big cat ranging from Canada to southern South America | mountain, forest, desert and grassland all possible."),
("Q","Q — Quail! Ground birds occur in many world regions | species determines geography."),
("R","R ... R ... Red Panda! Himalayan and southwestern Chinese mountain forests | bamboo-rich temperate forest, not savanna."),
("S","S? Seal! Marine mammals live on coasts and oceans in many regions | route moves to water."),
("T","T is Tiger. Asian big cat | forests, grasslands and mangroves vary by population."),
("U","U — Urial! Wild sheep of Central/South Asian dry mountains and steppe | rocky continental interior."),
("V","V ... V ... Vulture! Vultures occur in Old and New Worlds in different families | soaring scavenger role crosses regions."),
("W","W? Wolf! Gray wolves range across parts of North America, Europe and Asia | large territory, not safari-only."),
("X","X is Xenopus. African clawed frog genus | fully aquatic freshwater frog moves the map underwater."),
("Y","Y — Yellow Mongoose! Southern African species | dry grassland and scrub return the route south."),
("Z","Z ... Z ... Zebu! Humped domestic cattle widespread in tropical regions | human-managed livestock closes the map, not wild safari prey."),),
"style_blueprint":"Crisp diction. Open with Africa-Australia-Asia map jumps at 88 BPM in 4/4 with acoustic guitar, soft hand drum, bass and marimba. Use neutral musical transitions, no stereotyped regional instrumentation. Melody narrow. Round 1 explicitly names geography. Chorus region-habitat-animal. Round 2 uses map-point gestures. Duck targets. End with a world map closing."},
"0078":{
"authorial_intent":"Make Habitat Hop A-Z a habitat-fit matrix: forest, open grassland, desert, wetland, mountain, marine/ice and freshwater are compared, including animals that use multiple habitats.",
"lyric_identity":"A child places animals into habitat columns but allows overlap; one animal can span more than one box.",
"image_motifs":("camel desert","gorilla forest","flamingo wetland","walrus Arctic coast","yak high mountain"),
"semantic_arc":("forest/open land","dry/wet contrasts","mountain/tropical overlap","marine/freshwater finish"),
"forbidden_generic_language":("four windows glow","one place it may know","one habitat each","habitat hop"),
"rhyme_engine":"habitat-fit-overlap-rhyme","chorus_rhyme_engine":"place-fit-overlap-hook","point_of_view":"a child sorting habitat cards while allowing ecological overlap","chorus_function":"repeat place-fit-overlap","groove_meter":"measured 4/4 sorting pulse","round1_grammar":"hand-written habitat fit and range; overlaps explicit","round2_grammar":"habitat cue -> recall beat -> target -> card-sort gesture",
"intro_lines":("Forest, desert, wetland, mountain, ocean—some animals fit one strongly, others cross several.","Habitat is a relationship, not a single permanent box."),
"hook_lines":("Place, fit, overlap—A-B-C!","One animal can use more than one kind of home."),
"outro_lines":("Walrus stays coastal; Yak stays high; Jaguar can cross forest and wetland.","A to Z leaves the habitat cards connected, not isolated."),
"round2_patterns":("Habitat {letter} ... {object}! {action}","Fit {letter} ... {object}! {action}","One or many—{letter}? ... {object}! {action}","Place card {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Ape! Apes occupy African/Asian forests and, for some, mosaics of woodland/grassland | broad category needs species detail."),
("B","B ... B ... Baboon! Many baboons use savanna, woodland and rocky habitats | adaptable ground-traveling primates."),
("C","C? Camel! Dromedary and Bactrian camels suit arid environments | broad padded feet and fat-storing humps support dry-land life."),
("D","D is Deer. Deer species occupy forests, grasslands, wetlands and tundra edges | not one habitat box."),
("E","E — Elephant! African and Asian elephants use forests, savannas, grasslands and wetlands depending species/population."),
("F","F ... F ... Flamingo! Shallow saline/alkaline lakes, lagoons and wetlands provide filter-feeding habitat."),
("G","G? Gorilla! Central African forest great ape | dense vegetation and fruit/leaf resources define the core habitat."),
("H","H is Hyena. Species range from savanna and scrub to desert/woodland | not only open grassland."),
("I","I — Iguana! Mostly tropical American lizards using trees, ground, islands or rocky coast depending species."),
("J","J ... J ... Jaguar! Forest, wetland, scrub and grassland can all support jaguars | strong swimmer as well as land predator."),
("K","K? Koala! Australian eucalyptus woodland/forest specialist | tree food makes habitat unusually specific."),
("L","L is Lemur. Madagascar primates occupy rainforest, dry forest, spiny forest and more | island diversity creates many habitat fits."),
("M","M — Meerkat! Southern African arid/open habitats | burrows help manage heat and predation."),
("N","N ... N ... Nyala! Southern African antelope favors dense woodland/thickets near water | cover matters."),
("O","O? Ostrich! Open African savanna and semi-arid habitats | running body fits wide ground space."),
("P","P is Panda. Giant panda lives in cool mountain forests with abundant bamboo | specialized forest-mountain overlap."),
("Q","Q — Quokka! Southwestern Australian marsupial using dense vegetation and island/mainland habitats | not desert stereotype."),
("R","R ... R ... Red Panda! Himalayan temperate mountain forest with bamboo understory | forest plus elevation."),
("S","S? Seal! Marine/coastal mammal uses ocean for feeding and land/ice for haul-out depending species."),
("T","T is Tapir. Tropical forest and wet habitats in Central/South America or Southeast Asia depending species | water often nearby."),
("U","U — Urial! Dry mountain slopes, steppe and rocky terrain across Central/South Asia."),
("V","V ... V ... Vulture! Habitat follows food, cliffs/trees for roosting, and soaring conditions | open landscapes often useful."),
("W","W? Walrus! Arctic/sub-Arctic marine mammal tied to shallow seas, coasts and sea ice | not temperate zoo-water generic."),
("X","X is Xenopus. African clawed frog genus lives fully aquatic in freshwater | pond/stream system, not dry land."),
("Y","Y — Yak! Domestic/wild yak adapted to high Tibetan Plateau and Himalayan-region cold uplands | elevation and cold define the card."),
("Z","Z ... Z ... Zebra! African grasslands and open woodlands depending species | grazing habitat closes the matrix."),),
"style_blueprint":"Crisp diction. Open with five habitat columns and overlap at 84 BPM measured 4/4 with acoustic guitar, bass, soft shaker and marimba. Melody narrow. Arrangement shifts gently by habitat without stereotypes. Round 1 allows multiple habitats and range differences. Chorus place-fit-overlap. Round 2 uses card-sort gestures. Duck targets. End with connected habitat cards."},
"0079":{
"authorial_intent":"Make Wild World Letter Song a biogeography song: continents, islands and mountain belts explain why similarly sized animals never naturally meet, replacing generic safari percussion with a world distribution map.",
"lyric_identity":"A child draws range shapes and compares convergent roles across continents—lion versus puma, vicuna versus urial, koala versus panda.",
"image_motifs":("lion Africa map","puma Americas map","koala Australia","vicuna Andes","Xenopus Africa water"),
"semantic_arc":("Africa/Eurasia","Asia/Australia","Americas","islands/mountains and cross-continent comparison"),
"forbidden_generic_language":("soft safari drum","wild world beat","all animals together","jungle world"),
"rhyme_engine":"biogeography-range-contrast-rhyme","chorus_rhyme_engine":"range-region-compare-hook","point_of_view":"a child comparing geographic ranges","chorus_function":"repeat range-region-compare","groove_meter":"steady 4/4 map-drawing pulse","round1_grammar":"hand-written range; similar roles contrasted across continents","round2_grammar":"range cue -> recall beat -> target -> map gesture",
"intro_lines":("Lion in Africa; Puma in the Americas; Koala in Australia.","Wildlife shares one planet without sharing one neighborhood."),
"hook_lines":("Range, region, compare—A-B-C!","Same planet, different maps."),
"outro_lines":("Andes, Himalaya, Africa, Australia—the range lines stay separate.","A to Z ends with one world made of many biogeographic stories."),
"round2_patterns":("Range {letter} ... {object}! {action}","Region {letter} ... {object}! {action}","Which map {letter}? ... {object}! {action}","World clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Antelope! Broad hoofed-animal term mainly across Africa/Eurasia | many unrelated-looking species share grazing/browsing roles."),
("B","B ... B ... Baboon! African/Arabian primate | ground travel contrasts with arboreal monkeys elsewhere."),
("C","C? Camel! Dromedary roots in arid Africa/Arabia; Bactrian camels in Central Asia | one word spans two camel species."),
("D","D is Deer. Deer family ranges across much of Eurasia and the Americas | species replace each other geographically."),
("E","E — Emu! Australian flightless bird | geographic isolation helped produce a distinctive large-running bird fauna."),
("F","F ... F ... Fox! Foxes occupy several continents | species and climate define the actual range."),
("G","G? Gorilla! Central African great ape | no wild gorillas outside Africa."),
("H","H is Hyena. Hyenas are Old World carnivores, with living species centered in Africa and parts of Asia."),
("I","I — Ibex! Wild goats of Eurasian/African mountain systems depending species | high rock repeats across regions."),
("J","J ... J ... Jackal! Old World canids across Africa/Eurasia | different from coyotes of the Americas."),
("K","K? Koala! Native to eastern/southeastern Australia | eucalyptus specialization anchors the range."),
("L","L is Lion. Native wild lions survive mainly in sub-Saharan Africa plus a small population in India | range is not simply 'Africa only'."),
("M","M — Monkey! Broad term includes New World and Old World lineages | geography helps separate them."),
("N","N ... N ... Nyala! Southern African antelope | regional range much smaller than the word antelope suggests."),
("O","O? Okapi! Endemic to rainforests of the Democratic Republic of the Congo | giraffe relative with a narrow African range."),
("P","P is Panda. Giant panda is native to central Chinese mountain forests | not a global bamboo animal."),
("Q","Q — Quokka! Southwestern Australian marsupial, especially famous on offshore islands | tiny geographic footprint."),
("R","R ... R ... Rhino! Living rhinos occur naturally in parts of Africa and Asia | two continents, several species."),
("S","S? Serval! African spotted cat tied strongly to grassland/wetland mosaics | different continent from puma."),
("T","T is Tapir. Tapirs occur in Central/South America and Southeast Asia | separated lineages on distant continents."),
("U","U — Urial! Central/South Asian wild sheep | high dry range contrasts with Andean Vicuna."),
("V","V ... V ... Vicuna! Wild South American camelid of the Andes | continent and elevation define it."),
("W","W? Wolf! Gray wolves range across portions of Eurasia and North America | broad northern distribution."),
("X","X is Xenopus. African aquatic frog genus | freshwater range keeps X grounded in Africa."),
("Y","Y — Yellow Mongoose! Southern African species | another compact regional range."),
("Z","Z ... Z ... Zebu! Domestic humped cattle spread widely through human agriculture | current distribution reflects people as much as wild biogeography."),),
"style_blueprint":"Crisp diction. Open with three continent contrasts at 86 BPM in steady 4/4 with acoustic guitar, soft bass, woodblock and marimba. No safari-drum cliché or regional caricature. Melody narrow. Round 1 is range-first. Chorus range-region-compare. Round 2 uses air-map gestures. Duck targets. End with separate map lines on one globe."},
"0080":{
"authorial_intent":"Make Zoo Explorer Trail a welfare-and-field-note protocol: read signage, observe at distance, distinguish natural behavior from visitor expectation, and connect zoo education to conservation without claiming every facility is equal.",
"lyric_identity":"A child ranger records one behavior, one habitat clue and one unanswered question per exhibit; hidden animals count as a valid observation.",
"image_motifs":("signboard range map","tiger hidden in shade","vulture soaring enclosure","walrus pool/haulout","quokka rest area"),
"semantic_arc":("read signs","observe behavior","respect rest/privacy","connect range/conservation questions"),
"forbidden_generic_language":("ranger eyes ready","safely into picture space","zoo explorer fun","make animal come closer"),
"rhyme_engine":"zoo-fieldnote-question-rhyme","chorus_rhyme_engine":"read-watch-question-hook","point_of_view":"a child making respectful zoo field notes","chorus_function":"repeat read-watch-question","groove_meter":"walking 4/4 notebook pulse","round1_grammar":"hand-written sign+behavior+range; privacy/welfare explicit","round2_grammar":"field-note cue -> recall beat -> target -> point/sketch gesture",
"intro_lines":("Read the range map. Watch one behavior. Leave one question unanswered.","A zoo explorer learns without asking an animal to perform."),
"hook_lines":("Read, watch, question—A-B-C!","A hidden animal can still teach us patience."),
"outro_lines":("Notebook closes while the tiger stays in shade and the walrus rests.","A to Z leaves with questions, not demands."),
"round2_patterns":("Field note {letter} ... {object}! {action}","Sign/behavior {letter} ... {object}! {action}","What notice {letter}? ... {object}! {action}","Explorer note {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Antelope! Read the species name before assuming one antelope body fits all | horns, range and habitat vary."),
("B","B ... B ... Bison! North American/European bison species are massive grazers | signage distinguishes them from buffalo."),
("C","C? Camel! One or two humps depends on camel species | fat storage, not water tanks."),
("D","D is Deer. Antlers occur mainly in males of most deer species and are shed/regrown | sign prevents oversimplification."),
("E","E — Elephant! Watch trunk exploration, foraging and social behavior | welfare requires complexity and choice."),
("F","F ... F ... Flamingo! Filter feeding, preening and flocking reveal more than pink color | distance protects the group."),
("G","G? Giraffe! Long tongue and neck support browsing | social and movement space matter beyond height."),
("H","H is Hippo. Water use and nighttime grazing shape its behavior | never confuse stillness with harmlessness."),
("I","I — Ibex! Rocky terrain lets sure-footed movement appear naturally | observe rather than coax climbing."),
("J","J ... J ... Jackal! Wild canid behavior may include resting, scent investigation, foraging or social interaction | no dog-like pet expectation."),
("K","K? Koala! Long rest periods are normal because eucalyptus diet is low-energy | sleeping is a valid observation."),
("L","L is Lemur. Madagascar primates vary widely by species | sign gives exact species before we generalize."),
("M","M — Monkey! 'Monkey' is too broad for a field note | write the actual species from signage."),
("N","N ... N ... Nyala! Shy woodland antelope may use cover | hidden behavior can be normal and welfare-positive."),
("O","O? Ostrich! Flightless running bird needs ground space | wings still serve display/balance roles."),
("P","P is Puma. Solitary American cat also called cougar/mountain lion | cover and privacy are important behavior choices."),
("Q","Q — Quokka! Australian marsupial | visitor popularity never makes touching or feeding appropriate."),
("R","R ... R ... Red Panda! Arboreal Himalayan mammal | climbing, resting and scent behavior belong in a complex habitat."),
("S","S? Serval! African cat with long legs and huge ears | listening and pouncing behavior may appear without visitor prompts."),
("T","T is Tiger. Solitary Asian cat | a hidden/resting tiger is not a failed exhibit moment."),
("U","U — Uakari! Amazonian monkey with unusual short tail and bare face | species sign anchors tropical range."),
("V","V ... V ... Vulture! Scavenger ecology is essential ecosystem work | soaring or resting replaces villain stereotypes."),
("W","W? Walrus! Arctic marine mammal uses water and haul-out surfaces | tusks are real tools/traits, not props."),
("X","X is Xerus. African ground squirrel | digging and social vigilance make small-animal behavior worth watching."),
("Y","Y — Yellow Mongoose! Southern African ground predator | small size does not make it a pet."),
("Z","Z ... Z ... Zebu! Domestic cattle type | zoo/farm education should label domestication clearly beside wild animals."),),
"style_blueprint":"Crisp diction. Open with sign-read/watch/question protocol at 84 BPM in walking 4/4 with acoustic guitar, brush, bass and sparse marimba. Melody narrow. Round 1 treats hidden/resting behavior as valid and uses exact species signage. Chorus read-watch-question. Round 2 uses notebook/point gestures. No feeding, tapping, chasing, calling, or touching. Duck targets. End with unanswered-question cadence."}
}
