from __future__ import annotations

"""Authorial-identity deep polish for reptile/amphibian songs 0081-0085."""

GOLD_V5_81_85_SPEC_PATCHES: dict[str, dict[str, object]] = {
"0081":{
"authorial_intent":"Make Scales and Ponds ABC a reptile-versus-amphibian comparison built around skin, eggs, life cycle, habitat and breathing, rather than mixing every herp into one pond rhyme.",
"lyric_identity":"A child sorts pond-edge animals into amphibian and reptile columns while allowing semi-aquatic reptiles to cross the water edge.",
"image_motifs":("axolotl external gills","chameleon dry scales","newt pond edge","crocodile waterline","slider basking log"),
"semantic_arc":("amphibian water-linked life","reptile dry-scaled bodies","semi-aquatic overlap","taxonomy recap"),
"forbidden_generic_language":("frogs scales shells","all pond creatures","slimy reptiles","pond friends"),
"rhyme_engine":"herp-amphibian-reptile-contrast-rhyme","chorus_rhyme_engine":"skin-stage-habitat-hook","point_of_view":"a child classifying herps by body and life-history traits","chorus_function":"reset skin-stage-habitat","groove_meter":"measured 4/4 pond-edge pulse","round1_grammar":"hand-written taxonomy and habitat; venomous/dangerous species image-only","round2_grammar":"class cue -> recall beat -> target -> point/sort gesture",
"intro_lines":("Axolotl gills in water; chameleon scales on a branch; both are herps, but not the same class.","Pond edge is where amphibian and reptile stories can meet."),
"hook_lines":("Skin, stage, habitat—A-B-C!","Amphibian or reptile? Check more than the shape."),
"outro_lines":("Newt returns to the amphibian side; slider basks on the reptile side.","A to Z ends with the pond edge connected, not confused."),
"round2_patterns":("Class clue {letter} ... {object}! {action}","Pond/land {letter} ... {object}! {action}","Amphibian or reptile—{letter}? ... {object}! {action}","Herp clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Axolotl! Aquatic salamander that usually keeps external larval gills as an adult | amphibian, not fish."),
("B","B ... B ... Bullfrog! Large frog with strong hind legs | amphibian life begins in water as tadpoles."),
("C","C? Chameleon! Dry-scaled lizard with gripping feet and independently moving eyes | reptile."),
("D","D is Dragon Lizard. Project lizard picture with four limbs, claws and long tail | reptile mapping, not a mythical dragon."),
("E","E — Eastern Newt! Salamander with aquatic and terrestrial stages depending life phase | amphibian skin stays permeable."),
("F","F ... F ... Frog! Amphibian with moist permeable skin and powerful hind limbs | eggs usually lack hard shells."),
("G","G? Garter Snake! Slender North American snake | reptile with scales and no limbs."),
("H","H is Horned Lizard. Spiny-bodied lizard of dry North American habitats | reptile adapted far from ponds."),
("I","I — Iguana! Scaled lizard with long tail | reptile requiring external heat sources for thermoregulation."),
("J","J ... J ... Jumping Frog! Frog mapping emphasizes strong hind-leg locomotion | amphibian, not tiny reptile."),
("K","K? Komodo Dragon! World's largest living lizard | venomous monitor lizard, dangerous and distance-only."),
("L","L is Lizard. Reptile group with scales and usually four limbs | enormous diversity beyond one body color."),
("M","M — Mudpuppy! Fully aquatic salamander retaining external gills | amphibian specialized for freshwater."),
("N","N ... N ... Nile Crocodile! Large African semi-aquatic reptile | water use does not make it amphibian."),
("O","O? Olive Python! Large Australian python | nonvenomous constricting snake, still observe-only."),
("P","P is Python. Snake family kills prey mainly by constriction rather than venom | reptile."),
("Q","Q — Queensland Frog! Project frog mapping from Queensland | amphibian clue without inventing one exact species."),
("R","R ... R ... Rattlesnake! Venomous pit viper with tail rattle | reptile, never approach or handle."),
("S","S? Salamander! Amphibian with tail in adult form | many species rely on moist habitats or water."),
("T","T is Toad. Frog-family amphibian with generally drier, bumpier skin than many frogs | still an amphibian."),
("U","U — Urutu Snake! Venomous South American pit viper | scaled reptile, image-only safety target."),
("V","V ... V ... Veiled Chameleon! Arboreal lizard with casque and grasping feet | reptile."),
("W","W? Water Dragon! Semi-aquatic lizard | reptile that uses water for escape and habitat without amphibian skin."),
("X","X is Xenopus. African clawed frog genus fully aquatic as adults | amphibian with powerful webbed hind feet."),
("Y","Y — Yellow-bellied Slider! Freshwater turtle that basks on logs and banks | reptile with shell and scales."),
("Z","Z ... Z ... Zigzag Salamander! Salamander mapping clue | amphibian, with exact species traits kept to the provided image/label."),),
"style_blueprint":"Crisp diction. Open with axolotl-versus-chameleon at 86 BPM measured 4/4 with acoustic guitar, marimba, soft shaker and bass. Melody narrow. Round 1 repeatedly distinguishes amphibian/reptile and water use versus class. Chorus skin-stage-habitat. Round 2 uses sort/point gestures only. Venomous snakes, Komodo and crocodile are image-only. Duck targets. End with two connected classification columns."},
"0082":{
"authorial_intent":"Make Frog Snake Turtle Song a body-defense and safety comparison: constriction, venom, shell, camouflage, frill, gripping toes and moist skin are distinct adaptations, with no child imitation of attack behavior.",
"lyric_identity":"A child reads defense/feeding structures from pictures and keeps dangerous animals at visual distance.",
"image_motifs":("box turtle shell","king cobra hood","frilled lizard display","tree boa coil","poison frog warning color"),
"semantic_arc":("snake defenses","lizard displays/grip","frog skin/color","turtle shell and safety recap"),
"forbidden_generic_language":("sss picture sound","snake play","touch the scales","all reptiles bite"),
"rhyme_engine":"herp-defense-safe-observation-rhyme","chorus_rhyme_engine":"shell-scale-signal-hook","point_of_view":"a child comparing defensive structures from safe images","chorus_function":"repeat shell-scale-signal","groove_meter":"stop-go 4/4 safety pulse","round1_grammar":"hand-written adaptations; danger not dramatized as play","round2_grammar":"defense cue -> recall beat -> target -> abstract shape gesture",
"intro_lines":("A shell closes. A cobra raises a hood. A frog's color can warn.","Defense is something we study, not something we test."),
"hook_lines":("Shell, scale, signal—A-B-C!","Look at the adaptation; leave the animal space."),
"outro_lines":("Hands stay back; every defense stays with the animal.","A to Z closes the picture guide safely."),
"round2_patterns":("Defense clue {letter} ... {object}! {action}","Body signal {letter} ... {object}! {action}","Shell, scale, or skin—{letter}? ... {object}! {action}","Safe-view {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Alligator! Armored skin, broad snout and powerful tail | large crocodilian, always distance-only."),
("B","B ... B ... Boa! Heavy-bodied nonvenomous snake that constricts prey | coiling is feeding biology, not a handling game."),
("C","C? Chameleon! Color change helps signaling and physiology as well as camouflage | gripping feet anchor the lizard."),
("D","D is Dragon Lizard. Project lizard target with claws and long tail | exact species left unspecified."),
("E","E — Emerald Tree Boa! Green arboreal boa coils on branches | nonvenomous constrictor, observe-only."),
("F","F ... F ... Frilled Lizard! Neck frill expands in defensive/display behavior | warning display means give space."),
("G","G? Gecko! Adhesive toe structures help many geckos cling to surfaces | escape and camouflage differ by species."),
("H","H is Horned Lizard. Spiny scales and flattened body aid defense/camouflage | some species can squirt blood from eyes as extreme defense."),
("I","I — Italian Newt! Amphibian with moist skin and aquatic breeding | not a scaled reptile."),
("J","J ... J ... Jackson Chameleon! East African chameleon; males often carry three facial horns | visual signal, not a weapon for us to imitate."),
("K","K? King Cobra! World's longest venomous snake | hood display and venom demand complete distance."),
("L","L is Leopard Gecko. Ground-dwelling gecko with spotted pattern and movable eyelids | tail can store fat and may be shed defensively."),
("M","M — Monitor Lizard! Active predatory lizard group | strong claws/tails and species size require respectful distance."),
("N","N ... N ... Nile Crocodile! Armored semi-aquatic predator | still water posture hides powerful movement."),
("O","O? Ornate Box Turtle! Terrestrial turtle can close hinged plastron tightly | shell is living skeleton, not a removable house."),
("P","P is Poison Frog. Some wild poison frogs carry skin toxins derived largely from diet | never touch wild frogs; captive toxicity can differ."),
("Q","Q — Queensland Frog! Project frog target | moist amphibian skin is the reliable class clue."),
("R","R ... R ... Red-eyed Tree Frog! Arboreal frog with gripping toe pads | bright eyes/colors may startle predators."),
("S","S? Salamander! Amphibian whose skin can produce defensive secretions in some species | gentle observation only."),
("T","T is Toad. Many toads have parotoid glands producing defensive toxins | do not handle or let pets mouth them."),
("U","U — Uromastyx! Spiny-tailed herbivorous lizard | tail helps defense, while basking supports thermoregulation."),
("V","V ... V ... Viper! Venomous snake family with hinged fangs in many species | image-only target."),
("W","W? Water Dragon! Semi-aquatic lizard can flee into water | long tail aids swimming and balance."),
("X","X is Xenosaurus. Knob-scaled lizard genus from Mexico/Central America | crevice-dwelling body, not a fantasy monster."),
("Y","Y — Yellow-bellied Slider! Freshwater turtle with shell and yellow markings | defensive response is withdrawal, not a toy trick."),
("Z","Z ... Z ... Zigzag Salamander! Salamander mapping clue | amphibian safety stays no handling unless expert care context."),),
"style_blueprint":"Crisp diction. Open with shell/hood/color signals at 88 BPM stop-go 4/4 with acoustic guitar, low marimba, soft drum and shaker. Melody narrow. Round 1 treats defenses as observation, never performance. Chorus shell-scale-signal. Round 2 uses abstract hand shapes only—no striking, squeezing, biting, catching, or touching. Duck targets. End with hands-back quiet."},
"0083":{
"authorial_intent":"Make Scales and Slime Rhyme a skin-and-moisture lesson: reptile keratin scales, amphibian permeable skin, mucus, aquatic gills and shells are compared without using 'slimy' as an insult.",
"lyric_identity":"A child notices surface texture and moisture as physiology, not gross-out comedy.",
"image_motifs":("axolotl gills","frog moist skin","boa scales","box turtle shell","hellbender folded skin"),
"semantic_arc":("amphibian moisture","reptile scales","aquatic specializations","skin protection and habitat"),
"forbidden_generic_language":("slime rhyme gross","slimy creature","scales shine parade","eww"),
"rhyme_engine":"skin-moisture-physiology-rhyme","chorus_rhyme_engine":"scale-skin-water-hook","point_of_view":"a child comparing skin physiology respectfully","chorus_function":"repeat scale-skin-water","groove_meter":"gentle 6/8 wet-dry contrast","round1_grammar":"hand-written skin/moisture facts; no touching wildlife","round2_grammar":"surface cue -> recall beat -> target -> visual texture gesture",
"intro_lines":("Boa scales keep water in; frog skin must stay moist; axolotl gills wave outside the body.","Skin tells a habitat story."),
"hook_lines":("Scale, skin, water—A-B-C!","Texture is biology, not a joke."),
"outro_lines":("Rain darkens the log; no salamander is picked up to prove the lesson.","A to Z leaves every skin doing its own job."),
"round2_patterns":("Surface clue {letter} ... {object}! {action}","Wet/dry {letter} ... {object}! {action}","Scale or skin—{letter}? ... {object}! {action}","Texture {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Axolotl! Aquatic salamander retains feathery external gills | soft permeable amphibian skin stays underwater."),
("B","B ... B ... Boa! Keratinized reptile scales reduce water loss and protect the body | dry to the touch in normal conditions."),
("C","C? Crocodile! Tough scales and bony scutes armor a semi-aquatic reptile | water habitat does not mean amphibian skin."),
("D","D is Dart Frog. Moist amphibian skin supports gas/water exchange | bright color in many species warns predators."),
("E","E — Eastern Newt! Amphibian skin changes with aquatic/terrestrial life stages | moisture remains important."),
("F","F ... F ... Frog! Mucus helps keep permeable skin moist | healthy 'slime' is functional biology."),
("G","G? Garter Snake! Smooth/keeled scale patterns vary by species | scales protect a limbless reptile."),
("H","H is Hellbender. Giant aquatic salamander with folded skin increasing surface area | fully amphibian despite wrinkled appearance."),
("I","I — Italian Newt! Newt skin is permeable and glandular | aquatic breeding links it to water."),
("J","J ... J ... Jackson Chameleon! Scaled skin changes appearance through specialized cells | reptile surface, not wet frog skin."),
("K","K? Komodo Dragon! Large monitor lizard with scaled skin | venomous bite biology keeps it distance-only."),
("L","L is Leopard Gecko. Granular/tubercled scales and eyelids distinguish this gecko | dry-land reptile."),
("M","M — Mudpuppy! Aquatic salamander with external gills and permeable skin | freshwater specialist."),
("N","N ... N ... Newt! Salamander family member with permeable skin | toxins in some species reinforce no-handling."),
("O","O? Ornate Box Turtle! Scales cover limbs while shell encloses trunk | reptile surfaces combine keratin and bone."),
("P","P is Python. Smooth overlapping scales cover a muscular snake | shedding replaces the outer skin layer."),
("Q","Q — Queen Snake! North American semi-aquatic snake that often eats freshly molted crayfish | reptile scales remain dry-skin adaptation."),
("R","R ... R ... Red-eyed Tree Frog! Moist skin and adhesive toe pads support arboreal amphibian life."),
("S","S? Salamander! Permeable moist skin makes many species sensitive to dehydration and contaminants."),
("T","T is Turtle. Shell is bony skeleton covered by scutes in many species | not a loose external object."),
("U","U — Uromastyx! Dry-land lizard with spiny scaled tail | arid habitat contrasts sharply with salamanders."),
("V","V ... V ... Viper! Scaled venomous snake | surface pattern helps camouflage but does not make handling safe."),
("W","W? Wood Frog! Amphibian survives seasonal freezing of much body water in winter | moist skin returns to active spring life."),
("X","X is Xenosaurus. Knob-scaled lizard | textured reptile skin fits rocky crevices."),
("Y","Y — Yellow Anaconda! Large semi-aquatic boa relative with scales | wet habitat, reptile skin."),
("Z","Z ... Z ... Zebra Skink! Striped skink mapping clue | smooth scales and limbs mark a lizard."),),
"style_blueprint":"Crisp diction. Open with boa/frog/axolotl skin contrast at 82 BPM gentle 6/8 with nylon guitar, soft marimba droplets, bass and brush. Melody narrow. Use dry percussion for reptile scales and legato water texture for amphibian skin without gross SFX. Chorus scale-skin-water. Round 2 uses air-texture gestures only; no touching. Duck targets. End with rain-on-log ambience."},
"0084":{
"authorial_intent":"Repair Cold-Blooded Creatures into an ectothermy song: reptiles and amphibians rely strongly on external heat sources and behavioral thermoregulation, but their blood is not simply 'cold'.",
"lyric_identity":"A child follows sun, shade, burrow and water as temperature choices; color/pattern is secondary.",
"image_motifs":("uromastyx basking","snake shade","turtle sunning","frog cool water","chameleon moving between sun/shade"),
"semantic_arc":("bask/warm","seek shade/cool","water/burrow buffering","ectothermy recap"),
"forbidden_generic_language":("cold blood means cold","pattern parade","all bask in sun","scale shine"),
"rhyme_engine":"ectothermy-thermal-choice-rhyme","chorus_rhyme_engine":"warm-shade-move-hook","point_of_view":"a child mapping behavioral thermoregulation","chorus_function":"repeat warm-shade-move","groove_meter":"4/4 with warm/cool arrangement contrast","round1_grammar":"hand-written thermal behavior; no universal basking claim","round2_grammar":"temperature cue -> recall beat -> target -> safe sun/shade gesture",
"intro_lines":("A lizard warms in sun, then chooses shade; a frog may use cool water instead.","Ectotherm does not mean the body stays cold."),
"hook_lines":("Warm, shade, move—A-B-C!","Behavior helps body temperature track the environment."),
"outro_lines":("Sun patch empties as the animal chooses a cooler place.","A to Z ends with temperature as a moving balance."),
"round2_patterns":("Thermal clue {letter} ... {object}! {action}","Warm/cool {letter} ... {object}! {action}","Sun, shade, or water—{letter}? ... {object}! {action}","Ectotherm {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Alligator! Ectothermic crocodilian moves between water, sun and shade to regulate body temperature."),
("B","B ... B ... Boa! Snake thermoregulates by choosing warmer/cooler microhabitats | no internal furnace like a bird or mammal."),
("C","C? Crocodile! Basking warms; water can cool or buffer temperature | behavior changes through the day."),
("D","D is Dart Frog. Small amphibian avoids overheating/desiccation in humid shaded microhabitats | thermoregulation includes staying cool."),
("E","E — Emerald Tree Boa! Arboreal snake chooses branch positions and microclimates | warmth does not mean endless direct sun."),
("F","F ... F ... Frilled Lizard! Australian lizard can bask to warm, then retreat from excess heat | frill is not a thermostat."),
("G","G? Garter Snake! May bask in cool conditions and seek shelter when hot | temperature choice changes seasonally."),
("H","H is Hellbender. Cool flowing streams buffer this aquatic salamander | ectothermy can be water-based rather than basking."),
("I","I — Iguana! Basking raises body temperature; shade helps prevent overheating | heat gradient matters in captive care."),
("J","J ... J ... Jumping Frog! Amphibian may use water, shade and activity timing to manage heat/moisture."),
("K","K? Komodo Dragon! Large ectothermic lizard warms through sun and environment | size affects heating/cooling rate but does not make it endothermic."),
("L","L is Lizard. Broad reptile group showing many thermoregulatory strategies | one sun-basking picture is not universal."),
("M","M — Monitor Lizard! Active lizards often shuttle between heat and shade | behavioral control supports activity."),
("N","N ... N ... Newt! Amphibian thermal choices are constrained by moisture | cool damp refuges can be critical."),
("O","O? Olive Python! Large snake selects thermal zones for digestion/activity | safe distance only."),
("P","P is Python. Ectothermic snake uses environmental heat | some brooding pythons can generate limited muscular heat, an interesting exception."),
("Q","Q — Queen Snake! Semi-aquatic snake uses water and bank microclimates | temperature and prey habitat overlap."),
("R","R ... R ... Rattlesnake! Pit viper chooses sun, shade and shelter | venom makes all observation distance-only."),
("S","S? Skink! Many skinks bask briefly and use cover/burrows | thermal behavior varies by species."),
("T","T is Turtle. Basking turtles warm on logs then return to water | species and weather change the pattern."),
("U","U — Uromastyx! Desert lizard uses strong basking heat but also retreats to burrows | high preferred temperatures still require escape from extremes."),
("V","V ... V ... Veiled Chameleon! Moves through sun/shade and changes body orientation/color partly with thermoregulation and signaling."),
("W","W? Water Dragon! Water offers a cooling/refuge option beside basking sites | semi-aquatic thermoregulation."),
("X","X is Xenosaurus. Crevice-dwelling lizard can use stable rocky microclimates | not every ectotherm sits in open sun."),
("Y","Y — Yellow-bellied Slider! Freshwater turtle basks to warm and support normal physiology | dives back into water as conditions change."),
("Z","Z ... Z ... Zigzag Salamander! Amphibian mapping clue | moisture and cool refuge matter more than a hot basking rock."),),
"style_blueprint":"Crisp diction. Open with sun-to-shade choice at 86 BPM in 4/4 with acoustic guitar, warm marimba, cool soft pad, bass and brush. Melody narrow. Arrangement warms in register for basking lines and thins/cools for shade/water. Round 1 explicitly defines ectothermy behaviorally. Chorus warm-shade-move. Round 2 uses sun/shade hand positions only. Duck targets. End in a cooler refuge texture."},
"0085":{
"authorial_intent":"Repair Reptile House Walk into a herpetarium microclimate tour because the mapping contains amphibians: each enclosure is read for heat, humidity, water, substrate, hiding and UVB needs, with no tapping or handling.",
"lyric_identity":"A child reads enclosure labels and environmental controls rather than asking animals to swim/crawl/hop on cue.",
"image_motifs":("frog humid terrarium","gecko hide","Komodo barrier","box turtle substrate","Xenopus aquarium"),
"semantic_arc":("wet amphibian habitats","dry/arboreal reptile habitats","dangerous species barriers","microclimate/welfare recap"),
"forbidden_generic_language":("reptile house all reptiles","moves low","make it hop","tap glass"),
"rhyme_engine":"herpetarium-microclimate-rhyme","chorus_rhyme_engine":"heat-water-hide-hook","point_of_view":"a child reading herpetarium enclosure needs","chorus_function":"repeat heat-water-hide","groove_meter":"calm 4/4 exhibit-control pulse","round1_grammar":"hand-written microclimate; amphibians labeled correctly","round2_grammar":"enclosure cue -> recall beat -> target -> point-to-feature gesture",
"intro_lines":("One enclosure is humid for a frog; another has basking heat for a lizard.","This house holds reptiles and amphibians, so the microclimate must change."),
"hook_lines":("Heat, water, hide—A-B-C!","Build the enclosure around the species, not the sign color."),
"outro_lines":("Glass stays untapped; every hide remains available.","A to Z leaves each microclimate doing its quiet work."),
"round2_patterns":("Enclosure {letter} ... {object}! {action}","Microclimate {letter} ... {object}! {action}","Heat, water, or hide—{letter}? ... {object}! {action}","House clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Alligator! Large crocodilian requires professional-scale water/land habitat and secure barriers | not a home-terrarium animal."),
("B","B ... B ... Bullfrog! Amphibian tied to freshwater/wetland conditions | humidity/water quality matter, not reptile basking alone."),
("C","C? Crocodile! Large dangerous crocodilian | professional barrier, water and haul-out design dominate the enclosure."),
("D","D is Dart Frog. Small amphibian needs humid planted microhabitat and clean conditions | no handling because skin is delicate/toxic in wild species."),
("E","E — Eastern Newt! Amphibian may need aquatic/terrestrial features depending life stage | habitat must follow biology."),
("F","F ... F ... Frog! Moist permeable skin requires humidity/water appropriate to species | ventilation still prevents stagnant conditions."),
("G","G? Gecko! Gecko care varies widely: arboreal versus terrestrial, humid versus arid | exact species label controls setup."),
("H","H is Horned Lizard. Dry open-habitat specialist | hot basking zone, cooler refuge, substrate and diet differ from frogs."),
("I","I — Iguana! Large arboreal reptile needs major space, heat gradient, humidity, UVB and climbing structure."),
("J","J ... J ... Jumping Frog! Amphibian exhibit needs safe landing/cover and moisture | no visitor cue should provoke jumping."),
("K","K? Komodo Dragon! Giant venomous monitor requires secure professional habitat and trained care | distance is absolute."),
("L","L is Leopard Gecko. Terrestrial gecko needs warm hide, cool hide and appropriate substrate/humidity refuge | not an arboreal chameleon setup."),
("M","M — Monitor Lizard! Species range from modest to huge | enclosure size, heat and water needs must follow exact species."),
("N","N ... N ... Newt! Amphibian; many need cool moist/aquatic environments | label prevents placing it under desert heat."),
("O","O? Ornate Box Turtle! Terrestrial turtle needs floor space, substrate, hides, humidity gradient and appropriate UVB/heat."),
("P","P is Poison Frog. Humid amphibian display | wild toxicity and delicate skin keep hands out."),
("Q","Q — Queen Snake! Semi-aquatic North American snake specialized on crayfish | water/land access and prey ecology shape exhibit design."),
("R","R ... R ... Red-eyed Tree Frog! Arboreal amphibian needs vertical foliage, humidity and clean water access | nighttime activity means daytime rest is normal."),
("S","S? Skink! Care varies by skink species | exact heat, UVB, humidity, substrate and space come from species biology."),
("T","T is Toad. Amphibian needs species-appropriate moisture, substrate and hides | dry-looking skin still remains permeable."),
("U","U — Urutu Snake! Venomous pit viper | secure professional enclosure and no-contact visitor behavior."),
("V","V ... V ... Viper! Venomous snake category | barrier integrity and trained handling protocols belong to professionals."),
("W","W? Wood Frog! Cool-climate amphibian with seasonal freeze tolerance | hot tropical terrarium would be the wrong story."),
("X","X is Xenopus. Fully aquatic African frog genus | filtered water habitat, no basking-rock reptile template."),
("Y","Y — Yellow-bellied Slider! Aquatic turtle needs swimming water, filtration, basking platform, heat and UVB."),
("Z","Z ... Z ... Zigzag Salamander! Salamander mapping clue | cool/moist refuge illustrates the amphibian half of the house."),),
"style_blueprint":"Crisp diction. Open with frog-humidity versus lizard-basking contrast at 84 BPM calm 4/4 with nylon guitar, soft bass, marimba and subtle water/wood percussion. Melody narrow. Round 1 moves enclosure to enclosure by microclimate, explicitly calling amphibians amphibians. Chorus heat-water-hide. Round 2 uses point-to-imaginary-control gestures only. No tapping, handling, feeding, or attack SFX. Duck targets. End with enclosure lights dimming."}
}
