from __future__ import annotations

"""Authorial-identity deep polish for bird songs 0066-0070."""

GOLD_V5_66_70_SPEC_PATCHES: dict[str, dict[str, object]] = {
"0066": {
"authorial_intent":"Make Birdsong Alphabet an acoustic field guide: song, call, coo, drumming, silence and non-vocal clues are distinguished instead of forcing every bird into tweeting.",
"lyric_identity":"A child listens first, then checks bill, habitat and behavior; some targets are heard, some seen, and Nest is evidence rather than a bird.",
"image_motifs":("dove coo","lark song above field","woodpecker drum","owl call at dusk","kiwi quiet on forest floor"),
"semantic_arc":("soft calls","songs and contact calls","non-vocal sound and silence","visual clues and final listening map"),
"forbidden_generic_language":("tweet tweet every bird","morning melody","all birds sing","feathered clue"),
"rhyme_engine":"bird-acoustic-source-rhyme","chorus_rhyme_engine":"call-song-drum-hook","point_of_view":"a child building a listening map without assuming every bird sings","chorus_function":"reset call-song-drum-silence","groove_meter":"airy 4/4 with acoustic gaps","round1_grammar":"hand-written acoustic or visual clue; nest explicit non-bird","round2_grammar":"listen/look cue -> recall beat -> target -> safe gesture",
"intro_lines":("A dove coos. A woodpecker drums. A kiwi may be easier to spot than to hear.","Bird sound has more than one voice."),
"hook_lines":("Call, song, drum—A-B-C!","Listen for the source before you name the bird."),
"outro_lines":("The last call fades; one nest stays silent in the branch.","A to Z closes the listening map without making every bird sing."),
"round2_patterns":("Sound clue {letter} ... {object}! {action}","Listen or look {letter} ... {object}! {action}","Call, song, or sight—{letter}? ... {object}! {action}","Bird map {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Avocet! Long upcurved bill sweeps shallow water | wading shape may identify it before any call."),
("B","B ... B ... Budgie! Small parrot with curved bill and zygodactyl feet | social chirps and chatter can fill a flock."),
("C","C? Cardinal! Stout seed-cracking bill and red adult male plumage in Northern Cardinals | whistles carry through brush."),
("D","D is Dove. Soft coos are classic contact and courtship sounds | rounded body and small head back up the ear clue."),
("E","E — Eagle! Large raptor with hooked bill and broad wings | often a visual sky clue rather than a 'songbird' example."),
("F","F ... F ... Finch! Small seed-eating bird group with varied calls | bill shape differs among species."),
("G","G? Goldfinch! Small finch with conical bill | flight calls and bright plumage can both help identification."),
("H","H is Heron. Long legs, neck, and spear-like bill | harsh croaks may surprise anyone expecting a sweet song."),
("I","I — Ibis! Long downcurved bill probes wet ground | flock calls are only one clue among posture and habitat."),
("J","J ... J ... Junco! Ground-feeding sparrow with simple trills in many populations | white outer tail feathers can flash in flight."),
("K","K? Kiwi! Flightless nocturnal New Zealand bird with nostrils near the bill tip | ground calls replace any wingbeat clue."),
("L","L is Lark. Many larks sing in open habitats, sometimes during display flight | real song example, not a rule for all birds."),
("M","M — Magpie! Corvid with varied calls and complex social behavior | black-white pattern identifies some familiar species."),
("N","N ... N ... Nest! Structure for eggs or young | evidence of bird activity, not a bird and never something to disturb."),
("O","O? Owl! Hoots, screeches, whistles, or other calls vary by species | broad wings can be remarkably quiet in flight."),
("P","P is Parrot. Curved bill and grasping feet | vocal learning is strong in many parrots, but wild calls serve social functions."),
("Q","Q — Quetzal! Tropical trogon with brilliant plumage in some species | calls and long tail coverts can both identify males."),
("R","R ... R ... Robin! Thrush-like song and orange breast identify the American Robin | ground foraging adds a behavior clue."),
("S","S? Sparrow! Broad everyday group name covering many small seed-eating birds | chirps and songs vary widely."),
("T","T is Toucan. Huge colorful bill makes the visual ID first | croaks and rattles sound nothing like a generic tweet."),
("U","U — Upland Sandpiper! Long-necked grassland shorebird relative | distinctive whistled calls carry over open fields."),
("V","V ... V ... Veery! Thrush famous for descending, flute-like song | one strong acoustic specialist in the set."),
("W","W? Woodpecker! Bill strikes wood for feeding and drumming | drumming is mechanical communication, not vocal song."),
("X","X is Xenops. Small tropical bird that searches bark and branches for insects | behavior can identify it when sound does not."),
("Y","Y — Yellow Warbler! Small yellow songbird with thin bill | sweet notes belong to a real songbird, not the whole class Aves."),
("Z","Z ... Z ... Zenaida Dove! Caribbean-region dove with soft cooing calls | dove-like body and voice close the acoustic map."),),
"style_blueprint":"Crisp diction. Open with coo/drum/quiet contrast at 84 BPM in airy 4/4 with acoustic guitar, flute, soft shaker and sparse woodblock. Melody stays narrow around targets. Use vocal-like phrases for songs, dry woodblock only after Woodpecker, and silence for Nest/Kiwi visual moments. Round 1 distinguishes song, call and drumming. Chorus call-song-drum. Round 2 leaves one recall beat. Duck target onsets and end with a true acoustic fade."},
"0067": {
"authorial_intent":"Make Feather Nest Melody about what feathers and nests actually do: insulation, flight, waterproofing, display, egg protection and habitat-specific nest design, while flightless birds remain fully feathered birds.",
"lyric_identity":"A child compares feather function and nesting strategy rather than treating feathers as decoration and nests as one twig cup.",
"image_motifs":("albatross flight feathers","penguin dense feathers","flamingo nest mound","woodpecker cavity","ostrich ground nest"),
"semantic_arc":("feather functions","nest diversity","flightless bird contrasts","habitat and parental-care recap"),
"forbidden_generic_language":("feather nest melody","every nest is twigs","all feathers fly","binocular reply"),
"rhyme_engine":"feather-function-nest-form-rhyme","chorus_rhyme_engine":"feather-shelter-care-hook","point_of_view":"a child comparing feather and nest functions across bird lifestyles","chorus_function":"reset feather-shelter-care","groove_meter":"gentle 6/8 woven-texture sway","round1_grammar":"hand-written feather/nest function; flightless birds explicit","round2_grammar":"function cue -> recall beat -> target -> soft shape gesture",
"intro_lines":("A penguin has feathers without flying; an ostrich nests on the ground; a woodpecker uses a cavity.","Bird feathers and nests solve different problems."),
"hook_lines":("Feather, shelter, care—A-B-C!","One bird flies, one swims, one nests close to earth."),
"outro_lines":("No nest is touched; every feather stays on the bird or ground where found.","A to Z leaves twenty-six different ways to shelter and move."),
"round2_patterns":("Function {letter} ... {object}! {action}","Feather/nest {letter} ... {object}! {action}","Fly, swim, or shelter—{letter}? ... {object}! {action}","Bird-care clue {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Albatross! Long narrow wings suit efficient ocean soaring | dense feathers also insulate the body."),
("B","B ... B ... Bluebird! Small thrush; many species nest in cavities | feathers serve flight and insulation, not only blue color."),
("C","C? Cardinal! Contour feathers shape the body and provide color signals | cup nests are usually hidden in shrubs or dense growth."),
("D","D is Dove. Soft contour feathers cover a compact body | many doves build surprisingly simple platform nests."),
("E","E — Egret! Long plumes can serve display | wetland birds still depend on ordinary body feathers for flight and insulation."),
("F","F ... F ... Flamingo! Feathers gain pink pigments from diet-derived carotenoids | mud mound nests raise eggs above shallow water."),
("G","G? Goose! Down feathers insulate beneath outer feathers | ground nests are often lined with down."),
("H","H is Heron. Long-legged wader builds stick nests in trees, reeds, or colonies depending species | not one universal nest form."),
("I","I — Indian Roller! Blue wing patches flash in flight | cavity nesting keeps eggs inside a sheltered space."),
("J","J ... J ... Jay! Corvid feathers support agile flight | twig-and-root nests hide in branches."),
("K","K? Kingfisher! Compact feathers meet water during plunge dives | many kingfishers excavate nesting tunnels in banks."),
("L","L is Lorikeet. Parrot feathers create bright displays | many nest in tree hollows rather than open cups."),
("M","M — Macaw! Large flight feathers power strong flight | cavity nesting is common among macaws."),
("N","N ... N ... Nest! Any bird-built or selected site for eggs and young | cups, cavities, scrapes, burrows and mounds all count."),
("O","O? Ostrich! Feathers insulate and display but cannot produce flight | eggs lie in a ground scrape nest."),
("P","P is Penguin. Dense overlapping feathers insulate and streamline a swimmer | wings became flippers, yet feathers remain essential."),
("Q","Q — Quetzal! Brilliant body feathers and long tail coverts serve display | nests often occupy cavities in decaying wood."),
("R","R ... R ... Raven! Strong flight feathers carry a large corvid | bulky stick nests may sit on cliffs, trees, or structures."),
("S","S? Sparrow! Small contour and flight feathers manage heat and motion | nest styles vary from cups to cavities."),
("T","T is Toucan. Feathers cover a surprisingly light-bodied bird beneath a huge bill | many toucans use tree cavities for nesting."),
("U","U — Umbrellabird! Male crest and throat structures support display | tropical forest bird, not an umbrella-shaped nest builder."),
("V","V ... V ... Vulture! Broad flight feathers support soaring | nests may be simple scrapes, ledges, or platforms depending species."),
("W","W? Woodpecker! Stiff tail feathers brace against trunks | cavity excavation creates a protected nest chamber."),
("X","X is Xantus Hummingbird. Tiny hummingbird with rapid wingbeats | small cup nest is bound with plant fibers and spider silk."),
("Y","Y — Yellow Warbler! Fine feathers insulate a tiny migrant | cup nest is woven into shrubs or small trees."),
("Z","Z ... Z ... Zenaida Dove! Dove feathers power direct flight | simple twig nests fit the dove end of our nest spectrum."),),
"style_blueprint":"Crisp diction. Open with penguin/ostrich/woodpecker contrasts at 82 BPM in gentle 6/8 with nylon guitar, pizzicato strings, soft brush and flute. Melody narrow. Arrangement changes by function: airy for flight, fluid for penguin, dry for cavity/ground nests. Round 1 teaches feather and nest diversity. Chorus feather-shelter-care. Round 2 uses soft hand shapes; never mime taking feathers or nests. Duck targets. End with a quiet untouched-nest cadence."},
"0068": {
"authorial_intent":"Repair the misleading Backyard Birds theme by turning it into a backyard observation board plus world-comparison cards: local-looking feeder birds sit beside clearly labeled birds from wetlands, tropics, open ocean or Southern Hemisphere habitats.",
"lyric_identity":"A child starts at a yard feeder and compares each unfamiliar card to the backyard baseline, never claiming kiwi, ostrich, avocet or umbrellabird live in the yard.",
"image_motifs":("bluebird on fence","goldfinch at seed head","kiwi world card","ostrich savanna card","avocet wetland card"),
"semantic_arc":("yard baseline","wetland/coastal comparisons","tropical/flightless world cards","return to familiar small birds"),
"forbidden_generic_language":("backyard bird hop","every bird in our yard","feather clue below","all birds visit feeders"),
"rhyme_engine":"backyard-world-comparison-rhyme","chorus_rhyme_engine":"here-there-compare-hook","point_of_view":"a child comparing backyard observations with world bird cards","chorus_function":"reset here-there-compare","groove_meter":"light 4/4 porch pulse with world-card pauses","round1_grammar":"hand-written habitat placement; non-backyard birds explicitly world comparisons","round2_grammar":"here/there cue -> recall beat -> target -> point/card gesture",
"intro_lines":("Bluebird on the fence—then the next card shows a kiwi from New Zealand.","Our backyard is the starting point, not the habitat for every bird in the alphabet."),
"hook_lines":("Here, there, compare—A-B-C!","One yard opens a window to birds around the world."),
"outro_lines":("World cards close; the wren is still near the fence.","A to Z returns home without moving every bird into our backyard."),
"round2_patterns":("Here/there {letter} ... {object}! {action}","Habitat card {letter} ... {object}! {action}","Yard or world—{letter}? ... {object}! {action}","Compare {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Avocet! Wetland wader with upcurved bill | world-comparison card, not a typical backyard feeder bird."),
("B","B ... B ... Bluebird! Cavity-nesting thrush that may use nest boxes and open yards in its range | a genuine yard-edge comparison."),
("C","C? Crane! Tall wetland or grassland bird | far larger and more habitat-specific than a backyard songbird."),
("D","D is Duck. Webbed feet and broad bill suit water | ponds and wetlands, not seed feeders, define the main comparison."),
("E","E — Eagle! Large raptor seen overhead in suitable regions | sky visitor at best, never a feeder-table bird."),
("F","F ... F ... Finch! Small seed-eating finches can appear in gardens and yards | conical bill fits the home baseline."),
("G","G? Goldfinch! Seed specialist often visits gardens or seed heads | one believable backyard-card bird in its native range."),
("H","H is Hummingbird. Nectar-feeding birds may visit flower gardens or feeders in the Americas | hovering sets them apart."),
("I","I — Indian Roller! South Asian bird of open country | world card, not a generic backyard resident."),
("J","J ... J ... Jay! Intelligent corvid; some jays commonly visit yards in their ranges | bold behavior fits the home frame."),
("K","K? Kiwi! Flightless nocturnal bird endemic to New Zealand | world comparison only, never a backyard claim."),
("L","L is Lorikeet. Nectar-feeding parrot of Australasia | may occur in urban areas there, but remains a regional world card."),
("M","M — Magpie! Corvid name covers several regional species | some thrive around people, but location matters."),
("N","N ... N ... Nuthatch! Small trunk-climbing bird that can visit feeders | head-first descent is a useful backyard field mark."),
("O","O? Ostrich! Huge flightless African bird of open habitats | world card deliberately far from the backyard scale."),
("P","P is Parrot. Broad group mostly tropical/subtropical | some urban populations occur, but 'backyard' depends entirely on region."),
("Q","Q — Quail! Ground bird of fields, scrub, or woodland edges | may cross yards locally but does not live on a feeder tray."),
("R","R ... R ... Raven! Large corvid with heavy bill | may occur near people but needs a much wider territory than a yard."),
("S","S? Sparrow! Many sparrows thrive around human spaces | small ground and shrub foraging fits the home comparison."),
("T","T is Tern. Slender coastal or inland-water flyer | world habitat card, not backyard feeder bird."),
("U","U — Umbrellabird! Tropical American forest bird | unmistakable world-comparison species, not a porch visitor."),
("V","V ... V ... Vulture! Soaring scavenger may pass high overhead | never attract or approach for a backyard lesson."),
("W","W? Wren! Tiny energetic songbird often uses dense yard vegetation in its range | home-scale bird with upright tail in many species."),
("X","X is Xantus Hummingbird. Baja California-region hummingbird | geographic range matters before calling it a backyard bird."),
("Y","Y — Yellowhammer! Eurasian bunting of farmland and hedges | regional comparison rather than universal yard species."),
("Z","Z ... Z ... Zebra Finch! Australian grassland finch and common captive bird | world card unless local context truly fits."),),
"style_blueprint":"Crisp diction. Open with bluebird-versus-kiwi card contrast at 90 BPM in light 4/4 with acoustic guitar, soft bass, shaker and short flute motifs. Melody narrow. Home birds get warm porch texture; world cards get brief neutral pauses, not exotic stereotypes. Round 1 repeatedly protects habitat/range. Chorus here-there-compare. Round 2 uses point-to-card gestures. Duck targets. End back at the fence/wren image."},
"0069": {
"authorial_intent":"Make Wing and Water ABC a locomotion-and-habitat comparison: wading legs, webbed feet, diving, soaring, hovering, climbing, ground running and flightlessness replace the false nest-building premise.",
"lyric_identity":"A child tracks how feet, wings, bills and habitat fit movement on water, land, trunk or air.",
"image_motifs":("albatross glide","duck webbed foot","ibis probing","kiwi running","woodpecker climbing trunk"),
"semantic_arc":("ocean/wetland movement","air specialists","ground and flightless birds","tree-climbing and songbird finish"),
"forbidden_generic_language":("build a little nest beat","all birds fly","wingbeat meet","water and land friends"),
"rhyme_engine":"bird-locomotion-habitat-rhyme","chorus_rhyme_engine":"wade-fly-run-hook","point_of_view":"a child comparing locomotion across bird habitats","chorus_function":"reset wade-fly-run-climb","groove_meter":"4/4 with motion-specific pockets","round1_grammar":"hand-written locomotion; flightless species explicit","round2_grammar":"movement cue -> recall beat -> target -> safe abstract gesture",
"intro_lines":("One bird wades. One hovers. One runs because its wings cannot carry it into flight.","Bird movement changes with body and habitat."),
"hook_lines":("Wade, fly, run—A-B-C!","Feet and wings tell different travel stories."),
"outro_lines":("The woodpecker climbs; the swan settles; the kiwi stays on ground.","A to Z ends with movement matched to habitat."),
"round2_patterns":("Move clue {letter} ... {object}! {action}","Habitat/motion {letter} ... {object}! {action}","Wade, fly, or run—{letter}? ... {object}! {action}","Route {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Albatross! Long wings exploit ocean winds for efficient soaring | marine travel covers huge distances."),
("B","B ... B ... Bluebird! Perch-and-fly movement between open ground and branches | small thrush, not water specialist."),
("C","C? Crane! Long legs wade through shallows and stride across wetlands | broad wings handle migration."),
("D","D is Duck. Webbed feet paddle; wings fly in most species | body bridges water and air."),
("E","E — Egret! Long toes and legs move through shallow water | spear-like bill strikes at prey."),
("F","F ... F ... Flamingo! Long legs wade while webbed feet stir shallow water | flight carries flocks between wetlands."),
("G","G? Goldfinch! Small perching bird uses quick wingbeats over land | seed-feeding route differs from waders."),
("H","H is Hummingbird. Rotating wing motion supports hovering and backward flight | extreme air specialist."),
("I","I — Ibis! Long curved bill probes mud while long legs wade | water-edge movement more than swimming."),
("J","J ... J ... Junco! Ground-hopping and short flights through brush | terrestrial songbird pattern."),
("K","K? Kiwi! Flightless bird runs and probes forest floor | tiny vestigial wings do not power flight."),
("L","L is Lark. Ground bird that can launch into display or travel flight | land and air combine."),
("M","M — Macaw! Strong parrot wings cross forest openings | grasping feet handle branches after landing."),
("N","N ... N ... Nuthatch! Strong feet climb trunks and can move head-first downward | tree-surface specialist."),
("O","O? Owl! Broad wings support quiet flight; strong talons seize prey | air movement often begins from a perch."),
("P","P is Parrot. Wings fly; zygodactyl feet climb and grip | bill can help with climbing too."),
("Q","Q — Quail! Ground-running bird with short burst flight | land movement dominates daily life."),
("R","R ... R ... Robin! Runs or hops on ground, then flies to perches | mixed small-land-bird movement."),
("S","S? Swan! Webbed feet paddle and powerful wings fly | long water takeoff needs space."),
("T","T is Tern. Long pointed wings support agile flight over water | many plunge or dip for prey."),
("U","U — Umbrellabird! Tropical forest bird moves between branches and air | display structures do not define locomotion."),
("V","V ... V ... Veery! Thrush walks/hops on forest floor and flies through understory | song is separate from movement."),
("W","W? Woodpecker! Climbing feet and stiff tail brace against trunks | short flights connect trees."),
("X","X is Xantus Hummingbird. Tiny hovering specialist from Baja region | rapid wings contrast with grounded kiwi."),
("Y","Y — Yellow Warbler! Small migratory songbird uses quick flight among shrubs and trees | light body, air route."),
("Z","Z ... Z ... Zenaida Dove! Strong direct flight alternates with ground feeding | closes the land-air comparison."),),
"style_blueprint":"Crisp diction. Open wade/hover/run at 92 BPM in 4/4 with acoustic guitar, hand drum, bass, soft shaker and airy flute. Give waders long steps, hovering tremolo, ground birds short pulses, climbers dry syncopation. Melody narrow. Round 1 explicitly protects Kiwi flightlessness. Chorus wade-fly-run. Round 2 uses hand-level gestures, never literal running/flapping around a room. Duck targets. End by layering water, trunk and ground motifs softly."},
"0070": {
"authorial_intent":"Make Little Birdwatcher a disciplined field-identification song: size, silhouette, bill, legs, flight, habitat and call combine before a name; distance and nest ethics are built in.",
"lyric_identity":"A child birdwatcher records multiple field marks and leaves uncertain IDs open instead of answering every echo instantly.",
"image_motifs":("heron silhouette","kiwi range card","toucan bill","wren tail","upland sandpiper grassland stance"),
"semantic_arc":("silhouette and size","bill/leg traits","habitat and behavior","call plus cautious final ID"),
"forbidden_generic_language":("echoing birdwatch trail","answer with a letter","one clue identifies bird","birdwatch fun"),
"rhyme_engine":"birdwatch-multifieldmark-rhyme","chorus_rhyme_engine":"look-listen-check-hook","point_of_view":"a child making cautious multi-trait bird identifications","chorus_function":"repeat look-listen-check","groove_meter":"steady 4/4 observation pulse","round1_grammar":"hand-written field marks with range/habitat; no nest disturbance","round2_grammar":"field-mark cue -> recall beat -> target -> point/sketch gesture",
"intro_lines":("Silhouette first. Bill second. Habitat third. Call only if we actually hear it.","A careful birdwatcher lets several clues agree."),
"hook_lines":("Look, listen, check—A-B-C!","One field mark starts the idea; several build the ID."),
"outro_lines":("Binoculars down; no bird was chased and no nest was approached.","A to Z ends with field notes ready for another look."),
"round2_patterns":("Field mark {letter} ... {object}! {action}","Watch/listen {letter} ... {object}! {action}","Which clues {letter}? ... {object}! {action}","ID check {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Albatross! Enormous narrow-winged seabird | ocean habitat plus gliding silhouette makes the ID."),
("B","B ... B ... Budgie! Small Australian parrot with curved bill and long tail | wild range matters despite common pet familiarity."),
("C","C? Crane! Tall legs, long neck, straight bill | wetland or grassland silhouette, not just 'big bird'."),
("D","D is Duck. Webbed feet and broad bill support water life | shape, behavior, and plumage narrow the species."),
("E","E — Eagle! Large hooked bill, broad wings, strong talons | distance prevents size illusion from fooling us."),
("F","F ... F ... Finch! Small conical-billed seed eater | bill and flock behavior can guide ID."),
("G","G? Goose! Long neck, webbed feet, heavy body | flock formation and calls add context."),
("H","H is Heron. Long neck often folds in flight; long legs trail behind | silhouette separates it from crane flight posture."),
("I","I — Ibis! Downcurved probing bill is the strongest field mark | wetland habitat confirms the shape."),
("J","J ... J ... Junco! Small sparrow-like bird feeding near ground | plumage and white tail flashes help by region."),
("K","K? Kiwi! Flightless nocturnal New Zealand bird | range alone prevents a false local ID in most of the world."),
("L","L is Lorikeet. Brush-tipped tongue suits nectar feeding; curved bill shows parrot ancestry | region and color refine ID."),
("M","M — Macaw! Huge parrot with long tail and massive curved bill | tropical American range is essential context."),
("N","N ... N ... Nuthatch! Climbs bark and often descends head-first | behavior may identify it before plumage."),
("O","O? Ostrich! World's largest living bird, flightless with long running legs | African open-habitat card, unmistakable scale."),
("P","P is Penguin. Flightless seabird with flipper-like wings and upright stance | Southern Hemisphere marine context matters."),
("Q","Q — Quail! Plump ground bird with short bill | quick ground movement and burst flight support the ID."),
("R","R ... R ... Raven! Large corvid with heavy bill and wedge-shaped tail in Common Raven | compare carefully with crows by region."),
("S","S? Swan! Very large waterbird with long neck | size, water habitat, and bill shape combine."),
("T","T is Toucan. Huge colorful bill on a relatively light body | tropical American forest context prevents confusion."),
("U","U — Upland Sandpiper! Long-necked grassland shorebird relative | often found far from shore in open fields."),
("V","V ... V ... Vulture! Soaring silhouette, broad wings, scavenging ecology | identify from distance without approaching food or roosts."),
("W","W? Wren! Tiny active bird with often cocked tail | dense cover and rapid movement are strong behavioral marks."),
("X","X is Xenops. Small Neotropical bark-foraging bird | narrow bill and branch-creeping behavior guide ID."),
("Y","Y — Yellow Warbler! Small yellow warbler with thin insect-eating bill | color plus shape, habitat, and range make the ID."),
("Z","Z ... Z ... Zenaida Dove! Medium dove with soft coo and pointed wings | Caribbean and nearby regional context completes the note."),),
"style_blueprint":"Crisp diction. Open with silhouette/bill/habitat protocol at 86 BPM in steady 4/4 with acoustic guitar, soft bass, brush and sparse flute. Melody narrow and speech-clear. Round 1 builds IDs from several field marks; range cards prevent false local claims. Chorus look-listen-check. Round 2 uses binocular-frame and air-sketch gestures with one recall beat. No chasing, playback calls, feather collection, or nest approach. Duck target onsets. End by lowering binoculars into silence."}
}
