from __future__ import annotations

"""Authorial-identity deep polish for prehistoric songs 0056-0060."""

GOLD_V5_56_60_SPEC_PATCHES: dict[str, dict[str, object]] = {
"0056": {
"authorial_intent":"Replace the generic dinosaur stomp with a body-plan study: armor, beaks, tails, feet, wings, claws and posture produce different motions; fossils and volcano are evidence/context rather than animals.",
"lyric_identity":"A child compares how prehistoric bodies were built to move, feed, defend or fly, with explicit corrections for pterosaurs and uncertain sound.",
"image_motifs":("ankylosaur tail club","deinonychus sickle claw","hadrosaur beak","Pteranodon wing","fossil bone beside rock"),
"semantic_arc":("armor and feet","beaks jaws and claws","large herbivore body plans","flying reptile and geological context"),
"forbidden_generic_language":("dinosaur stomp","giant footprints","every dinosaur roars","big and small"),
"rhyme_engine":"prehistoric-bodyplan-motion-rhyme","chorus_rhyme_engine":"armor-beak-wing-hook","point_of_view":"a child comparing reconstructed body plans from fossil evidence","chorus_function":"reset armor-beak-wing distinctions","groove_meter":"grounded 4/4 with different motion pockets, not one stomp","round1_grammar":"hand-written anatomical comparisons with taxonomy boundaries","round2_grammar":"body clue -> recall beat -> target -> safe shape gesture",
"intro_lines":("One tail is a club. One mouth is a beak. One animal here flew on a wing membrane.","Prehistoric bodies did not all move the same way."),
"hook_lines":("Armor, beak, wing—A-B-C!","Build the body clue before you name the animal."),
"outro_lines":("The fossil case closes; no roar needs to be invented.","A to Z leaves twenty-six different body clues behind."),
"round2_patterns":("Body clue {letter} ... {object}! {action}","Feature {letter} ... {object}! {action}","Animal or evidence—{letter}? ... {object}! {action}","Prehistoric shape {letter} ... {object}! {action}"),
"round2_overrides":(("J","Feature J ... Jawbone! Trace a curved jaw line, then point to the teeth."),),
"round1_overrides":(
("A","A — Ankylosaurus! Heavy armor and a tail club protected a low-slung herbivore | not every dinosaur defense used horns or speed."),
("B","B ... B ... Bone! Hard body tissue can fossilize and preserve anatomy | evidence, not a living dinosaur."),
("C","C? Ceratopsian! Beaked plant-eating dinosaur group with frills and, in many members, horns | group clue rather than one species."),
("D","D is Deinonychus. Feathered dromaeosaurid with a large curved claw on each second toe | agile predator, not a giant movie monster."),
("E","E — Egg! Fossil eggs and nests can reveal reproduction and nesting behavior | shell evidence needs context."),
("F","F ... F ... Fossil! Preserved remains, impressions, or traces of past life | the main evidence source for this body study."),
("G","G? Gastonia! Armored ankylosaur with plates and spikes | defense by body armor rather than a classic Ankylosaurus tail club."),
("H","H is Hadrosaur. Duck-billed ornithopod group with broad beaks and complex teeth | many were large plant eaters."),
("I","I — Iguanodon! Large ornithopod with a distinctive thumb spike | hands and beak give two clear body clues."),
("J","J ... J ... Jawbone! Fossil jaw can preserve tooth shape and bite anatomy | evidence about feeding, not a whole animal by itself."),
("K","K? Kritosaurus! Hadrosaurid known especially from skull material | a duck-billed dinosaur reconstructed from incomplete evidence."),
("L","L is Lesothosaurus. Small early ornithischian with light build and long hind limbs | much smaller body plan than giant sauropods."),
("M","M — Maiasaura! Hadrosaurid known from nesting colonies and young of different ages | fossils support social nesting behavior."),
("N","N ... N ... Nodosaurus! Armored nodosaurid with body plates and spikes | unlike Ankylosaurus, nodosaurids lacked a heavy tail club."),
("O","O? Oviraptor! Beaked oviraptorid; fossils show adults brooding nests | the old 'egg thief' story came from an early mistaken interpretation."),
("P","P is Pteranodon. Large toothless pterosaur flew with membrane wings | flying reptile, not a dinosaur."),
("Q","Q — Qianzhousaurus! Long-snouted tyrannosaurid from Late Cretaceous Asia | skull shape differs from broad-snouted Tyrannosaurus."),
("R","R ... R ... Raptor! Everyday label often used for dromaeosaurids | scientific names tell us which animal we actually mean."),
("S","S? Stegosaurus! Back plates and paired tail spikes make a distinctive herbivore body | plates were not a shell of armor."),
("T","T is Triceratops. Three facial horns, large frill, and beak | ceratopsian body plan in one famous genus."),
("U","U — Unenlagia! South American dromaeosaurid relative | a lightly built feathered theropod, known from incomplete remains."),
("V","V ... V ... Volcano! Geological feature can bury, erode, or expose rocks over time | context, not a prehistoric animal."),
("W","W? Wuerhosaurus! Stegosaur from Early Cretaceous Asia | plates and tail spikes place it in the stegosaur body plan."),
("X","X is Xenoceratops. Ceratopsid with a frilled, horned skull | one branch of the diverse ceratopsian family."),
("Y","Y — Yinlong! Small early ceratopsian from Jurassic China | shows that horned-dinosaur relatives began with modest body size and simpler skull ornament."),
("Z","Z ... Z ... Zephyrosaurus! Small ornithopod from Early Cretaceous North America | light body and running legs close the comparison."),),
"style_blueprint":"Crisp diction. Open with three body-plan contrasts at 90 BPM in 4/4 with low drum, acoustic guitar, woodblock and sparse marimba. Do not use one stomp for every target: armor gets grounded holds, light theropods quick steps, pterosaur gets legato wing phrase, fossils get still pauses. Round 1 protects pterosaur/dinosaur taxonomy and uncertain sound. Chorus armor-beak-wing. Round 2 uses shape gestures and one recall beat. Duck target onsets. End with museum-case quiet, no invented roar SFX."},
"0057": {
"authorial_intent":"Make Fossil Finder an evidence reconstruction song: footprint, rib, bone, plant fossils and partial skeletons each answer different questions, and reconstruction uncertainty is part of the lyric.",
"lyric_identity":"A child fossil worker moves from trace to bone to skeleton to interpretation, repeatedly asking what the evidence can and cannot tell us.",
"image_motifs":("footprint slab","rib bone tray","fern impression","hadrosaur skull","field jacket around partial skeleton"),
"semantic_arc":("trace fossils","bones and anatomy","compare taxa from partial remains","state uncertainty and rebuild cautiously"),
"forbidden_generic_language":("build the past bone by bone","fossil finder fun","every bone tells everything","brush brush"),
"rhyme_engine":"fossil-evidence-reconstruction-rhyme","chorus_rhyme_engine":"find-compare-infer-hook","point_of_view":"a child learning how paleontologists infer from incomplete evidence","chorus_function":"repeat find-compare-infer","groove_meter":"patient 4/4 dig-site pulse with evidence pauses","round1_grammar":"hand-written evidence type plus taxonomic fact","round2_grammar":"evidence cue -> recall beat -> target -> brush/point/compare gesture",
"intro_lines":("A footprint tells movement; a rib tells anatomy; neither tells the whole animal alone.","Fossil work begins by asking what kind of evidence we found."),
"hook_lines":("Find, compare, infer—A-B-C!","Build only the part of the past the evidence can hold."),
"outro_lines":("Brushes down; labels keep both facts and uncertainty.","A to Z ends with a reconstruction we can revise."),
"round2_patterns":("Evidence {letter} ... {object}! {action}","Fossil clue {letter} ... {object}! {action}","What can it tell—{letter}? ... {object}! {action}","Compare {letter} ... {object}! {action}"),
"round2_overrides":(("R","Fossil clue R ... Rib Bone! Trace one gentle rib curve, then point to the specimen."),),
"round1_overrides":(
("A","A — Allosaurus! Large Jurassic theropod with three-fingered hands and serrated teeth | skeleton gives anatomy, not skin color certainty."),
("B","B ... B ... Brachiosaurus! Sauropod with forelimbs longer than hindlimbs | limb proportions help reconstruct its high-shouldered stance."),
("C","C? Ceratopsian! Beaks, frills, and horn patterns vary across the group | skull fossils are especially informative."),
("D","D is Deinonychus. Dromaeosaurid with a large second-toe claw and feathered relatives | bones plus feather evidence change old reconstructions."),
("E","E — Edmontosaurus! Large hadrosaur with broad beak and dense dental batteries | skin impressions preserve details beyond bone in some specimens."),
("F","F ... F ... Footprint! Trace fossil records a foot touching sediment | can suggest movement and trackmaker size without preserving the body."),
("G","G? Giganotosaurus! Huge South American carcharodontosaurid theropod | skull and skeleton distinguish it from Tyrannosaurus."),
("H","H is Hadrosaur. Duck-billed dinosaur group | teeth, jaws, crests, and limb bones reveal different parts of life."),
("I","I — Irritator! Brazilian spinosaurid known from a long narrow skull | incomplete remains mean reconstruction must stay cautious."),
("J","J ... J ... Jurassic Fern! Fern-like plants and plant fossils help reconstruct environments | a plant clue, not dinosaur anatomy."),
("K","K? Kentrosaurus! Stegosaur with plates toward the front and prominent spikes toward the rear | skeleton maps the armor arrangement."),
("L","L is Lambeosaurus. Hadrosaur with a hollow cranial crest | crest shape is preserved in skull fossils."),
("M","M — Mosasaurus! Giant marine squamate reptile | lived in Late Cretaceous seas and was not a dinosaur."),
("N","N ... N ... Nodosaurus! Armored dinosaur without an Ankylosaurus-style tail club | armor fossils show nodosaurid differences."),
("O","O? Ornithomimus! Ostrich-like theropod; fossil evidence from relatives and specimens supports feathers | long legs fit fast terrestrial movement."),
("P","P is Pachycephalosaurus. Thick domed skull roof is its signature fossil feature | exact behavior of the dome is still debated."),
("Q","Q — Qianzhousaurus! Long-snouted tyrannosaurid | skull proportions are the key comparison clue."),
("R","R ... R ... Rib Bone! Rib shape helps reconstruct chest anatomy | one bone must be placed in the larger skeleton."),
("S","S? Stegosaurus! Plates and tail spikes preserve a dramatic armor pattern | their exact color is not fossilized in ordinary bone."),
("T","T is Triceratops. Horned skull and frill preserve well enough for detailed comparison | famous face built from real bone."),
("U","U — Utahraptor! Large dromaeosaurid with sickle-clawed second toes | much larger than Velociraptor."),
("V","V ... V ... Velociraptor! Small feathered dromaeosaurid from Mongolia | far smaller than its common movie portrayal."),
("W","W? Wuerhosaurus! Cretaceous stegosaur from Asia | incomplete fossils still place it among plated stegosaurs."),
("X","X is Xixiasaurus. Small long-skulled theropod from China | known from limited material, so fine details remain uncertain."),
("Y","Y — Yinlong! Early ceratopsian from Jurassic China | small skull helps trace ceratopsian evolution before giant frills and horns."),
("Z","Z ... Z ... Zephyrosaurus! Small ornithopod known from fragmentary fossils | another reminder that paleontology often works with incomplete pieces."),),
"style_blueprint":"Crisp diction. Open by contrasting footprint and rib evidence at 86 BPM in patient 4/4 with brushed drum, acoustic guitar, muted marimba and soft bass. Keep a narrow mostly stepwise melody around target words and duck percussion at each target onset. Round 1 follows trace -> bone -> skeleton -> inference, with short pauses after uncertainty words. The arrangement stays sparse at incomplete evidence and grows slightly fuller only at well-supported comparisons. Chorus find-compare-infer. Round 2 uses brush/point gestures only, no digging-tool hazard play. Protect Mosasaurus as marine reptile, Velociraptor size, and debated Pachycephalosaurus behavior. End with a quiet museum-label cadence."},
"0058": {
"authorial_intent":"Turn Prehistoric Picture Walk into a museum reconstruction gallery: each image separates fossil-supported anatomy from artist reconstruction, especially color, soft tissue, behavior and habitat composition.",
"lyric_identity":"A child walks frame by frame and asks which parts are fossil, which are inference, and which are artistic choices.",
"image_motifs":("Ankylosaurus skeleton beside painting","feathered Yutyrannus silhouette","pterosaur wing diagram","nest display","fern backdrop label"),
"semantic_arc":("skeleton-to-picture basics","soft tissue and behavior inference","non-dinosaur reptiles and plants","end with reconstruction uncertainty"),
"forbidden_generic_language":("pictures wake up","museum magic","time travel","every picture is exact"),
"rhyme_engine":"museum-picture-evidence-layer-rhyme","chorus_rhyme_engine":"bone-infer-draw-hook","point_of_view":"a child comparing museum art with fossil evidence","chorus_function":"reset bone-infer-draw","groove_meter":"gallery 6/8 with frame-to-frame pauses","round1_grammar":"hand-written reconstruction layer per target","round2_grammar":"picture cue -> recall beat -> target -> frame/point gesture",
"intro_lines":("Skeleton on the left, painted reconstruction on the right.","We ask which details are fossil facts and which are careful inference."),
"hook_lines":("Bone, infer, draw—A-B-C!","A good picture shows evidence without pretending we know every color."),
"outro_lines":("Gallery lights dim; the labels keep their question marks.","A to Z leaves the pictures open to better evidence."),
"round2_patterns":("Picture {letter} ... {object}! {action}","Evidence layer {letter} ... {object}! {action}","Known or inferred—{letter}? ... {object}! {action}","Museum frame {letter} ... {object}! {action}"),
"round2_overrides":(("R","Evidence layer R ... Rib Bone! Trace one gentle rib curve, then point to the specimen."),),
"round1_overrides":(
("A","A — Ankylosaurus! Armor and tail club come from fossils | skin color in a painting is usually reconstruction."),
("B","B ... B ... Brachiosaurus! Long neck and longer forelimbs shape the skeleton | posture is reconstructed from joints and comparisons."),
("C","C? Carnotaurus! Two brow horns and extremely reduced forelimbs are fossil-supported | exact colors remain artistic."),
("D","D is Diplodocus. Long neck, whip-like tail, and peg-like front teeth come from fossils | living movement is reconstructed from anatomy."),
("E","E — Egg! Fossil eggs preserve shell, shape, and nest context | embryo fossils can sometimes identify the animal more directly."),
("F","F ... F ... Fossil! Preserved body part or trace is the evidence layer beneath every gallery reconstruction."),
("G","G? Gastonia! Armor plates and spikes are fossil features | spacing and soft-tissue appearance require reconstruction."),
("H","H is Herrerasaurus. Triassic predatory dinosaur with grasping hands and long hind limbs | an early dinosaur body plan, not a Jurassic movie monster."),
("I","I — Irritator! Spinosaurid with long narrow snout | much of the full-body image must be inferred from relatives because remains are incomplete."),
("J","J ... J ... Jurassic Fern! Ferns and fern-like plants help build habitat scenes | background plants need their own fossil evidence too."),
("K","K? Kritosaurus! Hadrosaurid known from incomplete skull and skeleton material | restorations must avoid filling gaps with certainty."),
("L","L is Lambeosaurus. Hollow head crest is fossil-supported | sound-production ideas are hypotheses tested from anatomy, not recorded calls."),
("M","M — Maiasaura! Nesting colonies and growth series support parental-care interpretations | behavior picture has unusually rich evidence."),
("N","N ... N ... Nest! Fossil nests and eggs are trace/body evidence together | arrangement can reveal breeding behavior."),
("O","O? Ornithomimus! Long-legged theropod with feather evidence | museum art should not default to bare reptile skin."),
("P","P is Pteranodon. Toothless flying pterosaur with long crest | pterosaur, not dinosaur, with membrane wings."),
("Q","Q — Quetzalcoatlus! Giant azhdarchid pterosaur | enormous winged reptile, not a feathered dinosaur or bird."),
("R","R ... R ... Rib Bone! One structural element of the chest | picture scale depends on fitting many bones together correctly."),
("S","S? Stegosaurus! Plates and tail spikes are clear fossil features | plate color and display patterns are less certain."),
("T","T is Tyrannosaurus. Huge skull, deep jaws, two-fingered forelimbs | feathers in adults remain a nuanced evidence question, not a simple all-or-none claim."),
("U","U — Utahraptor! Large dromaeosaurid | feathered reconstruction is supported by its place among feathered theropods."),
("V","V ... V ... Velociraptor! Small dromaeosaurid with quill knobs on the forearm in fossils | direct evidence supports feathers."),
("W","W? Wannanosaurus! Small pachycephalosaur relative from China | fragmentary remains mean the gallery picture should stay modest."),
("X","X is Xixiasaurus. Small theropod known from partial skull and skeleton | image fills missing body parts using close relatives."),
("Y","Y — Yutyrannus! Large tyrannosauroid preserved with filamentous feathers | direct fossil evidence changes the picture dramatically."),
("Z","Z ... Z ... Zuniceratops! Early ceratopsian with brow horns but simpler frill than later giant ceratopsids | transitional body plan in the gallery."),),
"style_blueprint":"Crisp diction. Open as a museum comparison at 82 BPM airy 6/8 with piano, pizzicato strings, acoustic guitar and soft brush. Each target gets a brief 'evidence layer' pause before inferred details. Chorus bone-infer-draw. Round 2 uses frame/point gestures and one recall beat. No magical awakening or time-machine effects. Protect pterosaur taxonomy, feather evidence, and uncertainty language. Duck target onsets. End with gallery lights dimming."},
"0059": {
"authorial_intent":"Make Dino Trail Explorer a habitat-and-trace walk: tracks, nests, bones, coastal/marine context and volcanic geology reveal where different animals lived; the song never places every prehistoric animal on one land trail.",
"lyric_identity":"A child follows evidence through land, shore, and water contexts, with explicit route changes for pterosaurs and Mosasaurus.",
"image_motifs":("theropod footprint","nest beside vegetation","pterosaur overhead","marine-reptile shoreline panel","volcanic ash layer"),
"semantic_arc":("land tracks","nests and herbivore habitat","air and coastal flyers","marine/geologic context and return to trail"),
"forbidden_generic_language":("roar echo","dino trail","every creature stomps","follow the dinosaur"),
"rhyme_engine":"prehistoric-habitat-trace-rhyme","chorus_rhyme_engine":"track-nest-shore-hook","point_of_view":"a child following fossil and habitat evidence rather than live-animal fantasy","chorus_function":"reset track-nest-shore","groove_meter":"walking 4/4 with habitat-change transitions","round1_grammar":"hand-written habitat placement with taxonomy boundaries","round2_grammar":"trace cue -> recall beat -> target -> point/track gesture",
"intro_lines":("One trackway crosses mud; one pterosaur belongs overhead; one marine reptile never walked this trail.","We follow evidence, not imaginary live dinosaurs."),
"hook_lines":("Track, nest, shore—A-B-C!","Change the habitat when the evidence tells us to."),
"outro_lines":("The trail ends at a label, not at a roaring animal.","A to Z returns us to the evidence underfoot."),
"round2_patterns":("Trace {letter} ... {object}! {action}","Habitat {letter} ... {object}! {action}","Land, air, or water—{letter}? ... {object}! {action}","Trail note {letter} ... {object}! {action}"),
"round2_overrides":(("J","Habitat J ... Jawbone! Trace a curved jaw line; this is fossil evidence, not a track."),),
"round1_overrides":(
("A","A — Allosaurus! Large Jurassic land predator | three-fingered hands and theropod feet fit a terrestrial trail."),
("B","B ... B ... Brachiosaurus! Giant sauropod herbivore | columnar limbs carried an enormous land body."),
("C","C? Carnotaurus! South American theropod with brow horns and tiny forelimbs | land-animal clue."),
("D","D is Diplodocus. Long-bodied sauropod with long tail and neck | tracks and limb anatomy belong to ground travel."),
("E","E — Edmontosaurus! Hadrosaur that walked on two or four limbs | broad beak marks a plant-eating trail clue."),
("F","F ... F ... Footprint! Trace fossil records contact with ancient ground | the trail itself becomes evidence."),
("G","G? Gastonia! Armored herbivore | plates and spikes belong to land, not water armor."),
("H","H is Herrerasaurus. Triassic predatory dinosaur from Argentina | an early dinosaur from a much older chapter than Tyrannosaurus."),
("I","I — Iguanodon! Large herbivorous ornithopod with thumb spike | terrestrial browser along the route."),
("J","J ... J ... Jawbone! Fossil jaw reveals feeding anatomy | a trail-side evidence object, not a roaming animal."),
("K","K? Kritosaurus! Hadrosaurid herbivore | broad-billed skull fits the plant-eating section."),
("L","L is Lesothosaurus. Small lightly built ornithischian | quick terrestrial body in the low-vegetation frame."),
("M","M — Mosasaurus! Huge marine squamate reptile | ocean predator, not a dinosaur and not a land-trail walker."),
("N","N ... N ... Nest! Eggs and nest structure anchor breeding behavior to a place | habitat evidence without chasing adults."),
("O","O? Oviraptor! Feathered beaked theropod known brooding nests | nesting evidence corrected the old egg-thief story."),
("P","P is Pteranodon. Flying pterosaur from marine-coastal settings | overhead or shore context, not dinosaur footsteps."),
("Q","Q — Quetzalcoatlus! Giant pterosaur likely spent much time on land as well as flying | still a pterosaur, not a dinosaur."),
("R","R ... R ... Raptor! Broad popular label for dromaeosaurid-style predators | use exact genus when evidence allows."),
("S","S? Spinosaurus! Giant spinosaurid with sail and crocodile-like snout | evidence supports strong association with aquatic environments, though exact lifestyle remains studied."),
("T","T is Tyrannosaurus. Late Cretaceous land predator | deep skull and powerful hind limbs fit terrestrial travel."),
("U","U — Utahraptor! Large dromaeosaurid from Early Cretaceous North America | terrestrial predator with sickle claws."),
("V","V ... V ... Volcano! Geological setting can lay down ash beds used to date and correlate fossil layers | landscape evidence, not animal habitat by itself."),
("W","W? Wuerhosaurus! Cretaceous stegosaur from Asia | plated land herbivore on the terrestrial branch."),
("X","X is Xixiasaurus. Small theropod from China | limited fossils make exact habitat details uncertain."),
("Y","Y — Yinlong! Small early ceratopsian from Jurassic China | land herbivore near the base of horned-dinosaur evolution."),
("Z","Z ... Z ... Zephyrosaurus! Small ornithopod from Early Cretaceous North America | final light-footed land clue."),),
"style_blueprint":"Crisp diction. Open with land/air/water habitat contrast at 88 BPM walking 4/4 with acoustic guitar, hand drum, woodblock and low strings. Change accompaniment when habitat changes: dry footsteps for land, airy sustained notes for pterosaurs, fluid bass for marine Mosasaurus/Spinosaurus context. Chorus track-nest-shore. Round 2 uses point/trace gestures only. No invented roars. Duck targets. End at an evidence label, not a fantasy encounter."},
"0060": {
"authorial_intent":"Turn Museum Dino March into a taxonomy-label walk: every exhibit label states whether the target is dinosaur, pterosaur, marine reptile, fossil part, trace, or reconstruction, replacing the fake time-machine premise.",
"lyric_identity":"A child museum visitor reads classification labels case by case and learns that prehistoric does not equal dinosaur.",
"image_motifs":("Allosaurus skeleton label","Mosasaurus marine hall","Quetzalcoatlus ceiling mount","rib bone drawer","ceratopsian skull case"),
"semantic_arc":("dinosaur skeletons","fossil parts and traces","non-dinosaur prehistoric reptiles","classification recap across museum halls"),
"forbidden_generic_language":("time machine","dino march","world long gone","museum magic"),
"rhyme_engine":"museum-taxonomy-label-rhyme","chorus_rhyme_engine":"read-sort-name-hook","point_of_view":"a child reading museum taxonomy labels","chorus_function":"repeat read-sort-name","groove_meter":"measured 4/4 gallery walk","round1_grammar":"hand-written classification label plus distinguishing feature","round2_grammar":"label cue -> recall beat -> target -> point/sort gesture",
"intro_lines":("First label: dinosaur. Next drawer: fossil bone. Ceiling mount: pterosaur.","The museum gets more interesting when 'prehistoric' is not one category."),
"hook_lines":("Read, sort, name—A-B-C!","Dinosaur, fossil, pterosaur, marine reptile—labels matter."),
"outro_lines":("Last case closed; every label stays more precise than 'dino'.", "A to Z leaves the museum sorted, not simplified."),
"round2_patterns":("Label {letter} ... {object}! {action}","Sort {letter} ... {object}! {action}","Which case, {letter}? ... {object}! {action}","Museum clue {letter} ... {object}! {action}"),
"round2_overrides":(("J","Sort J ... Jawbone! Trace a curved jaw line, then point to the fossil drawer."),("R","Sort R ... Rib Bone! Trace one rib curve, then point to the fossil drawer.")),
"round1_overrides":(
("A","A — Allosaurus! Theropod dinosaur | large Jurassic predator with three-fingered hands."),
("B","B ... B ... Bone! Anatomical tissue that may fossilize | specimen part, not a taxonomic animal."),
("C","C? Carnotaurus! Theropod dinosaur | brow horns and tiny forelimbs mark the genus."),
("D","D is Diplodocus. Sauropod dinosaur | long neck, long tail, peg-like front teeth."),
("E","E — Egg! Reproductive evidence | fossil eggs need nest and embryo context before assigning an exact parent."),
("F","F ... F ... Fossil! Preserved remain or trace of past life | evidence category spanning plants, animals, and activity."),
("G","G? Giganotosaurus! Carcharodontosaurid theropod dinosaur | enormous South American predator distinct from Tyrannosaurus."),
("H","H is Hadrosaur. Ornithopod dinosaur group | broad beaks and dental batteries define the duck-billed hall."),
("I","I — Iguanodon! Ornithopod dinosaur | thumb spike and robust herbivore body."),
("J","J ... J ... Jawbone! Fossil skeletal part | tooth sockets and jaw shape help identify feeding anatomy."),
("K","K? Kritosaurus! Hadrosaurid dinosaur | known from incomplete material, especially skull remains."),
("L","L is Lambeosaurus. Crested hadrosaurid dinosaur | hollow cranial crest is the label feature."),
("M","M — Mosasaurus! Marine squamate reptile | prehistoric, huge, and definitely not a dinosaur."),
("N","N ... N ... Nest! Trace/reproductive structure | evidence of breeding behavior and site use."),
("O","O? Ornithomimus! Feathered ornithomimid theropod dinosaur | long legs and toothless beak give an ostrich-like outline."),
("P","P is Pachycephalosaurus. Pachycephalosaurid dinosaur | thick domed skull roof, behavior still debated."),
("Q","Q — Quetzalcoatlus! Azhdarchid pterosaur | flying reptile, not dinosaur."),
("R","R ... R ... Rib Bone! Skeletal specimen part | belongs in anatomy drawers until matched to a skeleton."),
("S","S? Spinosaurus! Spinosaurid theropod dinosaur | sail-backed predator with strong aquatic adaptations."),
("T","T is Triceratops. Ceratopsid dinosaur | three horns, large frill, beaked mouth."),
("U","U — Unenlagia! Dromaeosaurid theropod dinosaur relative from South America | lightly built and likely feathered."),
("V","V ... V ... Velociraptor! Small feathered dromaeosaurid dinosaur | not the giant scaly movie version."),
("W","W? Wannanosaurus! Small pachycephalosaur relative | fragmentary Chinese fossils keep some details uncertain."),
("X","X is Xenoceratops. Ceratopsid dinosaur | frill ornament and horned skull place it with horned dinosaurs."),
("Y","Y — Yinlong! Early ceratopsian dinosaur | small Jurassic relative before later giant horned forms."),
("Z","Z ... Z ... Zephyrosaurus! Small ornithopod dinosaur | light-bodied herbivore closes the label walk."),),
"style_blueprint":"Crisp diction. Open with three museum label categories at 84 BPM measured 4/4 with piano, pizzicato strings, soft woodblock and bass. Each Round 1 line should sound like a clear exhibit label followed by one memorable feature. Chorus read-sort-name. Round 2 uses sorting/pointing gestures and one recall beat. Never call Mosasaurus or Quetzalcoatlus dinosaurs. No time-machine SFX. Duck target onsets. End with gallery-close cadence."}
}
