from __future__ import annotations

"""Authorial-identity deep polish for woodland songs 0021-0025."""

GOLD_V5_21_25_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0021": {
        "authorial_intent": "Make the alphabet feel like a quiet woodland walk heard as much as seen: leaf-crunch, bark-whisper, wing-burst, paw-step and woodpecker drum guide attention without turning the forest into noise.",
        "lyric_identity": "A child walks softly and listens for small sound clues; recurring language uses crunch, hush, rustle, tap, drum, whisper and sudden silence.",
        "image_motifs": ("leaf-crunch underfoot", "papery and ridged bark", "soft paws in cover", "fallen log shelter", "woodpecker drum overhead"),
        "semantic_arc": ("enter on quiet footsteps", "trees and bark shape the soundscape", "animals interrupt the hush", "the walk ends with the forest quiet again"),
        "forbidden_generic_language": ("woodland friends come walk with me", "fun in the forest", "look and see", "shining bright"),
        "rhyme_engine": "woodland-footstep-sound-mosaic",
        "chorus_rhyme_engine": "crunch-hush-echo-hook",
        "point_of_view": "a child walking softly enough to notice tiny woodland sounds before seeing their sources",
        "chorus_function": "reset the listening rule: step, stop, hear, then name",
        "groove_meter": "soft 4/4 walking pulse with leaf-crunch rests",
        "round1_grammar": "hand-written sound-and-texture observations; facts stay concrete while sound words recur only where the object can honestly support them",
        "round2_grammar": "listen cue -> one silent recall beat -> target -> one quiet safe gesture",
        "intro_lines": ("Crunch... then hush. One step settles into leaves.", "Before we name the forest, we listen to it."),
        "hook_lines": ("Step, stop, listen—A-B-C!", "The quiet woods keep answering softly."),
        "outro_lines": ("One last leaf turns under our shoe.", "A to Z fades back into woodland hush."),
        "interlude_lines": ("No footsteps for one beat—what woodland sounds can we remember?",),
        "round2_patterns": ("Listen or look for {letter} ... {object}! {action}", "Quiet clue {letter} ... {object}! {action}", "Hear or see {letter}? ... {object}! {action}", "Soft-step clue {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Aspen! Small leaves flicker in the breeze | pale trunks stand while the canopy whispers."),
            ("B", "B ... B ... Birch! Papery bark curls at the edge | a pale trunk bright between darker trees."),
            ("C", "C is Cedar. Green branches hold a soft hush | evergreen foliage gathers close around the trunk."),
            ("D", "D? Douglas Fir! Needle-like leaves, hanging cones | tall branches murmur above the trail."),
            ("E", "E — Evergreen! Some leaves or needles stay through the seasons | green held when other colors change."),
            ("F", "F ... F ... Fox! Pointed ears, bushy tail | soft paws cross cover without much sound."),
            ("G", "G? Grouse! Ground bird, sturdy body | one sudden wing-burst can break the forest hush."),
            ("H", "H is Hedgehog. Stiff spines cover its back | a small body can curl tight for protection."),
            ("I", "I — Ivy! Stems climb and trail | leaves follow the bark upward without making a footstep."),
            ("J", "J ... J ... Juniper! Evergreen leaves, berry-like seed cones | a sharp green shape beside the path."),
            ("K", "K? Knot! A hard twist in the wood | the old branch-place makes a swirl in the trunk."),
            ("L", "L is Log. Fallen trunk, rough bark | cracks and hollows can shelter small forest life."),
            ("M", "M — Maple! Broad leaves lift and turn | a dry one may rasp softly when the breeze moves through."),
            ("N", "N ... N ... Newt! Small amphibian near damp cover | careful steps leave it room to move."),
            ("O", "O? Owl! Round eyes, hooked beak, broad wings | a night call can travel far between trees."),
            ("P", "P is Pinecone. Woody scales overlap around seeds | one cone rests dry beneath the branches."),
            ("Q", "Q — Quartz Rock! Hard mineral, glassy sparkle | silent among leaf litter and roots."),
            ("R", "R ... R ... Rabbit! Long ears turn first | quick hind legs carry it through low cover."),
            ("S", "S? Squirrel! Claws grip bark | a scratch, a leap, then the branch is still again."),
            ("T", "T is Tree. Roots hold, trunk rises, branches spread | the whole woodland soundscape gathers around it."),
            ("U", "U — Upland Fern! Feathered fronds fan from the floor | green shapes soften the space between trunks."),
            ("V", "V ... V ... Vine! Long stem climbs or trails | leaves weave through the vertical forest."),
            ("W", "W? Woodpecker! Beak meets wood—tap, tap, drum | the sound points upward before we spot the bird."),
            ("X", "At the trail shelter, X is Xylem—tiny tubes carry water through a tree or plant stem."),
            ("Y", "Y — Yellow Warbler! Small yellow songbird | a light call can float from leaves above."),
            ("Z", "Z ... Z ... Zebra Swallowtail! Pale striped wings sweep past | a butterfly moving quietly through the last patch of light."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Close, warm adult lead at 86 BPM in soft acoustic 4/4. Use nylon guitar, brushed shaker, muted woodblock, tiny pizzicato strings and occasional breathy flute; production should feel like careful footsteps rather than a busy nature soundtrack. Open with one dry leaf-crunch, then silence. Round 1 alternates short sound-images with longer factual phrases; preserve real sound logic—trees may whisper in wind, Woodpecker may drum, Quartz stays silent. Chorus is a restrained step-stop-listen hook, not a generic sing-along. Round 2 leaves one true silent beat after each listening cue and keeps gestures quiet. Duck all percussion at target onset. Xylem is explained as the water-carrying tissue inside a plant stem. End by removing pulse until only one final leaf sound remains.",
    },
    "0022": {
        "authorial_intent": "Turn the forest floor into a layered living system: seed, litter, fungus, insects, roots, stones, underbrush and visiting animals all share the same ground without reducing the song to a taxonomy list.",
        "lyric_identity": "A kneeling observer reads the forest from ground level upward; recurring language uses under, through, beneath, litter, root, damp, layer and rise.",
        "image_motifs": ("acorn in leaf litter", "fern and mushroom close-up", "insect under a leaf", "roots beside quartz and river", "underbrush rising toward trunks"),
        "semantic_arc": ("start with seeds and litter", "discover small life and damp growth", "connect roots, rock and water", "rise from underbrush toward birds and canopy"),
        "forbidden_generic_language": ("leaves and logs are fun to see", "forest floor for you and me", "everything grows", "look and learn today"),
        "rhyme_engine": "forest-floor-layered-linked-rhyme",
        "chorus_rhyme_engine": "root-litter-layer-refrain",
        "point_of_view": "a child kneeling at ground level and following connections from leaf litter into roots, water and underbrush",
        "chorus_function": "return attention to the shared ground beneath very different forest things",
        "groove_meter": "low gentle 6/8 with descending-to-rising phrase shapes",
        "round1_grammar": "hand-written ecological close-ups; ground relation and physical layer matter more than decorative rhyme",
        "round2_grammar": "ground-layer cue -> recall beat -> target -> safe close-up gesture",
        "intro_lines": ("Kneel by one curled leaf; a whole forest begins underneath it.", "Seed, stone, root, wing—different lives share the same floor."),
        "hook_lines": ("Leaf, root, stone—A-B-C!", "The forest floor holds stories under every tree."),
        "outro_lines": ("We stand again; the small world stays below.", "A to Z keeps working under every tree."),
        "round2_patterns": ("Forest-floor clue {letter} ... {object}! {action}", "Layer clue {letter} ... {object}! {action}", "Low or high, {letter}? ... {object}! {action}", "Next layer, {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Acorn! Hard shell, little cap | an oak seed resting where leaves collect."),
            ("B", "B ... B ... Bear! Broad paws cross the litter | a large mammal passing over the small world below."),
            ("C", "C? Cedar! Roots hold beneath the surface | green branches rise far above our ground-level view."),
            ("D", "D is Douglas Fir. Tall evergreen, needle-like leaves, hanging cones | roots begin where the forest floor ends."),
            ("E", "Look up for E — Eagle. Strong wings cross the opening | a high visitor above our low forest map."),
            ("F", "F ... F ... Fern! Curled young growth unfurls | divided fronds arch over damp litter."),
            ("G", "G? Grass! Narrow leaves rise from rooted bases | a soft green edge where light reaches the floor."),
            ("H", "H is Hedgehog. Spines above, small feet below | it moves close to ground cover and can curl for protection."),
            ("I", "I — Insect! Six legs, three main body parts | tiny movement under bark, leaf, or stem."),
            ("J", "J ... J ... Jay! A forest bird drops to the ground, then lifts back to branches | beak and feet working between layers."),
            ("K", "K? Kingfisher! Near the river edge, a strong bill points toward water | one bright hunter beside the forest floor."),
            ("L", "L is Lynx. Wide quiet paws cross low cover | a wild cat moving without needing a trail."),
            ("M", "M — Mushroom! Cap rises from damp litter | the visible fruiting body appears above hidden fungal growth."),
            ("N", "N ... N ... Newt! Small amphibian near moist leaves | cool cover helps keep its skin from drying."),
            ("O", "O? Oak! Deep roots below, broad crown above | and every acorn begins another possible tree."),
            ("P", "P is Pine. Needles gather overhead | cones and old needles add new texture to the ground."),
            ("Q", "Q — Quartz Rock! Hard, glassy-looking mineral | a bright edge among dark soil and roots."),
            ("R", "R ... R ... River! Water cuts beside the forest floor | carrying sound, moisture, and moving reflections."),
            ("S", "S? Squirrel! Quick paws search leaf litter, then climb | one animal moving between ground and branch."),
            ("T", "T is Tree. Root below, trunk through, canopy high | one body connecting every forest layer."),
            ("U", "U — Underbrush! Shrubs and low plants fill the space below taller trees | a thick middle layer above the litter."),
            ("V", "V ... V ... Violet! Small leaves and low flowers sit close to the soil | color at knee height."),
            ("W", "W? Woodpecker! It works on trunks above the floor | chips, bark, and sound connect our low view to the tree."),
            ("X", "X is Xylem. Tiny tubes carry water upward through a stem | a hidden plant pathway below the forest leaves."),
            ("Y", "Y — Yellow Warbler! Small yellow bird among leaves | a moving point of color above the ground layers."),
            ("Z", "Z ... Z ... Zebra Swallowtail! Striped butterfly wings pass over the low plants | then lift beyond our close-up view."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Intimate adult lead, 82 BPM, gentle 6/8 with nylon guitar, soft marimba, brushed frame drum and low pizzicato bass. Arrange vertically: low-register sparse opening for litter/roots, slightly brighter midrange for ferns/insects, then modest lift when birds or canopy appear. Round 1 should feel like a camera at knee height, not a general forest tour. Use linked near-rhymes across two or three lines, then release them. Chorus returns to leaf-root-stone with a descending then rising melody. Round 2 gives one quiet beat for recall and simple ground/shape gestures. Keep Mushroom and Xylem speech-clear; no fantasy claims. End by lifting the listener back to standing height while the accompaniment thins.",
    },
    "0023": {
        "authorial_intent": "Compose the forest as a listening map where calls, wing sounds, river noise and deliberate silence reveal distance; non-sounding objects become the quiet spaces between calls.",
        "lyric_identity": "A child listens branch to branch; recurring language uses call, answer, echo, rustle, hush, far, near and between.",
        "image_motifs": ("grouse wing-burst", "jay call", "river under birdsong", "quiet nest", "wolf call far beyond the trail"),
        "semantic_arc": ("first calls wake the trees", "sounds move near and far", "river and trail widen the listening map", "evening quiet gathers the final calls"),
        "forbidden_generic_language": ("birds and plants sing back to me", "forest music everywhere", "sing with me", "every object makes a sound"),
        "rhyme_engine": "birdsong-call-answer-delayed-rhyme",
        "chorus_rhyme_engine": "call-echo-hush-hook",
        "point_of_view": "a child locating forest things by sound and by the silence between sounds",
        "chorus_function": "teach near/far listening and return to the call-answer-hush pattern",
        "groove_meter": "open 4/4 with stop-start call-and-silence pockets",
        "round1_grammar": "hand-written auditory map; audible targets get honest sound verbs while silent plants and objects are framed as pauses or visual anchors",
        "round2_grammar": "near/far or quiet cue -> recall beat -> target -> restrained listening gesture",
        "intro_lines": ("One call near. One answer far. Then the trees go still.", "We follow the spaces between sounds from A to Z."),
        "hook_lines": ("Call, echo, hush—A-B-C!", "Branch to branch, the forest answers carefully."),
        "outro_lines": ("The river keeps talking after the last bird call.", "A to Z settles into evening hush."),
        "round2_patterns": ("Listening map {letter} ... {object}! {action}", "Near-or-far clue {letter} ... {object}! {action}", "Between sounds, {letter}? ... {object}! {action}", "Sound-or-sight {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Aspen! Leaves flutter softly between bird calls | a pale trunk marks where one sound came from."),
            ("B", "B ... B ... Bear! Heavy paws can press the ground quietly | we give wild animals distance and listen from far away."),
            ("C", "C? Chipmunk! Quick rustle under leaves | a small mammal darts before the branch above answers."),
            ("D", "D is Deer. Hooves place softly on the trail edge | ears turn toward every nearby sound."),
            ("E", "E — Evergreen! Needles hold a green pause | a silent shape between one call and the next."),
            ("F", "F ... F ... Fox! Light paws, pointed ears | a quiet hunter moving through the gaps in our sound map."),
            ("G", "G? Grouse! Ground bird under cover | sudden wings can thunder up from the hush."),
            ("H", "H is Hollow Log. Empty space inside fallen wood | a shelter that can deepen a tap or hold complete silence."),
            ("I", "I — Insect! Six small legs, tiny body | buzz, click, or wing-whir only when the insect truly makes it."),
            ("J", "J ... J ... Jay! A strong bird call jumps from branch to branch | bright sound before the next pause."),
            ("K", "K? Knot! A silent twist in wood | one visual marker while our ears wait for another clue."),
            ("L", "L is Lynx. Wild cat, tufted ears, quiet paws | almost no sound is still part of the listening map."),
            ("M", "M — Maple! Leaves rub and rustle when wind arrives | then stop when the air goes still."),
            ("N", "N ... N ... Nest! Twigs form a careful cup | we watch from a distance and keep the nest quiet."),
            ("O", "O? Oak! Broad branches hold many listening places | leaves answer wind more than they answer us."),
            ("P", "P is Pinecone. Woody scales close around seeds | a quiet forest object until it drops or rolls."),
            ("Q", "Q — Quail! Small ground bird in cover | a call may come before the bird itself appears."),
            ("R", "R ... R ... River! Steady water makes the longest sound in the song | a flowing line beneath shorter calls."),
            ("S", "S? Squirrel! Claws scratch bark, feet land light | quick movement climbs out of our ground-level hearing."),
            ("T", "T is Trail. Our own footsteps belong here too | step, stop, then leave room for the forest."),
            ("U", "U — Underbrush! Leaves and stems make close rustles | low cover can hide the source of a sound."),
            ("V", "V ... V ... Violet! A small quiet flower near the trail | color becomes the clue when sound gives us nothing."),
            ("W", "W? Wolf! A distant howl can travel across open forest | we listen from far away and never approach wildlife."),
            ("X", "X is Xylem. Tiny tubes carry water through a stem | a quiet plant pathway beneath the forest leaves."),
            ("Y", "Y — Yew! Evergreen needles stay quiet | we only look and never taste unknown forest plants."),
            ("Z", "At the forest edge, Z is Zebra Swallowtail. Black-and-white striped wings pass between woodland flowers."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Warm precise lead at 88 BPM with spacious stop-start 4/4, acoustic guitar, soft pizzicato strings, single woodblock taps and sparse birdlike flute replies. Never use continuous realistic bird recordings. The mix is a listening map: sound cue on one side, instrumental answer on the other, then silence. Round 1 treats quiet targets as intentional rests rather than inventing sounds. Chorus is call-echo-hush with a true gap after 'hush'. Round 2 uses near/far cues and one clean recall beat; no percussion at target onset. Wolf and Bear remain distance-observation only; Yew is look-don't-taste. Zebra Swallowtail closes the route as a real butterfly moving between woodland flowers. End with river-like guitar motion under fading instrumentation.",
    },
    "0024": {
        "authorial_intent": "Make woodland exploration feel like careful field observation: notice evidence, sketch shapes, check a clue, and leave living things undisturbed instead of turning scouting into chasing or collecting.",
        "lyric_identity": "A child keeps a tiny field notebook; recurring verbs are notice, sketch, mark, compare, leave, check and observe-from-distance.",
        "image_motifs": ("pencil field note", "hoof and paw tracks", "cone and bark shapes", "hollow log left untouched", "bird silhouette above trail"),
        "semantic_arc": ("open the notebook at the trailhead", "collect observations without collecting objects", "learn distance and habitat clues", "close the notebook and leave the woodland as found"),
        "forbidden_generic_language": ("spot each woodland clue with me", "explorer eyes", "collect every clue", "fun on the trail"),
        "rhyme_engine": "field-note-observation-slant-rhyme",
        "chorus_rhyme_engine": "clue-sketch-check-refrain",
        "point_of_view": "a preschool field scout making safe observations and leaving wildlife, nests, mushrooms and logs undisturbed",
        "chorus_function": "reinforce observe-record-leave rather than chase-touch-collect",
        "groove_meter": "walking 4/4 folk with pencil-tap pickups and open rests",
        "round1_grammar": "hand-written field-note entries with visible evidence, safe distance, and concise facts",
        "round2_grammar": "field-note cue -> recall beat -> target -> sketch/point/shape gesture, never collect",
        "intro_lines": ("Notebook open. Pencil ready. Hands stay gentle.", "A good scout notices more than a hurried walker."),
        "hook_lines": ("Clue, sketch, check—A-B-C!", "See it, name it, leave it where it should be."),
        "outro_lines": ("Notebook closed; every nest and log stays where we found it.", "A to Z comes home as notes, not souvenirs."),
        "interlude_lines": ("Pencil down for one beat—what clues can we recall without touching them?",),
        "round2_patterns": ("Field note {letter} ... {object}! {action}", "Sketch clue {letter} ... {object}! {action}", "Check {letter}? ... {object}! {action}", "Leave it, name {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "Field note A — Acorn. Hard oak seed with a little cup | sketch the shape and leave forest food where it fell."),
            ("B", "B ... B ... Bear! Broad paw shape is a distance clue | if a bear is nearby, we stay far away with an adult."),
            ("C", "C? Chipmunk! Quick stripes and a darting shape | observe the small mammal without following it off trail."),
            ("D", "D is Deer. Split hoofprints can mark soft ground | the animal itself deserves quiet space."),
            ("E", "E — Eagle! Wide-wing silhouette high above | one field mark seen without needing to get closer."),
            ("F", "F ... F ... Fern! Divided fronds repeat a feather-like pattern | draw the curve instead of pulling a leaf."),
            ("G", "G? Grouse! Sturdy ground bird, quick burst of flight | note where it was and let it move away."),
            ("H", "H is Hollow Log. Empty spaces can shelter small animals | look at the opening and never reach inside."),
            ("I", "I — Ivy! Climbing stems trace bark upward | follow the line with your eyes, not by pulling the plant."),
            ("J", "J ... J ... Juniper! Evergreen leaves and berry-like seed cones | notice color and shape; do not taste wild plants."),
            ("K", "K? Knot! Hard swirl in a trunk or log | a perfect pencil-shape showing where a branch once grew."),
            ("L", "L is Log. Fallen wood can become habitat | record bark, cracks, and moss while leaving the log in place."),
            ("M", "M — Mushroom! Cap and stem rise from damp ground | wild mushrooms are for looking, never tasting."),
            ("N", "N ... N ... Nest! Twigs form a cup for eggs or chicks | watch from far enough away not to disturb it."),
            ("O", "O? Owl! Round head, broad wings, hooked beak | a silhouette or distant call may be all the clue we need."),
            ("P", "P is Pinecone. Overlapping woody scales make a repeating pattern | sketch one where it lies."),
            ("Q", "Q — Quail! Small ground bird, quick feet | one short observation before it returns to cover."),
            ("R", "R ... R ... Rabbit! Long ears and strong hind legs | note the shape, then give the animal room."),
            ("S", "S? Spruce! Needle-like leaves crowd around twigs | compare the branch shape without breaking one off."),
            ("T", "T is Trail. The safest clue is also our boundary | stay on the path where the place asks us to."),
            ("U", "U — Underbrush! Shrubs and low plants make dense cover | a habitat clue we look into, not push through."),
            ("V", "V ... V ... Vine! Long stem climbs or trails | trace its route with one finger in the air."),
            ("W", "W? Woodpecker! Beak marks and drumming can point to a trunk | watch upward without crowding the bird."),
            ("X", "X is Xylem. Tiny tubes carry water through a stem | note the hidden plant pathway beneath the woodland leaves."),
            ("Y", "Y — Yellow Warbler! Small yellow bird among leaves | color and song become two field marks at once."),
            ("Z", "Z ... Z ... Zebra Swallowtail! Pale striped wings and long tails | let the butterfly choose its own path while we sketch."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Friendly focused adult lead at 90 BPM in walking acoustic 4/4 with muted guitar, soft kick, pencil-like rim taps, small mandolin answers and warm bass. The arrangement should feel like opening and closing a field notebook: cue, observe, short note, move on. Round 1 uses concrete field marks and conservation language without sounding preachy. Chorus is clue-sketch-check and lands clearly on 'leave it where it should be.' Round 2 uses sketch/point/air-trace gestures; never author collecting, touching nests, tasting mushrooms/plants, or approaching wildlife. Duck rim taps at every target onset. Keep technical Xylem speech-like and visualize it as plant tissue, not a separate shrub. End with pencil taps disappearing and a clean walking cadence.",
    },
    "0025": {
        "authorial_intent": "Let autumn change the same woodland object by object: some leaves loosen, some plants stay green, damp ground brings mushrooms, animals move through cooler cover, and the forest becomes more open as the canopy thins.",
        "lyric_identity": "A child watches one autumn day deepen from first falling leaf toward cooler evening; recurring language uses turn, loosen, drift, gather, thin, cool, copper, gold and green-stays-green.",
        "image_motifs": ("first spinning leaf", "yellow birch and acorn drop", "evergreen against changing color", "river carrying leaves", "bare branches revealing nest and knot"),
        "semantic_arc": ("first leaf falls", "color and seed movement spread", "cooler damp forest reveals hidden forms", "thinning canopy and river carry the season onward"),
        "forbidden_generic_language": ("autumn forest sing with me", "leaves are fun to see", "everything turns red", "shining bright"),
        "rhyme_engine": "autumn-leaf-cascade-delayed-rhyme",
        "chorus_rhyme_engine": "turn-fall-stay-refrain",
        "point_of_view": "a child noticing what changes and what stays the same as one woodland day moves deeper into autumn",
        "chorus_function": "contrast falling color with evergreen continuity",
        "groove_meter": "gentle 3/4 leaf-fall waltz with drifting pickups",
        "round1_grammar": "hand-written seasonal observations; color and change are specific, never claim every plant changes the same way",
        "round2_grammar": "season cue -> recall beat -> target -> drift/turn/shape gesture",
        "intro_lines": ("One leaf lets go, turns once, and lands without hurrying.", "Autumn changes the forest unevenly—that is what makes it worth watching."),
        "hook_lines": ("Gold turns, red falls—A-B-C!", "Some things change; some green stays with the trees."),
        "outro_lines": ("The river carries one last leaf past the darkening bank.", "A to Z ends cooler, quieter, and more open than it began."),
        "round2_patterns": ("Autumn clue {letter} ... {object}! {action}", "Season check {letter} ... {object}! {action}", "Changed or steady, {letter}? ... {object}! {action}", "Autumn recall {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Acorn! Hard oak seed drops and rolls | a small autumn weight beneath loosening leaves."),
            ("B", "B ... B ... Birch! Pale bark stays bright | many birch leaves turn yellow before they fall."),
            ("C", "C? Chipmunk! Quick paws move among seeds and leaves | autumn ground cover rustles around the small mammal."),
            ("D", "D is Deer. Hooves cross cooler soil | ears rise above grass losing some summer height."),
            ("E", "E — Evergreen! While other leaves loosen, evergreen foliage stays | one deep green note inside changing color."),
            ("F", "F ... F ... Fox! Bushy tail passes through copper leaves | soft paws barely move the cold ground."),
            ("G", "G? Grass! Green fades toward straw in some patches | thin blades bend under fallen leaves."),
            ("H", "H is Hedgehog. Spines slip through leaf cover | cool days make sheltered ground feel deeper."),
            ("I", "I — Ivy! Climbing leaves keep tracing bark | green against trunks where other foliage thins."),
            ("J", "J ... J ... Juniper! Evergreen leaves and berry-like seed cones | a color that does not follow every falling leaf."),
            ("K", "K? Knot! As branches show through thinner foliage | the old twist in wood becomes easier to notice."),
            ("L", "L is Lynx. Quiet paws cross a colder floor | wild fur moves through longer evening shadow."),
            ("M", "M — Mushroom! Damp autumn ground can lift caps from leaf litter | soft shapes after rain."),
            ("N", "N ... N ... Nest! When leaves thin, old branch-cups can be easier to spot | we still watch from a respectful distance."),
            ("O", "O? Oak! Leaves loosen one by one | acorns below carry the tree's next beginning."),
            ("P", "P is Pine. Needles stay green while broad leaves fall nearby | another way a forest can hold autumn."),
            ("Q", "Q — Quail! Small ground bird moves through dry cover | quick feet disappear under leaf-color."),
            ("R", "R ... R ... River! Cold water keeps moving | fallen leaves turn, spin, and travel along the bank."),
            ("S", "S? Spruce! Needle-covered branches remain green | dark shape against gold and bare twigs."),
            ("T", "T is Tree. Canopy thins, branches show | the same trunk wears a different season overhead."),
            ("U", "U — Upland Fern! Fronds can fade and fold as weather cools | feathered shapes settling toward the ground."),
            ("V", "V ... V ... Violet! Low leaves stay close to the soil | small green shapes beneath the fallen color."),
            ("W", "W? Wolf! A distant wild shape crosses cooler country | we observe only from far away."),
            ("X", "At the cabin porch, X is Xylem—tiny tubes carry water upward through a tree or plant stem."),
            ("Y", "Y — Yellow Warbler! A brief yellow flash among autumn leaves | one small bird-color before the branches open wider."),
            ("Z", "Z ... Z ... Zebra Swallowtail! On a last warm patch, striped wings pass low | summer-like motion at the edge of the cooling season."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Gentle close lead in 3/4 at 84 BPM with acoustic guitar, soft cello pizzicato, brushed shaker, tiny glockenspiel and airy mandolin. Arrange like a leaf fall: phrases enter high and settle lower, while harmony stays simple. Round 1 is a seasonal progression, not a list of orange/red clichés; Evergreens, Pine and Spruce must explicitly stay green. Let end rhyme appear as delayed three-line payoffs and internal vowel echoes rather than every pair. Chorus contrasts change versus continuity. Round 2 uses drift/turn gestures and a real recall beat. Wolf remains distant observation; Xylem is the plant tissue that carries water through a stem. End with river-like guitar arpeggio and no large final chorus.",
    },
}
