from __future__ import annotations

"""Authorial-identity deep polish for songs 0011-0015.

V4 remains the source of locked mappings, object facts/actions and broad form.
This layer gives the five farm songs genuinely different intentions, narrators,
image systems, rhyme behavior and hand-written Round-1 language.
"""


GOLD_V5_11_15_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0011": {
        "authorial_intent": "Make a farm feel as if it wakes sound by sound: latch, hoof, cluck, pour, wheel and crow become the child's path into the alphabet.",
        "lyric_identity": "A close morning listener stands near the gate and barn, naming each farm word through sound, motion and small workday details rather than generic farm praise.",
        "image_motifs": ("gate latch", "hoofbeats", "coop and straw", "bucket and pour", "wheels in the yard"),
        "semantic_arc": ("quiet gate begins to stir", "animals and feed wake the yard", "chores and farm tools put the day in motion", "the full farm soundscape settles again"),
        "forbidden_generic_language": ("farm words for you and me", "fun on the farm", "in our world today", "shining bright"),
        "rhyme_engine": "barn-sound-mosaic-internal-rhyme",
        "chorus_rhyme_engine": "paired-sound-hook",
        "point_of_view": "a child at the farm gate listening as the morning wakes one sound and object at a time",
        "chorus_function": "soundscape reset built from cluck, hoofbeat and waking motion",
        "groove_meter": "warm porch 4/4 with lightly swung hoofbeat pockets",
        "round1_grammar": "hand-written morning soundscape; each target earns one concrete sound, motion, texture or job, with internal rhyme/consonance only where it belongs naturally",
        "round2_grammar": "morning sound cue -> recall beat -> target -> safe object-specific gesture",
        "intro_lines": (
            "Gate latch clicks; one rooster sends the morning wide.",
            "Hoofbeat, cluck, bucket-ring—the farm wakes sound by sound.",
        ),
        "hook_lines": (
            "Cluck, creak, hoofbeat—A-B-C!",
            "Morning wakes in sound from A to Z!",
        ),
        "outro_lines": (
            "The last hoofbeat softens by the gate.",
            "A to Z has filled the waking farm day.",
        ),
        "interlude_lines": ("The yard goes quiet for one beat—can the morning sounds come back?",),
        "round1_patterns": (),
        "round2_patterns": (
            "Hear {letter} ... {object}! {action}",
            "{letter} ... {letter} ... {object}! {action}",
            "Morning call {letter}? ... {object}! {action}",
            "At the gate, {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "A — Apron! Cloth across the front | ready for splashes, crumbs, and farm-day mess."),
            ("B", "B ... B ... Bucket! Handle up, hollow down | water or feed rides from place to place."),
            ("C", "C is for Cow. Slow hoof, soft moo | grass goes in, steady chewing all morning through."),
            ("D", "D? Donkey! Long ears turn toward the gate | sturdy hooves carry a strong body down the lane."),
            ("E", "Near the coop, E is Egg. Smooth oval shell | small and still in a nest of straw."),
            ("F", "F — Fence! Post after post | a clear edge keeps field and animal space apart."),
            ("G", "G ... G ... Grain! Tiny seeds in a golden handful | wheat, oats, or corn begin this small."),
            ("H", "H is for Hay. Cut, dried, stacked | summer grass becomes feed for another day."),
            ("I", "I? Irrigation Pump! Water wakes in the pipe | pushed through hose or line toward thirsty crops."),
            ("J", "J — Jug! Handle in one hand, narrow mouth above | tip it gently and the liquid pours."),
            ("K", "K ... K ... Kid Goat! Quick little hooves, curious ears | a young goat testing every step."),
            ("L", "L is for Lamb. Soft fleece, small hooves | a young sheep stays close to the flock."),
            ("M", "M? Mule! Strong legs, steady pace | a sturdy hoofed animal that can carry or pull farm loads."),
            ("N", "N — Nectarine! Smooth skin, round fruit | ripening warm on a tree before it is picked."),
            ("O", "O ... O ... Ox! Slow pull, strong shoulders | trained cattle can move heavy farm loads."),
            ("P", "P is for Pig. Snout to soil | rooting, sniffing, stepping on four hooved feet."),
            ("Q", "Q? Quail! Low in the grass | quick feet, small pecks, then a sudden burst of wing."),
            ("R", "R — Rooster! Comb catches sunrise red | one bright crow carries over the yard."),
            ("S", "S ... S ... Scarecrow! Sleeves spread wide in the field | a human-shaped watcher meant to discourage hungry birds."),
            ("T", "T is for Tractor. Big wheels, low rumble | built to pull or power heavy farm work."),
            ("U", "U? Utility Cart! Tools, feed, supplies aboard | a small carrier rolling between jobs."),
            ("V", "V — Vet Kit! Simple checking tools packed together | helpers for a veterinarian caring for animals."),
            ("W", "W ... W ... Wagon! Four wheels follow the path | crops or supplies ride together."),
            ("X", "At the porch, X is X-ray Vet Image | a clear picture helps a farm vet see animal bones."),
            ("Y", "Y? Yam! Hidden under soil | a thick tuber stores food below the leaves."),
            ("Z", "Z — Zebu! Hump above the shoulders | sturdy cattle standing warm in the sun."),
        ),
        "style_blueprint": "Warm close adult lead with crisp dry diction. Porch-folk preschool 4/4 at 88 BPM with acoustic guitar, pizzicato fiddle, soft woodblock, brushed kick and a restrained barn-percussion feel. Open with a real waking soundscape—gate latch, distant rooster, hoofbeat, bucket ring—then let Round 1 feel like the farm waking sound by sound. Preserve the hand-written short/long contrast; do not force every target into equal bars. Let internal rhyme, alliteration and consonance behave like tiny acoustic answers, not a nursery-rhyme quota. Chorus should be a compact cluck/creak/hoofbeat identity hook with a small group echo. Round 2 uses sound cue, one clean recall beat, target confirmation and one safe gesture; duck fiddle/woodblock at target onset and answer after the word. Keep X-ray Vet Image clearly framed as a farm-veterinary observation tool. Stable simple harmony, no exaggerated country accent, no rapid patter, no animal-noise clutter over diction. End by thinning back toward the quiet gate.",
    },
    "0012": {
        "authorial_intent": "Turn the barn bell into a navigation device: every ring moves the child to another farm station, so the alphabet feels like a route rather than a list.",
        "lyric_identity": "A child follows bell echoes from barn door to stall, field, grain bin, orchard, tool area and animal-care corner; place words and distance cues carry the lyric.",
        "image_motifs": ("bell echo", "swinging barn door", "stall and fence", "grain bin and orchard rows", "far pen"),
        "semantic_arc": ("first ring opens the barn", "middle rings cross work and food areas", "later rings reach tools and animal care", "final ring closes the route at the far pen"),
        "forbidden_generic_language": ("find the farm word one-two-three", "beside the barn today", "fun to see", "say it with me"),
        "rhyme_engine": "bell-route-delayed-answer-rhyme",
        "chorus_rhyme_engine": "paired-bell-echo",
        "point_of_view": "a child navigating the farm by following a bell that sounds near, then farther away",
        "chorus_function": "re-establish direction and listening through a near/far bell echo",
        "groove_meter": "gentle 6/8 barn-bell sway with two-bar answer phrases",
        "round1_grammar": "hand-written route quatrains; spatial words and bell echoes connect neighboring targets, while exact facts remain clean and speech-natural",
        "round2_grammar": "bell cue -> recall beat -> target -> small location or object gesture",
        "intro_lines": (
            "Ding—barn door. Ding—field path.",
            "Follow each ring; every stop holds a letter.",
        ),
        "hook_lines": (
            "Ding near, ding far—A-B-C!",
            "Every ring reveals what we see!",
        ),
        "outro_lines": (
            "One last bell floats over the field.",
            "A to Z has answered every ring.",
        ),
        "round1_patterns": (),
        "round2_patterns": (
            "Bell cue {letter} ... {object}! {action}",
            "Ring for {letter} ... {object}! {action}",
            "Next stop, {letter}? ... {object}! {action}",
            "{letter} ... {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "First bell, A — Apple! Round fruit rests in a farm basket | our route begins with a crisp orchard clue."),
            ("B", "B is Barn. Door on hinges, roof overhead | shelter for animals, hay, tools, or supplies."),
            ("C", "At the near stall, C is Cow. Chew, step, moo | split hooves press the bedding slow."),
            ("D", "D? Donkey! Long ears rise above the half-door | sturdy hooves wait in the lane."),
            ("E", "Second ring finds E — Ewe. Wool over her back | an adult female sheep moving with the flock."),
            ("F", "F is Fence. Post after post marks the field edge | a clear boundary beside the barn and path."),
            ("G", "At the fence, G is Goat. Cloven hooves climb and balance | a curious browser reaching for leaves."),
            ("H", "H? Hay! Dry stems stacked high | cut plants saved as animal feed."),
            ("I", "Next bell, I — Ice Chest. Insulated walls, lid shut | helping food or drinks stay cold beside the work."),
            ("J", "J is Jar. Wide mouth, firm sides, lid on top | small things stay gathered inside."),
            ("K", "At the grain bin, K is Kernel. One tiny seed | corn or another grain held in your fingertips."),
            ("L", "L? Ladder! Rung over rung reaches up | an adult tool children only observe safely."),
            ("M", "Midday bell, M — Milk. Pale food made by mammals | on dairy farms it may be collected from animals such as cows or goats."),
            ("N", "N is Nectarine. Smooth skin, round fruit | ripening among the orchard leaves."),
            ("O", "Beyond the barn, O is Orchard. Tree after tree | fruit or nuts growing together."),
            ("P", "P? Pitchfork! Long handle, pointed tines | a farm tool we identify from a safe distance."),
            ("Q", "Bell carries to Q — Quail. Low bird, quick feet | pecking under field-edge cover."),
            ("R", "R is Rake. Long handle, teeth in a row | adults gather loose material across the ground."),
            ("S", "At the field, S is Scarecrow. Coat and hat on a still frame | a crop-side shape meant to discourage birds."),
            ("T", "T? Tractor! Engine hum grows near | heavy machine ready to pull or operate farm equipment."),
            ("U", "Last barn ring, U — Udder. Milk-producing organ beneath animals such as cows, goats, and sheep."),
            ("V", "V is Vegetable Basket. Gathered produce settles together | ready to be carried from the field."),
            ("W", "By the gate, W is Wagon. Four wheels turn | crops and supplies travel together."),
            ("X", "X? X-ray Vet Image! A picture from inside | helping a veterinarian see bones without opening the body."),
            ("Y", "One more ring, Y — Yam. Thick tuber underground | food stored where soil hides it."),
            ("Z", "Z is Zebu. At the far pen, a shoulder hump rises over sturdy cattle | the final stop on our bell-route."),
        ),
        "style_blueprint": "Clear warm adult lead with crisp consonants. Gentle 6/8 country-pop at 90 BPM with muted banjo, upright bass, brushes and one small bell color used as navigation, not constant decoration. Open with two separated bell rings—near then farther—so the listener learns the route idea immediately. Round 1 should move spatially from barn to stall, field, grain area, orchard, tools and animal care; each four-letter block feels like another stop. Use delayed rhyme and repeated vowel colors across a block when natural, but let technical lines stay plain. Chorus is the near/far bell hook. Round 2 begins with a single bell cue, leaves a real silent beat, then confirms the target; never strike the bell on the target's first syllable. Keep rare or technical targets near speech rhythm. Stable harmony, no fast bluegrass picking, no cowbell barrage. End with one distant bell and a clean cadence.",
    },
    "0013": {
        "authorial_intent": "Make the tractor pulse carry the alphabet through an actual working route: start, roll, stop, notice, turn, and come back with the farm changed by the day's work.",
        "lyric_identity": "A child rides an imagined tractor route around barn, pond, rows, orchard, animal yard and porch; wheel words and stop/go syntax provide the signature cadence.",
        "image_motifs": ("wheel track", "gate and fence", "field rows", "orchard turn", "dust settling behind the tractor"),
        "semantic_arc": ("engine starts at the barn", "route crosses animals and field edges", "work stops reach orchard and animal areas", "last row turns home and the engine rests"),
        "forbidden_generic_language": ("tools and crops from A to Z", "on our tractor trail", "point and name it on the trail", "fun to see"),
        "rhyme_engine": "tractor-wheel-rolling-internal-rhyme",
        "chorus_rhyme_engine": "roll-go-slant-rhyme",
        "point_of_view": "a child riding a slow imaginary tractor circuit and noticing what each stop is for",
        "chorus_function": "restart the wheel pulse and signal the next leg of the route",
        "groove_meter": "stop-go 4/4 wheel pulse with two-beat chug pickups",
        "round1_grammar": "hand-written route narration; wheel/row/turn/stop words recur lightly while each object receives its own physical or functional image",
        "round2_grammar": "tractor stop cue -> recall beat -> target -> safe gesture -> roll onward",
        "intro_lines": (
            "Chug-chug, wheel-turn—the gate rolls by.",
            "We won't stand still; each stop has a word.",
        ),
        "hook_lines": (
            "Chug, turn, stop—then on we roll!",
            "A to Z around the farm we go!",
        ),
        "outro_lines": (
            "Engine down; dust settles in the track.",
            "A to Z rode out and circled back.",
        ),
        "interlude_lines": ("Engine idles for one breath—now call the route stops back.",),
        "round1_patterns": (),
        "round2_patterns": (
            "Tractor stops at {letter} ... {object}! {action}",
            "Roll to {letter} ... {object}! {action}",
            "Ready, {letter}? ... {object}! {action}",
            "{letter} ... {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "Engine starts; A is Apron. Cloth across the front | helping work clothes stay cleaner while the route begins."),
            ("B", "B — Barn! Wide door, high roof | our rolling route begins beside the shelter."),
            ("C", "C? Chicken! Scratch-scratch near the wheel track | feet rake soil while the beak pecks small bits."),
            ("D", "D ... D ... Duck! Pond-side paddle | broad bill dips as the tractor rolls past water."),
            ("E", "First row, E — Egg. Smooth oval shell | still in the nest while wheels keep turning."),
            ("F", "F is Fence. Post, gap, post | a boundary traces the field beside our path."),
            ("G", "G? Grain! Tiny seed becomes a load | wheat, oats, or corn ready for the bin."),
            ("H", "H — Hen! Soft cluck by the coop | an adult female chicken that can lay eggs."),
            ("I", "Next stop, I — Ice Chest. Cool box, lid shut | food and drinks stay chilled during the workday."),
            ("J", "J ... J ... Jar! Wide mouth, firm sides | a lidded container carried carefully from shelf to table."),
            ("K", "K? Kid Goat! Two quick hoofbeats beside the track | young goat trots, pauses, looks back."),
            ("L", "L is Ladder. Rung after rung | adult climbing tool parked safely by the barn."),
            ("M", "Halfway round, M — Mule. Steady hooves, strong body | a working animal that can carry or pull."),
            ("N", "N ... N ... Nest! Twigs curl into a cup | a bird-built place for eggs and chicks."),
            ("O", "O? Orchard! The tractor leaves the yard for rows of fruit or nut trees."),
            ("P", "P is Pig. Snout down, soil up | rooting beside the pen as wheels roll on."),
            ("Q", "Farmhouse stop, Q — Quilt. Stitch after stitch | layered cloth folded warm and thick."),
            ("R", "R ... R ... Rake! Teeth in a row | an adult tool gathers loose material from the ground."),
            ("S", "S? Scarecrow! Arms out in the crop row | a still field figure built to discourage birds."),
            ("T", "T is Trough. Long open container | feed or water waits where farm animals can reach it."),
            ("U", "At the animal yard, U — Udder. Milk-producing organ beneath animals such as cows, goats, and sheep."),
            ("V", "V ... V ... Vegetable Basket! Harvest gathered together | one carry from field toward the farm table."),
            ("W", "W? Wheat! Tall grain heads ripple beside the track | seeds later ground to make flour."),
            ("X", "X is X-ray Vet Image. The route pauses at animal care | an inside view of bones helps the vet check what eyes cannot see."),
            ("Y", "Near the porch, Y — Yam. A thick underground tuber stores food below the leaves."),
            ("Z", "Last row, Z — Zucchini! Long green squash under broad leaves | the tractor trail ends where harvest grows."),
        ),
        "style_blueprint": "Crisp friendly adult lead over a steady preschool tractor pulse at 92 BPM, 4/4, with acoustic guitar, woodblock axle-clicks, soft bass, tiny harmonica answers and restrained kick. Open with two slow chugs and a wheel-turn pickup; never use realistic loud engine noise. Round 1 must feel like a route: barn, pond edge, field rows, orchard, animal yard, farmhouse, final crop row. Preserve stop/go language and rolling internal consonance, but do not make every line end-rhyme. Let short stop-lines contrast with two-bar descriptive lines. Chorus should physically feel like the wheels restart. Round 2: tractor stop cue, one beat of silence, clear target, gesture, then a tiny woodblock/harmonica answer. Technical/safety targets stay near speech rhythm. No rapid country patter, no vocal twang caricature, no percussion on target onsets. End with the engine implied to stop and the rhythm settling rather than an instrumental tail.",
    },
    "0014": {
        "authorial_intent": "Let changing daylight be the composer: the same farm is revealed differently at dawn, noon, afternoon and evening, giving the alphabet a calm emotional arc.",
        "lyric_identity": "A quiet observer follows light, shadow, dew, warmth and silhouette instead of narrating chores; rhyme is sparse and image-led.",
        "image_motifs": ("gold on roof and fence", "dew and pond light", "short noon shade", "long afternoon shadows", "evening silhouette"),
        "semantic_arc": ("first gold reveals the quiet farm", "morning movement widens into noon", "afternoon light lengthens and softens", "last silhouettes settle at day end"),
        "forbidden_generic_language": ("country words wake up with me", "morning light shining bright", "point and name it right", "fun on the farm"),
        "rhyme_engine": "sunlight-assonance-open-cadence",
        "chorus_rhyme_engine": "slow-grow-paired-rhyme",
        "point_of_view": "a quiet child observer watching one farm change as sunlight travels across the day",
        "chorus_function": "mark the passage of light without turning the calm song into a high-energy reset",
        "groove_meter": "open 6/8 sunrise folk sway",
        "round1_grammar": "hand-written time-of-day imagery with sparse rhyme, assonance and long breathing space; facts are embedded in light, shadow, texture and movement",
        "round2_grammar": "soft light cue -> two-beat recall space -> target -> restrained gesture",
        "intro_lines": (
            "First gold touches the fence before the yard is loud.",
            "We follow the light as the farm wakes.",
        ),
        "hook_lines": (
            "Sunrise gold—soft and slow.",
            "A-B-C—the whole farm starts to glow.",
        ),
        "outro_lines": (
            "Long shadows cross the field, then fade.",
            "A to Z rests at the end of day.",
        ),
        "round1_patterns": (),
        "round2_patterns": (
            "Soft light, {letter} ... {object}! {action}",
            "Remember {letter} ... {object}! {action}",
            "{letter}? ... {object}! {action}",
            "Show {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "Dawn touches A — Apple. Round fruit hangs among leaves beaded with morning light."),
            ("B", "B is Barn. Roofline turns gold first | shelter still quiet beneath it."),
            ("C", "C? Chicken! Scratch in the soft yard | small pecks begin as the morning shadows shorten."),
            ("D", "D — Duck. First light trembles on pond water | webbed feet paddle through it."),
            ("E", "E ... E ... Ewe. Wool catches pale light | an adult female sheep walking out with the flock."),
            ("F", "F is Fence. Morning light catches each post | the field edge becomes a clear line beside the farm."),
            ("G", "G? Grain! Dew catches the field | wheat, oats, or corn all give us small harvested seeds."),
            ("H", "H — Hen. Soft cluck in the coop | an adult female chicken that can lay eggs."),
            ("I", "Sun climbs; I is Irrigation Pump. Water moves through hose and pipe toward the crops."),
            ("J", "J ... J ... Jug. Handle steady, narrow mouth | tip it and liquid pours in one clear stream."),
            ("K", "K? Kid Goat! Quick hooves cross a stripe of sun | curious ears turn toward every sound."),
            ("L", "L is Lamb. Small hooves, soft fleece | a young sheep warm in the widening light."),
            ("M", "At noon, M — Milk. Pale food from mammals | part of the daily work on a dairy farm."),
            ("N", "N ... N ... Nest. Twigs hold a shaded cup | eggs or chicks rest inside."),
            ("O", "O? Ox! Strong shoulders under bright noon | trained cattle can pull heavy loads."),
            ("P", "P is Pig. Snout searches cool soil | stout body steps into the shade."),
            ("Q", "Afternoon, Q — Quilt. Stitch after stitch | layered cloth waits folded for cooler hours."),
            ("R", "R ... R ... Rooster! Morning crow is gone | bright comb still catches the sun."),
            ("S", "S? Sheep! Fleece catches the long light | grazing slows near day's end."),
            ("T", "T is Trough. Long open shape holds feed or water as evening chores begin."),
            ("U", "Low sun finds U — Udder. Milk-producing organ beneath animals such as cows, goats, and sheep."),
            ("V", "V ... V ... Vet Kit. Simple animal-check tools packed together | ready when a veterinarian needs them."),
            ("W", "W? Wagon! Four wheels cross long shadows | carrying crops or supplies toward the barn."),
            ("X", "X is X-ray Vet Image. Bones show in an inside view | one quiet clue for animal care."),
            ("Y", "Last light, Y — Yam. Thick tuber stays hidden in soil while leaves darken above."),
            ("Z", "Z ... Z ... Zebu. Shoulder hump in silhouette | cattle standing calm as daylight leaves the field."),
        ),
        "style_blueprint": "Intimate warm adult lead, minimal vibrato and close diction. Open 6/8 sunrise folk at 84 BPM with nylon guitar, mandolin taps, soft shaker, tiny glockenspiel and warm bass. The arranging principle is daylight: sparse dawn, slightly fuller morning, warm noon center, then thinning afternoon and evening. Round 1 is image-led free verse with sparse end rhyme; use assonance, held vowels and silence instead of forcing couplets. Long factual lines may take two bars, while short light-images can land in one. Chorus stays gentle—sunrise gold, soft and slow—without a big pop lift. Round 2 uses two supportive beats of recall space and restrained gestures; no bell or percussion attack on target onset. Technical animal-care terms stay speech-clear. End with longer guitar decay and the image of shadows fading, not spoken praise or a repeated high-energy hook.",
    },
    "0015": {
        "authorial_intent": "Use harvest as a cumulative act of gathering: the day begins with an empty basket, crosses orchard, yard and field work, and ends with a full sense of what the farm produced and used.",
        "lyric_identity": "A child joins harvest day with hands, baskets, rows and carrying motions; the lyric distinguishes what is actually gathered from tools, animals and helpers that make gathering possible.",
        "image_motifs": ("empty basket", "orchard rows", "hands lifting and carrying", "stacked hay and grain", "full basket heading home"),
        "semantic_arc": ("empty basket and first pick", "farm helpers and field work support the harvest", "loads gather and move", "basket and day finish full"),
        "forbidden_generic_language": ("harvest words are fun to see", "fill the basket with every object", "show the match and say", "shining bright"),
        "rhyme_engine": "cumulative-harvest-refrain-rhyme",
        "chorus_rhyme_engine": "cumulative-open-refrain",
        "point_of_view": "a child helping with a safe harvest day and noticing what gets picked, carried, stored or simply observed",
        "chorus_function": "measure how the day is filling rather than claiming every mapped item literally goes in the basket",
        "groove_meter": "clap-friendly 4/4 harvest walk with lift-and-place accents",
        "round1_grammar": "hand-written cumulative harvest scene; use pick, lift, carry, stack, pour and gather vocabulary selectively while clearly separating animals/tools from actual basket contents",
        "round2_grammar": "gather cue -> recall beat -> target -> safe pick/carry/shape gesture",
        "intro_lines": (
            "Empty basket, cool morning, orchard rows ahead.",
            "Rustle, lift, carry—the harvest day begins.",
        ),
        "hook_lines": (
            "Fill the basket—A-B-C!",
            "Harvest day grows full by Z!",
        ),
        "outro_lines": (
            "Basket full; long shadows cross the floor.",
            "We gathered A to Z—and still the fields hold more.",
        ),
        "round1_patterns": (),
        "round2_patterns": (
            "Harvest clue {letter} ... {object}! {action}",
            "Spot {letter} ... {object}! {action}",
            "{letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
        ),
        "round1_overrides": (
            ("A", "Empty basket, A — Apple! Round fruit twists from the branch | first harvest weight in our hands."),
            ("B", "B is Bucket. Handle lifts, open top waits | water or gathered things can travel inside."),
            ("C", "C? Chicken! Scratch and peck beside the orchard path | quick feet stir dry earth."),
            ("D", "D ... D ... Duck! At the pond, webbed feet paddle | harvest day keeps moving past the water."),
            ("E", "Gather clue E — Egg. Smooth oval shell | set carefully, never tossed."),
            ("F", "F is Fence. Post after post | it marks where field ends and path begins."),
            ("G", "G? Goat! Cloven hooves at the gate | a curious browser reaches for leaves."),
            ("H", "H — Hay. Cut, dried, stacked | golden feed saved after the field is cleared."),
            ("I", "Next load, I — Irrigation Pump. Water pushed through hose and pipe helped crops reach harvest."),
            ("J", "J ... J ... Jug! Handle, narrow mouth | liquid pours in a steady stream."),
            ("K", "K? Kid Goat! Quick hooves circle the busy yard | a young goat curious about every lift and step."),
            ("L", "L is Ladder. Rung over rung | adults use it to reach high places; children watch safely."),
            ("M", "Midday break, M — Milk. Pale food produced by mammals | common in dairy-farm life."),
            ("N", "N ... N ... Nest. Twigs cradle eggs or chicks | a different kind of gathering place."),
            ("O", "O? Orchard! Tree after tree | this is where many fruit harvests begin."),
            ("P", "P is Pitchfork. Long handle, pointed tines | adult farm tool, seen and named from a safe distance."),
            ("Q", "Fuller day, Q — Quilt. Stitch after stitch | soft layers come together as one warm blanket."),
            ("R", "R ... R ... Rake! Teeth in a row | adults pull loose plant material into a pile."),
            ("S", "S? Sheep! Woolly fleece in the field | grazing while harvest work passes nearby."),
            ("T", "T is Tractor. Big wheels carry the work onward | pulling or powering heavy equipment."),
            ("U", "Last loads, U — Utility Cart. Tools and supplies ride together from job to job."),
            ("V", "V ... V ... Vegetable Basket! This one really fills | gathered produce settles side by side."),
            ("W", "W? Wheat! Tall grain heads hold the seeds | grain later ground to make flour."),
            ("X", "X is Xylem—plant tubes carry water upward | a hidden harvest helper inside every stem."),
            ("Y", "Near the bottom, Y — Yam. Thick underground tuber | harvest comes up from soil, not down from a branch."),
            ("Z", "Z ... Z ... Zebu. Shoulder hump above sturdy cattle | one last farm clue as the full basket heads home."),
        ),
        "style_blueprint": "Bright but grounded adult lead with crisp diction. Clap-friendly harvest acoustic pop in 4/4 at 93 BPM with ukulele, soft hand drum, shaker, pizzicato strings and occasional basket-tap percussion. Open with an empty-basket image and real lift/carry rhythm, not a generic celebration. Round 1 is cumulative: the listener should feel the day filling as fruit, grain and produce are gathered while animals, fences, tools and vehicles are clearly framed as helpers or surrounding farm life—not literally placed in the basket. Use repeated lift/place accents, internal rhyme and occasional refrain-like wording, but avoid one tail on all 26 lines. Chorus measures progress toward a full harvest day. Round 2 leaves one clear recall beat after each gather/basket cue; use safe pick, carry, point or shape motions and keep tools observation-only. Duck claps on target onsets. Xylem remains an explicit plant-water pathway inside the crop story. End with a full-basket image, long shadows and a clean acoustic stop.",
    },
}
