from __future__ import annotations

"""Authorial-identity deep polish for polar songs 0036-0040."""

GOLD_V5_36_40_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0036": {
        "authorial_intent": "Turn the polar parade into a study of movement across three surfaces—snow, ice and sea—so walking, flying, diving and swimming replace a generic marching-song idea.",
        "lyric_identity": "A child watches transitions between land, ice edge, air and water; recurring language uses step, slide, dive, surface, cross, launch and return.",
        "image_motifs": ("caribou hoof on snow", "dovekie dive", "seal at ice edge", "orca surfacing", "walrus hauling near shore"),
        "semantic_arc": ("begin on snowy ground", "reach ice edge and seabirds", "move into cold ocean", "return to tundra and shore with many movement types"),
        "forbidden_generic_language": ("snowy animals march with me", "polar parade", "everyone marches", "cold fun"),
        "rhyme_engine": "polar-land-ice-sea-motion-rhyme",
        "chorus_rhyme_engine": "step-dive-swim-hook",
        "point_of_view": "a child comparing honest ways animals cross land, ice, air and cold water",
        "chorus_function": "reset the land-ice-sea movement map rather than force all animals into marching",
        "groove_meter": "light 4/4 with grounded steps, open flight phrases and fluid swim tails",
        "round1_grammar": "hand-written locomotion contrasts; nonliving ice, tundra and quartz anchor movement instead of being made to move like animals",
        "round2_grammar": "surface/motion cue -> recall beat -> target -> safe abstract gesture",
        "intro_lines": ("One track crosses snow; one wing crosses air; one flipper cuts the sea.", "There is no single way to move through the polar world."),
        "hook_lines": ("Step, fly, dive—A-B-C!", "Land, ice, sea—each body finds a way."),
        "outro_lines": ("The last swimmer slips below; the last bird clears the shore.", "A to Z leaves tracks in three different worlds."),
        "round2_patterns": ("Surface clue {letter} ... {object}! {action}", "Movement clue {letter} ... {object}! {action}", "Land, air, or sea—{letter}? ... {object}! {action}", "Polar route {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Auk! Compact seabird uses wings in air and underwater | one body crossing two kinds of space."),
            ("B", "B ... B ... Bear! Broad paws carry a large furry mammal over land | movement stays grounded and powerful."),
            ("C", "C? Caribou! Broad hooves travel snow and soft tundra | long-distance walking begins our land route."),
            ("D", "D is Dovekie. Small black-and-white seabird dives into cold water | flight turns suddenly into swimming."),
            ("E", "E — Eider! Sea duck paddles, dives, then lifts on strong wings | shore, water, air in one route."),
            ("F", "F ... F ... Fur Seal! Front flippers steer a fast swimmer | thick fur belongs to a body built for cold coasts."),
            ("G", "G? Glacier! Huge ice mass moves very slowly over land | a non-animal motion measured on a far longer clock."),
            ("H", "H is Harp Seal. Flippers push through water, body rests on ice | movement changes at the ice edge."),
            ("I", "I — Iceberg! Floating ice drifts with water and wind | no legs, wings, or flippers needed."),
            ("J", "J ... J ... Jellyfish! Soft bell pulses while current carries it | a drifting kind of ocean movement."),
            ("K", "K? Kittiwake! Long wings carry a seabird over cold water | landing places wait on shore or cliffs."),
            ("L", "L is Lemming. Small northern rodent runs close to tundra ground | tiny steps under a huge sky."),
            ("M", "M — Murre! Seabird flies above waves and dives below them | another air-to-water switch."),
            ("N", "N ... N ... Northern Fulmar! Stiff wings glide low over ocean | long smooth motion using moving air."),
            ("O", "O? Orca! Powerful tail drives a large dolphin through cold sea | the back rises to breathe at the surface."),
            ("P", "P is Polar Bear. Broad paws cross ice and snow, and the bear can swim | one animal linking land and sea."),
            ("Q", "Q — Quartz! Hard mineral stays where rock holds it | a still marker among all these moving bodies."),
            ("R", "R ... R ... Reindeer! Reindeer are caribou | broad hooves support travel over snow and soft ground."),
            ("S", "S? Snowy Owl! Broad wings cross open tundra | feathered flight above low snow."),
            ("T", "T is Tundra. Cold open land with few or no trees | the ground stage for walkers, runners, and nests."),
            ("U", "U — Upland Goose! Strong legs walk ground and wings take over in flight | another two-mode traveler."),
            ("V", "V ... V ... Velvet Scoter! Dark sea duck with pale wing patch | paddling, diving, and flying across coastal water."),
            ("W", "W? Walrus! Flippers move a heavy body through sea | tusks and foreflippers help at the shore and ice edge."),
            ("X", "At the warm shelter, X is X-shaped Snowflake. Branching ice arms meet in a simple X-like crystal."),
            ("Y", "Y — Yellow-billed Loon! Large loon flies and dives | yellow bill points ahead over cold northern water."),
            ("Z", "Z ... Z ... Zoarcid Fish! Eel-shaped fish bends through cold water | our final route stays completely below the surface."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Warm adult lead at 90 BPM, clear 4/4 with muted guitar, soft kick, brushed snare, pizzicato strings and airy flute. Give locomotion families distinct phrasing: grounded quarter-note steps, legato flight, descending dive figures, fluid swim tails. Round 1 must not make ice, quartz or tundra 'march'. Chorus is step-fly-dive and land-ice-sea. Round 2 uses abstract arm/hand gestures, one recall beat, and dry target onsets. X-shaped Snowflake is a branching ice-crystal pattern, not an animal. End by thinning from land pulse into one low fluid note.",
    },
    "0037": {
        "authorial_intent": "Use reflected polar light as the organizing image: snow, floe, pale animals, dark birds and open water change how color is noticed in a low-light tundra world.",
        "lyric_identity": "A quiet child observer watches contrast rather than sparkle clichés; recurring language uses pale, blue-shadow, low sun, dark-on-white, reflection, soft edge and glow.",
        "image_motifs": ("arctic fox against snow", "beluga under blue water", "dark jaeger over pale tundra", "quartz catching low light", "yellow loon bill at dusk"),
        "semantic_arc": ("pale morning reveals low-contrast forms", "dark and bright animals sharpen the scene", "sea and ice reflect different color", "blue evening closes with small warm details"),
        "forbidden_generic_language": ("ice and snow shine back to me", "tundra glow", "sparkle everywhere", "everything is white"),
        "rhyme_engine": "polar-light-contrast-open-cadence",
        "chorus_rhyme_engine": "pale-dark-blue-hook",
        "point_of_view": "a child learning to see subtle color and contrast in snow, tundra and cold water",
        "chorus_function": "restate pale-dark-blue contrast without turning the song into a glitter effect",
        "groove_meter": "slow open 6/8 with held reflected-light phrases",
        "round1_grammar": "hand-written color-and-light observations; facts stay concrete and not every target is described as white or glowing",
        "round2_grammar": "light/contrast cue -> recall beat -> target -> gentle point/shape gesture",
        "intro_lines": ("Low light lies blue in the snow while one dark wing crosses it.", "Polar color is quiet until contrast teaches us where to look."),
        "hook_lines": ("Pale, dark, blue—A-B-C!", "Low light makes small colors matter more."),
        "outro_lines": ("Blue shadow deepens; one yellow bill is still easy to find.", "A to Z fades into a softer kind of light."),
        "interlude_lines": ("Close your eyes for one beat—what pale, dark, or blue clues return?",),
        "round2_patterns": ("Light clue {letter} ... {object}! {action}", "Contrast {letter} ... {object}! {action}", "Pale or dark, {letter}? ... {object}! {action}", "Blue-shadow {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Arctic Fox! Thick fur can look pale against winter snow | shape appears through shadow, ears, and movement."),
            ("B", "B ... B ... Beluga! Pale whale moves under blue-gray water | rounded forehead catches soft surface light."),
            ("C", "C? Caribou! Brown-gray body and antlers stand against open snow | dark legs sharpen the outline."),
            ("D", "D is Dovekie. Black-and-white seabird | strong contrast makes a tiny bird readable against sea and sky."),
            ("E", "E — Ermine! Small weasel may wear white winter fur in cold regions | dark eyes and nose remain clear points."),
            ("F", "F ... F ... Floe! Flat sea ice carries pale light on top | blue water cuts a darker edge around it."),
            ("G", "G? Goose! Feathered body crosses low tundra | color changes with species, but shape and wingbeat stay useful clues."),
            ("H", "H is Harp Seal. Pale coat can carry a dark harp-shaped marking in adults | pattern holds even in low color."),
            ("I", "I — Icefish! Cold-water fish stays below the bright ice surface | underwater light softens every edge."),
            ("J", "J ... J ... Jaeger! Darker seabird sweeps over pale ground and water | contrast makes fast flight easy to follow."),
            ("K", "K? Krill! Tiny crustaceans gather in cold water | small bodies become visible through number, not bold color."),
            ("L", "L is Lynx. Fur, ear tufts, and quiet outline | a warm-toned wild cat shape against colder ground."),
            ("M", "M — Musk Ox! Dark shaggy coat stands heavy against snow | long hair makes a broad silhouette."),
            ("N", "N ... N ... Northern Fulmar! Gray-white seabird glides over steel-blue water | soft colors, strong wing shape."),
            ("O", "O? Owl! Round head and wings can appear as pale or dark shapes depending on species | silhouette matters more than glitter."),
            ("P", "P is Puffin. Black-and-white body with a colorful bill | one small patch of strong color near cold water."),
            ("Q", "Q — Quartz! Hard mineral catches low-angle light with a glassy flash | a stone clue, not living glow."),
            ("R", "R ... R ... Ringed Seal! Pale ring patterns mark a gray coat | circles break up the body against ice and sea."),
            ("S", "S? Snowy Owl! Pale feathers blend with snow | dark eyes give the face its clearest contrast."),
            ("T", "T is Tundra. Low plants, snow, rock, and long sky | a wide background where tiny color differences matter."),
            ("U", "U — Umiak! Traditional open Arctic boat | dark hull shape can sit clearly against pale shore or water."),
            ("V", "V ... V ... Vole! Small ground mammal stays low | little dark movement against snow can reveal it before detail does."),
            ("W", "W? Walrus! Brown heavy body, pale tusks | warm earth color against cold blue-gray sea."),
            ("X", "X is X-shaped Snowflake. Branching ice arms meet in a simple X-like crystal | a clear pattern in the cold."),
            ("Y", "Y — Yellow-billed Loon! Dark-and-pale northern bird | the yellow bill becomes a small strong color at the end of day."),
            ("Z", "Z ... Z ... Zoarcid Fish! Eel-shaped cold-water fish | soft underwater light follows the long body into blue shadow."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Intimate lead at 80 BPM in open 6/8 with nylon guitar, soft piano, bowed pad, tiny glockenspiel and restrained bass. Use low dynamic range and lots of air; 'glow' comes from sustained harmony, not sparkly percussion everywhere. Round 1 emphasizes contrast—pale, dark, blue-gray, warm brown, one yellow detail. Chorus stays gentle. Round 2 leaves two quiet beats for recall and no attack on target syllables. Technical targets like Umiak, Krill and Zoarcid Fish stay near speech rhythm. End with blue-hour harmonic thinning.",
    },
    "0038": {
        "authorial_intent": "Build the frozen-ocean song around the boundary between sea ice and water: tiny drifting life supports fish, birds dive, seals and whales surface, while land tools and animals remain clearly outside the marine food web.",
        "lyric_identity": "A child looks above ice, at the edge, and below water; recurring language uses under-ice, surface, edge, drift, dive, breathe and food-web link.",
        "image_motifs": ("zooplankton drifting below ice", "cod and icefish", "dovekie/murre dive", "seal breathing at ice edge", "whale surfacing beyond floe"),
        "semantic_arc": ("start at ice surface", "look below to small ocean life and fish", "follow divers and marine mammals", "return to shore where sleds and land animals belong"),
        "forbidden_generic_language": ("cold blue words swim back to me", "everything swims", "frozen ocean fun", "under the ice all day"),
        "rhyme_engine": "sea-ice-boundary-foodweb-rhyme",
        "chorus_rhyme_engine": "above-edge-below-hook",
        "point_of_view": "a child studying the sea-ice boundary and separating marine life from shore and travel objects",
        "chorus_function": "orient above ice, ice edge and below water before another ecology block",
        "groove_meter": "stop-go 4/4 with submerged legato sections",
        "round1_grammar": "hand-written sea-ice ecology; links are factual and land/transport targets stay outside the food-web claim",
        "round2_grammar": "above/edge/below cue -> recall beat -> target -> safe position gesture",
        "intro_lines": ("Ice above. Dark water below. A tiny drifting life begins the story.", "The frozen ocean is an edge between two worlds, not one sheet of white."),
        "hook_lines": ("Above, edge, below—A-B-C!", "Under the ice, a cold ocean keeps moving."),
        "outro_lines": ("One last whale breath lifts beyond the floe.", "A to Z sinks back toward tiny drifting life below."),
        "round2_patterns": ("Ice-edge map {letter} ... {object}! {action}", "Above-or-below {letter} ... {object}! {action}", "Ocean-or-land clue {letter}? ... {object}! {action}", "Context clue {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Auk! Seabird flies above the ice edge and dives for food | air and cold water meet in one target."),
            ("B", "B ... B ... Beluga! Pale whale lives in northern seas | rounded forehead rises when the animal surfaces to breathe."),
            ("C", "C? Cod! Cold-water fish swims below the surface | part of the ocean food web beneath birds and larger predators."),
            ("D", "D is Dog Sled. Runners travel over snow on land or sea ice | transportation above the ocean, never a marine animal."),
            ("E", "E — Eider! Sea duck floats at the surface and dives | feathered life working right at the water-air boundary."),
            ("F", "F ... F ... Fur Seal! Strong flippers drive the swimmer | thick fur helps in cold coastal water."),
            ("G", "G? Glacier! Land ice flows slowly toward coast | frozen freshwater meeting the ocean scene from above."),
            ("H", "H is Husky. Thick-coated working dog belongs with people and sled travel | a shore-and-snow clue outside the marine food web."),
            ("I", "I — Icefish! Cold-water fish remains below the ice world | fins hold it inside the submerged layer."),
            ("J", "J ... J ... Jaeger! Strong-flying seabird crosses ocean and tundra | air route above the marine layers."),
            ("K", "K? Kittiwake! Seabird glides above waves and feeds around cold coasts | winged life tied to the ocean edge."),
            ("L", "L is Lynx. Wild cat stays on land | a deliberate contrast so our ocean map keeps its boundaries honest."),
            ("M", "M — Murre! Wings carry it above water, then help underwater pursuit | a true diver between layers."),
            ("N", "N ... N ... Narwhal! Arctic whale can carry a long spiral tusk | surfaces to breathe through the cold sea world."),
            ("O", "O? Owl! Land-and-air bird, not an ocean swimmer | one shoreline contrast beside all the divers."),
            ("P", "P is Polar Bear. Arctic bear crosses ice and can swim | a surface predator linking frozen platform and water."),
            ("Q", "Q — Qajaq! Greenlandic word behind kayak | narrow traditional boat used on Arctic waters, clearly a human craft."),
            ("R", "R ... R ... Ringed Seal! Small Arctic seal with pale ring markings | ice edge offers breathing and resting places."),
            ("S", "S? Snowy Owl! Tundra bird flies above the frozen-ocean margin | feathers stay in the air-and-land layer."),
            ("T", "T is Tern. Pointed wings carry a slender seabird | many terns dive toward water for food."),
            ("U", "U — Umiak! Traditional open Arctic boat carries people or supplies | another human travel object above the water."),
            ("V", "V ... V ... Vole! Tiny ground mammal lives on land | small tundra life outside our submerged food chain."),
            ("W", "W? Whale! Tail drives the body through sea | lungs mean every whale eventually returns to the surface to breathe."),
            ("X", "X is X-shaped Snowflake. Branching ice arms meet in a simple X-like crystal | a visible frozen pattern on the Arctic shore."),
            ("Y", "Y — Yak! Long-haired hoofed mammal belongs on land in cold high country | a Y contrast, not frozen-ocean wildlife."),
            ("Z", "Z ... Z ... Zooplankton! Tiny drifting animals move with water | small food-web life beneath much larger ocean motion."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Clear adult lead at 88 BPM, stop-go 4/4 with acoustic guitar, low marimba, soft kick, bowed bass and submerged synth-like pad kept very light. Above-ice lines are drier; below-water lines become legato and lower; ice-edge lines combine both. Round 1 must explicitly keep Dog Sled, Husky, Lynx, Owl, Vole, Yak as land or ice-edge subjects, while X-shaped Snowflake is treated as a visible branching ice pattern. Chorus is above-edge-below. Round 2 uses vertical hand positions and one recall beat. End by descending toward a quiet zooplankton-scale texture.",
    },
    "0039": {
        "authorial_intent": "Make an Arctic trek a sequence of changing travel conditions: walk on tundra, use sled routes on snow, stop at ice edge, shift to qajaq or umiak on water, and read wildlife without treating expedition as conquest.",
        "lyric_identity": "A child follows a supervised route and changes travel mode when terrain changes; recurring language uses map, route, runner, shore, launch, turn back, safe distance and next leg.",
        "image_motifs": ("map at tundra start", "dog-sled runners", "floe and glacier checkpoint", "qajaq/umiak at shore", "walrus at distant ice edge"),
        "semantic_arc": ("prepare and walk", "cross snow and ice by route", "reach water and change craft", "finish at shore with wildlife left undisturbed"),
        "forbidden_generic_language": ("find the icy clues with me", "Arctic explorer", "conquer the ice", "go anywhere"),
        "rhyme_engine": "arctic-route-mode-change-rhyme",
        "chorus_rhyme_engine": "map-route-change-hook",
        "point_of_view": "a child on a supervised Arctic learning expedition where terrain determines travel mode and wildlife sets distance rules",
        "chorus_function": "restate map-route-change and prepare the next terrain transition",
        "groove_meter": "walking 4/4 with mode-change half-time transitions",
        "round1_grammar": "hand-written route progression; travel objects have real functions and animals remain observations rather than obstacles or trophies",
        "round2_grammar": "route cue -> recall beat -> target -> map/point/shape gesture",
        "intro_lines": ("Map open: tundra first, snow route second, open water only where a safe crossing begins.", "A good trek changes plan when the ground changes."),
        "hook_lines": ("Map, route, change—A-B-C!", "Land, ice, water tell us how to travel next."),
        "outro_lines": ("Back at shore, every wild track keeps going without us.", "A to Z closes the map instead of claiming the route."),
        "interlude_lines": ("Map folded for one beat—what route changes can we remember?",),
        "round2_patterns": ("Route clue {letter} ... {object}! {action}", "Checkpoint {letter} ... {object}! {action}", "Land-or-water {letter}? ... {object}! {action}", "Map mark {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "Start A — Arctic Fox. Thick fur and small body move across tundra | wildlife clue beside the route, never something to follow closely."),
            ("B", "B ... B ... Beluga! Pale whale belongs to northern water | a sign that the route has reached sea, not another snow walker."),
            ("C", "C? Cod! Fish below cold water | a submerged checkpoint our boots can never reach."),
            ("D", "D is Dog Sled. Long runners glide over snow behind a trained dog team | a travel tool used with skilled adult handling."),
            ("E", "E — Ermine! Small weasel may turn white in winter | quick wildlife crossing near the land leg."),
            ("F", "F ... F ... Floe! Flat piece of floating sea ice | route boundary, not ordinary ground to wander onto."),
            ("G", "G? Glacier! Huge land-ice mass moves slowly | a landmark that changes the map on a much larger scale."),
            ("H", "H is Husky. Thick-coated working dog can be part of trained sled travel | animal partner, not a machine."),
            ("I", "I — Iceberg! Floating ice rises above water while much remains below | navigation means keeping safe distance."),
            ("J", "J ... J ... Jellyfish! Soft drifting body in cold water | one water clue after our route leaves the snow."),
            ("K", "K? Kittiwake! Seabird crosses above the route | wings ignore the boundaries that matter to people on the ground."),
            ("L", "L is Lemming. Small tundra rodent moves low among plants and snow | a land clue near our boot-level world."),
            ("M", "M — Musk Ox! Shaggy herd animal of Arctic tundra | broad shape watched from respectful distance."),
            ("N", "N ... N ... Narwhal! Arctic whale with a possible long spiral tusk | water-route wildlife beyond the ice edge."),
            ("O", "O? Orca! Powerful marine mammal surfaces to breathe | another reason water is its own route, not frozen land."),
            ("P", "P is Polar Bear. Large Arctic predator crosses ice and snow and can swim | any real encounter means expert safety and distance."),
            ("Q", "Q — Qajaq! Greenlandic traditional narrow boat behind the word kayak | one-person watercraft belongs to skilled Arctic travel."),
            ("R", "R ... R ... Reindeer! Reindeer are caribou | broad hooves move over snow and tundra beside our land route."),
            ("S", "S? Seal! Flippers take over where feet would fail | marine wildlife at the edge between travel modes."),
            ("T", "T is Tern. Pointed wings cross above shore and water | a sky route we only watch."),
            ("U", "U — Umiak! Traditional open Arctic boat carries people and supplies | a different watercraft for a different travel need."),
            ("V", "V ... V ... Velvet Scoter! Dark sea duck with pale wing patch | water-and-air clue near the marine leg."),
            ("W", "W? Walrus! Heavy marine mammal with tusks and whiskers | keep distance at shore or ice edge."),
            ("X", "X is X-shaped Snowflake. Branching ice arms meet in a simple X-like crystal | an ice-edge pattern to notice."),
            ("Y", "Y — Yellow-billed Loon! Large northern waterbird with a yellow bill | one final navigation color near cold water."),
            ("Z", "Z ... Z ... Zoarcid Fish! Eel-shaped cold-water fish | final clue stays below surface as our route turns back to shore."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Focused friendly adult lead at 90 BPM in walking 4/4 with acoustic guitar, muted hand drum, soft bass, pizzicato strings and sparse flute. Use clear arrangement changes when travel mode changes: grounded pulse for tundra, sliding legato for sled, suspended rest at ice edge, gentle rocking meter feel for qajaq/umiak without changing global tempo. Round 1 is route logic, not adventure boasting. Chorus says map-route-change. Round 2 uses map/point gestures with one recall beat. Polar Bear, Walrus and ice hazards are distance/safety framed. X-shaped Snowflake is a visible branching ice pattern at the cold edge. End by closing the route with a dry acoustic cadence.",
    },
    "0040": {
        "authorial_intent": "Compare cold-climate body solutions—fur, feather, flipper, broad paw, shaggy coat, tusk, diving body—while treating ice, tundra, boats and X-shaped Snowflake as context rather than pretending every target has a biological adaptation.",
        "lyric_identity": "A child notices body covering and shape; recurring language uses fur, feather, flipper, layer, broad, compact, shaggy, surface and warm-body tool.",
        "image_motifs": ("arctic-fox fur", "eider feathers", "seal flippers", "musk-ox shaggy coat", "walrus tusks and whiskers"),
        "semantic_arc": ("fur and feathers begin the comparison", "sea mammals add flippers and body mass", "birds/fish show different cold strategies", "context objects close the lesson without false biology"),
        "forbidden_generic_language": ("cold-climate friends come sing with me", "snowy wildlife", "everyone has thick fur", "warm and cozy"),
        "rhyme_engine": "fur-feather-flipper-feature-rhyme",
        "chorus_rhyme_engine": "fur-feather-flipper-hook",
        "point_of_view": "a child comparing visible body features that help different animals live in cold places",
        "chorus_function": "group body strategies while preserving differences between mammals, birds, fish and context objects",
        "groove_meter": "gentle 3/4 feature-study sway with crisp target space",
        "round1_grammar": "hand-written body-feature comparisons; nonliving and off-habitat mapping helpers are explicitly framed as context",
        "round2_grammar": "feature cue -> recall beat -> target -> body-shape or safe pointing gesture",
        "intro_lines": ("Fur is one answer. Feathers are another. Flippers solve a different problem.", "Cold places do not make every body the same."),
        "hook_lines": ("Fur, feather, flipper—A-B-C!", "Different bodies meet the cold differently."),
        "outro_lines": ("One wing folds; one flipper sinks; one furry paw leaves the frame.", "A to Z ends with differences, not one winter costume."),
        "round2_patterns": ("Feature-or-context {letter} ... {object}! {action}", "Body-or-object shape {letter} ... {object}! {action}", "What do we notice, {letter}? ... {object}! {action}", "Cold-world clue {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Arctic Fox! Thick fur covers a compact body | small ears reduce exposed surface in severe cold."),
            ("B", "B ... B ... Bear! Large furry mammal with broad paws | body size and coat shape differ from smaller cold animals."),
            ("C", "C? Cod! Scales and fins belong to a fish living entirely in water | no fur needed below the cold surface."),
            ("D", "D is Dog Sled. Wooden or synthetic runners carry a sled over snow | useful human travel context, not a body adaptation."),
            ("E", "E — Eider! Dense feathers cover a sea duck | soft down beneath outer feathers provides insulation."),
            ("F", "F ... F ... Fur Seal! Dense fur and strong flippers | one mammal combines insulation with a swimming body."),
            ("G", "G? Goose! Feathers cover the body while webbed feet and wings handle different movement jobs | bird design, not furry design."),
            ("H", "H is Harp Seal. Streamlined body and flippers work in water | coat pattern gives the adult its name."),
            ("I", "I — Iceberg! Frozen water has no body covering | context matters because animals live around physical cold, not inside a costume story."),
            ("J", "J ... J ... Jellyfish! Soft bell and tentacles drift in water | no bones, fur, feathers, or flippers at all."),
            ("K", "K? Kittiwake! Feathers and long wings suit a seabird | light body works above cold coasts."),
            ("L", "L is Lynx. Thick fur, broad paws, tufted ears | a land-cat body built for cold terrain."),
            ("M", "M — Musk Ox! Long shaggy outer hair hangs over dense underwool | layered coat turns the animal into a moving wall of insulation."),
            ("N", "N ... N ... Narwhal! Whale body stays smooth outside | insulation is carried under the skin rather than as fur."),
            ("O", "O? Owl! Feathers cover a bird body and broad wings spread for flight | cold-region owls use plumage, not mammal fur."),
            ("P", "P is Puffin. Dense feathers cover a compact seabird | wings work in air and underwater swimming."),
            ("Q", "Q — Qajaq! Traditional narrow Arctic boat | human design solves cold-water travel without being wildlife."),
            ("R", "R ... R ... Ringed Seal! Rounded marine body, flippers, coat with pale rings | compact shape suits life around sea ice."),
            ("S", "S? Seal! Streamlined body and flippers move through water | many seals rely on insulating fat beneath the skin."),
            ("T", "T is Tundra. Cold open land supports low plants and wildlife | habitat is the problem-space, not an animal feature."),
            ("U", "U — Upland Goose! Feathered body, strong legs, wings | one cold-country bird balancing ground and flight needs."),
            ("V", "V ... V ... Vole! Small furry mammal stays close to ground and cover | tiny body needs a very different strategy from a whale."),
            ("W", "W? Whale! Smooth skin outside, thick insulating tissue inside | tail drives a huge marine body through cold water."),
            ("X", "At the warm room, X is X-shaped Snowflake | branching ice arms meet in an X-like crystal pattern."),
            ("Y", "Y — Yellow-billed Loon! Dense feathers, strong swimming feet, pointed bill | bird body built for northern lakes and coasts."),
            ("Z", "Z ... Z ... Zoarcid Fish! Long eel-shaped fish lives in cold water | fins and flexible body solve movement without fur or feathers."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Warm close lead at 84 BPM in gentle 3/4 with nylon guitar, soft bass, brushed percussion, pizzicato strings and tiny glockenspiel. Arrange by feature family: warm low strings for fur, airy upper strings/flute for feathers, fluid bass/marimba for flippers/fish, dry sparse texture for context objects. Round 1 compares rather than ranks adaptations. Chorus is fur-feather-flipper with clear lexical stress. Round 2 leaves one recall beat and uses simple body-shape gestures. X-shaped Snowflake and Qajaq/Dog Sled remain explicit context, not biology. End by stripping each feature color away one by one.",
    },
}
