from __future__ import annotations

# Gold-standard Creative V4 data for songs 0001-0010.
# Keep this module data-only: the generator owns schemas/rendering, while this
# file owns object-conditioned semantic/action craft and per-song fingerprints.

OBJECT_CRAFT: dict[str, tuple[str, str]] = {
    "Alder": ("Alder grows beside damp banks, with roots close to the water.", "Reach both hands up like branches."),
    "Alligator": ("An alligator can rest by the bank, then glide quietly through the water.", "Make two quiet swimming hands."),
    "Anchor": ("An anchor drops down to help a boat stay in one place.", "Point down slowly, like an anchor dropping."),
    "Angelfish": ("An angelfish glides on tall fins through bright reef water.", "Glide two hands like fins."),
    "Beaver": ("A beaver paddles with a flat tail and builds with branches.", "Pat two hands softly like a flat tail."),
    "Boat": ("A boat floats on water and carries people or things.", "Row two slow strokes."),
    "Buoy": ("A buoy bobs on the water to mark a place.", "Bob one hand gently up and down."),
    "Canoe": ("A canoe slides across calm water with a paddle.", "Paddle left, then right."),
    "Catfish": ("A catfish swims near the bottom with whisker-like barbels around its mouth.", "Wiggle fingers like whiskers, then swim."),
    "Coral": ("Coral forms branching reef shapes where small sea animals can shelter.", "Spread fingers like reef branches."),
    "Crab": ("A crab scuttles sideways over sand and rock.", "Take two tiny sideways finger-steps."),
    "Dam": ("A dam holds back water and changes how it flows.", "Hold two palms together like a wall."),
    "Dock": ("A dock reaches over the water where boats can stop.", "Stretch one arm straight like a dock."),
    "Dolphin": ("A dolphin surfaces to breathe and swims in smooth arcs.", "Make one smooth diving arc with your hand."),
    "Duck": ("A duck paddles on top of the water and dips its beak below.", "Paddle both hands gently."),
    "Eel": ("An eel slips through the water with a long, winding body.", "Wiggle one hand in a long curve."),
    "Egret": ("An egret stands on long legs and watches shallow water.", "Hold two fingers tall like long legs."),
    "Estuary": ("An estuary is where river water meets the sea.", "Bring two hands together like waters meeting."),
    "Fish": ("A fish swims with fins and breathes through gills.", "Swish one hand like a fish tail."),
    "Fishing Rod": ("A fishing rod has a long pole, line, and reel for fishing.", "Pretend to hold a fishing rod safely."),
    "Flipper": ("A flipper is a broad limb that helps a sea animal swim.", "Sweep one hand like a flipper."),
    "Frog": ("A frog hops on land and swims with strong back legs.", "Make one little finger-hop."),
    "Goose": ("A goose paddles on water and walks along grassy banks.", "Glide one hand across the water."),
    "Green Algae": ("Green algae makes soft green patches in water and on wet surfaces.", "Wave fingers softly like green strands."),
    "Grouper": ("A grouper is a stout reef fish with a wide mouth.", "Make a slow fish-swim with one hand."),
    "Gull": ("A gull soars over shorelines and lands near the water.", "Spread arms gently like wings."),
    "Harbor": ("A harbor is sheltered water where boats can rest.", "Curve both hands into a safe little bay."),
    "Hermit Crab": ("A hermit crab carries a borrowed shell over its soft body.", "Curl one hand like a shell, then make tiny sideways steps."),
    "Heron": ("A heron stands very still, then steps through shallow water.", "Hold two fingers tall, then take one slow step."),
    "Hydrilla": ("Hydrilla is a submerged water plant with leafy stems.", "Point to the picture only."),
    "Insect": ("An insect has six legs and a body with three main parts.", "Make tiny walking fingers."),
    "Iris": ("An iris opens a bright flower near wet ground.", "Open your hands like a flower."),
    "Island": ("An island is land with water all around it.", "Draw a little circle in the air."),
    "Isopod": ("An isopod has many legs and a hard, segmented body.", "Walk fingertips in a tiny row."),
    "Jellyfish": ("A jellyfish drifts with a soft bell-shaped body and trailing tentacles.", "Pulse your fingers softly like a drifting bell."),
    "Jetty": ("A jetty sticks out into the water from the shore.", "Slide one hand straight out over imaginary water."),
    "June Bug": ("A June bug is a shiny beetle that can fly on warm evenings.", "Buzz your fingers in a small circle."),
    "Kayak": ("A kayak is a small narrow boat moved with a paddle.", "Paddle left, paddle right."),
    "Kelp": ("Kelp grows in long brown-green ribbons under the sea.", "Sway one hand like a long ribbon."),
    "Kingfisher": ("A kingfisher perches near water and dives after small fish.", "Make one quick hand-dive, then hold still."),
    "Lagoon": ("A lagoon is shallow water separated from the open sea.", "Make a quiet bowl shape with both hands."),
    "Lake": ("A lake is a large area of water surrounded by land.", "Spread both hands wide and calm."),
    "Lily Pad": ("A lily pad floats flat on the water like a green plate.", "Hold one flat palm like a floating leaf."),
    "Lobster": ("A lobster walks on the seafloor with claws held out front.", "Make two gentle claw shapes."),
    "Manatee": ("A manatee moves slowly through warm water with paddle-like flippers.", "Push both hands slowly through the water."),
    "Minnow": ("A minnow is a small fish that darts through shallow water.", "Dart one finger gently side to side."),
    "Muskrat": ("A muskrat swims with its body low and lives near wet banks.", "Paddle two fingers along an imaginary bank."),
    "Mussel": ("A mussel has a dark two-part shell and often holds tight to a surface.", "Close two palms like a shell."),
    "Narwhal": ("A narwhal is a whale that can have one long spiral tusk.", "Point one finger forward like a tusk, then glide."),
    "Nautilus": ("A nautilus swims with a coiled shell divided into many chambers.", "Trace a spiral with one finger."),
    "Nest": ("A nest is a place birds build to hold eggs and chicks.", "Cup both hands like a nest."),
    "Newt": ("A newt is a small amphibian with four legs and a long tail.", "Walk two fingers, then wiggle a little tail."),
    "Oar": ("An oar is a long paddle-like tool used to move a boat.", "Row one slow stroke."),
    "Octopus": ("An octopus has eight arms and can squeeze through small spaces.", "Wiggle your fingers like octopus arms."),
    "Otter": ("An otter floats, dives, and swims with quick turns.", "Float both palms, then make one little dive."),
    "Oyster": ("An oyster lives inside a rough two-part shell.", "Close two hands like a shell."),
    "Pelican": ("A pelican scoops fish with a long bill and throat pouch.", "Make one gentle scooping motion."),
    "Pike": ("A pike is a long freshwater fish that waits among water plants.", "Hold still, then make one quick fish-swim."),
    "Pond": ("A pond is a small body of still water where plants and animals live.", "Make a small calm circle with both hands."),
    "Pufferfish": ("A pufferfish can make its body look rounder when threatened.", "Make a small round shape with your hands."),
    "Quahog": ("A quahog is a hard-shelled clam that lives under coastal sand or mud.", "Close both palms like a clam shell."),
    "Quail": ("A quail is a small ground bird that walks and pecks.", "Make tiny pecking finger taps."),
    "Queen Angelfish": ("A queen angelfish is a bright reef fish with strong yellow and blue colors.", "Glide two hands like bright fins."),
    "Quillwort": ("Quillwort is a small spiky-looking plant that grows in wet places or water.", "Spread fingers upward like spiky leaves."),
    "Ray": ("A ray glides through water with wide fins that look like wings.", "Glide both hands wide like wings."),
    "Reed": ("A reed grows tall and straight at the water's edge.", "Stand one hand tall, then sway."),
    "Reef": ("A reef is a rocky or coral habitat with many hiding places.", "Make a little hiding arch with your hands."),
    "River": ("A river flows downhill in a channel toward other water.", "Move one hand in a winding path."),
    "Salamander": ("A salamander has a long body, four legs, and moist skin.", "Walk two fingers, then wiggle a tail."),
    "Seahorse": ("A seahorse swims upright and can curl its tail around plants.", "Curl one finger like a seahorse tail."),
    "Seal": ("A seal swims with flippers and rests on rocks or shore.", "Sweep both hands gently like flippers."),
    "Swan": ("A swan glides on water with a long curved neck.", "Curve one arm like a long neck."),
    "Tadpole": ("A tadpole starts life in water with a tail and later grows legs.", "Wiggle one finger like a tiny tail."),
    "Tidepool": ("A tidepool holds seawater in a rocky hollow when the tide goes out.", "Make a little bowl with both hands."),
    "Trout": ("A trout swims in cool freshwater and flicks its tail against the current.", "Flick one hand gently like a tail."),
    "Turtle": ("A turtle carries a hard shell and swims with steady strokes.", "Make a shell shape with both hands."),
    "Umbrella Sedge": ("Umbrella sedge has green stems topped with spreading leaf-like rays.", "Open fingers like a tiny green umbrella."),
    "Undersea Cave": ("An undersea cave is a hollow rocky space below the ocean surface.", "Make a cave arch with both hands."),
    "Underwater Plant": ("An underwater plant grows below the surface and waves with the water.", "Sway both hands like underwater leaves."),
    "Urchin": ("An urchin is a round sea animal covered in stiff spines.", "Spread fingers into a round spiky shape."),
    "Valley": ("A valley is low land between hills or mountains, often with water running through.", "Dip both hands down between two hills."),
    "Vallisneria": ("Vallisneria is a ribbon-leaved freshwater plant that grows underwater.", "Sway one hand like a long ribbon leaf."),
    "Vessel": ("A vessel is a boat or ship made to travel on water.", "Rock both hands gently like a boat."),
    "Violet Sea Snail": ("A violet sea snail is a small purple-blue ocean snail that can float near the surface.", "Trace a tiny spiral, then float your hand."),
    "Water Lily": ("A water lily has round floating leaves and a flower above the water.", "Hold one flat palm, then open a flower."),
    "Waterfall": ("A waterfall drops from higher ground in a rushing sheet of water.", "Let both hands tumble gently downward."),
    "Wave": ("A wave rises and falls as water moves across the surface.", "Roll one hand up and down."),
    "Whale": ("A whale is a giant marine mammal that comes to the surface to breathe.", "Glide both hands wide, then lift for a breath."),
    "X-ray Fish": ("An X-ray fish has a partly see-through body that can reveal tiny bones.", "Make a gentle fish-swim with one hand."),
    "X-ray Tetra": ("An X-ray tetra is a small translucent fish with a partly see-through body.", "Make a gentle fish-swim with one hand."),
    "Xiphophorus": ("Xiphophorus is a group of small freshwater fish that includes swordtails and platies.", "Make one small fish-swim, slow and clear."),
    "Yellow Perch": ("A yellow perch is a freshwater fish with yellow sides and dark vertical bars.", "Trace two short bars, then make a fish-swim."),
    "Yellow Tang": ("A yellow tang is a bright yellow reef fish with a flat oval body.", "Make a flat oval with your hands, then glide."),
    "Yellow Water Lily": ("A yellow water lily has yellow flowers above broad floating leaves.", "Hold one flat palm, then open a yellow flower."),
    "Yellowfin Tuna": ("A yellowfin tuna is a fast ocean fish with yellow-tinted fins.", "Make one smooth, speedy fish-swim."),
    "Zebra Danio": ("A zebra danio is a small freshwater fish with dark horizontal stripes.", "Trace two little stripes, then swim."),
    "Zebra Shark": ("A zebra shark is a long-tailed shark whose young have zebra-like dark bands.", "Glide one hand slowly like a long shark tail."),
    "Zooplankton": ("Tiny drifting zooplankton ride along with moving water.", "Let fingertips drift slowly with the current."),
}


# Short, object-conditioned rhyme-bearing phraselets for Creative V4.
# These are not filler tails: each cue reinforces motion, shape, location, or a
# visible property. The renderer uses them on alternating Round-1 targets so
# semantic teaching keeps breathing room while the verse still sounds musical.
RHYME_PHRASELETS: dict[str, str] = {
    "Alder": "Grow by the flow | roots by wet banks down low",
    "Alligator": "Glide and hide | by the riverside",
    "Anchor": "Down, down, around | anchor drops toward the ground",
    "Angelfish": "Glide with the tide | tall fins open wide",
    "Beaver": "Tail makes a trail",
    "Boat": "Row as we go",
    "Buoy": "Bob, stop, bob",
    "Canoe": "Canoe in view | paddle through blue",
    "Catfish": "Whiskers swish | barbels near the mouth of the fish",
    "Coral": "Shore to ocean floor | branching shelter, more and more",
    "Crab": "Across the sand | sideways steps along the land",
    "Dam": "Wall holds all",
    "Dock": "Dock by the rock",
    "Dolphin": "Play all day",
    "Duck": "Dip down, turn around",
    "Eel": "Slide with the tide | long body side to side",
    "Egret": "Stand in the sand | long legs step across the land",
    "Estuary": "River to sea | fresh and salt mix naturally",
    "Fish": "Swish with the fish",
    "Fishing Rod": "Cast fast",
    "Flipper": "Sweep deep",
    "Frog": "Hop, stop",
    "Goose": "Glide wide | grassy banks on either side",
    "Green Algae": "Green scene | soft patches grow between",
    "Grouper": "Round all around | wide mouth near the ground",
    "Gull": "Fly high in the sky | over shore as waves roll by",
    "Harbor": "Near and clear",
    "Hermit Crab": "Shell on the trail",
    "Heron": "Step slow, stay low",
    "Hydrilla": "Sway all day",
    "Insect": "Six legs to find | three body parts in line",
    "Iris": "Wet-ground sight | iris flower opens bright",
    "Island": "Land ringed by sand | water all around the land",
    "Isopod": "Small and low | many little legs in a row",
    "Jellyfish": "Drift, lift",
    "Jetty": "From shore, out some more",
    "June Bug": "Buzz because",
    "Kayak": "Paddle the track | forward and back",
    "Kelp": "Sway all day | long ribbons under the bay",
    "Kingfisher": "Flash and splash | dive for fish, then back in a dash",
    "Lagoon": "Blue lagoon under the moon",
    "Lake": "Wide inside",
    "Lily Pad": "Flat like that",
    "Lobster": "Claw by the ocean floor",
    "Manatee": "Slow in the sea | paddle flippers moving free",
    "Minnow": "Go with the flow | tiny fish darts to and fro",
    "Muskrat": "Body low | paddle where bank waters flow",
    "Mussel": "Shell, can you tell? | two dark halves hold well",
    "Narwhal": "Tusk tall, whale and all",
    "Nautilus": "Coil after coil by the ocean soil",
    "Nest": "Rest in the nest",
    "Newt": "Scoot, little newt",
    "Oar": "Row some more | long blade pulls toward the shore",
    "Octopus": "Squeeze with ease | eight arms bend as they please",
    "Otter": "Side to side | float, turn, dive and glide",
    "Oyster": "Shell, can you tell? | rough two halves hold well",
    "Pelican": "Scoop in a loop",
    "Pike": "Glide beside",
    "Pond": "Calm in your palm",
    "Pufferfish": "Round when danger is found",
    "Quahog": "Clam in sand | hard shell close at hand",
    "Quail": "Quail on the trail | ground bird with a little tail",
    "Queen Angelfish": "Bright in the light | yellow-blue colors shine just right",
    "Quillwort": "Quillwort low | spiky leaves in water grow",
    "Ray": "Ray by the bay",
    "Reed": "Reed from a seed",
    "Reef": "Reef underneath",
    "River": "Flow as we go",
    "Salamander": "Long and low | four legs help it go",
    "Seahorse": "Curl and twirl | tail grips plants in a whirl",
    "Seal": "Sweep and spin | flippers pull the seal back in",
    "Swan": "Glide beside | long curved neck, wings spread wide",
    "Tadpole": "Wiggle and giggle",
    "Tidepool": "Cool little tidepool",
    "Trout": "Dart in and out",
    "Turtle": "Slow as we go",
    "Umbrella Sedge": "Green rays spread | umbrella shape overhead",
    "Undersea Cave": "Under the wave | rocky hollow, undersea cave",
    "Underwater Plant": "Sway all day | underwater leaves bend this way",
    "Urchin": "Round on the ground | stiff spines point all around",
    "Valley": "Low where waters flow",
    "Vallisneria": "Sway all day",
    "Vessel": "Go with the flow",
    "Violet Sea Snail": "Snail on a trail",
    "Water Lily": "Bright in the light | round leaves float, flower in sight",
    "Waterfall": "Water falls tall | rushing sheet by rocky wall",
    "Wave": "Rise, surprise | crest and fall before our eyes",
    "Whale": "Whale with a tail | rises to breathe along the trail",
    "X-ray Fish": "See-through fish, swish-swish",
    "X-ray Tetra": "Clear to see in the sea",
    "Xiphophorus": "Fin after fin, let the swim begin",
    "Yellow Perch": "Bars in rows | yellow sides and off it goes",
    "Yellow Tang": "Yellow in view | flat oval body glides through blue",
    "Yellow Water Lily": "Yellow in the light | broad leaves float, flower bright",
    "Yellowfin Tuna": "Zoom through blue | yellow fins flash into view",
    "Zebra Danio": "Go with the flow",
    "Zebra Shark": "Shark in the dark",
    "Zooplankton": "Drift with the lift",
}


GOLD_V4_SPECS: dict[str, dict[str, object]] = {
    "0001": {
        "opening_type": "sound-image cold open",
        "target_entry_families": ("direct", "repeated-letter", "is-for", "question-answer", "narrative"),
        "line_length_contour": ("short", "medium", "long", "medium"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "paired",
        "point_of_view": "playful reef guide following splashes and movement",
        "chorus_function": "two-line splash hook that resets attention",
        "groove_meter": "syncopation-light 4/4 island bounce",
        "round1_grammar": "rotate five target-entry forms; attach one object-specific visible fact",
        "round2_grammar": "cue-gap-answer plus object-conditioned gesture; rotate direct, repeated, question and find forms",
        "section_contrast": "Round 1 sparse marimba/ukulele; chorus wider; Round 2 stop-start with percussion dropouts",
        "signature_color": "marimba splash answer after each target",
        "intro_lines": ("Splash-swish—what letter jumped in?", "Splash the letters, A-B-C!"),
        "hook_lines": ("Splash the letters, A-B-C!", "Ocean words roll back to me!"),
        "outro_lines": ("One last splash—A-B-C!", "Ocean words are riding with me!"),
        "interlude_lines": ("The water goes quiet—can the letters swim back?",),
        "chorus_after_round1": (2, 5),
        "chorus_after_round2": (4, 7),
        "round1_patterns": (
            "{letter} — {object}! {semantic}",
            "{letter} ... {letter} ... {object}! {semantic}",
            "{letter} is for {object}. {semantic}",
            "{letter}? {object}! {semantic}",
            "Here comes {letter} with {object}. {semantic}",
        ),
        "round2_patterns": (
            "{letter} ... {object}! {action}",
            "{letter} ... {letter} ... {object}! {action}",
            "{letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
        ),
        "style_blueprint": "Warm clear adult female lead with crisp dry diction. Playful 4/4 island-acoustic preschool groove at 88 BPM, narrow stepwise major-key melody. Open with a two-bar splash-and-marimba sound-image and the title hook, no generic spoken invitation. Round 1 stays sparse and alternates short target punches with longer descriptive phraselets; keep rare words near speech-rhythm. Chorus lifts into a simple two-line singalong with a light group echo. Round 2 becomes stop-start call-and-response with one real beat of silence after each letter cue. Thin percussion and backing vocals at every target-word onset, then let marimba answer after the word. Ukulele, marimba, soft shaker and warm bass; stable harmony, no melisma or rapid patter. End with one final hook and a short clean cadence.",
    },
    "0002": {
        "opening_type": "shoreline question",
        "target_entry_families": ("object-first", "action-first", "letter-led", "question-answer", "direct"),
        "line_length_contour": ("medium", "short", "long", "medium"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "paired",
        "point_of_view": "child beachcomber naming what appears at the shoreline",
        "chorus_function": "name-the-coast refrain, never phonics language",
        "groove_meter": "gentle 6/8 surf sway",
        "round1_grammar": "mix object-first discoveries, spot/find cues and direct letter naming with concrete coast facts",
        "round2_grammar": "search cue, brief gap, answer, then one small gesture",
        "section_contrast": "Round 1 guitar-forward and airy; chorus adds glockenspiel; Round 2 strips to bass pulse and hand taps",
        "signature_color": "soft surf-guitar upstroke with glockenspiel answer",
        "intro_lines": ("What washed up beside the blue?", "Shoreline letters—here's our clue!"),
        "hook_lines": ("Shoreline letters, one-two-three!", "Name the coast from A to Z!"),
        "outro_lines": ("Shoreline letters, A to Z!", "We named the coast beside the sea!"),
        "chorus_after_round1": (3, 7),
        "chorus_after_round2": (3, 7),
        "round1_patterns": (
            "{object} — that's {letter}. {semantic}",
            "Spot {letter}: {object}. {semantic}",
            "{letter} brings {object}. {semantic}",
            "What does {letter} bring? {object}! {semantic}",
            "{letter} — {object}. {semantic}",
        ),
        "round2_patterns": (
            "Spot {letter} ... {object}! {action}",
            "{letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
            "{letter} ... {object}! {action}",
        ),
        "style_blueprint": "Clear warm adult lead, crisp consonants and stable vowels. Gentle 6/8 acoustic surf sway at 90 BPM with clean guitar upstrokes, soft shaker, glockenspiel and rounded bass; narrow singable melody. Open with a shoreline question and answer it musically, not with a generic invitation. Round 1 feels like beachcombing: medium lines alternate with short discoveries and occasional longer two-phrase facts. Chorus brightens into a name-the-coast refrain, avoiding phonics or the word sound as an instructional claim. Round 2 uses search-and-find call-and-response with a predictable one-beat response gap. Duck guitar and percussion at target-word onset; glockenspiel answers afterward. Keep the arrangement airy and vocals forward. End with a gentle surf cadence and the final A-to-Z hook.",
    },
    "0003": {
        "opening_type": "rhythmic rowing pickup",
        "target_entry_families": ("repeated-letter", "direct", "narrative", "is-for", "question-answer"),
        "line_length_contour": ("short", "short", "medium", "long"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "paired",
        "point_of_view": "friendly boat crew calling sea clues from deck",
        "chorus_function": "crew response hook with strong beat-one returns",
        "groove_meter": "light 2/4 nautical stomp",
        "round1_grammar": "short deck calls mixed with fuller scene lines; semantic fact lands after the target",
        "round2_grammar": "crew caller leaves a beat, group confirms, then matching gesture",
        "section_contrast": "verses use brushes/accordion breaths; chorus adds claps; retrieval sections use bare stomp and voice",
        "signature_color": "soft stomp on beat one, accordion answer off the target onset",
        "intro_lines": ("Row... row... ready on the rail?", "Call the letters, tell the tale!"),
        "hook_lines": ("Row and say, A-B-C!", "Sea and boat words ride with me!"),
        "outro_lines": ("Oars come home—A-B-C!", "Sea-word crew, we named the sea!"),
        "interlude_lines": ("Oars rest for one breath; now the crew calls back.",),
        "chorus_after_round1": (2, 5, 7),
        "chorus_after_round2": (4, 7),
        "round1_patterns": (
            "{letter} ... {letter} ... {object}! {semantic}",
            "{letter} — {object}! {semantic}",
            "From the deck, {letter} finds {object}. {semantic}",
            "{letter} is for {object}. {semantic}",
            "Crew calls {letter}? {object}! {semantic}",
        ),
        "round2_patterns": (
            "Crew calls {letter} ... {object}! {action}",
            "{letter} ... {letter} ... {object}! {action}",
            "Ready, {letter}? ... {object}! {action}",
            "{letter} ... {object}! {action}",
        ),
        "style_blueprint": "Friendly clear adult lead with a small group response, crisp diction and no shouted delivery. Light 2/4 nautical preschool stomp at 92 BPM: brushed snare, ukulele, soft accordion breaths, hand claps and bass. Open with a rhythmic rowing pickup before the hook. Round 1 mixes short deck-call punches with medium and long descriptive phraselets while a narrow repeated-note motif preserves target stress. Chorus lands strongly on beat one as a crew-response refrain. Round 2 is stripped to soft stomp plus voice, with one clean beat of silence between letter cue and target confirmation. Keep backing voices out of target-word attacks; accordion may answer after. Stable simple harmony. End with the rowing pulse slowing into a short final cadence.",
    },
    "0004": {
        "opening_type": "cinematic scene drop",
        "target_entry_families": ("narrative", "object-first", "question-answer", "direct", "is-for"),
        "line_length_contour": ("long", "medium", "short", "medium"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "refrain-driven",
        "point_of_view": "gentle traveler watching sea and shore pass by",
        "chorus_function": "wide sailing hook that opens the arrangement",
        "groove_meter": "floating 6/8 travel sway",
        "round1_grammar": "scene-led phrases with internal images and occasional short target landing",
        "round2_grammar": "quiet cue-gap-answer with show/trace/glide gestures",
        "section_contrast": "verses intimate kalimba; chorus expands marimba/ukulele; Round 2 removes pads and leaves spacious pulse",
        "signature_color": "kalimba ripple into warm marimba cadence",
        "intro_lines": ("Morning light slides over the water.", "A little sail lifts—our letters are moving."),
        "hook_lines": ("Sail and see from A to Z!", "Every letter finds a clue!"),
        "outro_lines": ("Sail and see—our clues are through.", "A to Z came into view!"),
        "interlude_lines": ("The sail turns home; now the clues return from memory.",),
        "chorus_after_round1": (3, 7),
        "chorus_after_round2": (4, 7),
        "round1_patterns": (
            "On our way, {letter} meets {object}. {semantic}",
            "{object} — that's our {letter}. {semantic}",
            "What waits at {letter}? {object}! {semantic}",
            "{letter} — {object}. {semantic}",
            "{letter} is for {object}. {semantic}",
        ),
        "round2_patterns": (
            "Softly, {letter} ... {object}! {action}",
            "{letter}? ... {object}! {action}",
            "Show {letter} ... {object}! {action}",
            "{letter} ... {object}! {action}",
        ),
        "style_blueprint": "Warm intimate adult lead with clear consonants, minimal vibrato and calm breath. Floating 6/8 preschool travel-pop at 86 BPM with kalimba, soft marimba, brushed percussion, ukulele and light bass; narrow lyrical contour and stable major center. Open by dropping directly into a morning-on-the-water scene. Round 1 uses longer scene-led lines beside short target landings, with internal rhythmic echoes rather than forced end rhyme. Chorus opens the arrangement into a wide but simple sailing hook. Round 2 removes pads and becomes a spacious cue-gap-answer pattern with roughly two quiet beats for recall. Keep target words dry and exposed; no backing vocal or percussion attack on their first syllable. End by returning to the sailing hook over a soft two-chord cadence.",
    },
    "0005": {
        "opening_type": "field-guide movement pickup",
        "target_entry_families": ("action-first", "direct", "question-answer", "narrative", "repeated-letter"),
        "line_length_contour": ("short", "medium", "short", "long"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "paired",
        "point_of_view": "curious coast explorer using eyes, hands and pretend binoculars",
        "chorus_function": "explorer badge hook with clap-ready paired cadence",
        "groove_meter": "bouncy 4/4 explorer pop",
        "round1_grammar": "spot/look/scan cues alternate with direct and story lines; semantic clue is always object-specific",
        "round2_grammar": "brief recall gap followed by gesture or pretend-binocular action without generic point-and-say repetition",
        "section_contrast": "Round 1 claves and guitar; chorus adds claps; Round 2 uses muted guitar plus sparse marimba clues",
        "signature_color": "two-clave explorer tick before section turns",
        "intro_lines": ("Explorer eyes—up, down, near, far!", "A new coast clue is where you are."),
        "hook_lines": ("Explorer eyes—A-B-C!", "Spot the coast and call with me!"),
        "outro_lines": ("Explorer eyes found A to Z!", "Coast clues packed—what a journey!"),
        "chorus_after_round1": (2, 5),
        "chorus_after_round2": (3, 6),
        "round1_patterns": (
            "Spot {letter}: {object}! {semantic}",
            "{letter} — {object}. {semantic}",
            "What clue starts at {letter}? {object}! {semantic}",
            "Along the coast, {letter} finds {object}. {semantic}",
            "{letter} ... {letter} ... {object}! {semantic}",
        ),
        "round2_patterns": (
            "Scan for {letter} ... {object}! {action}",
            "{letter} ... {object}! {action}",
            "Clue {letter}? ... {object}! {action}",
            "{letter} ... {letter} ... {object}! {action}",
        ),
        "style_blueprint": "Curious clear adult lead, crisp diction, lightly animated but never breathless. Bouncy 4/4 preschool explorer-pop at 94 BPM with acoustic guitar, claves, marimba, soft bass and hand claps; compact stepwise melody. Open with a movement-based field-guide pickup, not a spoken welcome. Round 1 rotates spot, question, direct and mini-story entries, mixing short clues with longer semantic lines. Chorus becomes a clap-ready explorer badge hook with paired cadence. Round 2 uses a short one-beat recall gap, then object-specific gestures; muted guitar and sparse marimba leave target words uncovered. No dense choir, fast patter or vocal runs. End with two clave ticks, one final hook, then a clean stop.",
    },
    "0006": {
        "opening_type": "ripple onomatopoeia",
        "target_entry_families": ("direct", "is-for", "object-first", "question-answer", "narrative"),
        "line_length_contour": ("medium", "long", "short", "medium"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "paired",
        "point_of_view": "quiet observer following a ripple from pond edge into the river",
        "chorus_function": "flowing memory refrain with gentle rise and fall",
        "groove_meter": "relaxed 6/8 river folk",
        "round1_grammar": "facts flow as two-phrase lines around occasional short labels; difficult plant names stay deliberate",
        "round2_grammar": "two-beat supportive gap then action tied to swimming, growing, flowing or shape",
        "section_contrast": "Round 1 acoustic and pizzicato; chorus adds glockenspiel shimmer; Round 2 leaves woodblock pulse and voice",
        "signature_color": "pizzicato ripple followed by one soft bell",
        "intro_lines": ("Ripple... ripple... rings on the pond.", "Follow the water—our letters flow on."),
        "hook_lines": ("Ripple, ripple—A-B-C!", "River words come back to me!"),
        "outro_lines": ("Ripple quiet, A to Z.", "River words came home with me."),
        "interlude_lines": ("The ripple fades... now listen for what returns.",),
        "chorus_after_round1": (2, 5, 7),
        "chorus_after_round2": (4, 7),
        "round1_patterns": (
            "{letter} — {object}. {semantic}",
            "{letter} is for {object}. {semantic}",
            "{object} — remember {letter}. {semantic}",
            "What drifts in with {letter}? {object}! {semantic}",
            "By the water, {letter} meets {object}. {semantic}",
        ),
        "round2_patterns": (
            "{letter} ... wait ... {object}! {action}",
            "Remember {letter} ... {object}! {action}",
            "{letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
        ),
        "style_blueprint": "Clear gentle adult lead with close dry diction and stable vowels. Relaxed 6/8 river-folk at 84 BPM with acoustic guitar, pizzicato strings, soft woodblock, glockenspiel and light bass; narrow rising-and-falling contour. Open with quiet ripple onomatopoeia over two sparse bars. Round 1 flows between medium, long and very short target phrases; Tier-C plant words stay almost speech-like on repeated notes. Chorus adds a small glockenspiel shimmer and an easy flowing refrain. Round 2 drops to woodblock pulse plus voice, leaving about two supportive beats after each letter cue before confirmation. Thin every instrument at target-word onset, then answer with pizzicato. End by letting the ripple motif settle into one soft final chord.",
    },
    "0007": {
        "opening_type": "paddle-count pickup",
        "target_entry_families": ("action-first", "repeated-letter", "object-first", "direct", "question-answer"),
        "line_length_contour": ("short", "medium", "long", "short"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "paired",
        "point_of_view": "paddling guide moving across lakes, channels and river bends",
        "chorus_function": "paddle-and-answer refrain with bluegrass-lite bounce",
        "groove_meter": "light 4/4 acoustic hop",
        "round1_grammar": "movement cues and object-first names alternate with clear semantic descriptions",
        "round2_grammar": "one-beat silence, target answer, then compact gesture; hard names slow down",
        "section_contrast": "Round 1 banjo plucks stay sparse; chorus adds clap; Round 2 uses bass/wood pulse with whistle only between answers",
        "signature_color": "single banjo pluck pickup plus tiny whistle response",
        "intro_lines": ("Paddle left... paddle right...", "A new letter bends into sight!"),
        "hook_lines": ("Paddle on—A-B-C!", "Waterway words, call with me!"),
        "outro_lines": ("Paddles rest—A to Z.", "Waterway words came back to me!"),
        "chorus_after_round1": (3, 6),
        "chorus_after_round2": (4, 7),
        "round1_patterns": (
            "Paddle to {letter}: {object}! {semantic}",
            "{letter} ... {letter} ... {object}! {semantic}",
            "{object} — that's {letter}. {semantic}",
            "{letter} — {object}. {semantic}",
            "What's waiting at {letter}? {object}! {semantic}",
        ),
        "round2_patterns": (
            "{letter} ... {object}! {action}",
            "Paddle to {letter} ... {object}! {action}",
            "{letter} ... {letter} ... {object}! {action}",
            "Ready for {letter}? ... {object}! {action}",
        ),
        "style_blueprint": "Friendly adult lead with clean en-US diction and a tiny group echo only in the hook. Light 4/4 acoustic bluegrass-lite hop at 90 BPM: restrained banjo plucks, upright bass, hand claps, soft woodblock and brief whistle answers; no virtuoso picking or exaggerated twang. Open with two paddle motions as rhythmic pickup. Round 1 alternates short names, object-first phrases and longer descriptive lines inside one stable motif family. Chorus becomes a paddle-and-answer refrain. Round 2 leaves one clear beat of silence after each cue; hard words such as Xiphophorus slow to near speech rhythm. Keep whistle and claps away from target-word attacks. End with the paddle pulse stopping under a final sung hook.",
    },
    "0008": {
        "opening_type": "animal-motion montage",
        "target_entry_families": ("narrative", "direct", "question-answer", "action-first", "is-for"),
        "line_length_contour": ("medium", "short", "medium", "long"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "paired",
        "point_of_view": "friendly freshwater nature host following animals, plants and water objects",
        "chorus_function": "motion-word hook linking swim, hop and glide",
        "groove_meter": "bright 4/4 acoustic bounce",
        "round1_grammar": "mini nature snapshots, direct hits and action-led observations; acknowledge that mapping includes more than animals",
        "round2_grammar": "cue, gap, confirmation and safe mimed motion; Hydrilla remains point-only",
        "section_contrast": "Round 1 marimba/ukulele; chorus adds snaps; Round 2 soft kick drops out on targets and uses finger-tap answers",
        "signature_color": "marimba two-note animal-motion answer",
        "intro_lines": ("A tail flicks, a leaf sways, a paddle dips.", "Freshwater letters are on the move!"),
        "hook_lines": ("Freshwater friends—A-B-C!", "Swim, hop, glide from A to Z!"),
        "outro_lines": ("Freshwater friends, A to Z!", "Every move left a clue for me!"),
        "chorus_after_round1": (2, 5),
        "chorus_after_round2": (3, 6),
        "round1_patterns": (
            "{letter} finds {object}. {semantic}",
            "{letter} — {object}! {semantic}",
            "What moves with {letter}? {object}! {semantic}",
            "Look at {letter}: {object}. {semantic}",
            "{letter} is for {object}. {semantic}",
        ),
        "round2_patterns": (
            "{letter} ... {object}! {action}",
            "Move with {letter} ... {object}! {action}",
            "What was {letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
        ),
        "style_blueprint": "Bright clear adult female lead, friendly nature-host delivery, crisp consonants and no baby voice. Acoustic 4/4 preschool bounce at 91 BPM with marimba, ukulele, finger snaps, soft kick and bass; narrow stepwise melody. Open with a quick montage of three visible motions rather than saying the theme name generically. Round 1 uses mini nature snapshots, short target hits and medium descriptive lines; keep long plant or taxonomic names deliberate. Chorus lifts into a swim-hop-glide participation hook. Round 2 is cue-gap-confirm-action; drop the soft kick at every target-word onset and let finger taps answer afterward. Hydrilla is visual recognition only, never an imitation/use instruction. End with the motion hook once and a clean marimba button.",
    },
    "0009": {
        "opening_type": "quiet wetland soundscape",
        "target_entry_families": ("object-first", "narrative", "direct", "question-answer", "repeated-letter"),
        "line_length_contour": ("long", "short", "medium", "medium"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "refrain-driven",
        "point_of_view": "slow dawn walk through reeds, shallow water and bird calls",
        "chorus_function": "calm wonder refrain, not a high-energy reset",
        "groove_meter": "slow 3/4 nature sway",
        "round1_grammar": "object-first and scene-led phrases with sensory space; no generic 'wetland green' suffix",
        "round2_grammar": "two-beat recall window then small hand gesture; rare plant names receive unhurried confirmation",
        "section_contrast": "Round 1 airy kalimba; chorus gains bass and soft harmony; Round 2 nearly percussion-free",
        "signature_color": "single kalimba droplet between phrases",
        "intro_lines": ("Drip... hush... wings over the reeds.", "Morning wakes one letter at a time."),
        "hook_lines": ("Wetland wonders—A-B-C!", "Reeds and wings and water sing!"),
        "outro_lines": ("Wetland quiet, A to Z.", "Reeds and water keep the melody."),
        "interlude_lines": ("The marsh goes hush; one quiet clue at a time.",),
        "chorus_after_round1": (3, 7),
        "chorus_after_round2": (4, 7),
        "round1_patterns": (
            "{object} — our {letter}. {semantic}",
            "At wetland dawn, {letter} meets {object}. {semantic}",
            "{letter} — {object}. {semantic}",
            "What belongs to {letter}? {object}! {semantic}",
            "{letter} ... {letter} ... {object}. {semantic}",
        ),
        "round2_patterns": (
            "{letter} ... wait ... {object}. {action}",
            "Remember {letter} ... {object}. {action}",
            "{letter}? ... {object}. {action}",
            "Quiet clue, {letter} ... {object}. {action}",
        ),
        "style_blueprint": "Calm close adult lead with crisp diction, natural breath and minimal vibrato. Slow 3/4 preschool nature sway at 82 BPM with kalimba, soft shaker, airy pad used sparingly and gentle bass; narrow mostly stepwise melody. Open with a tiny wetland sound-image—drip, hush, distant wing motion—then enter the first clue. Round 1 gives spacious object-first and scene-led phrases with deliberate silence between them; avoid a repeated generic suffix. Chorus stays calm and memorable instead of becoming hyperactive. Round 2 becomes nearly percussion-free with about two beats of recall space before each answer; rare plant names are unhurried and speech-clear. Keep all target words dry and forward, with no harmony on their attack. End by thinning to solo kalimba and one soft final refrain line.",
    },
    "0010": {
        "opening_type": "walking-step count-in",
        "target_entry_families": ("repeated-letter", "action-first", "direct", "object-first", "question-answer"),
        "line_length_contour": ("short", "medium", "long", "short"),
        "rhyme_engine": "mixed-internal-phraselet",
        "chorus_rhyme_engine": "paired",
        "point_of_view": "riverbank explorer taking small observational steps",
        "chorus_function": "step-and-name hook with clean natural rhyme",
        "groove_meter": "easy 4/4 walking folk",
        "round1_grammar": "footstep pickups rotate with direct names, object-first clues and longer natural-history snapshots",
        "round2_grammar": "one-beat cue gap and a compact gesture; no generic tale/point formula",
        "section_contrast": "Round 1 guitar/shaker walking pulse; chorus adds glockenspiel; Round 2 strips to stomps and bass",
        "signature_color": "two soft footstep taps before every new section",
        "intro_lines": ("Step, step—something moved by the stream!", "Look close; a letter is joining the scene."),
        "hook_lines": ("Step by step beside the stream!", "A to Z—name what we've seen!"),
        "outro_lines": ("Steps slow down beside the stream.", "A to Z—we named the scene!"),
        "chorus_after_round1": (2, 5),
        "chorus_after_round2": (3, 6, 7),
        "round1_patterns": (
            "{letter} ... {letter} ... {object}! {semantic}",
            "Step to {letter}: {object}. {semantic}",
            "{letter} — {object}. {semantic}",
            "{object} — that's {letter}. {semantic}",
            "What did {letter} find? {object}! {semantic}",
        ),
        "round2_patterns": (
            "{letter} ... {object}! {action}",
            "One step, {letter} ... {object}! {action}",
            "{letter}? ... {object}! {action}",
            "Find {letter} ... {object}! {action}",
        ),
        "style_blueprint": "Bright clear adult lead with friendly walking-story delivery and crisp dry diction. Easy 4/4 campfire-folk preschool pulse at 89 BPM with acoustic guitar, light footstep stomps, shaker, glockenspiel and soft bass; narrow melody with simple paired cadences. Open with two audible walking steps and a stream-side discovery line. Round 1 rotates repeated-letter pickups, step cues, object-first clues and longer descriptive snapshots. Chorus uses the natural stream/seen rhyme as a compact step-and-name hook. Round 2 strips to soft stomps and bass, leaves one real beat after the letter cue, then confirms the object and one congruent gesture. Mute stomps and backing vocals on target-word attacks; glockenspiel answers afterward. End by slowing the steps and resolving on the final hook without extra spoken praise.",
    },
}
