from __future__ import annotations

"""Authorial-identity deep polish for space songs 0051-0055."""

GOLD_V5_51_55_SPEC_PATCHES: dict[str, dict[str, object]] = {
"0051": {
"authorial_intent":"Make Starship Letter Quest a coherent outbound mission: launch from Earth, enter orbit, pass observation targets, then reach outer-solar-system ideas while spacecraft parts remain tools rather than celestial objects.",
"lyric_identity":"A child mission log moves from ground to orbit to deep-space observation; each line answers where the target belongs: sky object, spacecraft hardware, path, or training helper.",
"image_motifs":("Earth shrinking below","capsule window","comet tail away from Sun","Neptune far blue","X-ray telescope above atmosphere"),
"semantic_arc":("launch and leave Earth","settle into orbit","observe small bodies and planets","finish with distant tools and training context"),
"forbidden_generic_language":("letters lift off","space fun","everything floats","past the moon"),
"rhyme_engine":"starship-mission-distance-rhyme","chorus_rhyme_engine":"launch-orbit-observe-hook","point_of_view":"a child narrating a science-first imaginary mission log","chorus_function":"reset launch-orbit-observe","groove_meter":"steady 4/4 launch pulse opening into wider orbital phrases","round1_grammar":"hand-written mission placement; celestial bodies, spacecraft, orbital concepts and training helpers stay distinct","round2_grammar":"mission cue -> recall beat -> target -> safe point/shape gesture",
"intro_lines":("Earth fills the window; the first burn ends; now the spacecraft keeps falling around the planet.","Our letter quest begins by learning where each thing really belongs."),
"hook_lines":("Launch, orbit, observe—A-B-C!","Space is a map of objects, paths, and tools—not one floating pile."),
"outro_lines":("Neptune stays distant; the telescope keeps watching.","A to Z closes the mission log back at the training room."),
"round2_patterns":("{letter} ... {object}! {action}","{letter} ... {object}! {action}","{letter}? ... {object}! {action}","{letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Asteroid! Rocky or metallic small body orbiting the Sun | many lie in the main belt."),
("B","B ... B ... Black Hole! Inside an event horizon, even light cannot escape outward | distant target, never a place we fly toward."),
("C","C? Comet! Ice and dust can form a coma and tails near the Sun | tails point generally away from the Sun."),
("D","D is Dwarf Planet. It orbits the Sun, is rounded by gravity, and has not cleared its orbital neighborhood | a distinct Solar System class."),
("E","E — Earth! Third planet from the Sun | oceans, land, atmosphere, and our launch site begin here."),
("F","F ... F ... Flag! Mission marker | in vacuum it cannot wave from air because there is no air."),
("G","G? Gemini Capsule! NASA Gemini carried two astronauts in the 1960s | a historical crew capsule."),
("H","H is Helmet. Spacesuit helmet protects the head and suit environment | crew equipment, not propulsion."),
("I","I — International Space Station! The ISS orbits Earth | crew and station share continuous free fall, producing microgravity."),
("J","J ... J ... Jet Pack! Some astronaut maneuvering units use small thrusters | the Jet Pack label is not standard gear for every spacewalk."),
("K","K? Krypton Tank! Some electric-propulsion spacecraft store krypton propellant | the tank feeds a thruster system."),
("L","L is Lander. Spacecraft designed to descend to a surface | landing hardware, not open-orbit hardware."),
("M","M — Meteor! A meteor is light from a meteoroid entering an atmosphere | the solid object in space is a meteoroid."),
("N","N ... N ... Neptune! Eighth major planet from the Sun | distant blue world."),
("O","O? Orbit! A curved path shaped by motion and gravity | spacecraft keep falling around a body."),
("P","P is Planet. Rounded world orbiting a star; Solar System planets have cleared their orbital neighborhoods."),
("Q","Q — Quarter Moon! Half the visible Moon is illuminated at first or last quarter | the word quarter names the cycle position, not a quarter-lit disk."),
("R","R ... R ... Rocket! Expelled propellant creates thrust | rocket carries its own reaction mass and works in vacuum."),
("S","S? Satellite! Natural or artificial object in orbit | the Moon and spacecraft can both be satellites."),
("T","T is Telescope. Instrument collects electromagnetic radiation | designs differ by wavelength."),
("U","U — Uranus! Seventh planet from the Sun | its rotation axis is tilted about 98 degrees."),
("V","V ... V ... Visor! Helmet shield protects the face and manages light | spacesuit part, not spacecraft window."),
("W","W? World! Broad word for a planet-like place | not a precise astronomical class."),
("X","X is X-ray Telescope. Cosmic X-rays are mostly absorbed by Earth's atmosphere | X-ray telescopes usually observe from space."),
("Y","Y — Yoke! A yoke is a vehicle control shape | our mapping helper is not universal spacecraft hardware."),
("Z","Z ... Z ... Zero-gravity Chair! A reclining chair may use this marketing name | it changes posture, not gravity."),),
"style_blueprint":"Crisp diction. Open with orbital free-fall rather than a countdown cliché. 92 BPM in 4/4 with acoustic/electronic hybrid: muted kick, warm bass, plucked synth, sparse bell and soft pad. Keep target melody narrow and stepwise. Round 1 follows Earth -> orbit -> observation -> outer system -> training room. Chorus is launch-orbit-observe. Round 2 leaves one clean recall beat. No rocket blasts over target words. Explicitly protect Meteor, ISS microgravity, Quarter Moon, X-ray Telescope and Zero-gravity Chair facts. End with a quiet mission-log cadence."},
"0052": {
"authorial_intent":"Turn Planet Parade into a scale-and-category gallery: astronaut and hardware in the foreground, moons and planets in the Solar System, Kuiper Belt farther out, then galaxy and universe at vastly larger scales.",
"lyric_identity":"A child zooms outward: human scale -> spacecraft -> moon/planet -> outer system -> galaxy -> universe, then zooms back to instruments.",
"image_motifs":("astronaut beside booster","Io near Jupiter","Kuiper Belt beyond Neptune","galaxy field","observatory dome"),
"semantic_arc":("human and launch scale","planet/moon scale","outer solar system","galaxy/universe scale then return to tools"),
"forbidden_generic_language":("planet parade","send it into orbit","stars blink clues","space friends"),
"rhyme_engine":"cosmic-scale-zoom-rhyme","chorus_rhyme_engine":"near-far-farther-hook","point_of_view":"a child zooming outward through astronomical scale","chorus_function":"reset near-far-farther","groove_meter":"6/8 expanding phrases with register widening","round1_grammar":"hand-written scale hierarchy; hardware does not masquerade as astronomy","round2_grammar":"scale cue -> recall beat -> target -> zoom/point gesture",
"intro_lines":("Astronaut near. Jupiter far. Galaxy farther than one Solar System can hold.","We zoom outward without confusing size, distance, and category."),
"hook_lines":("Near, far, farther—A-B-C!","One universe holds scales too large for one parade line."),
"outro_lines":("The zoom stops at the observatory screen.","A to Z comes back from universe-scale to one careful instrument."),
"round2_patterns":("Scale clue {letter} ... {object}! {action}","Near-or-far {letter} ... {object}! {action}","Zoom to {letter}? ... {object}! {action}","Cosmic frame {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Astronaut! Trained person works in spacecraft or space environments | human scale starts the zoom."),
("B","B ... B ... Booster! Launch stage or motor adds thrust during part of ascent | hardware larger than a person, tiny beside a planet."),
("C","C? Comet! Small icy body can grow a coma and tails near the Sun | Solar System object, not a star."),
("D","D is Dwarf Planet. Rounded body orbiting the Sun without clearing its orbital neighborhood | one Solar System category."),
("E","E — Eclipse! Alignment blocks some or all light from one body as seen from another | geometry event, not an object."),
("F","F ... F ... Fuel Tank! Stores propellant for a vehicle | mission hardware, not a celestial body."),
("G","G? Galaxy! Vast gravitational system of stars, gas, dust, dark matter and more | our Solar System occupies only a tiny place inside one galaxy."),
("H","H is Helmet. Crew protective equipment | foreground object before the astronomical zoom widens."),
("I","I — Io! One of Jupiter's large moons | extremely active volcanically because of tidal heating."),
("J","J ... J ... Jupiter! Fifth planet from the Sun and largest planet in our Solar System | giant scale after Io."),
("K","K? Kuiper Belt! Region beyond Neptune containing many icy small bodies | farther out than the major planets."),
("L","L is Lunar Rover. Wheeled vehicle used by Apollo astronauts on the Moon | surface hardware at moon scale."),
("M","M — Moon! Earth's natural satellite | smaller than Earth and orbiting it."),
("N","N ... N ... Neptune! Eighth major planet from the Sun | outer-planet scale before the Kuiper Belt."),
("O","O? Observatory! Facility built for astronomical observing | returns our zoom to human-made instruments."),
("P","P is Probe. Robotic spacecraft sent to collect data | tool that can travel far without becoming the thing it studies."),
("Q","Q — Quarter Moon! Half the visible lunar disk is illuminated at this phase | 'quarter' describes orbital phase position."),
("R","R ... R ... Rover! Mobile surface vehicle explores ground on another world | hardware at local surface scale."),
("S","S? Satellite! Object in orbit around another body | can be natural like a moon or artificial like a spacecraft."),
("T","T is Telescope. Collects radiation from distant sources | bridge between human scale and cosmic scale."),
("U","U — Universe! All space-time, matter, energy and cosmic contents we can describe | widest scale in the song."),
("V","V ... V ... Venus! Second planet from the Sun | rocky planet smaller than the Universe by an almost unimaginable factor."),
("W","W? World! Everyday broad term for a planet or inhabited place | not a strict scale category."),
("X","X is Xenon Thruster. Electric thruster can ionize xenon and accelerate ions for efficient propulsion | small hardware enabling long spacecraft journeys."),
("Y","Y — Yoke! Control-interface shape used in some vehicles | mapping helper, not a universal spacecraft standard."),
("Z","Z ... Z ... Zero-gravity Chair! Reclining chair changes body posture | does not make a person weightless or simulate orbital free fall."),),
"style_blueprint":"Crisp diction. Open with three scale levels at 86 BPM in airy 6/8 with nylon guitar, soft synth pad, marimba, bass and sparse chime. Melody begins narrow/low and widens in register as scale expands, then contracts at Observatory/Telescope. Round 1 distinguishes object, event, hardware, region and scale. Chorus near-far-farther. Round 2 uses hand zoom gestures and one recall beat. Duck targets. End back at observatory scale with clean cadence."},
"0053": {
"authorial_intent":"Make Rocket Ready an engineering checklist: communication, launch propulsion, tanks, capsule, observatory/science payload, rover and electric thruster each have a job; celestial targets are mission destinations or observations.",
"lyric_identity":"Mission Control reads subsystem by subsystem—structure, communication, propulsion, payload, destination—without pretending every space word belongs on one rocket.",
"image_motifs":("booster ignition diagram","dish antenna link","capsule cutaway","xenon thruster plume","rover on surface"),
"semantic_arc":("check launch hardware","check communications and crew/payload","check propulsion types","separate mission targets from vehicle systems"),
"forbidden_generic_language":("mission control ready","every letter opens a window","rocket beat","space hardware fun"),
"rhyme_engine":"rocket-checklist-function-rhyme","chorus_rhyme_engine":"check-link-thrust-hook","point_of_view":"a child reading a simplified systems-engineering checklist","chorus_function":"reset check-link-thrust","groove_meter":"precise 4/4 checklist pulse","round1_grammar":"hand-written function-first engineering lines plus honest astronomy context","round2_grammar":"system cue -> recall beat -> target -> function/point gesture",
"intro_lines":("Checklist first: communicate, carry, steer, thrust, observe.","A rocket mission works because different parts do different jobs."),
"hook_lines":("Check, link, thrust—A-B-C!","One system hands the mission to the next."),
"outro_lines":("Thruster quiet, antenna linked, science data saved.","A to Z signs off without calling the whole universe rocket hardware."),
"round2_patterns":("System clue {letter} ... {object}! {action}","Hardware or target {letter} ... {object}! {action}","What job, {letter}? ... {object}! {action}","Checklist {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Asteroid! Mission target or hazard context, not rocket hardware | small body orbiting the Sun."),
("B","B ... B ... Booster! Provides additional thrust during launch | one propulsion stage in the checklist."),
("C","C? Capsule! Enclosed spacecraft section can carry crew or cargo | structure and life-support context, not an engine."),
("D","D is Dish Antenna. Curved reflector focuses radio waves | communication system sends and receives signals."),
("E","E — Earth! Launch world and communication home base | destination context rather than subsystem."),
("F","F ... F ... Flag! Mission marker or symbol | carries no navigation or propulsion function."),
("G","G? Gemini Capsule! Historical two-person NASA spacecraft | engineering example from early crewed orbital missions."),
("H","H is Hubble Telescope. Space telescope in Earth orbit observes mainly ultraviolet, visible, and near-infrared wavelengths | science instrument, not crew cabin."),
("I","I — Io! Volcanically active moon of Jupiter | science target far beyond launch hardware."),
("J","J ... J ... Jupiter! Giant planet and possible mission destination region | not part of a rocket stack."),
("K","K? Krypton Tank! Stores krypton propellant used by some electric-propulsion systems | tank supplies reaction mass to a thruster."),
("L","L is Lunar Rover. Surface vehicle for mobility on the Moon | payload or surface system after landing."),
("M","M — Meteor! Light phenomenon in an atmosphere when a meteoroid enters | not a rock floating beside the rocket."),
("N","N ... N ... Nebula! Cloud of gas and dust in space | astronomical target, usually far beyond any classroom mission route."),
("O","O? Observatory! Place or platform for astronomical instruments | science context, not launch stage."),
("P","P is Planet. Rounded world orbiting a star | destination category, not vehicle hardware."),
("Q","Q — Quasar! Extremely luminous active galactic nucleus powered by matter falling toward a supermassive black hole | distant science target, not a nearby star."),
("R","R ... R ... Rover! Mobile robot or crewed surface vehicle | explores after arrival, not during launch."),
("S","S? Satellite! Object in orbit | mission payload can become an artificial satellite after deployment."),
("T","T is Thruster. Small rocket or electric propulsion device produces controlled force | used for maneuvering or sustained propulsion depending design."),
("U","U — Universe! Everything cosmic our mission belongs within | definitely not one checklist component."),
("V","V ... V ... Venus! Second planet from the Sun | target world, not propulsion hardware."),
("W","W? White Dwarf! Dense stellar remnant left by a Sun-like star after it sheds outer layers | astronomy target, not white-colored planet."),
("X","X is Xenon Thruster. Electric propulsion ionizes xenon and accelerates ions | efficient, low-thrust system very different from a launch booster."),
("Y","Y — Yellow Star! Everyday color label for some stars | stellar color relates to temperature, but apparent color also depends on viewing and classification."),
("Z","Z ... Z ... Zodiac Chart! Astronomical chart can mark constellations along the ecliptic | map context, not a device that predicts a mission's future."),),
"style_blueprint":"Crisp diction. Open like a calm engineering checklist at 94 BPM in 4/4 with muted kick, plucked synth, acoustic guitar, bass and small radio-click accents. Melody narrow, repeated-note friendly for technical terms. Round 1 groups communication, structure, propulsion, science and destination. Chorus check-link-thrust. Round 2 leaves one recall beat and uses function gestures. Booster, tank, thruster and xenon thruster must sound distinct. Duck target onsets. End with quiet data-save cadence."},
"0054": {
"authorial_intent":"Make Moonbeam Alphabet about gravity and motion: lunar surface gravity, orbital microgravity, spacecraft control and dust all behave differently; the song uses float imagery only where physics supports it.",
"lyric_identity":"A child compares standing on Moon, orbiting in free fall, drifting inside spacecraft, and operating equipment; 'float' becomes a precise contrast rather than a universal space verb.",
"image_motifs":("astronaut hopping on Moon","capsule in orbit","ISS free fall","moon dust settling ballistically","visor reflecting Earth"),
"semantic_arc":("Moon surface gravity","orbital microgravity","spacecraft systems and movement","deep-space targets and return to human controls"),
"forbidden_generic_language":("letters bounce like moon dust","zero gravity everywhere","float everything","moonbeam fun"),
"rhyme_engine":"gravity-motion-contrast-rhyme","chorus_rhyme_engine":"stand-fall-float-hook","point_of_view":"a child comparing lunar gravity with orbital free fall","chorus_function":"reset stand-fall-float distinctions","groove_meter":"gentle 3/4 with grounded moon steps and legato orbital phrases","round1_grammar":"hand-written gravity/motion contrasts; hardware and distant astronomy remain separate","round2_grammar":"gravity cue -> recall beat -> target -> hop/glide/point gesture",
"intro_lines":("On the Moon you still have weight; in orbit you keep falling around Earth.","Different places make different kinds of motion."),
"hook_lines":("Stand, fall, float—A-B-C!","Gravity stays; motion changes what weight can feel like."),
"outro_lines":("Boots touch ground again; the chair stays only a chair.","A to Z ends with gravity still doing its job."),
"round2_patterns":("Gravity {letter} ... {object}! {action}","Surface/orbit {letter} ... {object}! {action}","Motion {letter}? ... {object}! {action}","Flight {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Astronaut! On the Moon an astronaut can walk and hop under lower gravity | in orbit the same person can experience microgravity during free fall."),
("B","B ... B ... Booster! Strong launch thrust changes spacecraft speed | nothing about a booster removes gravity."),
("C","C? Capsule! Enclosed spacecraft can orbit in free fall | objects inside may seem to float together."),
("D","D is Dish Antenna. Communication hardware points or steers a radio beam | no floating metaphor needed."),
("E","E — Eclipse! Shadow geometry changes visible light | gravity sets orbits, but eclipse itself is an alignment event."),
("F","F ... F ... Fuel Tank! Stores propellant | contents can behave differently in microgravity, so spacecraft tank design matters."),
("G","G? Gemini Capsule! Crews in orbit experienced weightlessness-like microgravity | historical spacecraft in free fall around Earth."),
("H","H is Hubble Telescope. Space telescope orbits Earth | it and its components remain under Earth's gravity while continuously falling around the planet."),
("I","I — International Space Station! Crew and station share orbital free fall | microgravity is not the absence of gravity."),
("J","J ... J ... Jet Pack! Small thrusters can change an astronaut's motion during specialized maneuvering | not everyday spacewalk gear."),
("K","K? Krypton Tank! Stores propellant for some electric thrusters | tank remains mass under gravity wherever it travels."),
("L","L is Lander. Descends toward a surface and must manage gravity with propulsion or aerodynamics depending destination."),
("M","M — Moon! Earth's natural satellite has surface gravity about one-sixth of Earth's | enough to pull dust and astronauts back down."),
("N","N ... N ... Nebula! Vast gas-and-dust cloud in interstellar space | not something close enough to drift through on a Moon trip."),
("O","O? Orbit! Continuous free-fall path around a body | core idea behind orbital microgravity."),
("P","P is Planet. Planetary gravity shapes moons, rings, atmospheres, and spacecraft trajectories | gravity is part of the map."),
("Q","Q — Quasar! Distant active galactic nucleus powered by accretion onto a supermassive black hole | far beyond lunar motion scale."),
("R","R ... R ... Rocket! Thrust changes velocity against or with gravity | rocket works in vacuum by expelling propellant."),
("S","S? Spacesuit! Pressurized protective system lets crew work in vacuum | suit does not create weightlessness."),
("T","T is Thruster. Controlled force changes motion or orientation | small acceleration can matter greatly in orbit."),
("U","U — Universe! Gravity operates throughout cosmic structure | widest context for our motion lesson."),
("V","V ... V ... Visor! Helmet shield manages light and protection | reflective surface can show Earth without changing gravity."),
("W","W? World! Broad term for a planetary place | each world can have different surface gravity."),
("X","X is Xenon Thruster. Electric propulsion gives gentle sustained acceleration | slow change in velocity, not magical floating."),
("Y","Y — Yoke! Mapping helper for a control shape | some vehicles use yokes, but spacecraft controls vary widely."),
("Z","Z ... Z ... Zero-gravity Chair! Reclining chair redistributes body pressure and posture | it does not reproduce orbital free fall or lunar gravity."),),
"style_blueprint":"Crisp diction. Open with Moon gravity versus orbital free fall at 82 BPM in gentle 3/4 with nylon guitar, soft pad, pizzicato bass and sparse bell. Use grounded short notes for surface movement, long legato phrases for orbital free fall. Round 1 protects microgravity facts. Chorus stand-fall-float. Round 2 uses small safe hop versus hand-glide gestures. No fake floating for Moon dust, tanks, or chairs. Duck target onsets. End grounded with a clean low cadence."},
"0055": {
"authorial_intent":"Turn Little Space Lab into an evidence song: every major astronomy claim is paired with how we know—telescope, X-ray telescope, observatory, probe, rover, station, spectrum or repeated observation—while crew gear stays context.",
"lyric_identity":"A child scientist asks 'what is the evidence?' rather than simply naming spectacular objects; observation method becomes the compositional thread.",
"image_motifs":("observatory dome opening","X-ray telescope data","probe sending radio data","rover camera track","galaxy image on screen"),
"semantic_arc":("start human observer and tools","pair nearby worlds with probes/rovers","pair stars/nebulae with telescopes","finish with extreme objects and evidence limits"),
"forbidden_generic_language":("one bright clue","space science fun","telescope sees everything","glowing in the dark"),
"rhyme_engine":"space-lab-evidence-question-rhyme","chorus_rhyme_engine":"ask-observe-check-hook","point_of_view":"a child in a small astronomy lab asking how each claim is supported","chorus_function":"repeat ask-observe-check","groove_meter":"calm 4/4 lab pulse with question pauses","round1_grammar":"hand-written evidence-aware astronomy; tools have wavelength/mission limits","round2_grammar":"evidence cue -> recall beat -> target -> point/compare gesture",
"intro_lines":("A picture is useful; a measurement is better when we know how it was made.","Our space lab asks one question again and again: what is the evidence?"),
"hook_lines":("Ask, observe, check—A-B-C!","Science keeps the clue and tests the story."),
"outro_lines":("Screen dim, telescope parked, data saved for another question.","A to Z ends with evidence, not a guess dressed as fact."),
"round2_patterns":("Evidence {letter} ... {object}! {action}","Tool/target {letter} ... {object}! {action}","How know {letter}? ... {object}! {action}","Lab {letter} ... {object}! {action}"),
"round1_overrides":(
("A","A — Astronaut! Human observer and trained operator | crew reports combine with instrument data, not replace it."),
("B","B ... B ... Black Hole! We infer black holes from effects on nearby matter, light, motion, gravitational waves, and direct horizon-scale imaging in some cases | evidence without seeing a black interior."),
("C","C? Capsule! Spacecraft hardware carries people or cargo | lab distinguishes vehicle from the observations it returns."),
("D","D is Dish Antenna. Radio reflector links spacecraft and ground | data can travel farther than the probe itself can return."),
("E","E — Earth! Satellites, ground stations, and direct sampling provide many kinds of data | our best-known planet becomes the comparison case."),
("F","F ... F ... Flag! Symbolic object can appear in mission imagery | it is evidence of human activity only when supported by mission context."),
("G","G? Galaxy! Telescopes image starlight, gas emission, dust signatures and motion | one picture contains many physical clues."),
("H","H is Helmet. Crew safety hardware | not a science sensor unless special instruments are mounted or carried."),
("I","I — International Space Station! Orbiting laboratory hosts experiments and Earth/space observations | microgravity environment enables specific research."),
("J","J ... J ... Jet Pack! Maneuvering device label in our mapping | engineering object, not astronomy evidence."),
("K","K? Krypton Tank! Propellant storage for some electric propulsion systems | engineering telemetry can verify tank use and performance."),
("L","L is Lunar Rover. Surface vehicle extends where people or instruments can travel | images, samples, and measurements turn movement into evidence."),
("M","M — Moon! Orbiters, landers, samples, telescopes, and direct human exploration all contribute evidence | multiple methods agree on one nearby world."),
("N","N ... N ... Nebula! Gas and dust reveal themselves through images and spectra at different wavelengths | color alone is not the whole measurement."),
("O","O? Observatory! Facility organizes instruments, tracking, calibration, and repeated observation | place where evidence is built carefully."),
("P","P is Probe. Robotic spacecraft carries sensors to destinations | sends measurements back by radio."),
("Q","Q — Quasar! Spectra, variability, imaging and multiwavelength observations support the active-galactic-nucleus model | extreme brightness needs evidence across bands."),
("R","R ... R ... Rover! Mobile science platform carries imaging tools and instruments | surface path becomes a sequence of measured sites."),
("S","S? Spacesuit! Protective life-support system | lets humans work safely but does not itself prove an astronomy claim."),
("T","T is Telescope. Collects electromagnetic radiation | each design has wavelength, resolution, and sensitivity limits."),
("U","U — Uranus! Telescopes and Voyager 2 data reveal rings, moons, atmosphere and tilted rotation | evidence comes from more than apparent color."),
("V","V ... V ... Venus! Radar, orbiters, landers and spectroscopy reveal a hot dense atmosphere and hidden surface | clouds require instruments that see more than visible light."),
("W","W? White Dwarf! Dense stellar remnant identified through temperature, luminosity, spectra, mass and binary behavior | not merely a white point."),
("X","X is X-ray Telescope. Detects high-energy X-rays from hot and extreme cosmic environments | usually operates above most of Earth's atmosphere."),
("Y","Y — Yoke! Control-interface mapping helper | engineering context stays separate from science evidence."),
("Z","Z ... Z ... Zero-gravity Chair! Reclining furniture may use the marketing name | a lab note must state clearly that it does not create microgravity."),),
"style_blueprint":"Crisp diction. Open with evidence question at 84 BPM calm 4/4 with piano, plucked synth, soft bass, muted percussion and sparse glassy accents. Melody narrow and question-shaped. Round 1 pairs claims with methods and limitations. Chorus ask-observe-check. Round 2 leaves a full recall beat. Telescope and X-ray telescope have distinct wavelength roles; probes/rovers return data; crew gear stays context. Duck targets. End with screen-dim, data-save cadence."}
}
