from __future__ import annotations

"""Authorial-identity deep polish for rainforest songs 0026-0030."""

GOLD_V5_26_30_SPEC_PATCHES: dict[str, dict[str, object]] = {
    "0026": {
        "authorial_intent": "Build a rainforest rhythm from honest layers of water, leaf movement, wingbeats, calls and silence so the child hears an ecosystem instead of a generic jungle beat.",
        "lyric_identity": "A listener follows drip, rustle, flutter, call, splash and hush from wet ground to canopy; silent plants become rests in the rhythm.",
        "image_motifs": ("drips on broad leaves", "gecko feet on bark", "macaw wing flash", "frog in wet leaf litter", "waterfall under the canopy"),
        "semantic_arc": ("rain starts the pulse", "animals add short movement sounds", "color and calls widen the canopy", "waterfall gathers the rhythm and releases it"),
        "forbidden_generic_language": ("jungle words bounce back to me", "rainforest fun", "everything makes music", "bright and wild"),
        "rhyme_engine": "rainforest-layered-percussion-rhyme",
        "chorus_rhyme_engine": "drip-rustle-hush-refrain",
        "point_of_view": "a child listening to different rainforest layers as separate parts of one restrained rhythm",
        "chorus_function": "reassemble drip, rustle, wing and hush without covering learning words",
        "groove_meter": "syncopated but gentle 4/4 with wet-leaf rests",
        "round1_grammar": "hand-written sensory lines; only truthful sounds become percussion and silent targets get visual or tactile rests",
        "round2_grammar": "rhythm cue -> recall beat -> target -> one safe motion",
        "intro_lines": ("Drip. Leaf-rustle. Wing-flutter. Hush.", "The rainforest has layers, and each layer keeps a different pulse."),
        "hook_lines": ("Drip, rustle, hush—A-B-C!", "Layer by layer, the rainforest keeps time."),
        "outro_lines": ("The waterfall keeps moving after the small sounds fade.", "A to Z leaves one last drop in the leaves."),
        "round2_patterns": ("Rain beat {letter} ... {object}! {action}", "Layer cue {letter} ... {object}! {action}", "Hush for {letter}? ... {object}! {action}", "Rhythm clue {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Anteater! Long snout, sticky tongue | quiet searching for ants and termites beneath the larger forest sounds."),
            ("B", "B ... B ... Boa! Thick body curves along a branch | muscle makes the motion, not a drumbeat."),
            ("C", "C? Chameleon! Gripping feet hold bark | two eyes can scan in different directions before the long tongue strikes."),
            ("D", "D is Drongo. Dark bird, agile flight | a forked or notched tail cuts through a quick wing rhythm."),
            ("E", "E — Elephant! Trunk curls, touches, smells, drinks | one large body moving carefully through the green."),
            ("F", "F ... F ... Fern! Curled growth opens into divided fronds | a silent green rest between animal sounds."),
            ("G", "G? Gecko! Toe pads grip bark and leaf | tiny feet hold where smooth surfaces would make us slip."),
            ("H", "H is Hornbill. Large curved bill, raised casque | heavy wingbeats can pass high above the wet leaves."),
            ("I", "I — Iguana! Long tail, strong body, back spines | a lizard shape stretched across branch and light."),
            ("J", "J ... J ... Jungle Vine! It climbs through other plants toward brighter canopy | green motion measured in growth, not footsteps."),
            ("K", "K? Kinkajou! Gripping feet and long tail help it move among branches | a night visitor in the canopy."),
            ("L", "L is Leopard. Spotted coat, powerful body | quiet paws move through cover and can climb."),
            ("M", "M — Macaw! Broad wings flash red, blue, or gold | one bright sweep across the upper rhythm."),
            ("N", "N ... N ... Nectar Bat! Long tongue reaches flower nectar | quick wings carry it from bloom to bloom."),
            ("O", "O? Orchid! A shaped flower opens from green | color holds still while wings and rain move around it."),
            ("P", "P is Parrot. Curved beak, gripping feet | branch hold, bite, climb—small motions with clear purpose."),
            ("Q", "Q — Queen Butterfly! Orange-brown wings with dark veins and pale spots | a soft flutter crossing the stronger jungle pulse."),
            ("R", "R ... R ... Rainforest Frog! Moist skin, strong legs | wet leaves make the close world around its hop."),
            ("S", "S? Snake! Long scaled body bends in muscular curves | slither is movement, not a reason to move closer."),
            ("T", "T is Toucan. Huge colorful bill above a light body | one bold shape perched inside layered green."),
            ("U", "U — Uakari! Rainforest monkey with a short tail and bare face | branch movement adds another level to the canopy."),
            ("V", "V ... V ... Viper! Venomous snake, patterned body | we learn the shape only from a safe distance."),
            ("W", "W? Waterfall! Sheet and spray over rock | the longest, loudest rhythm in the rainforest scene."),
            ("X", "At the research shelter, X is Xenops. A small tropical bird searches bark and branches for insects."),
            ("Y", "Y — Yellow Anaconda! Large yellowish snake with dark blotches | a heavy curve through wet South American habitat."),
            ("Z", "Z ... Z ... Zingiber Plant! Leafy stems rise from underground rhizomes | tropical green closing the rhythm in stillness."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Clear warm adult lead at 90 BPM, restrained syncopated 4/4 with hand drum, muted claves, soft shaker, marimba droplets and warm bass. Treat the rainforest as layered rhythm, not percussion overload. Use one or two sound colors at a time; silent plants create rests. Round 1 must keep factual long lines speech-natural and never force every animal into onomatopoeia. Chorus is drip-rustle-hush with a real hush. Round 2 gives one beat of silence before targets; dangerous snakes stay observe-only. Duck percussion on every target onset. Xenops is a small bark-searching rainforest bird and remains visually recognizable. End with waterfall-like sustained texture fading under one final marimba drop.",
    },
    "0027": {
        "authorial_intent": "Make the canopy understandable as vertical space: floor, trunk, midstory and crown each hold different clues, and sunlight becomes the thread that pulls the alphabet upward.",
        "lyric_identity": "A child looks from low roots to high leaves; recurring language uses floor, trunk, climb, mid-level, overhead, gap, crown, shaft of light and down again.",
        "image_motifs": ("sun shaft through leaves", "kapok trunk rising", "liana and rattan climbing", "toucan silhouette overhead", "waterfall glimpsed through canopy gaps"),
        "semantic_arc": ("begin on the shaded floor", "follow trunks and climbers upward", "reach bright canopy animals and leaves", "look back down through the layered forest"),
        "forbidden_generic_language": ("tropical words grow high with me", "jungle up high", "everything lives in the canopy", "look and see"),
        "rhyme_engine": "vertical-canopy-rising-chain",
        "chorus_rhyme_engine": "low-mid-high-open-hook",
        "point_of_view": "a child mapping rainforest height from ground layer to canopy and back down",
        "chorus_function": "restate vertical orientation and make height the memory device",
        "groove_meter": "rising 6/8 with low-to-high melodic contour",
        "round1_grammar": "hand-written vertical placement; do not falsely place ground animals high in trees, instead use contrast between layers",
        "round2_grammar": "layer cue -> recall beat -> target -> point low/mid/high or object-specific gesture",
        "intro_lines": ("Start where the light is dim. Now follow one trunk upward.", "The rainforest changes every few meters above our heads."),
        "hook_lines": ("Low, middle, high—A-B-C!", "Sunlight threads the canopy layer by layer."),
        "outro_lines": ("From the bright crown, our eyes travel back to the shaded floor.", "A to Z has climbed the whole green height."),
        "interlude_lines": ("Look down from the canopy for one quiet beat—what layers can we remember?",),
        "round2_patterns": ("Layer map {letter} ... {object}! {action}", "Low or high, {letter} ... {object}! {action}", "Where is {letter}? ... {object}! {action}", "Canopy clue {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Anaconda! Heavy scaled body stays close to water and low cover | our vertical map begins near the bottom."),
            ("B", "B ... B ... Banana! Huge leaves spread from a tall herb | curved fruit hangs below the green fans."),
            ("C", "C? Chameleon! Gripping feet hold branch or twig | eyes scan sideways while the body stays nearly still."),
            ("D", "D is Drongo. Agile dark bird crosses an open gap | forked or notched tail cutting through brighter air."),
            ("E", "E — Emerald Tree Boa! Green coils rest around branches | one snake truly belonging in the tree layer."),
            ("F", "F ... F ... Frog! Strong back legs launch from wet ground or leaf | some rainforest frogs climb, others stay low."),
            ("G", "G? Gorilla! Powerful primate often moving on the forest floor | grasping hands can also help with climbing."),
            ("H", "H is Hornbill. Curved bill and casque show high against a light gap | broad wings cross between crowns."),
            ("I", "I — Insect! Six legs can work at every height | under litter, on bark, or among leaves above."),
            ("J", "J ... J ... Jaguar! Spotted cat moves mainly through ground cover | but strong claws can take it up a tree."),
            ("K", "K? Kapok Tree! Massive trunk rises from the shaded floor | branches spread into the bright upper forest."),
            ("L", "L is Liana. Woody vine begins low and climbs by using trees for support | a living line between layers."),
            ("M", "M — Monkey! Hands grip, feet push, body swings | branch to branch makes the middle and upper forest connected."),
            ("N", "N ... N ... Nectar Bat! Small wings move through flower-rich spaces | a long tongue reaches nectar where blooms open."),
            ("O", "O? Ocelot! Spotted wild cat works through dense lower cover | a low-layer contrast to the birds overhead."),
            ("P", "P is Palm. Trunk or strong stems lift a crown of broad leaves | green fans catching higher light."),
            ("Q", "Q — Queen Butterfly! Orange-brown wings cross sunlit gaps | small flutter between leaves at different heights."),
            ("R", "R ... R ... Rattan! Climbing palm sends long flexible stems through surrounding vegetation | another route upward."),
            ("S", "S? Snake! Some stay low, some climb | a long scaled body can use very different rainforest layers."),
            ("T", "T is Toucan. Huge bill, perched body | one unmistakable silhouette high in the leafy crown."),
            ("U", "U — Umbrella Leaf! Broad leaf catches light like a green roof | shade forms beneath it."),
            ("V", "V ... V ... Vine! Stem reaches and trails through support | vertical green stitching one layer to another."),
            ("W", "W? Waterfall! It ignores our neat layers | water drops from high rock toward the forest floor in one long line."),
            ("X", "X is Xenops. Small tropical bird works along bark and branches | searching surfaces for insects."),
            ("Y", "Y — Yellow Anaconda! Large blotched snake stays tied to low wet habitat | another reason not to call every rainforest animal a canopy animal."),
            ("Z", "Z ... Z ... Zingiber Plant! Leafy stems rise from rhizomes underground | a tropical plant closing our map near the lower green."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Precise gentle adult lead in 6/8 at 86 BPM with nylon guitar, marimba, airy flute, soft tom and warm bass. Arrange literally by height: low register and sparse texture for ground targets, midrange pizzicato for trunks/climbers, brighter flute/glockenspiel only for canopy openings. Round 1 must preserve correct layer placement; Gorilla, Ocelot and Yellow Anaconda are not magically canopy animals. Chorus climbs low-middle-high in melody. Round 2 uses layer cues plus a clean recall beat. Keep long botanical names on repeated notes. No dense tropical clichés or bird-noise loops. End by descending register back to the floor.",
    },
    "0028": {
        "authorial_intent": "Use movement as the organizing language: every living target has its own honest motion—climb, cling, glide, slither, step, swing, flutter—while plants and nests become anchors that motion passes around.",
        "lyric_identity": "A child watches motion paths across the jungle; verbs carry the rhyme and line rhythm more than object definitions do.",
        "image_motifs": ("dragonfly dart", "gecko cling", "howler branch sway", "tapir step", "butterfly glide"),
        "semantic_arc": ("small motions begin low", "climbing and swinging widen the paths", "large animals cross the scene", "light wing motions close the sequence"),
        "forbidden_generic_language": ("plants and creatures look and see", "jungle green for me", "move move move", "everything swings"),
        "rhyme_engine": "jungle-motion-verb-weave",
        "chorus_rhyme_engine": "slither-climb-glide-hook",
        "point_of_view": "a child tracing honest movement paths while still noticing stationary plants, nests and trunks",
        "chorus_function": "reset the motion vocabulary without asking children to imitate dangerous wildlife",
        "groove_meter": "stop-go 4/4 with contrasting motion pockets",
        "round1_grammar": "hand-written motion-specific lines; stationary targets anchor the choreography and dangerous animals stay observation-only",
        "round2_grammar": "motion cue -> recall beat -> target -> safe abstract or object-specific gesture",
        "intro_lines": ("One thing darts. One thing climbs. One thing barely moves at all.", "The jungle writes paths through the green."),
        "hook_lines": ("Slither, climb, glide—A-B-C!", "Different bodies move through green differently."),
        "outro_lines": ("The last butterfly path disappears between leaves.", "A to Z leaves motion hanging in the green."),
        "round2_patterns": ("Motion map {letter} ... {object}! {action}", "Trace {letter} ... {object}! {action}", "Moving or still, {letter}? ... {object}! {action}", "Freeze and find {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Anteater! Long snout leads, sturdy legs follow | searching along the ground for ants and termites."),
            ("B", "B ... B ... Banana! Huge leaves sway, fruit hangs | the plant anchors the scene while animals move around it."),
            ("C", "C? Ceiba Tree! Trunk rises, branches spread | one still giant that gives many moving paths a place to cross."),
            ("D", "D is Dragonfly. Four wings dart and hover | quick turns stitch bright lines over wet green."),
            ("E", "E — Elephant! Slow feet carry a huge body | flexible trunk curls, reaches, lifts, and drinks."),
            ("F", "F ... F ... Fern! Fronds unfurl rather than run | growth is the motion of this quiet target."),
            ("G", "G? Gecko! Toe pads cling | body pauses on bark, then slips to a new hold."),
            ("H", "H is Howler Monkey. Branches sway under a climbing body | loud calls travel farther than the animal moves."),
            ("I", "I — Insect! Six legs crawl, wings may buzz or dart | tiny bodies make many kinds of paths."),
            ("J", "J ... J ... Jaguar! Spotted cat steps through cover with powerful quiet motion | we watch only from a safe distance."),
            ("K", "K? Kinkajou! Feet grip branches, tail balances | night movement curls through the canopy."),
            ("L", "L is Liana. Woody vine climbs by growing along supports | a slow motion written into the forest itself."),
            ("M", "M — Macaw! Broad wings beat, then glide | a flash of color crossing open air."),
            ("N", "N ... N ... Nest! Twigs stay still in a cup | movement comes and goes around this sheltered center."),
            ("O", "O? Ocelot! Low spotted cat steps through dense cover | quiet body, quick change of direction."),
            ("P", "P is Parrot. Feet grip, beak helps climb | short branch movements before the wings take over."),
            ("Q", "Q — Quetzal! Long feathers trail behind flight | a green-bright bird path between branches."),
            ("R", "R ... R ... Rattan! Long climbing stems bend and weave | plant growth makes a slow spiral through the forest."),
            ("S", "S? Snake! Muscles send curves down a long scaled body | observe the slither without approaching."),
            ("T", "T is Tapir. Sturdy legs step through low vegetation | short flexible snout reaches leaves ahead."),
            ("U", "U — Umbrella Leaf! Broad surface nods under rain | a plant-motion made by water and wind."),
            ("V", "V ... V ... Vine! Climb, trail, curl | stems borrow support instead of building a trunk."),
            ("W", "W? Water Vine! Green stem stretches through light | a living line crossing other movement paths."),
            ("X", "X is Xenops. Small bird creeps along bark and branches | searching surfaces for insects."),
            ("Y", "Y — Yellow Butterfly! Broad wings flutter from plant to plant | light motion near flowers and leaves."),
            ("Z", "Z ... Z ... Zebra Longwing! Long dark wings striped pale yellow | smooth gliding closes the jungle choreography."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Friendly adult lead at 94 BPM in stop-go acoustic 4/4 with muted guitar, soft bass, claves, shaker and short marimba figures. Each motion family gets a rhythmic pocket: crawl low, climb syncopated, glide legato, step grounded, flutter light. Stationary plants create held notes and rests. Round 1 must never turn every target into the same dance. Chorus names slither-climb-glide but children use abstract arm/finger motions only; dangerous animals are observation-only. Round 2 leaves one beat after motion cue and keeps target onsets dry. End with a long gliding phrase and no percussion tail.",
    },
    "0029": {
        "authorial_intent": "Turn rainforest exploration into a visual mystery: partial silhouettes, color patches, leaf movement and texture clues appear before the full target, teaching careful noticing rather than frantic spotting.",
        "lyric_identity": "A child uses binocular-like framing; recurring language uses edge, glimpse, patch, shape, behind, reveal, still, closer-with-eyes and not-with-feet.",
        "image_motifs": ("green coil behind leaves", "dragonfly flash", "howler silhouette", "orchid shape in shade", "quetzal color through a gap"),
        "semantic_arc": ("first glimpses are partial", "clues become more specific", "harder camouflage and distance clues appear", "final reveals teach patience over chasing"),
        "forbidden_generic_language": ("explorer eyes come look with me", "find the jungle clues with me", "something moved", "spot it fast"),
        "rhyme_engine": "binocular-clue-reveal-rhyme",
        "chorus_rhyme_engine": "glimpse-shape-reveal-hook",
        "point_of_view": "a careful child observer solving visual clues from a fixed respectful distance",
        "chorus_function": "slow the search into glimpse-shape-name rather than speed spotting",
        "groove_meter": "walking 4/4 with suspense rests before reveals",
        "round1_grammar": "hand-written clue-first observations with varied syntax; dangerous or shy wildlife is never approached for a better view",
        "round2_grammar": "visual clue -> recall beat -> target reveal -> safe pointing/framing gesture",
        "intro_lines": ("A green curve vanishes behind one wet leaf.", "Do not chase the clue—hold still and let the picture come back."),
        "hook_lines": ("Glimpse, shape, reveal—A-B-C!", "Good explorer eyes can wait before they name."),
        "outro_lines": ("Binoculars down; the forest keeps most of itself hidden.", "A to Z was enough to notice, never enough to chase."),
        "round2_patterns": ("First clue {letter} ... {object}! {action}", "Frame {letter} ... {object}! {action}", "What shape, {letter}? ... {object}! {action}", "Reveal {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "First clue A — Anaconda. A long scaled curve near wet cover | enough to name from far away, never a reason to move closer."),
            ("B", "B ... B ... Banana! Huge torn-edged leaves make the first shape | curved fruit appears only after the eye settles."),
            ("C", "C? Ceiba Tree! Massive trunk fills the frame before the crown | a tree too large for one quick glance."),
            ("D", "D is Dragonfly. A flash, then hover | four clear wings become visible when the tiny shape pauses."),
            ("E", "E — Emerald Tree Boa! Green coil around a branch | camouflage turns into a snake once the outline is found."),
            ("F", "F ... F ... Frog! Strong back legs fold beneath a small body | wet leaf and animal separate when we look carefully."),
            ("G", "G? Gecko! Toes spread against bark | the small lizard shape appears where color nearly disappears."),
            ("H", "H is Howler Monkey. Dark body high in leaves | sometimes the call reveals the animal before binoculars do."),
            ("I", "I — Iguana! Long tail, row of back spines | a jagged silhouette turns into a large lizard."),
            ("J", "J ... J ... Jungle Vine! One green line crosses another | follow the stem with your eyes until it reaches higher light."),
            ("K", "K? Kinkajou! Round face, branch-gripping body | a night-active mammal best known through careful observation."),
            ("L", "L is Leopard. Rosette-like spots break up a powerful cat shape | camouflage works until motion gives one clue away."),
            ("M", "M — Monkey! A hand grips first, then the body swings into view | one clue becomes a whole animal."),
            ("N", "N ... N ... Nest! Twigs form a cup between branches | binoculars stay back so the nest stays undisturbed."),
            ("O", "O? Orchid! Strange petal shape in shade | color and central form reveal the flower without touching it."),
            ("P", "P is Parrot. Curved beak, gripping feet, feather color | three field marks solve one branch-top clue."),
            ("Q", "Q — Quetzal! Green-bright feathers and long tail can flash through a canopy gap | a brief reveal worth waiting for."),
            ("R", "R ... R ... Rainforest Frog! Moist skin, strong legs | small shape sits where wet leaf and animal colors meet."),
            ("S", "S? Sloth! Rounded body hangs beneath a branch | slow motion makes the hidden shape easier to keep in frame."),
            ("T", "T is Tapir. Short flexible snout appears ahead of a sturdy body | a low forest mammal crossing the opening."),
            ("U", "U — Umbrella Leaf! Broad leaf makes a green canopy of its own | one simple shape hiding smaller clues beneath."),
            ("V", "V ... V ... Viper! Patterned venomous snake | binocular distance is exactly the right distance."),
            ("W", "W? Waterfall! White moving strip through green | sound and motion reveal it before the full rock face appears."),
            ("X", "X is Xenops. Small bird works along bark | narrow bill and creeping branch search make the clue clearer."),
            ("Y", "Y — Yellow Anaconda! Dark blotches on yellowish skin | a large South American snake identified without approach."),
            ("Z", "Z ... Z ... Zingiber Plant! Leafy tropical stems rise from rhizomes below | final clue stays rooted while our eyes move on."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Warm curious lead at 88 BPM, walking 4/4 with muted guitar, soft bass, pizzicato strings, sparse marimba and one-beat suspense gaps. Round 1 should behave like clue then reveal, but vary syntax enough to avoid 26 identical riddles. Instrumentation briefly thins before the target name as if a visual comes into focus. Chorus is glimpse-shape-reveal, calm not triumphant. Round 2 uses a clean recall gap and hand-framing/pointing gestures; never author chasing or approaching wildlife. Viper and anacondas remain distance-only. End with binoculars-down quiet and one unresolved forest texture.",
    },
    "0030": {
        "authorial_intent": "Carry the alphabet along a rainforest river corridor where current, bank, overhanging canopy and reflected light connect objects that live at different heights.",
        "lyric_identity": "A child rides an imagined slow river route; recurring language uses bank, current, bend, reflection, overhang, downstream, crossing and shore.",
        "image_motifs": ("dark river under green roof", "anaconda near bank", "hornbill crossing overhead", "rattan reflected in water", "water vine and ginger at final bend"),
        "semantic_arc": ("push away from shaded bank", "follow bends under animals and climbers", "mid-route reflections mix canopy and water", "return to a quiet landing downstream"),
        "forbidden_generic_language": ("flowing jungle words for me", "river fun", "everything swims", "sail and see"),
        "rhyme_engine": "canopy-river-flow-return-rhyme",
        "chorus_rhyme_engine": "bend-flow-overhead-hook",
        "point_of_view": "a child on an imagined slow river journey observing banks, water, trunks and canopy without claiming every target is aquatic",
        "chorus_function": "restart the gentle current and orient bank-below-overhead",
        "groove_meter": "flowing 3/4 with long downstream phrase tails",
        "round1_grammar": "hand-written river-corridor scenes; each target is honestly placed on bank, ground, branch, canopy or water-adjacent space",
        "round2_grammar": "river-position cue -> recall beat -> target -> safe flow/point gesture",
        "intro_lines": ("Dark water moves under a roof of leaves.", "We follow one slow bend without pretending the whole rainforest lives in the river."),
        "hook_lines": ("Bank, bend, flow—A-B-C!", "Water below, green overhead, onward we go."),
        "outro_lines": ("The landing appears where the current finally softens.", "A to Z drifts out beneath the last green reflection."),
        "interlude_lines": ("Let the boat-glide stop for one beat—what river-corridor clues return?",),
        "round2_patterns": ("River-corridor clue {letter} ... {object}! {action}", "Bank-or-branch {letter} ... {object}! {action}", "Where on the route, {letter}? ... {object}! {action}", "Next bend, {letter} ... {object}! {action}"),
        "round1_overrides": (
            ("A", "A — Anaconda! Heavy scaled body near wet bank and water | a low curve beside the moving current."),
            ("B", "B ... B ... Boa! Thick-bodied snake can coil on branches | one dry perch above the river route."),
            ("C", "C? Ceiba Tree! Huge trunk rises from bank-side forest | crown disappears into the roof over our water."),
            ("D", "D is Dragonfly. Wings hover over the surface | quick turns catch reflected light at the first bend."),
            ("E", "E — Elephant! Large feet stay on land | trunk can reach, smell, touch, and drink near water's edge."),
            ("F", "F ... F ... Fern! Divided fronds lean from damp ground | quiet green at the edge of the current."),
            ("G", "G? Gorilla! Powerful primate remains on forest ground and bank-side cover | not every river clue belongs in water."),
            ("H", "H is Hornbill. Large bill crosses overhead | broad wings move from one bank of green to the other."),
            ("I", "I — Iguana! Long tail lies along a branch or bank-side perch | spines make a clear silhouette above reflection."),
            ("J", "J ... J ... Jungle Vine! Climbing stem drops through the green roof | one line nearly touching the river view."),
            ("K", "K? Kinkajou! Night-active branch traveler | gripping feet move above the route, not through the current."),
            ("L", "L is Liana. Woody climber loops from trunk to trunk | its curve repeats in the water below."),
            ("M", "M — Monkey! Branch grip, swing, pause | movement overhead follows the river bend beneath."),
            ("N", "N ... N ... Nest! Twig cup held above the corridor | we pass quietly and leave it undisturbed."),
            ("O", "O? Ocelot! Spotted cat moves through lower bank-side cover | quick shadow between roots and leaves."),
            ("P", "P is Palm. Crown of broad leaves leans toward open light | reflection breaks into green pieces on the water."),
            ("Q", "Q — Quetzal! Bright bird crosses a canopy gap | color flashes above a darker river mirror."),
            ("R", "R ... R ... Rattan! Climbing palm weaves long flexible stems | tangled bank-side lines follow us downstream."),
            ("S", "S? Sloth! Slow body hangs beneath a branch | current moves faster below than the animal moves above."),
            ("T", "T is Toucan. Huge bill perches over the corridor | one bold shape where canopy opens."),
            ("U", "U — Uakari! Short-tailed rainforest monkey moves among branches | another overhead clue beyond the next bend."),
            ("V", "V ... V ... Vine! Stem climbs, trails, and crosses supports | green lines frame the river without becoming water plants."),
            ("W", "W? Water Vine! Long green stem threads through humid forest | a living line near our last shaded bend."),
            ("X", "At the river camp, X is Xenops. A small tropical bird searches bark and branches for insects."),
            ("Y", "Y — Yellow Anaconda! Large yellowish snake with dark blotches | a wet-habitat curve seen from respectful distance."),
            ("Z", "Z ... Z ... Zingiber Plant! Leafy stems rise from underground rhizomes | tropical green waiting near the landing."),
        ),
        "style_blueprint": "Crisp diction. Open with the authored intro image; keep the melody narrow and mostly stepwise around learning targets. Flowing adult lead at 84 BPM in 3/4 with nylon guitar arpeggio, soft bass, brushed hand drum, marimba droplets and occasional airy flute. The accompaniment should feel like slow current: continuous but never rushed. Round 1 places each target honestly along bank, ground, branch, canopy, or river-adjacent habitat; Gorilla does not swim, and Xenops stays in the branches searching bark. Use internal flow rhyme and long phrase tails. Chorus reorients bank-bend-flow. Round 2 leaves a clear recall beat at each bend cue and uses pointing/flow gestures. Duck percussion on target onset. End with current texture thinning at the landing.",
    },
}
